const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-018',problems:[
{id:1325,slug:'delete-leaves-with-a-given-value',title:'删除给定值的叶子节点',studyTags:['树','深度优先搜索','后序遍历'],summary:'反复删除值为 target 的叶节点，直到不存在为止，返回最终二叉树。',insight:'后序递归先处理孩子；孩子删除后当前节点可能新变成叶子，因此在返回当前节点前再次检查左右为空且值等于目标即可一次递归完成级联删除。',pitfalls:['必须先处理左右子树再判断当前节点','原本非叶节点可能在孩子删除后成为叶子','根节点也可能最终被删除'],solutions:[s('postorder-cascading-prune','后序级联剪枝','孩子处理结果直接决定当前节点是否成为新目标叶。',['空节点返回空','node.left=dfs(node.left)，node.right=dfs(node.right)','若两孩子均空且 node.val==target 返回空，否则返回 node'],'O(n)','O(height)',
`class Solution { public TreeNode removeLeafNodes(TreeNode root,int target){if(root==null)return null;root.left=removeLeafNodes(root.left,target);root.right=removeLeafNodes(root.right,target);return root.left==null&&root.right==null&&root.val==target?null:root;} }`,
`class Solution { fun removeLeafNodes(root:TreeNode?,target:Int):TreeNode?{root?:return null;root.left=removeLeafNodes(root.left,target);root.right=removeLeafNodes(root.right,target);return if(root.left==null&&root.right==null&&root.\`val\`==target)null else root} }`,
`class Solution { public: TreeNode* removeLeafNodes(TreeNode* root,int target){if(!root)return nullptr;root->left=removeLeafNodes(root->left,target);root->right=removeLeafNodes(root->right,target);if(!root->left&&!root->right&&root->val==target){delete root;return nullptr;}return root;} };`)],tests:{schemaVersion:1,mode:'function',method:'removeLeafNodes',parameterTypes:['treeNode','int'],returnType:'treeNode',cases:[{name:'删除两个二叶节点',args:[[1,2,3,2,null,2,4],2],expected:[1,null,3,null,4]},{name:'级联删除整条目标链',args:[[1,3,3,3,2],3],expected:[1,3,null,null,2]},{name:'根本身被删除',args:[[1],1],expected:[]}]}},
{id:1326,slug:'minimum-number-of-taps-to-open-to-water-a-garden',title:'灌溉花园的最少水龙头数目',studyTags:['数组','贪心','区间覆盖'],summary:'第 i 个水龙头覆盖 [i-ranges[i],i+ranges[i]]，求覆盖整个 [0,n] 的最少水龙头数量，不可行返回负一。',insight:'把每个水龙头转成区间，并按左端点记录能到达的最远右端。随后像 Jump Game II 一样扫描：在当前已覆盖边界内收集最远延伸，抵达边界时必须选择一次。',pitfalls:['覆盖区间需裁剪到零和 n','若最远延伸没有超过当前边界则存在缺口','目标是连续覆盖实数区间而非只覆盖整数点'],solutions:[s('interval-jump-greedy','区间跳跃贪心','把区间覆盖转为每个起点的最远跳跃。',['maximumReach[left] 记录所有左端为 left 的区间最大 right','扫描 position=0..n-1，farthest=max(farthest,maximumReach[position])','position==currentEnd 时若 farthest<=position 返回 -1；否则 taps++、currentEnd=farthest，覆盖到 n 时返回 taps'],'O(n)','O(n)',
`class Solution { public int minTaps(int n,int[] ranges){int[] reach=new int[n+1];for(int i=0;i<=n;i++){int left=Math.max(0,i-ranges[i]),right=Math.min(n,i+ranges[i]);reach[left]=Math.max(reach[left],right);}int taps=0,currentEnd=0,farthest=0;for(int position=0;position<n;position++){farthest=Math.max(farthest,reach[position]);if(position==currentEnd){if(farthest<=position)return -1;taps++;currentEnd=farthest;if(currentEnd>=n)return taps;}}return taps;} }`,
`class Solution { fun minTaps(n:Int,ranges:IntArray):Int{val reach=IntArray(n+1);for(i in 0..n){val left=maxOf(0,i-ranges[i]);val right=minOf(n,i+ranges[i]);reach[left]=maxOf(reach[left],right)};var taps=0;var currentEnd=0;var farthest=0;for(position in 0 until n){farthest=maxOf(farthest,reach[position]);if(position==currentEnd){if(farthest<=position)return -1;taps++;currentEnd=farthest;if(currentEnd>=n)return taps}};return taps} }`,
`class Solution { public: int minTaps(int n,vector<int>& ranges){vector<int> reach(n+1);for(int i=0;i<=n;++i){int left=max(0,i-ranges[i]),right=min(n,i+ranges[i]);reach[left]=max(reach[left],right);}int taps=0,currentEnd=0,farthest=0;for(int position=0;position<n;++position){farthest=max(farthest,reach[position]);if(position==currentEnd){if(farthest<=position)return -1;++taps;currentEnd=farthest;if(currentEnd>=n)return taps;}}return taps;} };`)],tests:{schemaVersion:1,mode:'function',method:'minTaps',parameterTypes:['int','intArray'],returnType:'int',cases:[{name:'中心水龙头覆盖全园',args:[5,[3,4,1,1,0,0]],expected:1},{name:'所有水龙头无范围',args:[3,[0,0,0,0]],expected:-1},{name:'多个区间最少三只',args:[7,[1,2,1,0,2,1,0,1]],expected:3}]}},
{id:1328,slug:'break-a-palindrome',title:'破坏回文串',studyTags:['字符串','贪心'],summary:'把回文串恰好替换一个小写字母，使结果不是回文且字典序最小；不可能返回空串。',insight:'只需考虑前半部分：把最靠左的非 a 字符改成 a 会带来最大字典序下降且必破坏对称；若前半全是 a，则把最后字符改成 b 是最小增大。',pitfalls:['长度一无法通过一次替换得到非回文','奇数长度的中心字符不能靠单独修改破坏回文','只扫描前半不含中心'],solutions:[s('leftmost-non-a-or-last-b','首个非 a 或末尾 b','优先做最早的字典序下降，否则做最晚的最小上升。',['若 length==1 返回空','扫描 i<length/2，首个 chars[i]!=a 改 a 后返回','若没找到，把最后字符改为 b 并返回'],'O(n)','O(n)',
`class Solution { public String breakPalindrome(String palindrome){if(palindrome.length()==1)return "";char[] chars=palindrome.toCharArray();for(int i=0;i<chars.length/2;i++)if(chars[i]!='a'){chars[i]='a';return new String(chars);}chars[chars.length-1]='b';return new String(chars);} }`,
`class Solution { fun breakPalindrome(palindrome:String):String{if(palindrome.length==1)return "";val chars=palindrome.toCharArray();for(i in 0 until chars.size/2)if(chars[i]!='a'){chars[i]='a';return chars.concatToString()};chars[chars.lastIndex]='b';return chars.concatToString()} }`,
`class Solution { public: string breakPalindrome(string palindrome){if(palindrome.size()==1)return "";for(int i=0;i<(int)palindrome.size()/2;++i)if(palindrome[i]!='a'){palindrome[i]='a';return palindrome;}palindrome.back()='b';return palindrome;} };`)],tests:{schemaVersion:1,mode:'function',method:'breakPalindrome',parameterTypes:['string'],returnType:'string',cases:[{name:'最左非 a 改为 a',args:['abccba'],expected:'aaccba'},{name:'单字符无解',args:['a'],expected:''},{name:'全 a 改末尾为 b',args:['aa'],expected:'ab'}]}},
{id:1329,slug:'sort-the-matrix-diagonally',title:'将矩阵按对角线排序',studyTags:['数组','排序','矩阵'],summary:'把矩阵每条从左上到右下的对角线独立按升序排序并返回。',insight:'同一对角线的 r-c 相等；用该差作为键收集所有元素，排序后再按原遍历顺序逐个写回对应对角线。',pitfalls:['负的对角线键可直接用于哈希表','每条对角线独立排序','主对角线键为零'],solutions:[s('diagonal-key-buckets','对角线键分桶排序','按 r-c 分组、排序并回填。',['map 从 diagonal=r-c 到值列表，扫描矩阵收集','每个列表升序排序，并为每个键维护读取下标','再次按行列扫描，从对应列表取下一值写回，返回矩阵'],'O(rows·cols·log min(rows,cols))','O(rows·cols)',
`class Solution { public int[][] diagonalSort(int[][] mat){Map<Integer,List<Integer>> groups=new HashMap<>();for(int r=0;r<mat.length;r++)for(int c=0;c<mat[0].length;c++)groups.computeIfAbsent(r-c,key->new ArrayList<>()).add(mat[r][c]);for(List<Integer> values:groups.values())Collections.sort(values);Map<Integer,Integer> index=new HashMap<>();for(int r=0;r<mat.length;r++)for(int c=0;c<mat[0].length;c++){int key=r-c,position=index.getOrDefault(key,0);mat[r][c]=groups.get(key).get(position);index.put(key,position+1);}return mat;} }`,
`class Solution { fun diagonalSort(mat:Array<IntArray>):Array<IntArray>{val groups=mutableMapOf<Int,MutableList<Int>>();for(r in mat.indices)for(c in mat[0].indices)groups.getOrPut(r-c){mutableListOf()}.add(mat[r][c]);for(values in groups.values)values.sort();val index=mutableMapOf<Int,Int>();for(r in mat.indices)for(c in mat[0].indices){val key=r-c;val position=index[key]?:0;mat[r][c]=groups[key]!![position];index[key]=position+1};return mat} }`,
`class Solution { public: vector<vector<int>> diagonalSort(vector<vector<int>>& mat){unordered_map<int,vector<int>> groups;for(int r=0;r<(int)mat.size();++r)for(int c=0;c<(int)mat[0].size();++c)groups[r-c].push_back(mat[r][c]);for(auto& entry:groups)sort(entry.second.begin(),entry.second.end(),greater<int>());for(int r=0;r<(int)mat.size();++r)for(int c=0;c<(int)mat[0].size();++c){mat[r][c]=groups[r-c].back();groups[r-c].pop_back();}return mat;} };`)],tests:{schemaVersion:1,mode:'function',method:'diagonalSort',parameterTypes:['intMatrix'],returnType:'intMatrix',cases:[{name:'三乘四矩阵排序',args:[[[3,3,1,1],[2,2,1,2],[1,1,1,2]]],expected:[[1,1,1,1],[1,2,2,2],[1,2,3,3]]},{name:'单行保持不变',args:[[[4,3,2,1]]],expected:[[4,3,2,1]]},{name:'二阶主对角线交换',args:[[[5,2],[1,3]]],expected:[[3,2],[1,5]]}]}},
{id:1330,slug:'reverse-subarray-to-maximize-array-value',title:'翻转子数组得到最大的数组值',studyTags:['数组','数学','贪心'],summary:'数组价值为相邻元素绝对差之和，最多翻转一个连续子数组，求能得到的最大价值。',insight:'翻转内部相邻差不变，只改变区间两侧边界。枚举与数组端点相连的翻转收益；对于内部翻转，最大收益可化为两倍的“所有相邻对较小值最大值”减“较大值最小值”。',pitfalls:['允许不翻转，所以收益至少零','长度一翻转无影响','基础价值与收益用整数范围足够但公式需认真处理端点'],solutions:[s('boundary-gains-and-inner-extremes','端点收益与内部极值','线性汇总所有可能翻转的最大边界改善。',['base 累加所有 abs(nums[i]-nums[i+1])，gain=0','对每条相邻边，计算把前缀翻转到该边或把后缀从该边翻转的收益，更新 gain','同时维护 maxOfMin=max(min(a,b)) 与 minOfMax=min(max(a,b))；内部最大收益为 2*(maxOfMin-minOfMax)，更新 gain，返回 base+gain'],'O(n)','O(1)',
`class Solution { public int maxValueAfterReverse(int[] nums){int n=nums.length,base=0,gain=0,maxOfMin=Integer.MIN_VALUE,minOfMax=Integer.MAX_VALUE;for(int i=0;i<n-1;i++){int a=nums[i],b=nums[i+1],difference=Math.abs(a-b);base+=difference;gain=Math.max(gain,Math.abs(nums[0]-b)-difference);gain=Math.max(gain,Math.abs(nums[n-1]-a)-difference);maxOfMin=Math.max(maxOfMin,Math.min(a,b));minOfMax=Math.min(minOfMax,Math.max(a,b));}if(n>1)gain=Math.max(gain,2*(maxOfMin-minOfMax));return base+gain;} }`,
`class Solution { fun maxValueAfterReverse(nums:IntArray):Int{val n=nums.size;var base=0;var gain=0;var maxOfMin=Int.MIN_VALUE;var minOfMax=Int.MAX_VALUE;for(i in 0 until n-1){val a=nums[i];val b=nums[i+1];val difference=kotlin.math.abs(a-b);base+=difference;gain=maxOf(gain,kotlin.math.abs(nums[0]-b)-difference,kotlin.math.abs(nums[n-1]-a)-difference);maxOfMin=maxOf(maxOfMin,minOf(a,b));minOfMax=minOf(minOfMax,maxOf(a,b))};if(n>1)gain=maxOf(gain,2*(maxOfMin-minOfMax));return base+gain} }`,
`class Solution { public: int maxValueAfterReverse(vector<int>& nums){int n=nums.size(),base=0,gain=0,maxOfMin=INT_MIN,minOfMax=INT_MAX;for(int i=0;i<n-1;++i){int a=nums[i],b=nums[i+1],difference=abs(a-b);base+=difference;gain=max({gain,abs(nums[0]-b)-difference,abs(nums[n-1]-a)-difference});maxOfMin=max(maxOfMin,min(a,b));minOfMax=min(minOfMax,max(a,b));}if(n>1)gain=max(gain,2*(maxOfMin-minOfMax));return base+gain;} };`)],tests:{schemaVersion:1,mode:'function',method:'maxValueAfterReverse',parameterTypes:['intArray'],returnType:'int',cases:[{name:'翻转后价值十',args:[[2,3,1,5,4]],expected:10},{name:'复杂数组最大六十八',args:[[2,4,9,24,2,1,10]],expected:68},{name:'两个元素价值不变',args:[[1,2]],expected:1}]}}
]}
