const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-014',problems:[
{id:965,slug:'univalued-binary-tree',title:'单值二叉树',studyTags:['树','深度优先搜索','二叉树'],summary:'判断一棵非空二叉树的所有节点值是否都相同。',insight:'以根值为目标做深度优先遍历；任一节点值不同立即失败，空子树自然满足条件。',pitfalls:['左右子树都要验证','只有一个节点时返回真','可在发现不同值时短路'],solutions:[s('root-value-dfs','根值深度优先验证','递归检查每个节点是否等于根值。',['保存 target=root.val','递归函数遇空节点返回 true','非空节点要求 val==target 且左右递归均为 true'],'O(n)','O(height)',
`class Solution { public boolean isUnivalTree(TreeNode root){return check(root,root.val);}private boolean check(TreeNode node,int target){return node==null||node.val==target&&check(node.left,target)&&check(node.right,target);} }`,
`class Solution { fun isUnivalTree(root:TreeNode):Boolean=check(root,root.\`val\`);private fun check(node:TreeNode?,target:Int):Boolean=node==null||node.\`val\`==target&&check(node.left,target)&&check(node.right,target) }`,
`class Solution { bool check(TreeNode* node,int target){return !node||node->val==target&&check(node->left,target)&&check(node->right,target);}public:bool isUnivalTree(TreeNode* root){return check(root,root->val);} };`)],tests:{schemaVersion:1,mode:'function',method:'isUnivalTree',parameterTypes:['treeNode'],returnType:'boolean',cases:[{name:'所有节点为一',args:[[1,1,1,1,1,null,1]],expected:true},{name:'存在不同值',args:[[2,2,2,5,2]],expected:false},{name:'单节点',args:[[7]],expected:true}]}},
{id:966,slug:'vowel-spellchecker',title:'元音拼写检查器',studyTags:['数组','字符串','哈希表'],summary:'按精确匹配、忽略大小写、再把元音视为通配三档优先级，为每个查询返回词表中首个匹配单词或空串。',insight:'预处理三个索引：精确集合、小写键到首词、去元音键到首词；查询严格按优先级查找。',pitfalls:['同一键保留词表中最早单词','元音匹配同时忽略大小写','精确匹配必须返回查询本身的原拼写'],solutions:[s('three-level-normalized-index','三级规范化索引','为三种匹配规则建立从严到宽的查询结构。',['把 wordlist 加入 exact；lower 与 devowel 映射使用 putIfAbsent 保留首词','devowel 将小写 a/e/i/o/u 统一替换为 *','每个 query 先查 exact，再查 lower，再查 devowel，无匹配写空串'],'O(total characters)','O(total characters)',
`class Solution { public String[] spellchecker(String[] wordlist,String[] queries){Set<String> exact=new HashSet<>();Map<String,String> lower=new HashMap<>(),vowel=new HashMap<>();for(String word:wordlist){exact.add(word);String normalized=word.toLowerCase();lower.putIfAbsent(normalized,word);vowel.putIfAbsent(mask(normalized),word);}String[] answer=new String[queries.length];for(int i=0;i<queries.length;i++){String query=queries[i],normalized=query.toLowerCase();if(exact.contains(query))answer[i]=query;else if(lower.containsKey(normalized))answer[i]=lower.get(normalized);else answer[i]=vowel.getOrDefault(mask(normalized),"");}return answer;}private String mask(String word){return word.replaceAll("[aeiou]","*");} }`,
`class Solution { fun spellchecker(wordlist:Array<String>,queries:Array<String>):Array<String>{val exact=wordlist.toHashSet();val lower=mutableMapOf<String,String>();val vowel=mutableMapOf<String,String>();fun mask(word:String):String{return word.map{if(it in "aeiou")'*' else it}.joinToString("")};for(word in wordlist){val normalized=word.lowercase();lower.putIfAbsent(normalized,word);vowel.putIfAbsent(mask(normalized),word)};return Array(queries.size){i->val query=queries[i];val normalized=query.lowercase();when{query in exact->query;normalized in lower->lower[normalized]!!;else->vowel[mask(normalized)]?:""}}} }`,
`class Solution { string mask(string word){for(char& ch:word)if(string("aeiou").find(ch)!=string::npos)ch='*';return word;}public:vector<string> spellchecker(vector<string>& wordlist,vector<string>& queries){unordered_set<string> exact(wordlist.begin(),wordlist.end());unordered_map<string,string> lower,vowel;for(string word:wordlist){string normalized=word;transform(normalized.begin(),normalized.end(),normalized.begin(),::tolower);if(!lower.count(normalized))lower[normalized]=word;string key=mask(normalized);if(!vowel.count(key))vowel[key]=word;}vector<string> answer;for(string query:queries){string normalized=query;transform(normalized.begin(),normalized.end(),normalized.begin(),::tolower);if(exact.count(query))answer.push_back(query);else if(lower.count(normalized))answer.push_back(lower[normalized]);else answer.push_back(vowel.count(mask(normalized))?vowel[mask(normalized)]:"");}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'spellchecker',parameterTypes:['stringArray','stringArray'],returnType:'stringArray',cases:[{name:'经典优先级查询',args:[['KiTe','kite','hare','Hare'],['kite','Kite','KiTe','Hare','HARE','Hear','hear','keti','keet','keto']],expected:['kite','KiTe','KiTe','Hare','hare','','','KiTe','','KiTe']},{name:'精确优先于小写',args:[['Yellow','yellow'],['yellow','YELLOW']],expected:['yellow','Yellow']},{name:'无匹配返回空',args:[['apple'],['orange']],expected:['']}]}},
{id:967,slug:'numbers-with-same-consecutive-differences',title:'连续差相同的数字',studyTags:['广度优先搜索','回溯','数学'],summary:'返回所有长度为 n、无前导零且相邻数字绝对差为 k 的非负整数；n=1 时零也合法。',insight:'从首位 1 到 9 开始逐位扩展，末位 d 的下一位只能是 d+k 或 d-k；k=0 时去重即可。',pitfalls:['多位数首位不能为零','n=1 要额外包含零','d+k 与 d-k 相同不能重复加入'],solutions:[s('digit-layer-bfs','逐位数字 BFS','逐层为现有数字追加合法末位。',['n=1 返回 0..9，否则列表初始化 1..9','重复 n-1 次，对每个 number 取 last','尝试 last+k 与 last-k，范围 0..9 且去重后生成 number*10+digit；返回数组'],'O(result size)','O(result size)',
`class Solution { public int[] numsSameConsecDiff(int n,int k){if(n==1)return new int[]{0,1,2,3,4,5,6,7,8,9};List<Integer> values=new ArrayList<>();for(int digit=1;digit<=9;digit++)values.add(digit);for(int length=1;length<n;length++){List<Integer> next=new ArrayList<>();for(int value:values){int last=value%10;int a=last+k,b=last-k;if(a<10)next.add(value*10+a);if(b>=0&&b!=a)next.add(value*10+b);}values=next;}return values.stream().mapToInt(Integer::intValue).toArray();} }`,
`class Solution { fun numsSameConsecDiff(n:Int,k:Int):IntArray{if(n==1)return IntArray(10){it};var values=(1..9).toList();repeat(n-1){val next=mutableListOf<Int>();for(value in values){val last=value%10;val a=last+k;val b=last-k;if(a<10)next.add(value*10+a);if(b>=0&&b!=a)next.add(value*10+b)};values=next};return values.toIntArray()} }`,
`class Solution { public: vector<int> numsSameConsecDiff(int n,int k){if(n==1)return {0,1,2,3,4,5,6,7,8,9};vector<int> values{1,2,3,4,5,6,7,8,9};for(int length=1;length<n;++length){vector<int> next;for(int value:values){int last=value%10,a=last+k,b=last-k;if(a<10)next.push_back(value*10+a);if(b>=0&&b!=a)next.push_back(value*10+b);}values.swap(next);}return values;} };`)],tests:{schemaVersion:1,mode:'function',method:'numsSameConsecDiff',parameterTypes:['int','int'],returnType:'intArray',cases:[{name:'三位差七',args:[3,7],expected:[181,292,707,818,929]},{name:'两位差零',args:[2,0],expected:[11,22,33,44,55,66,77,88,99]},{name:'一位包含零',args:[1,5],expected:[0,1,2,3,4,5,6,7,8,9]}]}},
{id:968,slug:'binary-tree-cameras',title:'监控二叉树',studyTags:['树','深度优先搜索','贪心'],summary:'摄像头可监控自身、父节点和直接孩子，求覆盖整棵二叉树所需最少摄像头数。',insight:'后序遍历让孩子先决定状态；若任一孩子未覆盖，当前节点必须装摄像头；若孩子有摄像头，当前已覆盖，否则把当前留给父节点。',pitfalls:['空节点视为已覆盖且无需摄像头','根遍历结束仍未覆盖时要补一个摄像头','三个状态要区分摄像头与仅被覆盖'],solutions:[s('postorder-three-state-greedy','后序三状态贪心','自底向上只在孩子未覆盖时放置摄像头。',['定义 0=未覆盖、1=有摄像头、2=已覆盖；空节点返回 2','后序取左右状态；任一为 0 时 cameras++ 并返回 1','任一为 1 返回 2，否则返回 0；根若返回 0 再加一'],'O(n)','O(height)',
`class Solution { private int cameras=0;public int minCameraCover(TreeNode root){if(state(root)==0)cameras++;return cameras;}private int state(TreeNode node){if(node==null)return 2;int left=state(node.left),right=state(node.right);if(left==0||right==0){cameras++;return 1;}if(left==1||right==1)return 2;return 0;} }`,
`class Solution { private var cameras=0;fun minCameraCover(root:TreeNode?):Int{if(state(root)==0)cameras++;return cameras};private fun state(node:TreeNode?):Int{node?:return 2;val left=state(node.left);val right=state(node.right);if(left==0||right==0){cameras++;return 1};if(left==1||right==1)return 2;return 0} }`,
`class Solution { int cameras=0;int state(TreeNode* node){if(!node)return 2;int left=state(node->left),right=state(node->right);if(left==0||right==0){++cameras;return 1;}if(left==1||right==1)return 2;return 0;}public:int minCameraCover(TreeNode* root){if(state(root)==0)++cameras;return cameras;} };`)],tests:{schemaVersion:1,mode:'function',method:'minCameraCover',parameterTypes:['treeNode'],returnType:'int',cases:[{name:'父节点一个摄像头覆盖',args:[[0,0,null,0,0]],expected:1},{name:'长链需要两个',args:[[0,0,null,0,null,0]],expected:2},{name:'单节点需要一个',args:[[0]],expected:1}]}},
{id:969,slug:'pancake-sorting',title:'煎饼排序',studyTags:['数组','贪心','排序'],summary:'每次可翻转数组前 k 个元素，返回一组不超过十倍长度的翻转序列把排列升序排列。',insight:'从目标末位向前处理：在未排序前缀中找到最大值，先把它翻到顶部，再翻到当前末位；已在末位则跳过。',pitfalls:['返回的是每次翻转长度而非下标','最大值在顶部时只需第二次翻转','已放到后缀的元素不再参与后续翻转'],solutions:[s('place-maximum-by-two-flips','两次翻转放置最大值','逐步把当前最大值固定到未排序前缀末尾。',['size 从 n 降到二，在 [0,size) 找最大值下标 index','若 index==size-1 跳过；若 index>0，翻转 index+1 并记录','翻转 size 并记录；最终返回记录数组'],'O(n²)','O(n)',
`class Solution { public List<Integer> pancakeSort(int[] arr){List<Integer> moves=new ArrayList<>();for(int size=arr.length;size>1;size--){int index=0;for(int i=1;i<size;i++)if(arr[i]>arr[index])index=i;if(index==size-1)continue;if(index>0){flip(arr,index+1);moves.add(index+1);}flip(arr,size);moves.add(size);}return moves;}private void flip(int[] arr,int length){for(int left=0,right=length-1;left<right;left++,right--){int temporary=arr[left];arr[left]=arr[right];arr[right]=temporary;}} }`,
`class Solution { fun pancakeSort(arr:IntArray):List<Int>{val moves=mutableListOf<Int>();fun flip(length:Int){var left=0;var right=length-1;while(left<right){val temporary=arr[left];arr[left++]=arr[right];arr[right--]=temporary}};for(size in arr.size downTo 2){var index=0;for(i in 1 until size)if(arr[i]>arr[index])index=i;if(index==size-1)continue;if(index>0){flip(index+1);moves.add(index+1)};flip(size);moves.add(size)};return moves} }`,
`class Solution { void flip(vector<int>& arr,int length){reverse(arr.begin(),arr.begin()+length);}public:vector<int> pancakeSort(vector<int>& arr){vector<int> moves;for(int size=arr.size();size>1;--size){int index=max_element(arr.begin(),arr.begin()+size)-arr.begin();if(index==size-1)continue;if(index>0){flip(arr,index+1);moves.push_back(index+1);}flip(arr,size);moves.push_back(size);}return moves;} };`)],tests:{schemaVersion:1,mode:'function',method:'pancakeSort',parameterTypes:['intArray'],returnType:'intList',cases:[{name:'四元素排列',args:[[3,2,4,1]],expected:[3,4,2,3,2]},{name:'已经升序',args:[[1,2,3]],expected:[]},{name:'交换前两项',args:[[2,1,3]],expected:[2]}]}}
]}
