const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-014',problems:[
{id:1000,slug:'minimum-cost-to-merge-stones',title:'合并石头的最低成本',studyTags:['数组','动态规划','区间动态规划','前缀和'],summary:'每次把连续 k 堆石头合成一堆，代价为这些石头总数，求把全部合成一堆的最低总代价；无解返回负一。',insight:'每次堆数减少 k-1，因此先判可行性；区间 DP 用步长 k-1 枚举切点，把区间尽可能合并，只有区间长度满足可再合成一堆时才加区间总和。',pitfalls:['全局可行条件是 (n-1)%(k-1)==0','切点按 k-1 递增以保证左右状态堆数兼容','并非每个区间都能最终合成一堆'],solutions:[s('interval-dp-with-pile-congruence','堆数同余区间动态规划','按区间长度合并兼容子区间并在可归一时付总和。',['不可行直接返回 -1，构建前缀和与 dp[n][n]','length 从 2 到 n；对区间 [left,right]，mid 从 left 按 k-1 跳到 right-1，取 dp[left][mid]+dp[mid+1][right] 最小值','若 (length-1)%(k-1)==0，再加区间和；返回 dp[0][n-1]'],'O(n³/k)','O(n²)',
`class Solution { public int mergeStones(int[] stones,int k){int n=stones.length;if((n-1)%(k-1)!=0)return -1;int[] prefix=new int[n+1];for(int i=0;i<n;i++)prefix[i+1]=prefix[i]+stones[i];int[][] dp=new int[n][n];for(int length=2;length<=n;length++)for(int left=0;left+length<=n;left++){int right=left+length-1;dp[left][right]=Integer.MAX_VALUE/2;for(int middle=left;middle<right;middle+=k-1)dp[left][right]=Math.min(dp[left][right],dp[left][middle]+dp[middle+1][right]);if((length-1)%(k-1)==0)dp[left][right]+=prefix[right+1]-prefix[left];}return dp[0][n-1];} }`,
`class Solution { fun mergeStones(stones:IntArray,k:Int):Int{val n=stones.size;if((n-1)%(k-1)!=0)return -1;val prefix=IntArray(n+1);for(i in stones.indices)prefix[i+1]=prefix[i]+stones[i];val dp=Array(n){IntArray(n)};for(length in 2..n)for(left in 0..n-length){val right=left+length-1;dp[left][right]=Int.MAX_VALUE/2;var middle=left;while(middle<right){dp[left][right]=minOf(dp[left][right],dp[left][middle]+dp[middle+1][right]);middle+=k-1};if((length-1)%(k-1)==0)dp[left][right]+=prefix[right+1]-prefix[left]};return dp[0][n-1]} }`,
`class Solution { public: int mergeStones(vector<int>& stones,int k){int n=stones.size();if((n-1)%(k-1))return -1;vector<int> prefix(n+1);for(int i=0;i<n;++i)prefix[i+1]=prefix[i]+stones[i];vector<vector<int>> dp(n,vector<int>(n));for(int length=2;length<=n;++length)for(int left=0;left+length<=n;++left){int right=left+length-1;dp[left][right]=INT_MAX/2;for(int middle=left;middle<right;middle+=k-1)dp[left][right]=min(dp[left][right],dp[left][middle]+dp[middle+1][right]);if((length-1)%(k-1)==0)dp[left][right]+=prefix[right+1]-prefix[left];}return dp[0][n-1];} };`)],tests:{schemaVersion:1,mode:'function',method:'mergeStones',parameterTypes:['intArray','int'],returnType:'int',cases:[{name:'两两合并成本二十',args:[[3,2,4,1],2],expected:20},{name:'四堆无法三合一',args:[[3,2,4,1],3],expected:-1},{name:'三合一成本二十五',args:[[3,5,1,2,6],3],expected:25}]}},
{id:1001,slug:'grid-illumination',title:'网格照明',studyTags:['数组','哈希表','模拟'],summary:'n×n 网格上若某格同行、同列或同对角线有亮灯则被照亮；每次查询返回照明状态，随后关闭查询格及其八个邻格的灯。',insight:'不展开巨大网格；用集合保存活跃灯，并分别计数行、列、主对角线 r-c、副对角线 r+c 上灯数，查询 O(1)，关闭局部九格时同步减计数。',pitfalls:['重复灯坐标只算一盏','无论查询是否照亮都要执行关灯操作','主对角线键可能为负数'],solutions:[s('active-lamp-line-counters','活跃灯集合与四类线计数','用稀疏哈希结构维护照明与局部删除。',['遍历 lamps，若编码坐标首次加入 active，则递增 row、column、diag、anti 计数','对查询 (r,c)，任一对应计数大于零则答案一','枚举 dr,dc∈[-1,1] 的有效邻格；若 active 删除成功，同步四类计数减一'],'O(lamps+queries)','O(lamps)',
`class Solution { public int[] gridIllumination(int n,int[][] lamps,int[][] queries){Set<Long> active=new HashSet<>();Map<Integer,Integer> rows=new HashMap<>(),columns=new HashMap<>(),diagonals=new HashMap<>(),antis=new HashMap<>();for(int[] lamp:lamps)if(active.add(key(lamp[0],lamp[1]))){add(rows,lamp[0],1);add(columns,lamp[1],1);add(diagonals,lamp[0]-lamp[1],1);add(antis,lamp[0]+lamp[1],1);}int[] answer=new int[queries.length];for(int i=0;i<queries.length;i++){int r=queries[i][0],c=queries[i][1];answer[i]=rows.getOrDefault(r,0)>0||columns.getOrDefault(c,0)>0||diagonals.getOrDefault(r-c,0)>0||antis.getOrDefault(r+c,0)>0?1:0;for(int dr=-1;dr<=1;dr++)for(int dc=-1;dc<=1;dc++){int nr=r+dr,nc=c+dc;if(nr>=0&&nr<n&&nc>=0&&nc<n&&active.remove(key(nr,nc))){add(rows,nr,-1);add(columns,nc,-1);add(diagonals,nr-nc,-1);add(antis,nr+nc,-1);}}}return answer;}private long key(int r,int c){return((long)r<<32)^(c&0xffffffffL);}private void add(Map<Integer,Integer> map,int key,int delta){map.put(key,map.getOrDefault(key,0)+delta);} }`,
`class Solution { fun gridIllumination(n:Int,lamps:Array<IntArray>,queries:Array<IntArray>):IntArray{fun key(r:Int,c:Int):Long{return (r.toLong() shl 32) xor (c.toLong() and 0xffffffffL)};val active=mutableSetOf<Long>();val rows=mutableMapOf<Int,Int>();val columns=mutableMapOf<Int,Int>();val diagonals=mutableMapOf<Int,Int>();val antis=mutableMapOf<Int,Int>();fun add(map:MutableMap<Int,Int>,line:Int,delta:Int){map[line]=(map[line]?:0)+delta};for(lamp in lamps)if(active.add(key(lamp[0],lamp[1]))){add(rows,lamp[0],1);add(columns,lamp[1],1);add(diagonals,lamp[0]-lamp[1],1);add(antis,lamp[0]+lamp[1],1)};return IntArray(queries.size){i->val r=queries[i][0];val c=queries[i][1];val illuminated=if((rows[r]?:0)>0||(columns[c]?:0)>0||(diagonals[r-c]?:0)>0||(antis[r+c]?:0)>0)1 else 0;for(dr in -1..1)for(dc in -1..1){val nr=r+dr;val nc=c+dc;if(nr in 0 until n&&nc in 0 until n&&active.remove(key(nr,nc))){add(rows,nr,-1);add(columns,nc,-1);add(diagonals,nr-nc,-1);add(antis,nr+nc,-1)}};illuminated}} }`,
`class Solution { long long key(int r,int c){return((long long)r<<32)^(unsigned int)c;}void add(unordered_map<int,int>& map,int line,int delta){map[line]+=delta;}public:vector<int> gridIllumination(int n,vector<vector<int>>& lamps,vector<vector<int>>& queries){unordered_set<long long> active;unordered_map<int,int> rows,columns,diagonals,antis;for(auto& lamp:lamps)if(active.insert(key(lamp[0],lamp[1])).second){add(rows,lamp[0],1);add(columns,lamp[1],1);add(diagonals,lamp[0]-lamp[1],1);add(antis,lamp[0]+lamp[1],1);}vector<int> answer;for(auto& query:queries){int r=query[0],c=query[1];answer.push_back(rows[r]>0||columns[c]>0||diagonals[r-c]>0||antis[r+c]>0);for(int dr=-1;dr<=1;++dr)for(int dc=-1;dc<=1;++dc){int nr=r+dr,nc=c+dc;if(nr>=0&&nr<n&&nc>=0&&nc<n&&active.erase(key(nr,nc))){add(rows,nr,-1);add(columns,nc,-1);add(diagonals,nr-nc,-1);add(antis,nr+nc,-1);}}}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'gridIllumination',parameterTypes:['int','intMatrix','intMatrix'],returnType:'intArray',cases:[{name:'经典两次查询',args:[5,[[0,0],[4,4]],[[1,1],[1,0]]],expected:[1,0]},{name:'查询关闭邻近灯',args:[3,[[1,1]],[[0,0],[2,2]]],expected:[1,0]},{name:'重复灯只计一次',args:[2,[[0,0],[0,0]],[[1,1]]],expected:[1]}]}},
{id:1002,slug:'find-common-characters',title:'查找共用字符',studyTags:['数组','字符串','计数'],summary:'返回字符串数组中所有字符串都出现的字符，重复次数取各字符串出现次数的最小值，顺序任意。',insight:'维护二十六个字符的全局最小频次；每个单词单独计数后逐位取最小，最后按频次输出字符。',pitfalls:['重复字符要重复输出','初始最小频次可设为很大或首词频次','比较区分小写字母'],solutions:[s('minimum-letter-frequency','字符最小频次','逐词收紧每个字母可共同出现的次数。',['minimum[26] 初始化为极大值','对每个 word 统计 frequency[26]，再令 minimum[i]=min(minimum[i],frequency[i])','按 a 到 z，把每个字符重复 minimum 次加入结果'],'O(total characters+26m)','O(1)',
`class Solution { public List<String> commonChars(String[] words){int[] minimum=new int[26];Arrays.fill(minimum,Integer.MAX_VALUE);for(String word:words){int[] frequency=new int[26];for(char ch:word.toCharArray())frequency[ch-'a']++;for(int i=0;i<26;i++)minimum[i]=Math.min(minimum[i],frequency[i]);}List<String> answer=new ArrayList<>();for(int i=0;i<26;i++)for(int count=0;count<minimum[i];count++)answer.add(String.valueOf((char)('a'+i)));return answer;} }`,
`class Solution { fun commonChars(words:Array<String>):List<String>{val minimum=IntArray(26){Int.MAX_VALUE};for(word in words){val frequency=IntArray(26);for(ch in word)frequency[ch-'a']++;for(i in 0..25)minimum[i]=minOf(minimum[i],frequency[i])};val answer=mutableListOf<String>();for(i in 0..25)repeat(minimum[i]){answer.add(('a'.code+i).toChar().toString())};return answer} }`,
`class Solution { public: vector<string> commonChars(vector<string>& words){vector<int> minimum(26,INT_MAX);for(string& word:words){vector<int> frequency(26);for(char ch:word)++frequency[ch-'a'];for(int i=0;i<26;++i)minimum[i]=min(minimum[i],frequency[i]);}vector<string> answer;for(int i=0;i<26;++i)for(int count=0;count<minimum[i];++count)answer.push_back(string(1,'a'+i));return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'commonChars',parameterTypes:['stringArray'],returnType:'stringList',cases:[{name:'bella 集合',args:[['bella','label','roller']],expected:['e','l','l']},{name:'cool 集合',args:[['cool','lock','cook']],expected:['c','o']},{name:'没有共同字符',args:[['a','b']],expected:[]}]}},
{id:1003,slug:'check-if-word-is-valid-after-substitutions',title:'检查替换后的词是否有效',studyTags:['字符串','栈'],summary:'从空串开始可在任意位置插入 abc，判断给定字符串能否通过若干次插入得到。',insight:'顺序扫描把字符压栈；每当栈顶三个字符恰为 abc 就立即消去，等价于逆序撤销一次插入，最终栈空则有效。',pitfalls:['abc 可嵌套或并列出现','必须检查栈长度至少三','消除后可能与前缀组成新的 abc，但当前字符触发的循环已由逐次扫描覆盖'],solutions:[s('abc-reduction-stack','abc 消除栈','在线撤销所有可见的合法插入块。',['StringBuilder 作为栈','逐字符追加','若末三字符是 a,b,c，则把长度缩短三；扫描结束返回栈是否为空'],'O(n)','O(n)',
`class Solution { public boolean isValid(String s){StringBuilder stack=new StringBuilder();for(char ch:s.toCharArray()){stack.append(ch);int n=stack.length();if(n>=3&&stack.charAt(n-3)=='a'&&stack.charAt(n-2)=='b'&&stack.charAt(n-1)=='c')stack.setLength(n-3);}return stack.length()==0;} }`,
`class Solution { fun isValid(s:String):Boolean{val stack=StringBuilder();for(ch in s){stack.append(ch);val n=stack.length;if(n>=3&&stack[n-3]=='a'&&stack[n-2]=='b'&&stack[n-1]=='c')stack.setLength(n-3)};return stack.isEmpty()} }`,
`class Solution { public: bool isValid(string s){string stack;for(char ch:s){stack+=ch;int n=stack.size();if(n>=3&&stack[n-3]=='a'&&stack[n-2]=='b'&&stack[n-1]=='c')stack.resize(n-3);}return stack.empty();} };`)],tests:{schemaVersion:1,mode:'function',method:'isValid',parameterTypes:['string'],returnType:'boolean',cases:[{name:'嵌套有效串',args:['aabcbc'],expected:true},{name:'多次插入有效',args:['abcabcababcc'],expected:true},{name:'顺序错误',args:['abccba'],expected:false}]}},
{id:1004,slug:'max-consecutive-ones-iii',title:'最大连续 1 的个数 III',studyTags:['数组','滑动窗口'],summary:'最多把 k 个零翻成一，求数组中可得到的最长连续一段。',insight:'等价于寻找含零数不超过 k 的最长子数组；右端扩张计零，超过限制时移动左端直到重新合法。',pitfalls:['k 可以为零','窗口中一的数量无需单独维护','每个元素最多进出窗口一次'],solutions:[s('zero-budget-sliding-window','零预算滑动窗口','维护窗口内零数不超过可翻转预算。',['left=0,zeros=0,answer=0','右指针扫描，遇零 zeros++','zeros>k 时移动 left，移出的值为零则 zeros--；更新窗口长度最大值'],'O(n)','O(1)',
`class Solution { public int longestOnes(int[] nums,int k){int left=0,zeros=0,answer=0;for(int right=0;right<nums.length;right++){if(nums[right]==0)zeros++;while(zeros>k)if(nums[left++]==0)zeros--;answer=Math.max(answer,right-left+1);}return answer;} }`,
`class Solution { fun longestOnes(nums:IntArray,k:Int):Int{var left=0;var zeros=0;var answer=0;for(right in nums.indices){if(nums[right]==0)zeros++;while(zeros>k)if(nums[left++]==0)zeros--;answer=maxOf(answer,right-left+1)};return answer} }`,
`class Solution { public: int longestOnes(vector<int>& nums,int k){int left=0,zeros=0,answer=0;for(int right=0;right<(int)nums.size();++right){if(nums[right]==0)++zeros;while(zeros>k)if(nums[left++]==0)--zeros;answer=max(answer,right-left+1);}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'longestOnes',parameterTypes:['intArray','int'],returnType:'int',cases:[{name:'翻两个零得六',args:[[1,1,1,0,0,0,1,1,1,1,0],2],expected:6},{name:'翻三个零得十一',args:[[0,0,1,1,1,0,0,1,1,0,1,1,1,0,0,0,1,1,1,1],3],expected:11},{name:'不能翻零',args:[[1,1,0,1],0],expected:2}]}}
]}
