const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-021',problems:[
{id:1497,slug:'check-if-array-pairs-are-divisible-by-k',title:'检查数组对是否可被 K 整除',studyTags:['数组','哈希表','计数'],summary:'把偶数长度数组配成若干对，判断能否让每对元素和都被 k 整除。',insight:'余数 r 只能与 k-r 配对；余数零必须有偶数个，当 k 为偶数时余数 k/2 也必须为偶数。',pitfalls:['负数余数要规范到零至 k-1','互补余数频次必须相等','自互补余数检查偶数性'],solutions:[s('complementary-remainder-counts','互补余数计数','用模 k 频次验证所有配对需求。',['count[normalized(value%k)]++','count[0] 必须偶数','对 r=1..k-1，若 r==k-r 则 count[r] 偶数，否则 count[r]==count[k-r]'],'O(n+k)','O(k)',
`class Solution { public boolean canArrange(int[] arr,int k){int[] count=new int[k];for(int value:arr)count[((value%k)+k)%k]++;if(count[0]%2!=0)return false;for(int remainder=1;remainder<k;remainder++)if(remainder==k-remainder){if(count[remainder]%2!=0)return false;}else if(count[remainder]!=count[k-remainder])return false;return true;} }`,
`class Solution { fun canArrange(arr:IntArray,k:Int):Boolean{val count=IntArray(k);for(value in arr)count[((value%k)+k)%k]++;if(count[0]%2!=0)return false;for(remainder in 1 until k)if(remainder==k-remainder){if(count[remainder]%2!=0)return false}else if(count[remainder]!=count[k-remainder])return false;return true} }`,
`class Solution { public: bool canArrange(vector<int>& arr,int k){vector<int> count(k);for(int value:arr)++count[(value%k+k)%k];if(count[0]%2)return false;for(int remainder=1;remainder<k;++remainder)if(remainder==k-remainder){if(count[remainder]%2)return false;}else if(count[remainder]!=count[k-remainder])return false;return true;} };`)],tests:{schemaVersion:1,mode:'function',method:'canArrange',parameterTypes:['intArray','int'],returnType:'boolean',cases:[{name:'十个数可配成五的倍数',args:[[1,2,3,4,5,10,6,7,8,9],5],expected:true},{name:'一至六可配成七的倍数',args:[[1,2,3,4,5,6],7],expected:true},{name:'无法配成十的倍数',args:[[1,2,3,4,5,6],10],expected:false}]}},
{id:1498,slug:'number-of-subsequences-that-satisfy-the-given-sum-condition',title:'满足条件的子序列数目',studyTags:['数组','双指针','排序'],summary:'统计非空子序列，使其中最小值与最大值之和不超过 target，结果取模。',insight:'排序后用左右指针。若 nums[left]+nums[right]<=target，以 left 为最小值、从中间元素任取的子序列共有 2^(right-left) 个；否则最大值过大。',pitfalls:['子序列按下标选择计数','需要预计算二的幂并取模','满足时移动左指针，不满足时移动右指针'],solutions:[s('sorted-two-pointers-powers','排序双指针与二次幂','固定当前最小值时一次计数所有可选其余元素。',['排序 nums，pow2[i]=2^i mod MOD','left=0,right=n-1','和不超过 target 时 answer+=pow2[right-left],left++；否则 right--'],'O(n log n)','O(n)',
`class Solution { public int numSubseq(int[] nums,int target){Arrays.sort(nums);int n=nums.length,mod=1_000_000_007;long[] powers=new long[n];powers[0]=1;for(int i=1;i<n;i++)powers[i]=powers[i-1]*2%mod;int left=0,right=n-1;long answer=0;while(left<=right)if(nums[left]+nums[right]<=target){answer=(answer+powers[right-left])%mod;left++;}else right--;return (int)answer;} }`,
`class Solution { fun numSubseq(nums:IntArray,target:Int):Int{nums.sort();val mod=1_000_000_007L;val powers=LongArray(nums.size);powers[0]=1;for(i in 1 until nums.size)powers[i]=powers[i-1]*2%mod;var left=0;var right=nums.lastIndex;var answer=0L;while(left<=right)if(nums[left]+nums[right]<=target){answer=(answer+powers[right-left])%mod;left++}else right--;return answer.toInt()} }`,
`class Solution { public: int numSubseq(vector<int>& nums,int target){sort(nums.begin(),nums.end());const long long mod=1000000007;vector<long long> powers(nums.size(),1);for(int i=1;i<(int)nums.size();++i)powers[i]=powers[i-1]*2%mod;int left=0,right=nums.size()-1;long long answer=0;while(left<=right)if(nums[left]+nums[right]<=target){answer=(answer+powers[right-left])%mod;++left;}else --right;return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'numSubseq',parameterTypes:['intArray','int'],returnType:'int',cases:[{name:'三五六七目标九有四个',args:[[3,5,6,7],9],expected:4},{name:'含重复三目标十有六个',args:[[3,3,6,8],10],expected:6},{name:'六元素目标十二有六十一',args:[[2,3,3,4,6,7],12],expected:61}]}},
{id:1499,slug:'max-value-of-equation',title:'满足不等式的最大值',studyTags:['数组','队列','滑动窗口','单调队列'],summary:'点按 x 严格递增，选择 xi<xj 且 xj-xi<=k，最大化 yi+yj+|xi-xj|。',insight:'式子化为 (yi-xi)+(yj+xj)。扫描 j 时用递减双端队列维护距离窗口内最大的 yi-xi。',pitfalls:['先移除与当前 x 距离超过 k 的旧点','队列按 yi-xi 递减','点的 x 已按严格递增给出'],solutions:[s('monotonic-deque-transformation','公式变形与单调队列','把二元式拆成当前项和窗口历史最大项。',['deque 存下标且 points[i].y-points[i].x 递减','扫描 j，移除 xj-xfront>k','队首存在时用 yj+xj+yfront-xfront 更新答案；再维护递减性并加入 j'],'O(n)','O(n)',
`class Solution { public int findMaxValueOfEquation(int[][] points,int k){Deque<Integer> deque=new ArrayDeque<>();int answer=Integer.MIN_VALUE;for(int j=0;j<points.length;j++){while(!deque.isEmpty()&&points[j][0]-points[deque.peekFirst()][0]>k)deque.removeFirst();if(!deque.isEmpty()){int i=deque.peekFirst();answer=Math.max(answer,points[j][1]+points[j][0]+points[i][1]-points[i][0]);}int value=points[j][1]-points[j][0];while(!deque.isEmpty()&&points[deque.peekLast()][1]-points[deque.peekLast()][0]<=value)deque.removeLast();deque.addLast(j);}return answer;} }`,
`class Solution { fun findMaxValueOfEquation(points:Array<IntArray>,k:Int):Int{val deque=java.util.ArrayDeque<Int>();var answer=Int.MIN_VALUE;for(j in points.indices){while(deque.isNotEmpty()&&points[j][0]-points[deque.peekFirst()][0]>k)deque.removeFirst();if(deque.isNotEmpty()){val i=deque.peekFirst();answer=maxOf(answer,points[j][1]+points[j][0]+points[i][1]-points[i][0])};val value=points[j][1]-points[j][0];while(deque.isNotEmpty()&&points[deque.peekLast()][1]-points[deque.peekLast()][0]<=value)deque.removeLast();deque.addLast(j)};return answer} }`,
`class Solution { public: int findMaxValueOfEquation(vector<vector<int>>& points,int k){deque<int> pending;int answer=INT_MIN;for(int j=0;j<(int)points.size();++j){while(!pending.empty()&&points[j][0]-points[pending.front()][0]>k)pending.pop_front();if(!pending.empty()){int i=pending.front();answer=max(answer,points[j][1]+points[j][0]+points[i][1]-points[i][0]);}int value=points[j][1]-points[j][0];while(!pending.empty()&&points[pending.back()][1]-points[pending.back()][0]<=value)pending.pop_back();pending.push_back(j);}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'findMaxValueOfEquation',parameterTypes:['intMatrix','int'],returnType:'int',cases:[{name:'距离一最大值四',args:[[[1,3],[2,0],[5,10],[6,-10]],1],expected:4},{name:'距离三选择前两点',args:[[[0,0],[3,0],[9,2]],3],expected:3},{name:'首尾点距离二得到六',args:[[[1,1],[2,2],[3,3]],2],expected:6}]}},
{id:1502,slug:'can-make-arithmetic-progression-from-sequence',title:'判断能否形成等差数列',studyTags:['数组','排序'],summary:'判断数组重排后能否使相邻元素差值全部相同。',insight:'升序排序后等差数列顺序唯一，只需比较每个相邻差与首个差。',pitfalls:['差值可为零或负数但排序后非负','数组至少两个元素','重复元素全部相同时也合法'],solutions:[s('sorted-difference-check','排序后差值检查','把重排问题规范为升序相邻比较。',['排序 arr','difference=arr[1]-arr[0]','i 从二开始，若 arr[i]-arr[i-1]!=difference 返回 false，否则最终 true'],'O(n log n)','O(log n)',
`class Solution { public boolean canMakeArithmeticProgression(int[] arr){Arrays.sort(arr);int difference=arr[1]-arr[0];for(int i=2;i<arr.length;i++)if(arr[i]-arr[i-1]!=difference)return false;return true;} }`,
`class Solution { fun canMakeArithmeticProgression(arr:IntArray):Boolean{arr.sort();val difference=arr[1]-arr[0];return (2 until arr.size).all{arr[it]-arr[it-1]==difference}} }`,
`class Solution { public: bool canMakeArithmeticProgression(vector<int>& arr){sort(arr.begin(),arr.end());int difference=arr[1]-arr[0];for(int i=2;i<(int)arr.size();++i)if(arr[i]-arr[i-1]!=difference)return false;return true;} };`)],tests:{schemaVersion:1,mode:'function',method:'canMakeArithmeticProgression',parameterTypes:['intArray'],returnType:'boolean',cases:[{name:'三一五可排为等差',args:[[3,5,1]],expected:true},{name:'一二四差值不同',args:[[1,2,4]],expected:false},{name:'全部相等差为零',args:[[7,7,7]],expected:true}]}},
{id:1503,slug:'last-moment-before-all-ants-fall-out-of-a-plank',title:'所有蚂蚁掉下木板前的最后一刻',studyTags:['数组','脑筋急转弯','模拟'],summary:'蚂蚁以单位速度在长度 n 木板上移动，相遇时各自反向，求最后一只掉落时刻。',insight:'相遇反向等价于两只蚂蚁穿过彼此并交换身份，所以只需看每只左行蚂蚁到零的距离和右行蚂蚁到 n 的距离。',pitfalls:['身份交换不影响最后掉落时间','左行时间等于当前位置','右行时间等于 n-position'],solutions:[s('identity-swap-equivalence','相遇等价穿越','忽略身份后独立计算每只蚂蚁的离板时间。',['answer=0','对 left 位置更新 max(answer,position)','对 right 位置更新 max(answer,n-position)，返回'],'O(l+r)','O(1)',
`class Solution { public int getLastMoment(int n,int[] left,int[] right){int answer=0;for(int position:left)answer=Math.max(answer,position);for(int position:right)answer=Math.max(answer,n-position);return answer;} }`,
`class Solution { fun getLastMoment(n:Int,left:IntArray,right:IntArray):Int=maxOf(left.maxOrNull()?:0,right.maxOfOrNull{n-it}?:0) }`,
`class Solution { public: int getLastMoment(int n,vector<int>& left,vector<int>& right){int answer=0;for(int position:left)answer=max(answer,position);for(int position:right)answer=max(answer,n-position);return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'getLastMoment',parameterTypes:['int','intArray','intArray'],returnType:'int',cases:[{name:'两侧都有蚂蚁最后四秒',args:[4,[4,3],[0,1]],expected:4},{name:'全部向右最后七秒',args:[7,[],[0,1,2,3,4,5,6,7]],expected:7},{name:'全部向左最后七秒',args:[7,[0,1,2,3,4,5,6,7],[]],expected:7}]}}
]}
