const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-006',problems:[
{id:393,slug:'utf-8-validation',title:'UTF-8 编码验证',studyTags:['位运算','状态计数','数组'],summary:'判断整数数组的低八位是否构成合法 UTF-8 字节序列。',insight:'首字节的连续前导一决定总字节数，后续指定数量的字节必须以二进制 10 开头。',pitfalls:['多字节字符长度只能为二到四','单独一个前导一非法','序列末尾不能缺少延续字节'],solutions:[s('leading-bit-state','前导位状态扫描','remaining 记录当前字符仍需要的 10xxxxxx 延续字节数。',['remaining=0 时按首字节统计前导一','长度为一或大于四返回假，设置 remaining=count-1','remaining>0 时检查最高两位为 10 并递减，最终需为零'],'O(n)','O(1)',
`class Solution { public boolean validUtf8(int[] data){int remaining=0;for(int value:data){value&=255;if(remaining==0){if((value&128)==0)continue;int count=0,mask=128;while((value&mask)!=0){count++;mask>>=1;}if(count==1||count>4)return false;remaining=count-1;}else{if((value&192)!=128)return false;remaining--;}}return remaining==0;} }`,
`class Solution { fun validUtf8(data:IntArray):Boolean{var remaining=0;for(raw in data){val value=raw and 255;if(remaining==0){if(value and 128==0)continue;var count=0;var mask=128;while(value and mask!=0){count++;mask=mask shr 1};if(count==1||count>4)return false;remaining=count-1}else{if(value and 192!=128)return false;remaining--}};return remaining==0} }`,
`class Solution { public: bool validUtf8(vector<int>& data){int remaining=0;for(int raw:data){int value=raw&255;if(remaining==0){if((value&128)==0)continue;int count=0,mask=128;while(value&mask){++count;mask>>=1;}if(count==1||count>4)return false;remaining=count-1;}else{if((value&192)!=128)return false;--remaining;}}return remaining==0;} };`)],tests:{schemaVersion:1,mode:'function',method:'validUtf8',parameterTypes:['intArray'],returnType:'boolean',cases:[{name:'合法双字节后接单字节',args:[[197,130,1]],expected:true},{name:'延续字节前缀错误',args:[[235,140,4]],expected:false},{name:'五个前导一非法',args:[[255]],expected:false}]}},
{id:396,slug:'rotate-function',title:'旋转函数',studyTags:['递推','数组','数学'],summary:'定义数组每次循环右移后的加权和，求所有旋转状态中的最大加权和。',insight:'从前一状态右移一次时，大多数元素权重加一，而移到首位的元素少了 n 倍，因此可常数时间递推。',pitfalls:['初始状态 F(0) 需要直接计算','使用总和避免每轮重算','旋转取出的元素下标为 n-k'],solutions:[s('rotation-recurrence','旋转加权和递推','利用 F(k)=F(k-1)+sum-n*nums[n-k] 逐状态更新。',['计算 sum 和 F0','k 从一到 n-1 更新 current','持续维护最大值'],'O(n)','O(1)',
`class Solution { public int maxRotateFunction(int[] nums){long sum=0,current=0;for(int i=0;i<nums.length;i++){sum+=nums[i];current+=(long)i*nums[i];}long best=current;for(int k=1;k<nums.length;k++){current+=sum-(long)nums.length*nums[nums.length-k];best=Math.max(best,current);}return(int)best;} }`,
`class Solution { fun maxRotateFunction(nums:IntArray):Int{var sum=0L;var current=0L;for(i in nums.indices){sum+=nums[i];current+=i.toLong()*nums[i]};var best=current;for(k in 1 until nums.size){current+=sum-nums.size.toLong()*nums[nums.size-k];best=maxOf(best,current)};return best.toInt()} }`,
`class Solution { public: int maxRotateFunction(vector<int>& nums){long long sum=0,current=0;for(int i=0;i<(int)nums.size();++i){sum+=nums[i];current+=1LL*i*nums[i];}long long best=current;for(int k=1;k<(int)nums.size();++k){current+=sum-1LL*nums.size()*nums[nums.size()-k];best=max(best,current);}return best;} };`)],tests:{schemaVersion:1,mode:'function',method:'maxRotateFunction',parameterTypes:['intArray'],returnType:'int',cases:[{name:'经典旋转最大值',args:[[4,3,2,6]],expected:26},{name:'单元素',args:[[100]],expected:0},{name:'初始状态最大',args:[[1,2,3]],expected:8}]}},
{id:397,slug:'integer-replacement',title:'整数替换',studyTags:['贪心','位运算','整数'],summary:'把正整数通过偶数除二、奇数加一或减一变成一，求最少操作次数。',insight:'奇数时通常选择能制造更多尾随零的方向；二进制末两位为 11 时加一更优，三需要特判减一。',pitfalls:['最大整数加一会溢出，需转长整型','n=3 选择减一','偶数始终直接除二'],solutions:[s('bit-greedy','按末两位贪心','每步让数值尽快获得更多可连续除二的低位零。',['value 转 long','偶数右移一位','奇数若 value==3 或 bit1 为零则减一，否则加一，计数至一'],'O(log n)','O(1)',
`class Solution { public int integerReplacement(int n){long value=n;int steps=0;while(value!=1){if((value&1)==0)value>>=1;else if(value==3||(value&2)==0)value--;else value++;steps++;}return steps;} }`,
`class Solution { fun integerReplacement(n:Int):Int{var value=n.toLong();var steps=0;while(value!=1L){value=if(value and 1L==0L)value shr 1 else if(value==3L||value and 2L==0L)value-1 else value+1;steps++};return steps} }`,
`class Solution { public: int integerReplacement(int n){long long value=n;int steps=0;while(value!=1){if((value&1)==0)value>>=1;else if(value==3||(value&2)==0)--value;else ++value;++steps;}return steps;} };`)],tests:{schemaVersion:1,mode:'function',method:'integerReplacement',parameterTypes:['int'],returnType:'int',cases:[{name:'八连续除二',args:[8],expected:3},{name:'七先加一',args:[7],expected:4},{name:'最大整数边界',args:[2147483647],expected:32}]}},
{id:400,slug:'nth-digit',title:'第 N 位数字',studyTags:['数学','数位分组','定位'],summary:'在正整数依次拼接成的无限字符串中，返回从一开始计数的第 n 个数字。',insight:'先按一位数、两位数等分组扣除字符数量，再定位到具体整数和该整数中的具体下标。',pitfalls:['n 从一开始计数','分组总字符数使用长整型','定位整数时使用 (n-1) 避免整除边界偏移'],solutions:[s('digit-block-location','按位数块定位','逐块跳过完整位数区间，在目标块中用商余数求答案。',['digit=1,start=1,count=9','当 n>digit*count 时扣除并进入下一位数块','number=start+(n-1)/digit，取字符串下标 (n-1)%digit'],'O(log n)','O(1)',
`class Solution { public int findNthDigit(int n){long position=n,digit=1,start=1,count=9;while(position>digit*count){position-=digit*count;digit++;start*=10;count*=10;}long number=start+(position-1)/digit;return String.valueOf(number).charAt((int)((position-1)%digit))-'0';} }`,
`class Solution { fun findNthDigit(n:Int):Int{var position=n.toLong();var digit=1L;var start=1L;var count=9L;while(position>digit*count){position-=digit*count;digit++;start*=10;count*=10};val number=start+(position-1)/digit;return number.toString()[((position-1)%digit).toInt()]-'0'} }`,
`class Solution { public: int findNthDigit(int n){long long position=n,digit=1,start=1,count=9;while(position>digit*count){position-=digit*count;++digit;start*=10;count*=10;}long long number=start+(position-1)/digit;return to_string(number)[(position-1)%digit]-'0';} };`)],tests:{schemaVersion:1,mode:'function',method:'findNthDigit',parameterTypes:['int'],returnType:'int',cases:[{name:'个位数区间',args:[3],expected:3},{name:'十的第二位',args:[11],expected:0},{name:'三位数区间首位',args:[190],expected:1}]}},
{id:401,slug:'binary-watch',title:'二进制手表',studyTags:['位计数','枚举','格式化'],summary:'二进制手表用四个灯表示小时、六个灯表示分钟，返回亮灯数等于指定值的所有可能时间。',insight:'合法状态只有十二乘六十种，直接枚举并比较小时与分钟的置位数最清晰可靠。',pitfalls:['分钟不足两位要补前导零','小时不能补零','小时范围零到十一、分钟零到五十九'],solutions:[s('enumerate-valid-times','枚举全部合法时间','遍历有限状态空间，用 bitCount 筛选并格式化。',['枚举 hour=0..11','枚举 minute=0..59','置位数之和等于 turnedOn 时加入格式化字符串'],'O(1)','O(1) excluding output',
`class Solution { public List<String> readBinaryWatch(int turnedOn){List<String> answer=new ArrayList<>();for(int hour=0;hour<12;hour++)for(int minute=0;minute<60;minute++)if(Integer.bitCount(hour)+Integer.bitCount(minute)==turnedOn)answer.add(hour+":"+(minute<10?"0":"")+minute);return answer;} }`,
`class Solution { fun readBinaryWatch(turnedOn:Int):List<String>{val answer=mutableListOf<String>();for(hour in 0..11)for(minute in 0..59)if(Integer.bitCount(hour)+Integer.bitCount(minute)==turnedOn)answer.add(hour.toString()+":"+(if(minute<10)"0" else "")+minute);return answer} }`,
`class Solution { public: vector<string> readBinaryWatch(int turnedOn){vector<string> answer;for(int hour=0;hour<12;++hour)for(int minute=0;minute<60;++minute)if(__builtin_popcount(hour)+__builtin_popcount(minute)==turnedOn)answer.push_back(to_string(hour)+":"+(minute<10?"0":"")+to_string(minute));return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'readBinaryWatch',parameterTypes:['int'],returnType:'stringList',cases:[{name:'一盏灯',args:[1],expected:['0:01','0:02','0:04','0:08','0:16','0:32','1:00','2:00','4:00','8:00']},{name:'没有灯',args:[0],expected:['0:00']},{name:'九盏灯无合法时间',args:[9],expected:[]}]}}
]}
