const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-005',problems:[
{id:227,slug:'basic-calculator-ii',title:'基本计算器 II',studyTags:['表达式解析','栈思想','运算优先级'],summary:'计算只含非负整数、加减乘除和空格的有效表达式，整数除法向零截断。',insight:'延迟处理当前运算符后的数字；加减把带符号数累加，乘除立即作用于上一项即可实现优先级。',pitfalls:['数字可能有多位','最后一个数字也要在扫描末尾结算','除法使用语言的整数向零截断语义'],solutions:[s('last-term-accumulation','累计结果与最后一项','result 保存已确定的加减项，last 保存尚可被乘除修改的最近项。',['扫描并累积 number','遇运算符或末尾时按 previousOperator 结算','加减把旧 last 加入 result，最终返回 result+last'],'O(n)','O(1)',
`class Solution { public int calculate(String s){int result=0,last=0,number=0;char operator='+';for(int i=0;i<s.length();i++){char c=s.charAt(i);if(Character.isDigit(c))number=number*10+c-'0';if((!Character.isDigit(c)&&c!=' ')||i==s.length()-1){if(operator=='+'){result+=last;last=number;}else if(operator=='-'){result+=last;last=-number;}else if(operator=='*')last*=number;else last/=number;operator=c;number=0;}}return result+last;} }`,
`class Solution { fun calculate(s:String):Int{var result=0;var last=0;var number=0;var operator='+';for(i in s.indices){val c=s[i];if(c.isDigit())number=number*10+(c-'0');if((!c.isDigit()&&c!=' ')||i==s.lastIndex){when(operator){'+'->{result+=last;last=number};'-'->{result+=last;last=-number};'*'->last*=number;'/'->last/=number};operator=c;number=0}};return result+last} }`,
`class Solution { public: int calculate(string s){int result=0,last=0,number=0;char op='+';for(int i=0;i<(int)s.size();++i){char c=s[i];if(isdigit(c))number=number*10+c-'0';if((!isdigit(c)&&c!=' ')||i==(int)s.size()-1){if(op=='+'){result+=last;last=number;}else if(op=='-'){result+=last;last=-number;}else if(op=='*')last*=number;else last/=number;op=c;number=0;}}return result+last;} };`)],tests:{schemaVersion:1,mode:'function',method:'calculate',parameterTypes:['string'],returnType:'int',cases:[{name:'乘法优先',args:['3+2*2'],expected:7},{name:'除法向零截断',args:[' 3/2 '],expected:1},{name:'混合运算',args:[' 3+5 / 2 '],expected:5}]}},
{id:228,slug:'summary-ranges',title:'汇总区间',studyTags:['数组','区间','双指针'],summary:'把严格递增且无重复的整数数组汇总为覆盖所有数字的最少连续区间字符串。',insight:'每次从一段起点向右扩展到不再连续的位置，单点和多点区间采用不同格式。',pitfalls:['相邻差判断应避免整数溢出','单点不能输出箭头','空数组返回空列表'],solutions:[s('run-scanning','扫描连续段','双指针定位每个最大连续区间并格式化。',['start 指向当前段首','end 在后继恰好加一时扩展','根据 start==end 输出单点或范围'],'O(n)','O(1) excluding output',
`class Solution { public List<String> summaryRanges(int[] nums){List<String> answer=new ArrayList<>();for(int start=0;start<nums.length;){int end=start;while(end+1<nums.length&&(long)nums[end+1]-nums[end]==1)end++;answer.add(start==end?String.valueOf(nums[start]):nums[start]+"->"+nums[end]);start=end+1;}return answer;} }`,
`class Solution { fun summaryRanges(nums:IntArray):List<String>{val answer=mutableListOf<String>();var start=0;while(start<nums.size){var end=start;while(end+1<nums.size&&nums[end+1].toLong()-nums[end]==1L)end++;answer.add(if(start==end)nums[start].toString() else "\${nums[start]}->\${nums[end]}");start=end+1};return answer} }`,
`class Solution { public: vector<string> summaryRanges(vector<int>& nums){vector<string> answer;for(int start=0;start<(int)nums.size();){int end=start;while(end+1<(int)nums.size()&&(long long)nums[end+1]-nums[end]==1)++end;answer.push_back(start==end?to_string(nums[start]):to_string(nums[start])+"->"+to_string(nums[end]));start=end+1;}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'summaryRanges',parameterTypes:['intArray'],returnType:'stringList',cases:[{name:'单点与连续段',args:[[0,1,2,4,5,7]],expected:['0->2','4->5','7']},{name:'多个单点',args:[[0,2,3,4,6,8,9]],expected:['0','2->4','6','8->9']},{name:'空数组',args:[[]],expected:[]}]}},
{id:229,slug:'majority-element-ii',title:'多数元素 II',studyTags:['摩尔投票','数组','候选验证'],summary:'返回数组中所有出现次数严格超过三分之一的元素。',insight:'这样的元素最多两个；摩尔投票维护两个候选并抵消其他值，最后再验证真实频次。',pitfalls:['候选阶段结束后必须二次计数','答案最多含两个值','匹配候选要先于空计数槽判断'],solutions:[s('boyer-moore-two-candidates','双候选摩尔投票','用两个槽位抵消不属于候选的元素，再验证候选是否过阈值。',['扫描更新 candidate1/candidate2 与计数','其他值令两个计数同时减一','重新统计候选出现次数并筛选'],'O(n)','O(1)',
`class Solution { public List<Integer> majorityElement(int[] nums){int first=0,second=1,count1=0,count2=0;for(int value:nums){if(value==first)count1++;else if(value==second)count2++;else if(count1==0){first=value;count1=1;}else if(count2==0){second=value;count2=1;}else{count1--;count2--;}}count1=count2=0;for(int value:nums){if(value==first)count1++;else if(value==second)count2++;}List<Integer> answer=new ArrayList<>();if(count1>nums.length/3)answer.add(first);if(count2>nums.length/3)answer.add(second);Collections.sort(answer);return answer;} }`,
`class Solution { fun majorityElement(nums:IntArray):List<Int>{var first=0;var second=1;var count1=0;var count2=0;for(value in nums){when{value==first->count1++;value==second->count2++;count1==0->{first=value;count1=1};count2==0->{second=value;count2=1};else->{count1--;count2--}}};count1=nums.count{it==first};count2=nums.count{it==second};val answer=mutableListOf<Int>();if(count1>nums.size/3)answer.add(first);if(count2>nums.size/3)answer.add(second);answer.sort();return answer} }`,
`class Solution { public: vector<int> majorityElement(vector<int>& nums){int first=0,second=1,count1=0,count2=0;for(int value:nums){if(value==first)++count1;else if(value==second)++count2;else if(count1==0){first=value;count1=1;}else if(count2==0){second=value;count2=1;}else{--count1;--count2;}}count1=count2=0;for(int value:nums){if(value==first)++count1;else if(value==second)++count2;}vector<int> answer;if(count1>(int)nums.size()/3)answer.push_back(first);if(count2>(int)nums.size()/3)answer.push_back(second);sort(answer.begin(),answer.end());return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'majorityElement',parameterTypes:['intArray'],returnType:'intList',cases:[{name:'一个多数元素',args:[[3,2,3]],expected:[3]},{name:'单元素',args:[[1]],expected:[1]},{name:'两个多数元素',args:[[1,2]],expected:[1,2]}]}},
{id:231,slug:'power-of-two',title:'2 的幂',studyTags:['位运算','数学','最低位'],summary:'判断整数 n 是否恰好是二的整数次幂。',insight:'正的二次幂二进制只有一个一，n 与 n-1 按位与会清掉这个唯一的一。',pitfalls:['零不是二的幂','负数也应返回假','表达式需要先检查 n>0'],solutions:[s('single-set-bit','清除最低位一','用 n&(n-1) 判断二进制是否仅含一个一。',['排除非正数','计算 n&(n-1)','结果为零则为二的幂'],'O(1)','O(1)',
`class Solution { public boolean isPowerOfTwo(int n){return n>0&&(n&(n-1))==0;} }`,
`class Solution { fun isPowerOfTwo(n:Int):Boolean=n>0&&(n and (n-1))==0 }`,
`class Solution { public: bool isPowerOfTwo(int n){return n>0&&(n&(n-1))==0;} };`)],tests:{schemaVersion:1,mode:'function',method:'isPowerOfTwo',parameterTypes:['int'],returnType:'boolean',cases:[{name:'一是零次幂',args:[1],expected:true},{name:'十六',args:[16],expected:true},{name:'非二次幂',args:[3],expected:false}]}},
{id:232,slug:'implement-queue-using-stacks',title:'用栈实现队列',studyTags:['设计','双栈','惰性转移'],summary:'只使用栈的基本操作实现先进先出的队列，支持入队、出队、查看队首和判空。',insight:'输入栈负责接收新元素；输出栈为空时一次性倒入输入栈，倒序后栈顶就是最早元素。',pitfalls:['只有输出栈为空时才转移','转移后可以连续出队','empty 需同时检查两个栈'],solutions:[s('two-stacks','输入栈 + 输出栈','通过惰性转移让每个元素最多在两个栈间移动一次。',['push 放入 input','peek/pop 前若 output 为空则倒入','从 output 栈顶读取或删除'],'amortized O(1)','O(n)',
`class MyQueue { private final Deque<Integer> input=new ArrayDeque<>(),output=new ArrayDeque<>();public void push(int x){input.push(x);}private void move(){if(output.isEmpty())while(!input.isEmpty())output.push(input.pop());}public int pop(){move();return output.pop();}public int peek(){move();return output.peek();}public boolean empty(){return input.isEmpty()&&output.isEmpty();} }`,
`class MyQueue { private val input=ArrayDeque<Int>();private val output=ArrayDeque<Int>();fun push(x:Int){input.addLast(x)}private fun move(){if(output.isEmpty())while(input.isNotEmpty())output.addLast(input.removeLast())}fun pop():Int{move();return output.removeLast()}fun peek():Int{move();return output.last()}fun empty():Boolean=input.isEmpty()&&output.isEmpty() }`,
`class MyQueue { stack<int> input,output;void move(){if(output.empty())while(!input.empty()){output.push(input.top());input.pop();}}public:void push(int x){input.push(x);}int pop(){move();int value=output.top();output.pop();return value;}int peek(){move();return output.top();}bool empty(){return input.empty()&&output.empty();} };`)],tests:{schemaVersion:1,mode:'design',className:'MyQueue',constructorTypes:[],cases:[{name:'先进先出',constructorArgs:[],calls:[{method:'push',parameterTypes:['int'],args:[1]},{method:'push',parameterTypes:['int'],args:[2]},{method:'peek',parameterTypes:[],args:[],returnType:'int',expected:1},{method:'pop',parameterTypes:[],args:[],returnType:'int',expected:1},{method:'empty',parameterTypes:[],args:[],returnType:'boolean',expected:false}]},{name:'转移后继续入队',constructorArgs:[],calls:[{method:'push',parameterTypes:['int'],args:[3]},{method:'pop',parameterTypes:[],args:[],returnType:'int',expected:3},{method:'push',parameterTypes:['int'],args:[4]},{method:'peek',parameterTypes:[],args:[],returnType:'int',expected:4}]},{name:'初始为空',constructorArgs:[],calls:[{method:'empty',parameterTypes:[],args:[],returnType:'boolean',expected:true}]}]}}
]}
