const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-012',problems:[
{id:900,slug:'rle-iterator',title:'RLE 迭代器',studyTags:['设计','数组','双指针'],summary:'游程编码数组交替保存次数和值，next(n) 耗尽接下来的 n 个元素并返回最后耗尽元素的值，不足则返回负一。',insight:'维护当前计数对下标；每次从当前段扣除能消费的数量，段耗尽就跳到下一对，直到 n 归零或所有段结束。',pitfalls:['次数可为零，要自动跳过','next 会永久消耗序列','计数和 n 可用长整型避免累减溢出'],solutions:[s('run-pointer-consumption','游程指针逐段消费','原地减少当前段剩余次数。',['把 encoding 转为 long 数组，index=0','next(n) 中 while index<length：若 counts[index]>=remaining，扣除并返回 value','否则 remaining-=counts[index]，index+=2；耗尽所有段返回 -1'],'O(number of exhausted runs)','O(runs)',
`class RLEIterator { private final long[] encoding;private int index;public RLEIterator(int[] encoding){this.encoding=new long[encoding.length];for(int i=0;i<encoding.length;i++)this.encoding[i]=encoding[i];}public int next(int n){long remaining=n;while(index<encoding.length){if(encoding[index]>=remaining){encoding[index]-=remaining;return(int)encoding[index+1];}remaining-=encoding[index];index+=2;}return -1;} }`,
`class RLEIterator(encoding:IntArray){private val values=LongArray(encoding.size){encoding[it].toLong()};private var index=0;fun next(n:Int):Int{var remaining=n.toLong();while(index<values.size){if(values[index]>=remaining){values[index]-=remaining;return values[index+1].toInt()};remaining-=values[index];index+=2};return -1} }`,
`class RLEIterator { vector<long long> encoding;int index=0;public:RLEIterator(vector<int>& values):encoding(values.begin(),values.end()){}int next(int n){long long remaining=n;while(index<(int)encoding.size()){if(encoding[index]>=remaining){encoding[index]-=remaining;return encoding[index+1];}remaining-=encoding[index];index+=2;}return -1;} };`)],tests:{schemaVersion:1,mode:'design',className:'RLEIterator',constructorTypes:['intArray'],cases:[{name:'经典游程消费',constructorArgs:[[3,8,0,9,2,5]],calls:[{method:'next',parameterTypes:['int'],args:[2],returnType:'int',expected:8},{method:'next',parameterTypes:['int'],args:[1],returnType:'int',expected:8},{method:'next',parameterTypes:['int'],args:[1],returnType:'int',expected:5},{method:'next',parameterTypes:['int'],args:[2],returnType:'int',expected:-1}]},{name:'跨段消费',constructorArgs:[[1,1,2,2]],calls:[{method:'next',parameterTypes:['int'],args:[2],returnType:'int',expected:2},{method:'next',parameterTypes:['int'],args:[1],returnType:'int',expected:2}]},{name:'零次数开头',constructorArgs:[[0,7,1,4]],calls:[{method:'next',parameterTypes:['int'],args:[1],returnType:'int',expected:4}]}]}},
{id:901,slug:'online-stock-span',title:'股票价格跨度',studyTags:['设计','栈','单调栈','数据流'],summary:'逐日输入股票价格，返回当天向前连续小于等于当前价格的天数。',insight:'维护价格严格递减的栈，每项携带自身已经覆盖的跨度；新价格弹出所有不大于它的项并累加跨度，再压入。',pitfalls:['条件包含等于当前价格','被弹出的连续区间可整体合并','每个价格最多入栈出栈一次'],solutions:[s('decreasing-price-span-stack','递减价格跨度栈','把已计算跨度作为可合并块保存。',['栈元素为 [price,span]','next(price) 初始化 span=1','while 栈顶 price<=当前，span+=top.span 并弹出；压入当前对并返回 span'],'O(1) amortized','O(number of calls)',
`class StockSpanner { private final Deque<int[]> stack=new ArrayDeque<>();public StockSpanner(){}public int next(int price){int span=1;while(!stack.isEmpty()&&stack.peek()[0]<=price)span+=stack.pop()[1];stack.push(new int[]{price,span});return span;} }`,
`class StockSpanner { private val stack=java.util.ArrayDeque<IntArray>();fun next(price:Int):Int{var span=1;while(stack.isNotEmpty()&&stack.peek()[0]<=price)span+=stack.pop()[1];stack.push(intArrayOf(price,span));return span} }`,
`class StockSpanner { vector<pair<int,int>> stack;public:StockSpanner(){}int next(int price){int span=1;while(!stack.empty()&&stack.back().first<=price){span+=stack.back().second;stack.pop_back();}stack.push_back({price,span});return span;} };`)],tests:{schemaVersion:1,mode:'design',className:'StockSpanner',constructorTypes:[],cases:[{name:'经典七日价格',constructorArgs:[],calls:[{method:'next',parameterTypes:['int'],args:[100],returnType:'int',expected:1},{method:'next',parameterTypes:['int'],args:[80],returnType:'int',expected:1},{method:'next',parameterTypes:['int'],args:[60],returnType:'int',expected:1},{method:'next',parameterTypes:['int'],args:[70],returnType:'int',expected:2},{method:'next',parameterTypes:['int'],args:[60],returnType:'int',expected:1},{method:'next',parameterTypes:['int'],args:[75],returnType:'int',expected:4},{method:'next',parameterTypes:['int'],args:[85],returnType:'int',expected:6}]},{name:'连续上涨',constructorArgs:[],calls:[{method:'next',parameterTypes:['int'],args:[1],returnType:'int',expected:1},{method:'next',parameterTypes:['int'],args:[2],returnType:'int',expected:2},{method:'next',parameterTypes:['int'],args:[3],returnType:'int',expected:3}]},{name:'相等价格也合并',constructorArgs:[],calls:[{method:'next',parameterTypes:['int'],args:[5],returnType:'int',expected:1},{method:'next',parameterTypes:['int'],args:[5],returnType:'int',expected:2}]}]}},
{id:902,slug:'numbers-at-most-n-given-digit-set',title:'最大为 N 的数字组合',studyTags:['数组','数学','数位动态规划'],summary:'用给定数字集合中的字符任意重复组成正整数，统计不大于 n 的数量。',insight:'位数小于 n 的数全部合法，贡献 d^length；位数相同时从高位扫描，当前位置选比 n 当前位小的数字可任意填后缀，选相同才能继续。',pitfalls:['数字集合不含零，因此没有前导零问题','若某位无法选到相同数字应立即返回累计值','若全部位相同匹配，n 本身还贡献一'],solutions:[s('length-count-and-prefix-scan','短位数计数与同长度前缀扫描','按位组合计数而无需枚举所有数字。',['text=n.toString，d=digits.length；累加 length=1..L-1 的 d^length','逐位置统计 less=digits 中小于 text[i] 的数量，answer+=less*d^(remaining)','若当前位不在 digits 中返回 answer；全部匹配后返回 answer+1'],'O(L·d)','O(1)',
`class Solution { public int atMostNGivenDigitSet(String[] digits,int n){String text=Integer.toString(n);int base=digits.length,answer=0;for(int length=1;length<text.length();length++)answer+=power(base,length);for(int i=0;i<text.length();i++){int less=0;boolean equal=false;for(String digit:digits){if(digit.charAt(0)<text.charAt(i))less++;else if(digit.charAt(0)==text.charAt(i))equal=true;}answer+=less*power(base,text.length()-1-i);if(!equal)return answer;}return answer+1;}private int power(int base,int exponent){int result=1;while(exponent-->0)result*=base;return result;} }`,
`class Solution { fun atMostNGivenDigitSet(digits:Array<String>,n:Int):Int{val text=n.toString();val base=digits.size;var answer=0;for(length in 1 until text.length)answer+=power(base,length);for(i in text.indices){var less=0;var equal=false;for(digit in digits)if(digit[0]<text[i])less++ else if(digit[0]==text[i])equal=true;answer+=less*power(base,text.length-1-i);if(!equal)return answer};return answer+1};private fun power(base:Int,exponentInput:Int):Int{var exponent=exponentInput;var result=1;while(exponent-->0)result*=base;return result} }`,
`class Solution { int power(int base,int exponent){int result=1;while(exponent--)result*=base;return result;}public:int atMostNGivenDigitSet(vector<string>& digits,int n){string text=to_string(n);int base=digits.size(),answer=0;for(int length=1;length<(int)text.size();++length)answer+=power(base,length);for(int i=0;i<(int)text.size();++i){int less=0;bool equal=false;for(string& digit:digits)if(digit[0]<text[i])++less;else if(digit[0]==text[i])equal=true;answer+=less*power(base,text.size()-1-i);if(!equal)return answer;}return answer+1;} };`)],tests:{schemaVersion:1,mode:'function',method:'atMostNGivenDigitSet',parameterTypes:['stringArray','int'],returnType:'int',cases:[{name:'四数字到一百',args:[['1','3','5','7'],100],expected:20},{name:'三个数字到十亿',args:[['1','4','9'],1000000000],expected:29523},{name:'单数字七',args:[['7'],8],expected:1}]}},
{id:903,slug:'valid-permutations-for-di-sequence',title:'DI 序列的有效排列',studyTags:['字符串','动态规划','前缀和'],summary:'字符串由 D 和 I 构成，统计 0..n 的排列满足相邻下降或上升关系的数量并取模。',insight:'dp[j] 表示当前长度排列末元素的相对秩为 j 的方案数；添加新末位时，I 转移是左侧前缀和，D 转移是右侧后缀和。',pitfalls:['排列元素为零到字符串长度','每轮 dp 长度增加一','前后缀累加均需取模'],solutions:[s('last-rank-prefix-suffix-dp','末位秩前后缀 DP','滚动计算每个可能末位相对秩的方案数。',['dp=[1]','对字符：next 长度 dp.size+1；I 时 next[j]=next[j-1]+dp[j-1] (j从1)，D 时 next[j]=next[j+1]+dp[j] (j倒序)','dp=next；最后求 dp 全部元素之和取模'],'O(n²)','O(n)',
`class Solution { public int numPermsDISequence(String s){long mod=1000000007L;long[] dp={1};for(char relation:s.toCharArray()){long[] next=new long[dp.length+1];if(relation=='I')for(int j=1;j<next.length;j++)next[j]=(next[j-1]+dp[j-1])%mod;else for(int j=dp.length-1;j>=0;j--)next[j]=(next[j+1]+dp[j])%mod;dp=next;}long answer=0;for(long value:dp)answer=(answer+value)%mod;return(int)answer;} }`,
`class Solution { fun numPermsDISequence(s:String):Int{val mod=1000000007L;var dp=longArrayOf(1);for(relation in s){val next=LongArray(dp.size+1);if(relation=='I')for(j in 1 until next.size)next[j]=(next[j-1]+dp[j-1])%mod else for(j in dp.lastIndex downTo 0)next[j]=(next[j+1]+dp[j])%mod;dp=next};return(dp.fold(0L){sum,value->(sum+value)%mod}).toInt()} }`,
`class Solution { public: int numPermsDISequence(string s){const long long mod=1000000007;vector<long long> dp{1};for(char relation:s){vector<long long> next(dp.size()+1);if(relation=='I')for(int j=1;j<(int)next.size();++j)next[j]=(next[j-1]+dp[j-1])%mod;else for(int j=dp.size()-1;j>=0;--j)next[j]=(next[j+1]+dp[j])%mod;dp.swap(next);}return accumulate(dp.begin(),dp.end(),0LL)%mod;} };`)],tests:{schemaVersion:1,mode:'function',method:'numPermsDISequence',parameterTypes:['string'],returnType:'int',cases:[{name:'DID 有五种',args:['DID'],expected:5},{name:'单个下降',args:['D'],expected:1},{name:'全递增唯一',args:['III'],expected:1}]}},
{id:904,slug:'fruit-into-baskets',title:'水果成篮',studyTags:['数组','哈希表','滑动窗口'],summary:'从一排果树连续采摘，每棵取一个果实且两个篮子各只能装一种，求最多能采摘多少。',insight:'等价于最长只含至多两种值的连续子数组；右端扩展计数，种类超过二时移动左端并删除频次归零类型。',pitfalls:['必须选择连续树段','同类型果实数量不限','窗口缩小时只在频次归零后减少类型数'],solutions:[s('at-most-two-sliding-window','至多两类滑动窗口','维护当前窗口果实类型频次。',['left=0，frequency 映射','right 扫描并增加 fruits[right]','while frequency.size>2，递减 fruits[left++]，归零删除；更新 answer=max(answer,right-left+1)'],'O(n)','O(2)',
`class Solution { public int totalFruit(int[] fruits){Map<Integer,Integer> frequency=new HashMap<>();int left=0,answer=0;for(int right=0;right<fruits.length;right++){frequency.merge(fruits[right],1,Integer::sum);while(frequency.size()>2){int value=fruits[left++],count=frequency.get(value)-1;if(count==0)frequency.remove(value);else frequency.put(value,count);}answer=Math.max(answer,right-left+1);}return answer;} }`,
`class Solution { fun totalFruit(fruits:IntArray):Int{val frequency=mutableMapOf<Int,Int>();var left=0;var answer=0;for(right in fruits.indices){frequency[fruits[right]]=(frequency[fruits[right]]?:0)+1;while(frequency.size>2){val value=fruits[left++];val count=frequency[value]!!-1;if(count==0)frequency.remove(value)else frequency[value]=count};answer=maxOf(answer,right-left+1)};return answer} }`,
`class Solution { public: int totalFruit(vector<int>& fruits){unordered_map<int,int> frequency;int left=0,answer=0;for(int right=0;right<(int)fruits.size();++right){++frequency[fruits[right]];while(frequency.size()>2){int value=fruits[left++];if(--frequency[value]==0)frequency.erase(value);}answer=max(answer,right-left+1);}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'totalFruit',parameterTypes:['intArray'],returnType:'int',cases:[{name:'三棵全部可采',args:[[1,2,1]],expected:3},{name:'最长尾部三棵',args:[[0,1,2,2]],expected:3},{name:'最长四棵',args:[[1,2,3,2,2]],expected:4}]}}
]}
