const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-015',problems:[
{id:1021,slug:'remove-outermost-parentheses',title:'删除最外层的括号',studyTags:['字符串','栈','深度'],summary:'有效括号串可分解为若干不可再分的原语，删除每个原语最外层一对括号后返回结果。',insight:'扫描维护处理字符前后的深度；左括号在增加深度前若深度大于零则保留，右括号先减深度后若仍大于零则保留。',pitfalls:['每个原语的第一个左括号不保留','每个原语的最后一个右括号不保留','无需显式分割原语'],solutions:[s('parenthesis-depth-filter','括号深度过滤','只输出处于至少一层外壳内部的括号。',['depth=0，answer 为空','遇左括号：若 depth>0 追加，再 depth++','遇右括号：先 depth--，若 depth>0 追加；返回字符串'],'O(n)','O(n)',
`class Solution { public String removeOuterParentheses(String s){StringBuilder answer=new StringBuilder();int depth=0;for(char ch:s.toCharArray())if(ch=='('){if(depth++>0)answer.append(ch);}else{if(--depth>0)answer.append(ch);}return answer.toString();} }`,
`class Solution { fun removeOuterParentheses(s:String):String{val answer=StringBuilder();var depth=0;for(ch in s)if(ch=='('){if(depth++>0)answer.append(ch)}else{depth--;if(depth>0)answer.append(ch)};return answer.toString()} }`,
`class Solution { public: string removeOuterParentheses(string s){string answer;int depth=0;for(char ch:s)if(ch=='('){if(depth++>0)answer+=ch;}else if(--depth>0)answer+=ch;return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'removeOuterParentheses',parameterTypes:['string'],returnType:'string',cases:[{name:'三个原语',args:['(()())(())'],expected:'()()()'},{name:'嵌套原语',args:['(()())(())(()(()))'],expected:'()()()()(())'},{name:'两个最小原语',args:['()()'],expected:''}]}},
{id:1022,slug:'sum-of-root-to-leaf-binary-numbers',title:'从根到叶的二进制数之和',studyTags:['树','深度优先搜索','位运算'],summary:'二叉树节点值为零或一，每条根到叶路径组成一个二进制数，求所有路径数值之和。',insight:'DFS 过程中把前缀左移一位并加入当前比特；到叶节点时该前缀就是完整数值，非叶返回左右子树和。',pitfalls:['路径最高位是根节点','叶节点定义为左右孩子都为空','题目保证结果在整数范围内'],solutions:[s('dfs-binary-prefix','DFS 二进制前缀','沿路径滚动构造数值并在叶端累加。',['dfs(node,prefix)，空节点返回零','current=(prefix<<1)|node.val','若叶节点返回 current，否则返回 dfs(left,current)+dfs(right,current)'],'O(n)','O(height)',
`class Solution { public int sumRootToLeaf(TreeNode root){return dfs(root,0);}private int dfs(TreeNode node,int prefix){if(node==null)return 0;int current=(prefix<<1)|node.val;if(node.left==null&&node.right==null)return current;return dfs(node.left,current)+dfs(node.right,current);} }`,
`class Solution { fun sumRootToLeaf(root:TreeNode?):Int=dfs(root,0);private fun dfs(node:TreeNode?,prefix:Int):Int{node?:return 0;val current=(prefix shl 1) or node.\`val\`;if(node.left==null&&node.right==null)return current;return dfs(node.left,current)+dfs(node.right,current)} }`,
`class Solution { int dfs(TreeNode* node,int prefix){if(!node)return 0;int current=prefix<<1|node->val;if(!node->left&&!node->right)return current;return dfs(node->left,current)+dfs(node->right,current);}public:int sumRootToLeaf(TreeNode* root){return dfs(root,0);} };`)],tests:{schemaVersion:1,mode:'function',method:'sumRootToLeaf',parameterTypes:['treeNode'],returnType:'int',cases:[{name:'七节点总和二十二',args:[[1,0,1,0,1,0,1]],expected:22},{name:'单节点零',args:[[0]],expected:0},{name:'路径一零为二',args:[[1,0]],expected:2}]}},
{id:1023,slug:'camelcase-matching',title:'驼峰式匹配',studyTags:['数组','字符串','双指针'],summary:'对每个查询判断能否在 pattern 任意位置插入小写字母得到该查询，返回对应布尔列表。',insight:'双指针扫描 query：字符等于 pattern 当前字符就消费模式，否则它必须是可额外插入的小写字母；任何未匹配大写字母立即失败。',pitfalls:['只能额外插入小写字母','模式字符区分大小写','扫描结束必须完整消费 pattern'],solutions:[s('pattern-query-two-pointer','模式查询双指针','跳过查询中的额外小写字符并拒绝额外大写。',['对每个 query 令 index=0,valid=true','扫描字符；若 index<pattern.length 且相等则 index++','否则若字符为大写令 valid=false；最终要求 valid 且 index==pattern.length'],'O(total query characters)','O(output)',
`class Solution { public List<Boolean> camelMatch(String[] queries,String pattern){List<Boolean> answer=new ArrayList<>();for(String query:queries){int index=0;boolean valid=true;for(char ch:query.toCharArray())if(index<pattern.length()&&ch==pattern.charAt(index))index++;else if(Character.isUpperCase(ch)){valid=false;break;}answer.add(valid&&index==pattern.length());}return answer;} }`,
`class Solution { fun camelMatch(queries:Array<String>,pattern:String):List<Boolean>{return queries.map{query->var index=0;var valid=true;for(ch in query)if(index<pattern.length&&ch==pattern[index])index++ else if(ch.isUpperCase()){valid=false;break};valid&&index==pattern.length}} }`,
`class Solution { public: vector<bool> camelMatch(vector<string>& queries,string pattern){vector<bool> answer;for(string& query:queries){int index=0;bool valid=true;for(char ch:query)if(index<(int)pattern.size()&&ch==pattern[index])++index;else if(isupper(ch)){valid=false;break;}answer.push_back(valid&&index==(int)pattern.size());}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'camelMatch',parameterTypes:['stringArray','string'],returnType:'booleanList',cases:[{name:'经典 FB 模式',args:[['FooBar','FooBarTest','FootBall','FrameBuffer','ForceFeedBack'],'FB'],expected:[true,false,true,true,false]},{name:'FoBa 模式',args:[['FooBar','FooBarTest','FootBall','FrameBuffer','ForceFeedBack'],'FoBa'],expected:[true,false,true,false,false]},{name:'缺少模式字符',args:[['abc'],'abcd'],expected:[false]}]}},
{id:1024,slug:'video-stitching',title:'视频拼接',studyTags:['数组','动态规划','贪心','区间'],summary:'用若干视频片段覆盖连续时间区间 [0,time]，片段可裁剪，求最少片段数；无法覆盖返回负一。',insight:'类似最少跳跃：当前已选片段覆盖到 currentEnd，扫描所有起点不超过 currentEnd 的片段扩展 farthest；每次走到边界必须提交一个片段。',pitfalls:['片段起点等于当前边界可衔接','若 farthest 未超过 currentEnd 则出现缺口','达到 time 后立即返回使用数'],solutions:[s('greedy-farthest-reach','最远覆盖贪心','在每个已覆盖边界内选择能延伸最远的片段。',['按起点升序排序 clips，index=0,currentEnd=0,used=0','while currentEnd<time：枚举所有 start<=currentEnd 的片段更新 farthest','若 farthest==currentEnd 返回 -1；否则 used++、currentEnd=farthest，循环结束返回 used'],'O(n log n)','O(log n)',
`class Solution { public int videoStitching(int[][] clips,int time){Arrays.sort(clips,Comparator.comparingInt(a->a[0]));int index=0,currentEnd=0,used=0;while(currentEnd<time){int farthest=currentEnd;while(index<clips.length&&clips[index][0]<=currentEnd)farthest=Math.max(farthest,clips[index++][1]);if(farthest==currentEnd)return -1;currentEnd=farthest;used++;}return used;} }`,
`class Solution { fun videoStitching(clips:Array<IntArray>,time:Int):Int{clips.sortBy{it[0]};var index=0;var currentEnd=0;var used=0;while(currentEnd<time){var farthest=currentEnd;while(index<clips.size&&clips[index][0]<=currentEnd)farthest=maxOf(farthest,clips[index++][1]);if(farthest==currentEnd)return -1;currentEnd=farthest;used++};return used} }`,
`class Solution { public: int videoStitching(vector<vector<int>>& clips,int time){sort(clips.begin(),clips.end());int index=0,currentEnd=0,used=0;while(currentEnd<time){int farthest=currentEnd;while(index<(int)clips.size()&&clips[index][0]<=currentEnd)farthest=max(farthest,clips[index++][1]);if(farthest==currentEnd)return -1;currentEnd=farthest;++used;}return used;} };`)],tests:{schemaVersion:1,mode:'function',method:'videoStitching',parameterTypes:['intMatrix','int'],returnType:'int',cases:[{name:'经典最少三段',args:[[[0,2],[4,6],[8,10],[1,9],[1,5],[5,9]],10],expected:3},{name:'起点有缺口',args:[[[0,1],[1,2]],5],expected:-1},{name:'一段完整覆盖',args:[[[0,4],[2,8]],4],expected:1}]}},
{id:1025,slug:'divisor-game',title:'除数博弈',studyTags:['数学','博弈'],summary:'两人从 n 开始轮流选 0<x<n 且 n%x=0，并把 n 替换为 n-x；无法操作者输，判断先手是否必胜。',insight:'偶数时先手可选 x=1 把奇数交给对手；奇数的所有因子都是奇数，减后得到偶数，因此奇偶状态互相归纳，先手仅在 n 为偶数时胜。',pitfalls:['x 必须严格小于 n','n=1 无合法操作所以先手输','结论是偶数充要条件'],solutions:[s('parity-game-invariant','奇偶博弈不变量','用归纳得到偶数必胜、奇数必败。',['观察 n=1 为败态，n=2 可减一到败态','偶数总可选一转成奇数；奇数任一合法因子均为奇数，减后成为偶数','因此直接返回 n%2==0'],'O(1)','O(1)',
`class Solution { public boolean divisorGame(int n){return n%2==0;} }`,
`class Solution { fun divisorGame(n:Int):Boolean=n%2==0 }`,
`class Solution { public: bool divisorGame(int n){return n%2==0;} };`)],tests:{schemaVersion:1,mode:'function',method:'divisorGame',parameterTypes:['int'],returnType:'boolean',cases:[{name:'二先手胜',args:[2],expected:true},{name:'三先手败',args:[3],expected:false},{name:'十先手胜',args:[10],expected:true}]}}
]}
