const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-006',problems:[
{id:349,slug:'intersection-of-two-arrays',title:'两个数组的交集',studyTags:['哈希集合','排序','数组'],summary:'返回两个整数数组共有的不同元素，每个元素在结果中只出现一次。',insight:'先把一个数组放入集合，再扫描另一个数组收集命中值；最终排序使输出稳定。',pitfalls:['结果不能含重复元素','答案顺序本身不限','空交集返回空数组'],solutions:[s('set-intersection','集合求交集','集合提供常数期望时间查找，结果集合负责去重。',['建立 nums1 的集合','扫描 nums2 并收集存在值','结果升序排序后转数组'],'O(m+n+k log k)','O(m+k)',
`class Solution { public int[] intersection(int[] nums1,int[] nums2){Set<Integer> first=new HashSet<>();for(int value:nums1)first.add(value);Set<Integer> common=new TreeSet<>();for(int value:nums2)if(first.contains(value))common.add(value);return common.stream().mapToInt(Integer::intValue).toArray();} }`,
`class Solution { fun intersection(nums1:IntArray,nums2:IntArray):IntArray{val first=nums1.toHashSet();return nums2.filter{it in first}.distinct().sorted().toIntArray()} }`,
`class Solution { public: vector<int> intersection(vector<int>& nums1,vector<int>& nums2){unordered_set<int> first(nums1.begin(),nums1.end());set<int> common;for(int value:nums2)if(first.count(value))common.insert(value);return vector<int>(common.begin(),common.end());} };`)],tests:{schemaVersion:1,mode:'function',method:'intersection',parameterTypes:['intArray','intArray'],returnType:'intArray',cases:[{name:'单个交集值',args:[[1,2,2,1],[2,2]],expected:[2]},{name:'两个交集值',args:[[4,9,5],[9,4,9,8,4]],expected:[4,9]},{name:'没有交集',args:[[1,2],[3,4]],expected:[]}]}},
{id:350,slug:'intersection-of-two-arrays-ii',title:'两个数组的交集 II',studyTags:['排序','双指针','多重集合'],summary:'返回两个数组的多重交集，每个值在结果中的出现次数等于两侧频次的较小值。',insight:'排序后用双指针同步扫描，相等时加入答案并同时推进，较小值一侧单独推进。',pitfalls:['重复元素需要按次数保留','两个输入都可排序','结果长度不超过较短数组'],solutions:[s('sorted-two-pointers','排序 + 双指针','有序扫描天然按较小频次输出每个重复值。',['两个数组排序','比较 nums1[left] 与 nums2[right]','相等加入并双移，否则移动较小侧'],'O(m log m+n log n)','O(k)',
`class Solution { public int[] intersect(int[] nums1,int[] nums2){Arrays.sort(nums1);Arrays.sort(nums2);int[] buffer=new int[Math.min(nums1.length,nums2.length)];int i=0,j=0,size=0;while(i<nums1.length&&j<nums2.length){if(nums1[i]==nums2[j]){buffer[size++]=nums1[i];i++;j++;}else if(nums1[i]<nums2[j])i++;else j++;}return Arrays.copyOf(buffer,size);} }`,
`class Solution { fun intersect(nums1:IntArray,nums2:IntArray):IntArray{nums1.sort();nums2.sort();val answer=mutableListOf<Int>();var i=0;var j=0;while(i<nums1.size&&j<nums2.size){if(nums1[i]==nums2[j]){answer.add(nums1[i]);i++;j++}else if(nums1[i]<nums2[j])i++ else j++};return answer.toIntArray()} }`,
`class Solution { public: vector<int> intersect(vector<int>& nums1,vector<int>& nums2){sort(nums1.begin(),nums1.end());sort(nums2.begin(),nums2.end());vector<int> answer;int i=0,j=0;while(i<(int)nums1.size()&&j<(int)nums2.size()){if(nums1[i]==nums2[j]){answer.push_back(nums1[i]);++i;++j;}else if(nums1[i]<nums2[j])++i;else ++j;}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'intersect',parameterTypes:['intArray','intArray'],returnType:'intArray',cases:[{name:'保留两个重复值',args:[[1,2,2,1],[2,2]],expected:[2,2]},{name:'两个不同交集值',args:[[4,9,5],[9,4,9,8,4]],expected:[4,9]},{name:'频次取较小侧',args:[[1,1,1],[1,1]],expected:[1,1]}]}},
{id:354,slug:'russian-doll-envelopes',title:'俄罗斯套娃信封问题',studyTags:['排序','最长递增子序列','二分查找'],summary:'信封只有宽和高都严格更大时才能套入，求最多可嵌套多少个。',insight:'宽升序且同宽高度降序排序后，问题转化为高度的严格最长递增子序列；同宽不会被误选。',pitfalls:['宽高都必须严格增加','同宽高度必须降序排列','高度 LIS 使用 lower bound'],solutions:[s('sort-and-lis','排序后高度 LIS','特殊排序消除同宽干扰，再维护高度子序列的最小结尾。',['按宽升序、同宽高降序排序','对每个高度在 tails 中找首个不小于它的位置','替换或追加并返回 tails 长度'],'O(n log n)','O(n)',
`class Solution { public int maxEnvelopes(int[][] envelopes){Arrays.sort(envelopes,(a,b)->a[0]==b[0]?Integer.compare(b[1],a[1]):Integer.compare(a[0],b[0]));int[] tails=new int[envelopes.length];int size=0;for(int[] envelope:envelopes){int left=0,right=size;while(left<right){int middle=(left+right)/2;if(tails[middle]<envelope[1])left=middle+1;else right=middle;}tails[left]=envelope[1];if(left==size)size++;}return size;} }`,
`class Solution { fun maxEnvelopes(envelopes:Array<IntArray>):Int{envelopes.sortWith(Comparator{a,b->if(a[0]==b[0])b[1].compareTo(a[1]) else a[0].compareTo(b[0])});val tails=IntArray(envelopes.size);var size=0;for(envelope in envelopes){var left=0;var right=size;while(left<right){val middle=(left+right)/2;if(tails[middle]<envelope[1])left=middle+1 else right=middle};tails[left]=envelope[1];if(left==size)size++};return size} }`,
`class Solution { public: int maxEnvelopes(vector<vector<int>>& envelopes){sort(envelopes.begin(),envelopes.end(),[](const auto& a,const auto& b){return a[0]==b[0]?a[1]>b[1]:a[0]<b[0];});vector<int> tails;for(auto& envelope:envelopes){auto it=lower_bound(tails.begin(),tails.end(),envelope[1]);if(it==tails.end())tails.push_back(envelope[1]);else *it=envelope[1];}return tails.size();} };`)],tests:{schemaVersion:1,mode:'function',method:'maxEnvelopes',parameterTypes:['intMatrix'],returnType:'int',cases:[{name:'三级嵌套',args:[[[5,4],[6,4],[6,7],[2,3]]],expected:3},{name:'完全相同不能嵌套',args:[[[1,1],[1,1],[1,1]]],expected:1},{name:'同宽不同高',args:[[[2,3],[2,4],[3,5]]],expected:2}]}},
{id:357,slug:'count-numbers-with-unique-digits',title:'统计各位数字都不同的数字个数',studyTags:['排列组合','数学','计数'],summary:'统计零到 10^n-1 中十进制各位数字互不相同的整数数量。',insight:'位数为 digits 的正整数首位有九种选择，后续依次有九、八等选择，再加上零。',pitfalls:['n=0 时范围只有零','首位不能选零','十进制最多十位互异，题目范围更小'],solutions:[s('combinatorial-counting','逐位排列计数','累计每种有效位数的互异数字数量。',['n=0 返回一','total=10 处理一位数','digits 从二到 n：unique*=available 并累计，available 递减'],'O(n)','O(1)',
`class Solution { public int countNumbersWithUniqueDigits(int n){if(n==0)return 1;int total=10,unique=9,available=9;for(int digits=2;digits<=n;digits++){unique*=available--;total+=unique;}return total;} }`,
`class Solution { fun countNumbersWithUniqueDigits(n:Int):Int{if(n==0)return 1;var total=10;var unique=9;var available=9;for(digits in 2..n){unique*=available--;total+=unique};return total} }`,
`class Solution { public: int countNumbersWithUniqueDigits(int n){if(n==0)return 1;int total=10,unique=9,available=9;for(int digits=2;digits<=n;++digits){unique*=available--;total+=unique;}return total;} };`)],tests:{schemaVersion:1,mode:'function',method:'countNumbersWithUniqueDigits',parameterTypes:['int'],returnType:'int',cases:[{name:'两位范围',args:[2],expected:91},{name:'零位范围',args:[0],expected:1},{name:'三位范围',args:[3],expected:739}]}},
{id:365,slug:'water-and-jug-problem',title:'水壶问题',studyTags:['数学','最大公约数','裴蜀定理'],summary:'两个无刻度水壶允许装满、倒空和互相倾倒，判断能否量出指定水量。',insight:'可量出的水量必须不超过总容量，并且是两个容量最大公约数的倍数。',pitfalls:['目标为零总能实现','目标不能超过两壶容量之和','容量为零时要正确处理最大公约数'],solutions:[s('bezout-gcd','裴蜀定理 + 最大公约数','用可达水量的整数组合条件直接判定。',['target=0 返回真','target>x+y 返回假','计算 gcd(x,y)，判断 target%gcd==0'],'O(log min(x,y))','O(1)',
`class Solution { public boolean canMeasureWater(int x,int y,int target){if(target==0)return true;if((long)x+y<target)return false;int gcd=gcd(x,y);return gcd!=0&&target%gcd==0;}private int gcd(int a,int b){while(b!=0){int value=a%b;a=b;b=value;}return a;} }`,
`class Solution { fun canMeasureWater(x:Int,y:Int,target:Int):Boolean{if(target==0)return true;if(x.toLong()+y<target)return false;fun gcdValue(first:Int,second:Int):Int{var a=first;var b=second;while(b!=0){val value=a%b;a=b;b=value};return a};val gcd=gcdValue(x,y);return gcd!=0&&target%gcd==0} }`,
`class Solution { int gcdValue(int a,int b){while(b){int value=a%b;a=b;b=value;}return a;}public:bool canMeasureWater(int x,int y,int target){if(target==0)return true;if((long long)x+y<target)return false;int gcd=gcdValue(x,y);return gcd&&target%gcd==0;} };`)],tests:{schemaVersion:1,mode:'function',method:'canMeasureWater',parameterTypes:['int','int','int'],returnType:'boolean',cases:[{name:'三五量四',args:[3,5,4],expected:true},{name:'二六不能量五',args:[2,6,5],expected:false},{name:'总容量目标',args:[1,2,3],expected:true}]}}
]}
