const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-025',problems:[
{id:1737,slug:'change-minimum-characters-to-satisfy-one-of-three-conditions',title:'满足三条件之一需改变的最少字符数',studyTags:['哈希表','字符串','计数','前缀和'],summary:'修改 a、b 中最少字符，使 a 所有字符都严格小于 b 所有字符，或 b 全小于 a，或两串都只含同一字符。',insight:'统计两串 26 个字母频次。前两条件枚举字母分界线，用前缀和计算两侧越界字符数；第三条件保留两串中合计频次最高的字母。',pitfalls:['严格小于的分界只枚举 a 到 y','修改可换成任意小写字母','第三条件要求两串共同只含同一个字符'],solutions:[s('frequency-boundary-enumeration','频次分界枚举','分别计算三类目标条件的最小修改代价。',['统计 countA、countB 与前缀','condition3=|a|+|b|-max(countA[i]+countB[i])','boundary=0..24：a>b 代价为 a 中大于 boundary 加 b 中小于等于 boundary；反向同理，取最小'],'O(n+alphabet)','O(alphabet)',
`class Solution { public int minCharacters(String a,String b){int[] first=new int[26],second=new int[26];for(char letter:a.toCharArray())first[letter-'a']++;for(char letter:b.toCharArray())second[letter-'a']++;int answer=a.length()+b.length();for(int letter=0;letter<26;letter++)answer=Math.min(answer,a.length()+b.length()-first[letter]-second[letter]);int prefixFirst=0,prefixSecond=0;for(int boundary=0;boundary<25;boundary++){prefixFirst+=first[boundary];prefixSecond+=second[boundary];answer=Math.min(answer,a.length()-prefixFirst+prefixSecond);answer=Math.min(answer,b.length()-prefixSecond+prefixFirst);}return answer;} }`,
`class Solution { fun minCharacters(a:String,b:String):Int{val first=IntArray(26);val second=IntArray(26);for(letter in a)first[letter-'a']++;for(letter in b)second[letter-'a']++;var answer=a.length+b.length;for(letter in 0 until 26)answer=minOf(answer,a.length+b.length-first[letter]-second[letter]);var prefixFirst=0;var prefixSecond=0;for(boundary in 0 until 25){prefixFirst+=first[boundary];prefixSecond+=second[boundary];answer=minOf(answer,a.length-prefixFirst+prefixSecond,b.length-prefixSecond+prefixFirst)};return answer} }`,
`class Solution { public: int minCharacters(string a,string b){array<int,26> first{},second{};for(char letter:a)++first[letter-'a'];for(char letter:b)++second[letter-'a'];int answer=a.size()+b.size();for(int letter=0;letter<26;++letter)answer=min(answer,(int)a.size()+(int)b.size()-first[letter]-second[letter]);int prefixFirst=0,prefixSecond=0;for(int boundary=0;boundary<25;++boundary){prefixFirst+=first[boundary];prefixSecond+=second[boundary];answer=min(answer,(int)a.size()-prefixFirst+prefixSecond);answer=min(answer,(int)b.size()-prefixSecond+prefixFirst);}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'minCharacters',parameterTypes:['string','string'],returnType:'int',cases:[{name:'aba 与 caa 最少修改二',args:['aba','caa'],expected:2},{name:'dabadd 与 cda 最少修改三',args:['dabadd','cda'],expected:3},{name:'相同单字符无需修改',args:['a','a'],expected:0}]}},
{id:1738,slug:'find-kth-largest-xor-coordinate-value',title:'找出第 K 大的异或坐标值',studyTags:['数组','分治','堆（优先队列）','矩阵','前缀和'],summary:'坐标 (a,b) 的值是 matrix[0..a][0..b] 全部元素异或，返回所有坐标值中第 k 大者。',insight:'二维异或前缀满足 prefix[r][c]=matrix xor 上 xor 左 xor 左上。计算所有坐标值后排序即可。',pitfalls:['异或重复区域通过再异或左上抵消','前缀数组多开一行一列简化边界','k 从一开始且按降序'],solutions:[s('two-dimensional-xor-prefix','二维异或前缀','在线生成每个坐标异或值并统一选择第 k 大。',['prefix[rows+1][cols+1]','prefix[r+1][c+1]=matrix[r][c]^prefix[r][c+1]^prefix[r+1][c]^prefix[r][c]','收集全部值升序排序，返回 values[size-k]'],'O(mn log(mn))','O(mn)',
`class Solution { public int kthLargestValue(int[][] matrix,int k){int rows=matrix.length,cols=matrix[0].length;int[][] prefix=new int[rows+1][cols+1];int[] values=new int[rows*cols];int index=0;for(int row=0;row<rows;row++)for(int col=0;col<cols;col++){prefix[row+1][col+1]=matrix[row][col]^prefix[row][col+1]^prefix[row+1][col]^prefix[row][col];values[index++]=prefix[row+1][col+1];}Arrays.sort(values);return values[values.length-k];} }`,
`class Solution { fun kthLargestValue(matrix:Array<IntArray>,k:Int):Int{val rows=matrix.size;val cols=matrix[0].size;val prefix=Array(rows+1){IntArray(cols+1)};val values=IntArray(rows*cols);var index=0;for(row in 0 until rows)for(col in 0 until cols){prefix[row+1][col+1]=matrix[row][col] xor prefix[row][col+1] xor prefix[row+1][col] xor prefix[row][col];values[index++]=prefix[row+1][col+1]};values.sort();return values[values.size-k]} }`,
`class Solution { public: int kthLargestValue(vector<vector<int>>& matrix,int k){int rows=matrix.size(),cols=matrix[0].size();vector<vector<int>> prefix(rows+1,vector<int>(cols+1));vector<int> values;for(int row=0;row<rows;++row)for(int col=0;col<cols;++col){prefix[row+1][col+1]=matrix[row][col]^prefix[row][col+1]^prefix[row+1][col]^prefix[row][col];values.push_back(prefix[row+1][col+1]);}nth_element(values.begin(),values.end()-k,values.end());return values[values.size()-k];} };`)],tests:{schemaVersion:1,mode:'function',method:'kthLargestValue',parameterTypes:['intMatrix','int'],returnType:'int',cases:[{name:'二乘二矩阵第一大为七',args:[[[5,2],[1,6]],1],expected:7},{name:'第二大为五',args:[[[5,2],[1,6]],2],expected:5},{name:'第四大为零',args:[[[5,2],[1,6]],4],expected:0}]}},
{id:1739,slug:'building-boxes',title:'放置盒子',studyTags:['数学','贪心','二分查找'],summary:'在墙角地面堆 n 个立方盒，非地面盒的下、左、后都必须有盒子支撑，求最少接触地面的盒子数。',insight:'先放尽可能大的完整四面体层：高 h 使用 h(h+1)(h+2)/6 个盒、地面占 h(h+1)/2 个。剩余盒沿新斜层扩展，第 1、2、3 个新增地面位置分别可承载 1、2、3 个剩余盒。',pitfalls:['完整层盒数是四面体数','地面数是三角形数','不足完整层的扩展容量按一、二、三递增'],solutions:[s('complete-layers-then-fringe','完整层与边缘贪心','最大化完整金字塔后用最少新地面列覆盖余量。',['height 从零增长，直到下一完整层盒数超过 n','remaining=n-tetrahedral(height)，floor=triangular(height)','addition=1,2,...；每次 remaining-=addition、floor++，直到 remaining<=0'],'O(n^(1/3)+sqrt n)','O(1)',
`class Solution { public int minimumBoxes(int n){int height=0,used=0,floor=0;while(true){int nextLayer=(height+1)*(height+2)/2;if(used+nextLayer>n)break;height++;used+=nextLayer;floor+=height;}int remaining=n-used;for(int capacity=1;remaining>0;capacity++){remaining-=capacity;floor++;}return floor;} }`,
`class Solution { fun minimumBoxes(n:Int):Int{var height=0;var used=0;var floor=0;while(true){val nextLayer=(height+1)*(height+2)/2;if(used+nextLayer>n)break;height++;used+=nextLayer;floor+=height};var remaining=n-used;var capacity=1;while(remaining>0){remaining-=capacity++;floor++};return floor} }`,
`class Solution { public: int minimumBoxes(int n){int height=0,used=0,floor=0;while(true){int nextLayer=(height+1)*(height+2)/2;if(used+nextLayer>n)break;++height;used+=nextLayer;floor+=height;}int remaining=n-used;for(int capacity=1;remaining>0;++capacity){remaining-=capacity;++floor;}return floor;} };`)],tests:{schemaVersion:1,mode:'function',method:'minimumBoxes',parameterTypes:['int'],returnType:'int',cases:[{name:'三个盒子都需接触地面',args:[3],expected:3},{name:'四盒形成二层需三个地面盒',args:[4],expected:3},{name:'十盒完整三层需六个地面盒',args:[10],expected:6}]}},
{id:1742,slug:'maximum-number-of-balls-in-a-box',title:'盒子中小球的最大数量',studyTags:['哈希表','数学','计数'],summary:'编号 lowLimit 到 highLimit 的球按编号各位数字和放入对应盒子，求任一盒子中的最多球数。',insight:'逐编号计算十进制数位和并累计盒子频次，同时维护最大频次。范围不大，直接模拟足够。',pitfalls:['区间两端都包含','盒子编号是数位和而非球编号','相同数位和累积到同一盒'],solutions:[s('digit-sum-frequency','数位和频次模拟','对每个球计算唯一目标盒并计数。',['counts 数组或哈希表','number 从 lowLimit 到 highLimit 计算 digitSum','answer=max(answer,++counts[digitSum])，返回'],'O(range·digits)','O(digits)',
`class Solution { private int digitSum(int value){int sum=0;while(value>0){sum+=value%10;value/=10;}return sum;}public int countBalls(int lowLimit,int highLimit){int[] counts=new int[50];int answer=0;for(int value=lowLimit;value<=highLimit;value++)answer=Math.max(answer,++counts[digitSum(value)]);return answer;} }`,
`class Solution { fun countBalls(lowLimit:Int,highLimit:Int):Int{val counts=IntArray(50);var answer=0;for(original in lowLimit..highLimit){var value=original;var sum=0;while(value>0){sum+=value%10;value/=10};counts[sum]++;answer=maxOf(answer,counts[sum])};return answer} }`,
`class Solution { int digitSum(int value){int sum=0;while(value){sum+=value%10;value/=10;}return sum;}public:int countBalls(int lowLimit,int highLimit){int counts[50]={},answer=0;for(int value=lowLimit;value<=highLimit;++value)answer=max(answer,++counts[digitSum(value)]);return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'countBalls',parameterTypes:['int','int'],returnType:'int',cases:[{name:'一到十最多两个球同盒',args:[1,10],expected:2},{name:'五到十五最多两个',args:[5,15],expected:2},{name:'十九到二十八最多两个',args:[19,28],expected:2}]}},
{id:1743,slug:'restore-the-array-from-adjacent-pairs',title:'从相邻元素对还原数组',studyTags:['数组','哈希表'],summary:'给出原数组所有无序相邻元素对，原数组元素互不相同，还原任意一个符合的数组。',insight:'相邻对构成一条无向路径，两个端点度数为一。任选端点开始，每步走向不是上一个节点的邻居即可恢复整条路径。',pitfalls:['每个 pair 内顺序不代表原数组方向','正向或反向答案都合法但测试需选确定端点','内部节点恰有两个邻居'],solutions:[s('path-endpoint-walk','无向路径端点遍历','把相邻关系图沿唯一未回退方向走到底。',['构建 value 到邻居列表','选一个 degree==1 的节点为 answer[0]','依次从当前邻居中选不等于 previous 的值，填满 n 个位置'],'O(n)','O(n)',
`class Solution { public int[] restoreArray(int[][] adjacentPairs){Map<Integer,List<Integer>> graph=new HashMap<>();for(int[] pair:adjacentPairs){graph.computeIfAbsent(pair[0],key->new ArrayList<>()).add(pair[1]);graph.computeIfAbsent(pair[1],key->new ArrayList<>()).add(pair[0]);}int start=0;outer:for(int[] pair:adjacentPairs)for(int value:pair)if(graph.get(value).size()==1){start=value;break outer;}int[] answer=new int[graph.size()];answer[0]=start;for(int i=1;i<answer.length;i++){List<Integer> neighbors=graph.get(answer[i-1]);answer[i]=neighbors.get(0);if(i>1&&answer[i]==answer[i-2])answer[i]=neighbors.get(1);}return answer;} }`,
`class Solution { fun restoreArray(adjacentPairs:Array<IntArray>):IntArray{val graph=mutableMapOf<Int,MutableList<Int>>();for(pair in adjacentPairs){graph.getOrPut(pair[0]){mutableListOf()}.add(pair[1]);graph.getOrPut(pair[1]){mutableListOf()}.add(pair[0])};val answer=IntArray(graph.size);answer[0]=adjacentPairs.asSequence().flatMap{it.asSequence()}.first{graph[it]!!.size==1};for(i in 1 until answer.size){val neighbors=graph[answer[i-1]]!!;answer[i]=neighbors[0];if(i>1&&answer[i]==answer[i-2])answer[i]=neighbors[1]};return answer} }`,
`class Solution { public: vector<int> restoreArray(vector<vector<int>>& adjacentPairs){unordered_map<int,vector<int>> graph;for(auto& pair:adjacentPairs){graph[pair[0]].push_back(pair[1]);graph[pair[1]].push_back(pair[0]);}int start=0;bool found=false;for(auto& pair:adjacentPairs){for(int value:pair)if(graph[value].size()==1){start=value;found=true;break;}if(found)break;}vector<int> answer(graph.size());answer[0]=start;for(int i=1;i<(int)answer.size();++i){auto& neighbors=graph[answer[i-1]];answer[i]=neighbors[0];if(i>1&&answer[i]==answer[i-2])answer[i]=neighbors[1];}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'restoreArray',parameterTypes:['intMatrix'],returnType:'intArray',cases:[{name:'三对还原四元素路径',args:[[[2,1],[3,4],[3,2]]],expected:[1,2,3,4]},{name:'负数路径从端点开始',args:[[[4,-2],[1,4],[-3,1]]],expected:[-2,4,1,-3]},{name:'单对还原两个元素',args:[[[100000,-100000]]],expected:[100000,-100000]}]}}
]}
