const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-021',problems:[
{id:1477,slug:'find-two-non-overlapping-sub-arrays-each-with-target-sum',title:'两个和为目标值且不重叠的子数组',studyTags:['数组','动态规划','滑动窗口'],summary:'在正整数数组中找到两个互不重叠且和均为 target 的子数组，使长度和最小；不存在返回负一。',insight:'滑动窗口枚举每个以 right 结尾的目标子数组，同时 best[i] 保存前 i 范围内目标子数组的最短长度；当前窗口与 best[left-1] 组合即可保证不重叠。',pitfalls:['数组元素为正才能用单调滑窗','只与当前窗口左端之前的最优解组合','best 需要随 right 继承此前最小值'],solutions:[s('sliding-window-prefix-best','滑窗与前缀最短长度','在线组合当前目标窗口和其左侧最短目标窗口。',['left=0,sum=0,bestSoFar=INF,result=INF','right 扩展，sum>target 时移动 left；sum==target 时用 best[left-1] 更新 result，并更新 bestSoFar','best[right]=bestSoFar；结束返回 result 或 -1'],'O(n)','O(n)',
`class Solution { public int minSumOfLengths(int[] arr,int target){int n=arr.length,inf=1_000_000,left=0,sum=0,bestSoFar=inf,result=inf;int[] best=new int[n];Arrays.fill(best,inf);for(int right=0;right<n;right++){sum+=arr[right];while(sum>target)sum-=arr[left++];if(sum==target){int length=right-left+1;if(left>0&&best[left-1]<inf)result=Math.min(result,length+best[left-1]);bestSoFar=Math.min(bestSoFar,length);}best[right]=bestSoFar;}return result==inf?-1:result;} }`,
`class Solution { fun minSumOfLengths(arr:IntArray,target:Int):Int{val inf=1_000_000;val best=IntArray(arr.size){inf};var left=0;var sum=0;var bestSoFar=inf;var result=inf;for(right in arr.indices){sum+=arr[right];while(sum>target)sum-=arr[left++];if(sum==target){val length=right-left+1;if(left>0&&best[left-1]<inf)result=minOf(result,length+best[left-1]);bestSoFar=minOf(bestSoFar,length)};best[right]=bestSoFar};return if(result==inf)-1 else result} }`,
`class Solution { public: int minSumOfLengths(vector<int>& arr,int target){int n=arr.size(),inf=1000000,left=0,sum=0,bestSoFar=inf,result=inf;vector<int> best(n,inf);for(int right=0;right<n;++right){sum+=arr[right];while(sum>target)sum-=arr[left++];if(sum==target){int length=right-left+1;if(left&&best[left-1]<inf)result=min(result,length+best[left-1]);bestSoFar=min(bestSoFar,length);}best[right]=bestSoFar;}return result==inf?-1:result;} };`)],tests:{schemaVersion:1,mode:'function',method:'minSumOfLengths',parameterTypes:['intArray','int'],returnType:'int',cases:[{name:'首尾两个三长度和二',args:[[3,2,2,4,3],3],expected:2},{name:'两个七各为单元素',args:[[7,3,4,7],7],expected:2},{name:'只有一个目标子数组',args:[[4,3,2,6,2,3,4],6],expected:-1}]}},
{id:1478,slug:'allocate-mailboxes',title:'安排邮筒',studyTags:['数组','数学','动态规划','排序'],summary:'在数轴上为房屋安排 k 个邮筒，最小化每户到最近邮筒的距离总和。',insight:'排序后，一个连续房屋段使用一个邮筒时放在中位数处最优。预计算所有段成本，再做分组动态规划。',pitfalls:['最优分组在排序后是连续段','偶数段取两个中位数任一都得到相同成本','必须恰好使用不超过房屋数的 k 个邮筒'],solutions:[s('median-segment-partition-dp','中位数分段动态规划','预计算单邮筒服务区间成本并划分前缀。',['排序 houses；cost[i][j]=Σ|houses[t]-houses[(i+j)/2]|','dp[boxes][count] 表示前 count 户用 boxes 个邮筒最小成本','枚举最后一段起点 previous，转移 dp[b-1][previous]+cost[previous][count-1]'],'O(n³+n²k)','O(n²+nk)',
`class Solution { public int minDistance(int[] houses,int k){Arrays.sort(houses);int n=houses.length;int[][] segment=new int[n][n];for(int left=0;left<n;left++)for(int right=left;right<n;right++){int median=houses[(left+right)/2];for(int i=left;i<=right;i++)segment[left][right]+=Math.abs(houses[i]-median);}int inf=1_000_000_000;int[][] dp=new int[k+1][n+1];for(int[] row:dp)Arrays.fill(row,inf);dp[0][0]=0;for(int boxes=1;boxes<=k;boxes++)for(int count=1;count<=n;count++)for(int previous=0;previous<count;previous++)if(dp[boxes-1][previous]<inf)dp[boxes][count]=Math.min(dp[boxes][count],dp[boxes-1][previous]+segment[previous][count-1]);return dp[k][n];} }`,
`class Solution { fun minDistance(houses:IntArray,k:Int):Int{houses.sort();val n=houses.size;val segment=Array(n){IntArray(n)};for(left in 0 until n)for(right in left until n){val median=houses[(left+right)/2];for(i in left..right)segment[left][right]+=kotlin.math.abs(houses[i]-median)};val inf=1_000_000_000;val dp=Array(k+1){IntArray(n+1){inf}};dp[0][0]=0;for(boxes in 1..k)for(count in 1..n)for(previous in 0 until count)if(dp[boxes-1][previous]<inf)dp[boxes][count]=minOf(dp[boxes][count],dp[boxes-1][previous]+segment[previous][count-1]);return dp[k][n]} }`,
`class Solution { public: int minDistance(vector<int>& houses,int k){sort(houses.begin(),houses.end());int n=houses.size();vector<vector<int>> segment(n,vector<int>(n));for(int left=0;left<n;++left)for(int right=left;right<n;++right){int median=houses[(left+right)/2];for(int i=left;i<=right;++i)segment[left][right]+=abs(houses[i]-median);}const int inf=1000000000;vector<vector<int>> dp(k+1,vector<int>(n+1,inf));dp[0][0]=0;for(int boxes=1;boxes<=k;++boxes)for(int count=1;count<=n;++count)for(int previous=0;previous<count;++previous)if(dp[boxes-1][previous]<inf)dp[boxes][count]=min(dp[boxes][count],dp[boxes-1][previous]+segment[previous][count-1]);return dp[k][n];} };`)],tests:{schemaVersion:1,mode:'function',method:'minDistance',parameterTypes:['intArray','int'],returnType:'int',cases:[{name:'五户三邮筒最小距离五',args:[[1,4,8,10,20],3],expected:5},{name:'五户两邮筒最小距离九',args:[[2,3,5,12,18],2],expected:9},{name:'四户一个邮筒距离八',args:[[7,4,6,1],1],expected:8}]}},
{id:1480,slug:'running-sum-of-1d-array',title:'一维数组的动态和',studyTags:['数组','前缀和'],summary:'返回数组每个位置从开头到当前位置的元素总和。',insight:'从索引一开始把前一位置已经计算好的前缀和加到当前值，可原地完成。',pitfalls:['第零项保持原值','结果可复用输入数组','每项依赖更新后的前一项'],solutions:[s('in-place-prefix-sum','原地前缀和','让每个位置累加前一个前缀结果。',['i 从一到末尾','nums[i]+=nums[i-1]','返回 nums'],'O(n)','O(1)',
`class Solution { public int[] runningSum(int[] nums){for(int i=1;i<nums.length;i++)nums[i]+=nums[i-1];return nums;} }`,
`class Solution { fun runningSum(nums:IntArray):IntArray{for(i in 1 until nums.size)nums[i]+=nums[i-1];return nums} }`,
`class Solution { public: vector<int> runningSum(vector<int>& nums){for(int i=1;i<(int)nums.size();++i)nums[i]+=nums[i-1];return nums;} };`)],tests:{schemaVersion:1,mode:'function',method:'runningSum',parameterTypes:['intArray'],returnType:'intArray',cases:[{name:'四个一递增前缀',args:[[1,1,1,1]],expected:[1,2,3,4]},{name:'普通数组前缀和',args:[[1,2,3,4]],expected:[1,3,6,10]},{name:'单元素',args:[[5]],expected:[5]}]}},
{id:1481,slug:'least-number-of-unique-integers-after-k-removals',title:'不同整数的最少数目',studyTags:['数组','哈希表','贪心','排序','计数'],summary:'从数组恰好删除 k 个元素，求剩余不同整数数量的最小值。',insight:'为了最少种类，应优先完整删除出现次数最少的值；按频次升序消耗 k，无法完整删除下一类时停止。',pitfalls:['只删除某类一部分不会减少种类数','删除次数恰为 k，但剩余删除可落在现存类内','返回未被完整删除的类别数'],solutions:[s('ascending-frequency-removal','频次升序贪心删除','以最小代价逐个消除整数类别。',['统计每个值频次并升序排序 frequencies','unique=frequencies.length','若 k>=frequency，则 k-=frequency、unique--；否则停止，返回 unique'],'O(n log n)','O(n)',
`class Solution { public int findLeastNumOfUniqueInts(int[] arr,int k){Map<Integer,Integer> count=new HashMap<>();for(int value:arr)count.merge(value,1,Integer::sum);List<Integer> frequencies=new ArrayList<>(count.values());Collections.sort(frequencies);int unique=frequencies.size();for(int frequency:frequencies){if(k<frequency)break;k-=frequency;unique--;}return unique;} }`,
`class Solution { fun findLeastNumOfUniqueInts(arr:IntArray,k:Int):Int{val frequencies=arr.toList().groupingBy{it}.eachCount().values.sorted();var remaining=k;var unique=frequencies.size;for(frequency in frequencies){if(remaining<frequency)break;remaining-=frequency;unique--};return unique} }`,
`class Solution { public: int findLeastNumOfUniqueInts(vector<int>& arr,int k){unordered_map<int,int> count;for(int value:arr)++count[value];vector<int> frequencies;for(auto [value,frequency]:count)frequencies.push_back(frequency);sort(frequencies.begin(),frequencies.end());int unique=frequencies.size();for(int frequency:frequencies){if(k<frequency)break;k-=frequency;--unique;}return unique;} };`)],tests:{schemaVersion:1,mode:'function',method:'findLeastNumOfUniqueInts',parameterTypes:['intArray','int'],returnType:'int',cases:[{name:'删掉单个四只剩一种',args:[[5,5,4],1],expected:1},{name:'删除三项后剩两种',args:[[4,3,1,1,3,3,2],3],expected:2},{name:'不删除保留三种',args:[[1,2,3],0],expected:3}]}},
{id:1482,slug:'minimum-number-of-days-to-make-m-bouquets',title:'制作 M 束花所需的最少天数',studyTags:['数组','二分查找'],summary:'第 bloomDay[i] 天第 i 朵花开放，每束需 k 朵相邻开放花，求制作 m 束的最早天数。',insight:'给定天数能否制作足够花束具有单调性。二分天数，线性扫描连续开放花数并每满 k 朵组成一束。',pitfalls:['同一朵花不能重复使用','花束中的花必须相邻','m*k>花朵数时直接无解'],solutions:[s('binary-search-feasible-day','可行天数二分','在最小与最大开放日间寻找首个可行值。',['若 (long)m*k>n 返回 -1','feasible(day) 扫描 bloomDay，开放则 consecutive++，满 k 后 bouquets++ 并清零；未开放清零','二分闭区间，feasible(mid) 收缩右界，否则左界右移'],'O(n log D)','O(1)',
`class Solution { private boolean feasible(int[] bloomDay,int m,int k,int day){int bouquets=0,consecutive=0;for(int bloom:bloomDay){if(bloom<=day){if(++consecutive==k){bouquets++;consecutive=0;}}else consecutive=0;}return bouquets>=m;}public int minDays(int[] bloomDay,int m,int k){if((long)m*k>bloomDay.length)return -1;int left=Arrays.stream(bloomDay).min().getAsInt(),right=Arrays.stream(bloomDay).max().getAsInt();while(left<right){int middle=left+(right-left)/2;if(feasible(bloomDay,m,k,middle))right=middle;else left=middle+1;}return left;} }`,
`class Solution { private fun feasible(bloomDay:IntArray,m:Int,k:Int,day:Int):Boolean{var bouquets=0;var consecutive=0;for(bloom in bloomDay){if(bloom<=day){consecutive++;if(consecutive==k){bouquets++;consecutive=0}}else consecutive=0};return bouquets>=m};fun minDays(bloomDay:IntArray,m:Int,k:Int):Int{if(m.toLong()*k>bloomDay.size)return -1;var left=bloomDay.minOrNull()!!;var right=bloomDay.maxOrNull()!!;while(left<right){val middle=left+(right-left)/2;if(feasible(bloomDay,m,k,middle))right=middle else left=middle+1};return left} }`,
`class Solution { bool feasible(vector<int>& bloomDay,int m,int k,int day){int bouquets=0,consecutive=0;for(int bloom:bloomDay){if(bloom<=day){if(++consecutive==k){++bouquets;consecutive=0;}}else consecutive=0;}return bouquets>=m;}public:int minDays(vector<int>& bloomDay,int m,int k){if(1LL*m*k>(int)bloomDay.size())return -1;int left=*min_element(bloomDay.begin(),bloomDay.end()),right=*max_element(bloomDay.begin(),bloomDay.end());while(left<right){int middle=left+(right-left)/2;if(feasible(bloomDay,m,k,middle))right=middle;else left=middle+1;}return left;} };`)],tests:{schemaVersion:1,mode:'function',method:'minDays',parameterTypes:['intArray','int','int'],returnType:'int',cases:[{name:'单花花束最早第三天',args:[[1,10,3,10,2],3,1],expected:3},{name:'花数不足制作三束',args:[[1,10,3,10,2],3,2],expected:-1},{name:'相邻三花需等到十二天',args:[[7,7,7,7,12,7,7],2,3],expected:12}]}}
]}
