const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-011',problems:[
{id:844,slug:'backspace-string-compare',title:'比较含退格的字符串',studyTags:['字符串','双指针','模拟'],summary:'井号表示退格删除前一个字符，判断两个字符串在编辑器中最终是否相等。',insight:'从后向前扫描，用 skip 计数跳过被退格删除的字符；每次找到两串下一个有效字符并比较，无需构造结果串。',pitfalls:['空文本上的退格没有效果','连续井号会累计删除数量','一串先耗尽而另一串仍有有效字符时不相等'],solutions:[s('reverse-skip-two-pointers','反向退格双指针','逐次定位两串的下一个可见字符。',['i、j 从各自末尾开始','辅助循环：遇 # 则 skip++，遇普通字符且 skip>0 则 skip-- 并跳过，否则停下','比较停下字符；不同返回假，相同则双指针各减一，直到都结束'],'O(m+n)','O(1)',
`class Solution { public boolean backspaceCompare(String s,String t){int i=s.length()-1,j=t.length()-1;while(i>=0||j>=0){i=previous(s,i);j=previous(t,j);if(i<0||j<0)return i==j;if(s.charAt(i)!=t.charAt(j))return false;i--;j--;}return true;}private int previous(String text,int index){int skip=0;while(index>=0){if(text.charAt(index)=='#'){skip++;index--;}else if(skip>0){skip--;index--;}else break;}return index;} }`,
`class Solution { fun backspaceCompare(s:String,t:String):Boolean{var i=s.lastIndex;var j=t.lastIndex;while(i>=0||j>=0){i=previous(s,i);j=previous(t,j);if(i<0||j<0)return i==j;if(s[i]!=t[j])return false;i--;j--};return true};private fun previous(text:String,start:Int):Int{var index=start;var skip=0;while(index>=0){if(text[index]=='#'){skip++;index--}else if(skip>0){skip--;index--}else break};return index} }`,
`class Solution { int previous(string& text,int index){int skip=0;while(index>=0){if(text[index]=='#'){++skip;--index;}else if(skip){--skip;--index;}else break;}return index;}public:bool backspaceCompare(string s,string t){int i=s.size()-1,j=t.size()-1;while(i>=0||j>=0){i=previous(s,i);j=previous(t,j);if(i<0||j<0)return i==j;if(s[i]!=t[j])return false;--i;--j;}return true;} };`)],tests:{schemaVersion:1,mode:'function',method:'backspaceCompare',parameterTypes:['string','string'],returnType:'boolean',cases:[{name:'两串都变为 ac',args:['ab#c','ad#c'],expected:true},{name:'连续退格',args:['ab##','c#d#'],expected:true},{name:'最终字符不同',args:['a#c','b'],expected:false}]}},
{id:845,slug:'longest-mountain-in-array',title:'数组中的最长山脉',studyTags:['数组','双指针','动态规划'],summary:'山脉子数组先严格递增再严格递减，且长度至少三，求最长山脉长度。',insight:'一次扫描维护当前连续上升边数 up 和下降边数 down；平台或下降后重新上升会结束旧山脉并重置状态。',pitfalls:['必须同时有上升段和下降段','相等元素会中断山脉','下降结束后遇新上升要清空旧下降和上升计数'],solutions:[s('rolling-up-down-lengths','滚动上升下降边数','按相邻比较更新当前山脉状态。',['up=down=0','若相等，或 down>0 后又上升，则 up=down=0','上升时 up++，下降时 down++；当 up>0 且 down>0 更新 answer=up+down+1'],'O(n)','O(1)',
`class Solution { public int longestMountain(int[] arr){int answer=0,up=0,down=0;for(int i=1;i<arr.length;i++){if(arr[i]==arr[i-1]||down>0&&arr[i]>arr[i-1]){up=0;down=0;}if(arr[i]>arr[i-1])up++;else if(arr[i]<arr[i-1])down++;if(up>0&&down>0)answer=Math.max(answer,up+down+1);}return answer;} }`,
`class Solution { fun longestMountain(arr:IntArray):Int{var answer=0;var up=0;var down=0;for(i in 1 until arr.size){if(arr[i]==arr[i-1]||down>0&&arr[i]>arr[i-1]){up=0;down=0};if(arr[i]>arr[i-1])up++ else if(arr[i]<arr[i-1])down++;if(up>0&&down>0)answer=maxOf(answer,up+down+1)};return answer} }`,
`class Solution { public: int longestMountain(vector<int>& arr){int answer=0,up=0,down=0;for(int i=1;i<(int)arr.size();++i){if(arr[i]==arr[i-1]||(down>0&&arr[i]>arr[i-1]))up=down=0;if(arr[i]>arr[i-1])++up;else if(arr[i]<arr[i-1])++down;if(up&&down)answer=max(answer,up+down+1);}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'longestMountain',parameterTypes:['intArray'],returnType:'int',cases:[{name:'最长山脉长度五',args:[[2,1,4,7,3,2,5]],expected:5},{name:'全平台',args:[[2,2,2]],expected:0},{name:'完整长山脉',args:[[0,1,2,3,4,5,4,3,2,1,0]],expected:11}]}},
{id:846,slug:'hand-of-straights',title:'一手顺子',studyTags:['数组','哈希表','排序','有序映射'],summary:'把所有牌分成每组 groupSize 张的连续数字，判断是否可行。',insight:'每次从当前最小牌开始，它不可能作为更大顺子的中间，因此必须取从它起的 groupSize 个连续值；有序计数表支持重复执行。',pitfalls:['牌数不能被 groupSize 整除时立即失败','每取一张要删除或递减频次','缺少任一连续值就失败'],solutions:[s('smallest-card-greedy-treemap','有序频次表最小牌贪心','反复消费以最小剩余值开头的顺子。',['若 hand.length%groupSize!=0 返回假，建立有序频次表','while 表非空，start=firstKey','for value=start..start+groupSize-1，若不存在返回假；频次一则删除，否则减一；耗尽返回真'],'O(n log n)','O(n)',
`class Solution { public boolean isNStraightHand(int[] hand,int groupSize){if(hand.length%groupSize!=0)return false;TreeMap<Integer,Integer> count=new TreeMap<>();for(int value:hand)count.merge(value,1,Integer::sum);while(!count.isEmpty()){int start=count.firstKey();for(int value=start;value<start+groupSize;value++){Integer frequency=count.get(value);if(frequency==null)return false;if(frequency==1)count.remove(value);else count.put(value,frequency-1);}}return true;} }`,
`class Solution { fun isNStraightHand(hand:IntArray,groupSize:Int):Boolean{if(hand.size%groupSize!=0)return false;val count=java.util.TreeMap<Int,Int>();for(value in hand)count[value]=(count[value]?:0)+1;while(count.isNotEmpty()){val start=count.firstKey();for(value in start until start+groupSize){val frequency=count[value]?:return false;if(frequency==1)count.remove(value)else count[value]=frequency-1}};return true} }`,
`class Solution { public: bool isNStraightHand(vector<int>& hand,int groupSize){if(hand.size()%groupSize)return false;map<int,int> count;for(int value:hand)++count[value];while(!count.empty()){int start=count.begin()->first;for(int value=start;value<start+groupSize;++value){auto found=count.find(value);if(found==count.end())return false;if(--found->second==0)count.erase(found);}}return true;} };`)],tests:{schemaVersion:1,mode:'function',method:'isNStraightHand',parameterTypes:['intArray','int'],returnType:'boolean',cases:[{name:'可分三个顺子',args:[[1,2,3,6,2,3,4,7,8],3],expected:true},{name:'无法分四张连续牌',args:[[1,2,3,4,5],4],expected:false},{name:'重复两组顺子',args:[[1,1,2,2,3,3],3],expected:true}]}},
{id:847,slug:'shortest-path-visiting-all-nodes',title:'访问所有节点的最短路径',studyTags:['图论','广度优先搜索','状态压缩'],summary:'连通无向图可从任意节点出发、重复经过节点，求访问所有节点的最短路径长度。',insight:'状态由当前位置和已访问节点位掩码组成；把每个节点作为零步起点同时入队，多源 BFS 首次得到全掩码就是全局最短。',pitfalls:['路径可重复节点和边','起点可任意选择，所以全部单节点状态都是 BFS 源','visited 要区分相同节点下不同掩码'],solutions:[s('multi-source-mask-bfs','多源状态压缩 BFS','在节点乘访问集合的状态图上求最短路。',['targetMask=(1<<n)-1；为每个 node 入队 (node,1<<node,0) 并标记','弹出状态，mask==target 返回 distance','对每个邻居生成 nextMask=mask|1<<neighbor，未访问状态入队 distance+1'],'O((v+e)·2^v)','O(v·2^v)',
`class Solution { public int shortestPathLength(int[][] graph){int n=graph.length,target=(1<<n)-1;boolean[][] seen=new boolean[n][1<<n];Queue<int[]> queue=new ArrayDeque<>();for(int node=0;node<n;node++){queue.offer(new int[]{node,1<<node,0});seen[node][1<<node]=true;}while(!queue.isEmpty()){int[] state=queue.poll();if(state[1]==target)return state[2];for(int next:graph[state[0]]){int mask=state[1]|1<<next;if(!seen[next][mask]){seen[next][mask]=true;queue.offer(new int[]{next,mask,state[2]+1});}}}return -1;} }`,
`class Solution { fun shortestPathLength(graph:Array<IntArray>):Int{val n=graph.size;val target=(1 shl n)-1;val seen=Array(n){BooleanArray(1 shl n)};val queue=java.util.ArrayDeque<IntArray>();for(node in 0 until n){queue.addLast(intArrayOf(node,1 shl node,0));seen[node][1 shl node]=true};while(queue.isNotEmpty()){val state=queue.removeFirst();if(state[1]==target)return state[2];for(next in graph[state[0]]){val mask=state[1] or (1 shl next);if(!seen[next][mask]){seen[next][mask]=true;queue.addLast(intArrayOf(next,mask,state[2]+1))}}};return -1} }`,
`class Solution { public: int shortestPathLength(vector<vector<int>>& graph){int n=graph.size(),target=(1<<n)-1;vector<vector<bool>> seen(n,vector<bool>(1<<n));queue<array<int,3>> pending;for(int node=0;node<n;++node){pending.push({node,1<<node,0});seen[node][1<<node]=true;}while(!pending.empty()){auto [node,mask,distance]=pending.front();pending.pop();if(mask==target)return distance;for(int next:graph[node]){int nextMask=mask|1<<next;if(!seen[next][nextMask]){seen[next][nextMask]=true;pending.push({next,nextMask,distance+1});}}}return -1;} };`)],tests:{schemaVersion:1,mode:'function',method:'shortestPathLength',parameterTypes:['intMatrix'],returnType:'int',cases:[{name:'星形图四步',args:[[[1,2,3],[0],[0],[0]]],expected:4},{name:'五节点图四步',args:[[[1],[0,2,4],[1,3,4],[2],[1,2]]],expected:4},{name:'单节点',args:[[[]]],expected:0}]}},
{id:848,slug:'shifting-letters',title:'字母移位',studyTags:['数组','字符串','前缀和'],summary:'第 i 个操作把字符串前 i+1 个字母都向后移 shifts[i] 次，返回全部操作后的字符串。',insight:'位置 i 受到 shifts[i..n-1] 的所有操作影响；从右向左维护后缀移位和并对 26 取模即可原地计算。',pitfalls:['z 后移一位回到 a','后缀总和可能很大，应持续取模或用长整型','每个 shifts[i] 影响的是前缀而非后缀'],solutions:[s('reverse-suffix-shift-sum','反向后缀移位和','从末尾累加每个位置所受总移位。',['字符数组 chars=s.toCharArray，shift=0','i 从 n-1 到零，shift=(shift+shifts[i])%26','chars[i]=(chars[i]-a+shift)%26+a，结束返回字符串'],'O(n)','O(n)',
`class Solution { public String shiftingLetters(String s,int[] shifts){char[] chars=s.toCharArray();long shift=0;for(int i=chars.length-1;i>=0;i--){shift=(shift+shifts[i])%26;chars[i]=(char)('a'+(chars[i]-'a'+shift)%26);}return new String(chars);} }`,
`class Solution { fun shiftingLetters(s:String,shifts:IntArray):String{val chars=s.toCharArray();var shift=0L;for(i in chars.indices.reversed()){shift=(shift+shifts[i])%26;chars[i]=('a'.code+(chars[i]-'a'+shift).toInt()%26).toChar()};return String(chars)} }`,
`class Solution { public: string shiftingLetters(string s,vector<int>& shifts){long long shift=0;for(int i=s.size()-1;i>=0;--i){shift=(shift+shifts[i])%26;s[i]='a'+(s[i]-'a'+shift)%26;}return s;} };`)],tests:{schemaVersion:1,mode:'function',method:'shiftingLetters',parameterTypes:['string','intArray'],returnType:'string',cases:[{name:'经典三字符',args:['abc',[3,5,9]],expected:'rpl'},{name:'递增移位',args:['aaa',[1,2,3]],expected:'gfd'},{name:'z 环回 a',args:['z',[1]],expected:'a'}]}}
]}
