const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-014',problems:[
{id:970,slug:'powerful-integers',title:'强整数',studyTags:['数学','枚举','哈希集合'],summary:'返回所有不超过 bound 且可写成 x^i+y^j 的正整数，其中 i、j 为非负整数。',insight:'当底数大于一时幂次只需枚举到超过 bound，底数为一时幂值始终为一；双层枚举并用集合去重。',pitfalls:['i 和 j 可以为零，因此幂从一开始','x 或 y 等于一时必须显式终止避免死循环','不同幂组合可能得到相同和'],solutions:[s('bounded-power-pair-enumeration','有界幂对枚举','生成两个有限幂集合的所有合法和。',['外层 a 从 1 按 x 倍增，内层 b 从 1 按 y 倍增','若 a+b≤bound 加入有序集合','底数为一或下一次乘法会越界时停止对应循环，返回集合列表'],'O(log_x B·log_y B)','O(result)',
`class Solution { public List<Integer> powerfulIntegers(int x,int y,int bound){Set<Integer> values=new TreeSet<>();for(long a=1;a<=bound;){for(long b=1;b<=bound;){if(a+b<=bound)values.add((int)(a+b));if(y==1||b>bound/y)break;b*=y;}if(x==1||a>bound/x)break;a*=x;}return new ArrayList<>(values);} }`,
`class Solution { fun powerfulIntegers(x:Int,y:Int,bound:Int):List<Int>{val values=sortedSetOf<Int>();var a=1L;while(a<=bound){var b=1L;while(b<=bound){if(a+b<=bound)values.add((a+b).toInt());if(y==1||b>bound/y)break;b*=y};if(x==1||a>bound/x)break;a*=x};return values.toList()} }`,
`class Solution { public: vector<int> powerfulIntegers(int x,int y,int bound){set<int> values;for(long long a=1;a<=bound;){for(long long b=1;b<=bound;){if(a+b<=bound)values.insert(a+b);if(y==1||b>bound/y)break;b*=y;}if(x==1||a>bound/x)break;a*=x;}return {values.begin(),values.end()};} };`)],tests:{schemaVersion:1,mode:'function',method:'powerfulIntegers',parameterTypes:['int','int','int'],returnType:'intList',cases:[{name:'二和三的幂',args:[2,3,10],expected:[2,3,4,5,7,9,10]},{name:'三和五的幂',args:[3,5,15],expected:[2,4,6,8,10,14]},{name:'两个底数为一',args:[1,1,2],expected:[2]}]}},
{id:971,slug:'flip-binary-tree-to-match-preorder-traversal',title:'翻转二叉树以匹配先序遍历',studyTags:['树','深度优先搜索','贪心'],summary:'可在任意节点交换左右孩子，返回一组翻转节点值使树的先序遍历等于 voyage；无法做到返回 [-1]。',insight:'按 voyage 指针做先序 DFS；根值必须匹配，若下一目标值不等于当前左孩子值，就只能在当前节点翻转并先遍历右子树。',pitfalls:['节点值互不相同，可据下一值唯一决定翻转','值不匹配要传播失败状态','叶节点或已消费完 voyage 时按原顺序递归即可'],solutions:[s('preorder-next-value-greedy','先序下一值贪心','用即将访问的目标值决定是否交换遍历顺序。',['index=0，flips 为空','DFS 节点：空返回真；若 index 越界或 node.val!=voyage[index] 返回假，否则 index++','若左孩子存在且其值不等于 voyage[index]，记录 node.val 并先 DFS right 后 left；否则先 left 后 right；失败返回 [-1]'],'O(n)','O(height)',
`class Solution { private int index;private List<Integer> flips;public List<Integer> flipMatchVoyage(TreeNode root,int[] voyage){index=0;flips=new ArrayList<>();if(!dfs(root,voyage))return Arrays.asList(-1);return flips;}private boolean dfs(TreeNode node,int[] voyage){if(node==null)return true;if(index>=voyage.length||node.val!=voyage[index++])return false;if(node.left!=null&&index<voyage.length&&node.left.val!=voyage[index]){flips.add(node.val);return dfs(node.right,voyage)&&dfs(node.left,voyage);}return dfs(node.left,voyage)&&dfs(node.right,voyage);} }`,
`class Solution { private var index=0;private val flips=mutableListOf<Int>();fun flipMatchVoyage(root:TreeNode?,voyage:IntArray):List<Int>{index=0;flips.clear();return if(dfs(root,voyage))flips else listOf(-1)};private fun dfs(node:TreeNode?,voyage:IntArray):Boolean{node?:return true;if(index>=voyage.size||node.\`val\`!=voyage[index++])return false;if(node.left!=null&&index<voyage.size&&node.left!!.\`val\`!=voyage[index]){flips.add(node.\`val\`);return dfs(node.right,voyage)&&dfs(node.left,voyage)};return dfs(node.left,voyage)&&dfs(node.right,voyage)} }`,
`class Solution { int index;vector<int> flips;bool dfs(TreeNode* node,vector<int>& voyage){if(!node)return true;if(index==(int)voyage.size()||node->val!=voyage[index++])return false;if(node->left&&index<(int)voyage.size()&&node->left->val!=voyage[index]){flips.push_back(node->val);return dfs(node->right,voyage)&&dfs(node->left,voyage);}return dfs(node->left,voyage)&&dfs(node->right,voyage);}public:vector<int> flipMatchVoyage(TreeNode* root,vector<int>& voyage){index=0;flips.clear();return dfs(root,voyage)?flips:vector<int>{-1};} };`)],tests:{schemaVersion:1,mode:'function',method:'flipMatchVoyage',parameterTypes:['treeNode','intArray'],returnType:'intList',cases:[{name:'根值不匹配',args:[[1,2],[2,1]],expected:[-1]},{name:'在根节点翻转',args:[[1,2,3],[1,3,2]],expected:[1]},{name:'无需翻转',args:[[1,2,3],[1,2,3]],expected:[]}]}},
{id:972,slug:'equal-rational-numbers',title:'相等的有理数',studyTags:['字符串','数学'],summary:'判断两个含整数、小数及可选循环小数部分的非负有理数字符串是否表示同一数值。',insight:'非循环小数 A 有 m 位、循环块 B 有 r 位时，小数贡献为 A/10^m+B/[10^m(10^r-1)]；按公式解析后比较即可。',pitfalls:['循环块可使 0.9(9) 等于一','小数点后非循环部分可以为空','比较浮点解析结果使用足够小的容差'],solutions:[s('rational-part-formula','小数部分公式解析','分别计算整数、非循环和循环三段贡献。',['按小数点分整数部分与 fraction','若有左括号，分出 nonRepeat 与 repeat，否则全部为 nonRepeat','value=integer+nonRepeat/10^m；循环非空时再加 repeat/[10^m(10^r-1)]，比较两值差小于 1e-10'],'O(|s|+|t|)','O(|s|+|t|)',
`class Solution { public boolean isRationalEqual(String s,String t){return Math.abs(value(s)-value(t))<1e-10;}private double value(String text){int dot=text.indexOf('.');double result=Double.parseDouble(text.substring(0,dot));String fraction=text.substring(dot+1);int open=fraction.indexOf('(');String nonRepeat=open<0?fraction:fraction.substring(0,open);String repeat=open<0?"":fraction.substring(open+1,fraction.length()-1);double scale=Math.pow(10,nonRepeat.length());if(!nonRepeat.isEmpty())result+=Long.parseLong(nonRepeat)/scale;if(!repeat.isEmpty())result+=Long.parseLong(repeat)/(scale*(Math.pow(10,repeat.length())-1));return result;} }`,
`class Solution { fun isRationalEqual(s:String,t:String):Boolean=kotlin.math.abs(value(s)-value(t))<1e-10;private fun value(text:String):Double{val dot=text.indexOf('.');var result=text.substring(0,dot).toDouble();val fraction=text.substring(dot+1);val open=fraction.indexOf('(');val nonRepeat=if(open<0)fraction else fraction.substring(0,open);val repeat=if(open<0)"" else fraction.substring(open+1,fraction.length-1);val scale=Math.pow(10.0,nonRepeat.length.toDouble());if(nonRepeat.isNotEmpty())result+=nonRepeat.toLong()/scale;if(repeat.isNotEmpty())result+=repeat.toLong()/(scale*(Math.pow(10.0,repeat.length.toDouble())-1));return result} }`,
`class Solution { double value(string text){int dot=text.find('.');double result=stod(text.substr(0,dot));string fraction=text.substr(dot+1);int open=fraction.find('(');string nonRepeat=open<0?fraction:fraction.substr(0,open),repeat=open<0?"":fraction.substr(open+1,fraction.size()-open-2);double scale=pow(10.0,nonRepeat.size());if(!nonRepeat.empty())result+=stoll(nonRepeat)/scale;if(!repeat.empty())result+=stoll(repeat)/(scale*(pow(10.0,repeat.size())-1));return result;}public:bool isRationalEqual(string s,string t){return abs(value(s)-value(t))<1e-10;} };`)],tests:{schemaVersion:1,mode:'function',method:'isRationalEqual',parameterTypes:['string','string'],returnType:'boolean',cases:[{name:'循环写法不同但相等',args:['0.(52)','0.5(25)'],expected:true},{name:'循环六位置不同',args:['0.1666(6)','0.166(66)'],expected:true},{name:'循环九等于一',args:['0.9(9)','1.'],expected:true}]}},
{id:973,slug:'k-closest-points-to-origin',title:'最接近原点的 K 个点',studyTags:['数组','几何','排序'],summary:'返回平面点集中欧氏距离原点最近的 k 个点，答案顺序任意。',insight:'平方距离与真实距离排序一致且无需开方；按 x²+y² 升序排序后取前 k 个点。',pitfalls:['平方计算用长整型防止中间溢出','题目允许任意答案顺序','返回点坐标而非距离'],solutions:[s('squared-distance-sort','平方距离排序','按无需开方的距离键排序全部点。',['按 (long)x*x+(long)y*y 对 points 升序排序','创建长度 k 的结果矩阵','复制排序后的前 k 行并返回'],'O(n log n)','O(log n)',
`class Solution { public int[][] kClosest(int[][] points,int k){Arrays.sort(points,Comparator.comparingLong(p->(long)p[0]*p[0]+(long)p[1]*p[1]));return Arrays.copyOf(points,k);} }`,
`class Solution { fun kClosest(points:Array<IntArray>,k:Int):Array<IntArray>{points.sortBy{it[0].toLong()*it[0]+it[1].toLong()*it[1]};return points.copyOfRange(0,k)} }`,
`class Solution { public: vector<vector<int>> kClosest(vector<vector<int>>& points,int k){sort(points.begin(),points.end(),[](auto& a,auto& b){return (long long)a[0]*a[0]+(long long)a[1]*a[1]<(long long)b[0]*b[0]+(long long)b[1]*b[1];});return {points.begin(),points.begin()+k};} };`)],tests:{schemaVersion:1,mode:'function',method:'kClosest',parameterTypes:['intMatrix','int'],returnType:'intMatrix',cases:[{name:'两点取最近',args:[[[1,3],[-2,2]],1],expected:[[-2,2]]},{name:'三点取两个',args:[[[3,3],[5,-1],[-2,4]],2],expected:[[3,3],[-2,4]]},{name:'单点',args:[[[0,1]],1],expected:[[0,1]]}]}},
{id:974,slug:'subarray-sums-divisible-by-k',title:'和可被 K 整除的子数组',studyTags:['数组','哈希表','前缀和'],summary:'统计非空连续子数组中元素和能被 k 整除的数量。',insight:'子数组和可整除当且仅当两端前缀和模 k 相同；扫描时累加此前同余数出现次数，再记录当前余数。',pitfalls:['初始前缀余数零出现一次','负前缀和余数要规范到 0..k-1','计数结果在题目范围内用整数即可'],solutions:[s('prefix-remainder-frequency','前缀余数频次','把可整除子数组转化为同余前缀对。',['frequency[0]=1，remainder=0，answer=0','逐元素令 remainder=((remainder+value)%k+k)%k','answer+=frequency[remainder]，再 frequency[remainder]++；返回 answer'],'O(n)','O(k)',
`class Solution { public int subarraysDivByK(int[] nums,int k){int[] frequency=new int[k];frequency[0]=1;int remainder=0,answer=0;for(int value:nums){remainder=((remainder+value)%k+k)%k;answer+=frequency[remainder]++;}return answer;} }`,
`class Solution { fun subarraysDivByK(nums:IntArray,k:Int):Int{val frequency=IntArray(k);frequency[0]=1;var remainder=0;var answer=0;for(value in nums){remainder=((remainder+value)%k+k)%k;answer+=frequency[remainder]++};return answer} }`,
`class Solution { public: int subarraysDivByK(vector<int>& nums,int k){vector<int> frequency(k);frequency[0]=1;int remainder=0,answer=0;for(int value:nums){remainder=((remainder+value)%k+k)%k;answer+=frequency[remainder]++;}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'subarraysDivByK',parameterTypes:['intArray','int'],returnType:'int',cases:[{name:'经典答案七',args:[[4,5,0,-2,-3,1],5],expected:7},{name:'单元素不可整除',args:[[5],9],expected:0},{name:'两个零有三段',args:[[0,0],3],expected:3}]}}
]}
