const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-019',problems:[
{id:1354,slug:'construct-target-array-with-multiple-sums',title:'多次求和构造目标数组',studyTags:['数组','堆（优先队列）','贪心'],summary:'从全一数组出发，每次把一个位置替换为当前数组总和，判断能否得到 target。',insight:'逆向恢复时只有最大值可能是最后被替换的位置。其替换前的值等于 max 对其余元素和 rest 取模；用最大堆反复恢复。',pitfalls:['总和必须用 long','rest 为一时一定能继续恢复','余数为零、rest 不小于最大值或 rest 为零时无解'],solutions:[s('reverse-max-heap','最大堆逆向恢复','每次把当前最大值批量还原到对其余和取模后的前驱值。',['将 target 放入最大堆并计算 total','取 max，令 rest=total-max；max 或 rest 为一时成功，非法状态时失败','previous=max%rest，更新 total 并把 previous 放回堆'],'O(n log n + log M log n)','O(n)',
`class Solution { public boolean isPossible(int[] target){PriorityQueue<Long> heap=new PriorityQueue<>(Collections.reverseOrder());long total=0;for(int value:target){heap.offer((long)value);total+=value;}while(true){long maximum=heap.poll(),rest=total-maximum;if(maximum==1||rest==1)return true;if(rest==0||rest>=maximum||maximum%rest==0)return false;long previous=maximum%rest;total=rest+previous;heap.offer(previous);}} }`,
`class Solution { fun isPossible(target:IntArray):Boolean{val heap=java.util.PriorityQueue<Long>(reverseOrder());var total=0L;for(value in target){heap.add(value.toLong());total+=value};while(true){val maximum=heap.remove();val rest=total-maximum;if(maximum==1L||rest==1L)return true;if(rest==0L||rest>=maximum||maximum%rest==0L)return false;val previous=maximum%rest;total=rest+previous;heap.add(previous)}} }`,
`class Solution { public: bool isPossible(vector<int>& target){priority_queue<long long> heap;long long total=0;for(int value:target){heap.push(value);total+=value;}while(true){long long maximum=heap.top();heap.pop();long long rest=total-maximum;if(maximum==1||rest==1)return true;if(rest==0||rest>=maximum||maximum%rest==0)return false;long long previous=maximum%rest;total=rest+previous;heap.push(previous);}} };`)],tests:{schemaVersion:1,mode:'function',method:'isPossible',parameterTypes:['intArray'],returnType:'boolean',cases:[{name:'九三五可以构造',args:[[9,3,5]],expected:true},{name:'总和关系不合法',args:[[1,1,1,2]],expected:false},{name:'两个数可按欧几里得式恢复',args:[[8,5]],expected:true}]}},
{id:1356,slug:'sort-integers-by-the-number-of-1-bits',title:'根据数字二进制下 1 的数目排序',studyTags:['数组','位运算','排序'],summary:'按每个整数二进制表示中的一位数量升序排序，相同数量时按数值升序。',insight:'排序键是二元组（bitCount(value), value）；直接用语言内置位计数作为比较器即可。',pitfalls:['位数相同时必须按原数值升序','返回排序后的数组','比较器应满足稳定一致的顺序'],solutions:[s('bit-count-comparator','位计数比较器','以一位数量和数值组成复合排序键。',['把整数装箱或直接使用可定制比较器的排序','先比较 bitCount，再比较 value','输出排序结果'],'O(n log n)','O(n)',
`class Solution { public int[] sortByBits(int[] arr){Integer[] values=Arrays.stream(arr).boxed().toArray(Integer[]::new);Arrays.sort(values,Comparator.comparingInt((Integer value)->Integer.bitCount(value)).thenComparingInt(value->value));for(int i=0;i<arr.length;i++)arr[i]=values[i];return arr;} }`,
`class Solution { fun sortByBits(arr:IntArray):IntArray=arr.sortedWith(compareBy<Int>{Integer.bitCount(it)}.thenBy{it}).toIntArray() }`,
`class Solution { public: vector<int> sortByBits(vector<int>& arr){sort(arr.begin(),arr.end(),[](int a,int b){int ca=__builtin_popcount((unsigned)a),cb=__builtin_popcount((unsigned)b);return ca==cb?a<b:ca<cb;});return arr;} };`)],tests:{schemaVersion:1,mode:'function',method:'sortByBits',parameterTypes:['intArray'],returnType:'intArray',cases:[{name:'零到八按位数排序',args:[[0,1,2,3,4,5,6,7,8]],expected:[0,1,2,4,8,3,5,6,7]},{name:'全为二的幂按值排序',args:[[1024,512,256,128,64,32,16,8,4,2,1]],expected:[1,2,4,8,16,32,64,128,256,512,1024]},{name:'重复数字保留',args:[[3,8,3]],expected:[8,3,3]}]}},
{id:1357,slug:'apply-discount-every-n-orders',title:'每隔 n 个顾客打折',studyTags:['设计','哈希表','模拟'],summary:'设计收银系统，按商品单价计算账单，并对每第 n 位顾客应用固定百分比折扣。',insight:'用哈希表保存商品价格、计数器记录已结账次数；只有计数能被 n 整除时乘折扣系数。',pitfalls:['折扣作用于整张账单','顾客计数在每次 getBill 时增加','金额使用 double'],solutions:[s('price-map-counter','价格表与订单计数','查询商品价格求和后按订单序号决定是否折扣。',['构造时建立 product 到 price 的映射','getBill 中累加 price[product[i]]*amount[i] 并增加 counter','若 counter%n==0，乘 (100-discount)/100，返回'],'O(p)','O(m)',
`class Cashier { private final int n,discount;private int counter=0;private final Map<Integer,Integer> prices=new HashMap<>();public Cashier(int n,int discount,int[] products,int[] values){this.n=n;this.discount=discount;for(int i=0;i<products.length;i++)prices.put(products[i],values[i]);}public double getBill(int[] product,int[] amount){double total=0;for(int i=0;i<product.length;i++)total+=prices.get(product[i])*amount[i];counter++;return counter%n==0?total*(100-discount)/100.0:total;} }`,
`class Cashier(private val n:Int,private val discount:Int,products:IntArray,values:IntArray){private var counter=0;private val prices=products.indices.associate{products[it] to values[it]};fun getBill(product:IntArray,amount:IntArray):Double{var total=0.0;for(i in product.indices)total+=prices.getValue(product[i])*amount[i];counter++;return if(counter%n==0)total*(100-discount)/100.0 else total}}`,
`class Cashier { int n,discount,counter=0;unordered_map<int,int> prices;public:Cashier(int n,int discount,vector<int>& products,vector<int>& values):n(n),discount(discount){for(int i=0;i<(int)products.size();++i)prices[products[i]]=values[i];}double getBill(vector<int> product,vector<int> amount){double total=0;for(int i=0;i<(int)product.size();++i)total+=prices[product[i]]*amount[i];++counter;return counter%n==0?total*(100-discount)/100.0:total;} };`)],tests:{schemaVersion:1,mode:'design',className:'Cashier',constructorTypes:['int','int','intArray','intArray'],cases:[{name:'第三单应用五折',constructorArgs:[3,50,[1,2,3,4,5,6,7],[100,200,300,400,300,200,100]],calls:[{method:'getBill',parameterTypes:['intArray','intArray'],args:[[1,2],[1,2]],returnType:'double',expected:500.0},{method:'getBill',parameterTypes:['intArray','intArray'],args:[[3,7],[10,10]],returnType:'double',expected:4000.0},{method:'getBill',parameterTypes:['intArray','intArray'],args:[[1,2,3,4,5,6,7],[1,1,1,1,1,1,1]],returnType:'double',expected:800.0}]},{name:'每单都打八折',constructorArgs:[1,20,[5],[10]],calls:[{method:'getBill',parameterTypes:['intArray','intArray'],args:[[5],[3]],returnType:'double',expected:24.0}]},{name:'每第二单打七五折',constructorArgs:[2,25,[1],[8]],calls:[{method:'getBill',parameterTypes:['intArray','intArray'],args:[[1],[1]],returnType:'double',expected:8.0},{method:'getBill',parameterTypes:['intArray','intArray'],args:[[1],[1]],returnType:'double',expected:6.0}]}]}},
{id:1358,slug:'number-of-substrings-containing-all-three-characters',title:'包含所有三种字符的子字符串数目',studyTags:['字符串','滑动窗口'],summary:'统计只含 a、b、c 的字符串中，同时包含三种字符的子字符串数量。',insight:'记录三种字符最近出现位置。以 i 结尾时，合法起点共有 min(last)+1 个，逐位累加即可。',pitfalls:['未出现的位置初始化为负一','每个位置统计的是以当前位置结尾的子串','答案可能达到平方级但题目范围内 int 可容纳'],solutions:[s('last-occurrence-minimum','最近位置最小值','由三种字符最近位置中最早的一个确定合法起点上界。',['last 三项初始化为 -1','扫描 i，更新 s[i] 对应的 last','answer += 1 + min(last)，返回 answer'],'O(n)','O(1)',
`class Solution { public int numberOfSubstrings(String text){int[] last={-1,-1,-1};int answer=0;for(int i=0;i<text.length();i++){last[text.charAt(i)-'a']=i;answer+=1+Math.min(last[0],Math.min(last[1],last[2]));}return answer;} }`,
`class Solution { fun numberOfSubstrings(text:String):Int{val last=intArrayOf(-1,-1,-1);var answer=0;for(i in text.indices){last[text[i]-'a']=i;answer+=1+minOf(last[0],last[1],last[2])};return answer} }`,
`class Solution { public: int numberOfSubstrings(string text){int last[3]={-1,-1,-1},answer=0;for(int i=0;i<(int)text.size();++i){last[text[i]-'a']=i;answer+=1+min({last[0],last[1],last[2]});}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'numberOfSubstrings',parameterTypes:['string'],returnType:'int',cases:[{name:'重复 abc 共有十个',args:['abcabc'],expected:10},{name:'多个 a 后出现 cb',args:['aaacb'],expected:3},{name:'恰好三个字符',args:['abc'],expected:1}]}},
{id:1359,slug:'count-all-valid-pickup-and-delivery-options',title:'有效的快递序列数目',studyTags:['数学','组合数学'],summary:'计算 n 份订单的取货和送货排列中，每份订单均先取后送的合法序列数。',insight:'加入第 i 份订单时，可在已有 2(i-1) 个动作序列中选择取货位置，再在其后选择送货位置，共 i(2i-1) 种插入方式。',pitfalls:['每步都要取模','乘法使用 long','n=1 的结果为一'],solutions:[s('multiplicative-counting','递推乘法计数','依次把一对新取送货动作插入已有合法序列。',['answer=1','对 i 从 1 到 n，乘 i*(2*i-1) 并取模','返回 answer'],'O(n)','O(1)',
`class Solution { public int countOrders(int n){long answer=1,mod=1_000_000_007L;for(long i=1;i<=n;i++)answer=answer*i%mod*(2*i-1)%mod;return (int)answer;} }`,
`class Solution { fun countOrders(n:Int):Int{val mod=1_000_000_007L;var answer=1L;for(i in 1L..n.toLong())answer=answer*i%mod*(2*i-1)%mod;return answer.toInt()} }`,
`class Solution { public: int countOrders(int n){const long long mod=1000000007;long long answer=1;for(long long i=1;i<=n;++i)answer=answer*i%mod*(2*i-1)%mod;return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'countOrders',parameterTypes:['int'],returnType:'int',cases:[{name:'一份订单',args:[1],expected:1},{name:'两份订单六种',args:[2],expected:6},{name:'三份订单九十种',args:[3],expected:90}]}}
]}
