const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-024',problems:[
{id:1690,slug:'stone-game-vii',title:'石子游戏 VII',studyTags:['数组','数学','动态规划','博弈'],summary:'两人轮流移除两端石子，获得移除后剩余石子总和，双方最优；求 Alice 与 Bob 最终分差。',insight:'区间 DP 直接记录当前玩家从区间 [left,right] 开始能取得的最大净胜分。移除一端的即时得分减去对手在剩余区间的净胜分，二者取大。',pitfalls:['得分是移除后剩余石子之和','DP 值是当前玩家相对对手的分差','单石区间无法获得分数，状态为零'],solutions:[s('interval-score-difference-dp','区间分差动态规划','用零和博弈的净胜分消去玩家维度。',['前缀和支持区间求和，dp 单点为零','区间长度从二递增','removeLeft=sum(left+1,right)-dp[left+1][right]，removeRight=sum(left,right-1)-dp[left][right-1]，取最大'],'O(n²)','O(n²)',
`class Solution { public int stoneGameVII(int[] stones){int n=stones.length;int[] prefix=new int[n+1];for(int i=0;i<n;i++)prefix[i+1]=prefix[i]+stones[i];int[][] dp=new int[n][n];for(int length=2;length<=n;length++)for(int left=0;left+length<=n;left++){int right=left+length-1;int removeLeft=prefix[right+1]-prefix[left+1]-dp[left+1][right];int removeRight=prefix[right]-prefix[left]-dp[left][right-1];dp[left][right]=Math.max(removeLeft,removeRight);}return dp[0][n-1];} }`,
`class Solution { fun stoneGameVII(stones:IntArray):Int{val n=stones.size;val prefix=IntArray(n+1);for(i in stones.indices)prefix[i+1]=prefix[i]+stones[i];val dp=Array(n){IntArray(n)};for(length in 2..n)for(left in 0..n-length){val right=left+length-1;val removeLeft=prefix[right+1]-prefix[left+1]-dp[left+1][right];val removeRight=prefix[right]-prefix[left]-dp[left][right-1];dp[left][right]=maxOf(removeLeft,removeRight)};return dp[0][n-1]} }`,
`class Solution { public: int stoneGameVII(vector<int>& stones){int n=stones.size();vector<int> prefix(n+1);for(int i=0;i<n;++i)prefix[i+1]=prefix[i]+stones[i];vector<vector<int>> dp(n,vector<int>(n));for(int length=2;length<=n;++length)for(int left=0;left+length<=n;++left){int right=left+length-1;int removeLeft=prefix[right+1]-prefix[left+1]-dp[left+1][right];int removeRight=prefix[right]-prefix[left]-dp[left][right-1];dp[left][right]=max(removeLeft,removeRight);}return dp[0][n-1];} };`)],tests:{schemaVersion:1,mode:'function',method:'stoneGameVII',parameterTypes:['intArray'],returnType:'int',cases:[{name:'五堆石子最优分差六',args:[[5,3,1,4,2]],expected:6},{name:'八堆石子最优分差一百二十二',args:[[7,90,5,1,100,10,10,2]],expected:122},{name:'两堆石子取小端得分二',args:[[1,2]],expected:2}]}},
{id:1691,slug:'maximum-height-by-stacking-cuboids',title:'堆叠长方体的最大高度',studyTags:['数组','动态规划','排序'],summary:'每个长方体可旋转，堆叠时上方三个维度都不能超过下方对应维度，求最大总高度。',insight:'先把每个长方体三个维度排序，等价于固定最大维作高；再按三维字典序排序，对可逐维包含的长方体做加权最长递增子序列。',pitfalls:['每个长方体内部维度先排序以统一旋转','堆叠比较包含三个维度','相等维度允许堆叠'],solutions:[s('normalized-cuboid-lis','维度归一化与三维 DP','把旋转选择吸收到每个长方体的排序表示中。',['每个 cuboid 维度升序排序，再对所有 cuboid 字典序排序','dp[i]=cuboids[i][2]','若 cuboid[j] 三维都<=cuboid[i]，则 dp[i]=max(dp[i],dp[j]+height[i])，取全局最大'],'O(n²)','O(n)',
`class Solution { public int maxHeight(int[][] cuboids){for(int[] cuboid:cuboids)Arrays.sort(cuboid);Arrays.sort(cuboids,(a,b)->a[0]!=b[0]?a[0]-b[0]:a[1]!=b[1]?a[1]-b[1]:a[2]-b[2]);int[] dp=new int[cuboids.length];int answer=0;for(int i=0;i<cuboids.length;i++){dp[i]=cuboids[i][2];for(int j=0;j<i;j++)if(cuboids[j][0]<=cuboids[i][0]&&cuboids[j][1]<=cuboids[i][1]&&cuboids[j][2]<=cuboids[i][2])dp[i]=Math.max(dp[i],dp[j]+cuboids[i][2]);answer=Math.max(answer,dp[i]);}return answer;} }`,
`class Solution { fun maxHeight(cuboids:Array<IntArray>):Int{for(cuboid in cuboids)cuboid.sort();cuboids.sortWith(compareBy<IntArray>{it[0]}.thenBy{it[1]}.thenBy{it[2]});val dp=IntArray(cuboids.size);var answer=0;for(i in cuboids.indices){dp[i]=cuboids[i][2];for(j in 0 until i)if((0..2).all{cuboids[j][it]<=cuboids[i][it]})dp[i]=maxOf(dp[i],dp[j]+cuboids[i][2]);answer=maxOf(answer,dp[i])};return answer} }`,
`class Solution { public: int maxHeight(vector<vector<int>>& cuboids){for(auto& cuboid:cuboids)sort(cuboid.begin(),cuboid.end());sort(cuboids.begin(),cuboids.end());vector<int> dp(cuboids.size());int answer=0;for(int i=0;i<(int)cuboids.size();++i){dp[i]=cuboids[i][2];for(int j=0;j<i;++j)if(cuboids[j][0]<=cuboids[i][0]&&cuboids[j][1]<=cuboids[i][1]&&cuboids[j][2]<=cuboids[i][2])dp[i]=max(dp[i],dp[j]+cuboids[i][2]);answer=max(answer,dp[i]);}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'maxHeight',parameterTypes:['intMatrix'],returnType:'int',cases:[{name:'三个长方体最大堆高一百九十',args:[[[50,45,20],[95,37,53],[45,23,12]]],expected:190},{name:'两个长方体无法同时最优堆叠',args:[[[38,25,45],[76,35,3]]],expected:76},{name:'三个相同长方体高度累加',args:[[[7,11,17],[7,11,17],[7,11,17]]],expected:51}]}},
{id:1694,slug:'reformat-phone-number',title:'重新格式化电话号码',studyTags:['字符串'],summary:'移除电话号码中的空格和连字符，再从左向右分组：尽量三位一组，最后四位必须分成两个两位组。',insight:'先提取纯数字。只要剩余超过四位就取三位；剩四位时取两个两位，否则把剩余两或三位作为最后一组。',pitfalls:['不能出现最后一组只有一位','恰好四位必须分为二加二','输出组之间用单个连字符'],solutions:[s('greedy-digit-grouping','纯数字贪心分组','根据剩余位数决定下一组长度。',['过滤出 digits','while remaining>4，取三位加入 groups','remaining==4 取两组两位，否则取全部剩余；用连字符连接'],'O(n)','O(n)',
`class Solution { public String reformatNumber(String number){String digits=number.replace(" ","").replace("-","");List<String> groups=new ArrayList<>();int index=0;while(digits.length()-index>4){groups.add(digits.substring(index,index+3));index+=3;}int remaining=digits.length()-index;if(remaining==4){groups.add(digits.substring(index,index+2));groups.add(digits.substring(index+2));}else groups.add(digits.substring(index));return String.join("-",groups);} }`,
`class Solution { fun reformatNumber(number:String):String{val digits=number.filter{it.isDigit()};val groups=mutableListOf<String>();var index=0;while(digits.length-index>4){groups.add(digits.substring(index,index+3));index+=3};val remaining=digits.length-index;if(remaining==4){groups.add(digits.substring(index,index+2));groups.add(digits.substring(index+2))}else groups.add(digits.substring(index));return groups.joinToString("-")} }`,
`class Solution { public: string reformatNumber(string number){string digits;for(char value:number)if(isdigit(value))digits+=value;vector<string> groups;int index=0;while((int)digits.size()-index>4){groups.push_back(digits.substr(index,3));index+=3;}int remaining=digits.size()-index;if(remaining==4){groups.push_back(digits.substr(index,2));groups.push_back(digits.substr(index+2,2));}else groups.push_back(digits.substr(index));string answer;for(auto& group:groups){if(!answer.empty())answer+='-';answer+=group;}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'reformatNumber',parameterTypes:['string'],returnType:'string',cases:[{name:'十二位按三位分组',args:['1-23-45 6'],expected:'123-456'},{name:'最后四位拆成两个两位组',args:['123 4-567'],expected:'123-45-67'},{name:'长号码尾部避免单字符组',args:['12'],expected:'12'}]}},
{id:1695,slug:'maximum-erasure-value',title:'删除子数组的最大得分',studyTags:['数组','哈希表','滑动窗口'],summary:'选择一个元素互不相同的连续子数组并删除，得分为元素和，求最大得分。',insight:'所有数为正，固定右端时最优左端是刚好消除重复后的最早位置。用集合维护无重复窗口和窗口总和。',pitfalls:['子数组必须连续','窗口内所有数值互不相同','正数保证扩大合法窗口不会降低得分'],solutions:[s('unique-sum-sliding-window','无重复和滑动窗口','遇到重复时从左侧移除直到当前值可加入。',['seen 集合，left=0，sum=answer=0','right 扫描；while nums[right] 已在 seen，移除 nums[left] 并从 sum 扣除，left++','加入当前值和 sum，更新 answer'],'O(n)','O(n)',
`class Solution { public int maximumUniqueSubarray(int[] nums){Set<Integer> seen=new HashSet<>();int left=0,sum=0,answer=0;for(int value:nums){while(seen.contains(value)){seen.remove(nums[left]);sum-=nums[left++];}seen.add(value);sum+=value;answer=Math.max(answer,sum);}return answer;} }`,
`class Solution { fun maximumUniqueSubarray(nums:IntArray):Int{val seen=mutableSetOf<Int>();var left=0;var sum=0;var answer=0;for(value in nums){while(value in seen){seen.remove(nums[left]);sum-=nums[left++]};seen.add(value);sum+=value;answer=maxOf(answer,sum)};return answer} }`,
`class Solution { public: int maximumUniqueSubarray(vector<int>& nums){unordered_set<int> seen;int left=0,sum=0,answer=0;for(int value:nums){while(seen.count(value)){seen.erase(nums[left]);sum-=nums[left++];}seen.insert(value);sum+=value;answer=max(answer,sum);}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'maximumUniqueSubarray',parameterTypes:['intArray'],returnType:'int',cases:[{name:'二到五组成最大无重复和十七',args:[[4,2,4,5,6]],expected:17},{name:'重复数组最大得分八',args:[[5,2,1,2,5,2,1,2,5]],expected:8},{name:'单元素得分为自身',args:[[9]],expected:9}]}},
{id:1696,slug:'jump-game-vi',title:'跳跃游戏 VI',studyTags:['数组','动态规划','队列','单调队列','滑动窗口'],summary:'从下标零出发，每次最多向前跳 k 格，到达末尾；得分为经过元素之和，求最大得分。',insight:'dp[i]=nums[i]+前 k 个 dp 的最大值。用下标单调队列维护窗口内 dp 递减序列，队首就是转移最大值。',pitfalls:['窗口只包含 i-k 到 i-1','过期下标要在转移前移除','负数也必须经过某条合法路径'],solutions:[s('monotonic-queue-dp','单调队列优化动态规划','维护滑动窗口最大 dp，把转移降为常数均摊。',['dp[0]=nums[0]，deque=[0]','i 从一开始，移除 deque.front<i-k','dp[i]=nums[i]+dp[front]；从尾部移除 dp<=dp[i] 的下标，再加入 i'],'O(n)','O(n)',
`class Solution { public int maxResult(int[] nums,int k){int[] dp=new int[nums.length];dp[0]=nums[0];Deque<Integer> deque=new ArrayDeque<>();deque.offerLast(0);for(int i=1;i<nums.length;i++){while(deque.peekFirst()<i-k)deque.pollFirst();dp[i]=nums[i]+dp[deque.peekFirst()];while(!deque.isEmpty()&&dp[deque.peekLast()]<=dp[i])deque.pollLast();deque.offerLast(i);}return dp[nums.length-1];} }`,
`class Solution { fun maxResult(nums:IntArray,k:Int):Int{val dp=IntArray(nums.size);dp[0]=nums[0];val deque=java.util.ArrayDeque<Int>();deque.addLast(0);for(i in 1 until nums.size){while(deque.first<i-k)deque.removeFirst();dp[i]=nums[i]+dp[deque.first];while(deque.isNotEmpty()&&dp[deque.last]<=dp[i])deque.removeLast();deque.addLast(i)};return dp.last()} }`,
`class Solution { public: int maxResult(vector<int>& nums,int k){vector<int> dp(nums.size());dp[0]=nums[0];deque<int> candidates{0};for(int i=1;i<(int)nums.size();++i){while(candidates.front()<i-k)candidates.pop_front();dp[i]=nums[i]+dp[candidates.front()];while(!candidates.empty()&&dp[candidates.back()]<=dp[i])candidates.pop_back();candidates.push_back(i);}return dp.back();} };`)],tests:{schemaVersion:1,mode:'function',method:'maxResult',parameterTypes:['intArray','int'],returnType:'int',cases:[{name:'最多跳两格最大得分七',args:[[1,-1,-2,4,-7,3],2],expected:7},{name:'最多跳三格最大得分十七',args:[[10,-5,-2,4,0,3],3],expected:17},{name:'负数路径最大得分零',args:[[1,-5,-20,4,-1,3,-6,-3],2],expected:0}]}}
]}
