const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-005',problems:[
{id:174,slug:'dungeon-game',title:'地下城游戏',studyTags:['动态规划','逆向推导','网格'],summary:'计算骑士从左上角走到右下角并始终保持至少一点生命所需的最小初始生命值。',insight:'从终点逆推进入每个格子前至少需要的生命值，后继取向右和向下需求的较小值。',pitfalls:['生命值任何时刻都不能降到零','应从终点向起点计算','每格需求至少为一'],solutions:[s('reverse-dp','逆向一维动态规划','用 dp[column] 保存从当前格进入后走到终点所需的最小生命。',['边界设为无穷并在终点外侧放一','从右下向左上更新','需求=max(1,min(右,下)-当前值)'],'O(mn)','O(n)',
`class Solution { public int calculateMinimumHP(int[][] dungeon) { int n=dungeon[0].length; int[] dp=new int[n+1]; Arrays.fill(dp,Integer.MAX_VALUE); dp[n-1]=1; for(int r=dungeon.length-1;r>=0;r--) for(int c=n-1;c>=0;c--){ int next=Math.min(dp[c],dp[c+1]); dp[c]=Math.max(1,next-dungeon[r][c]); } return dp[0]; } }`,
`class Solution { fun calculateMinimumHP(dungeon:Array<IntArray>):Int { val n=dungeon[0].size; val dp=IntArray(n+1){Int.MAX_VALUE}; dp[n-1]=1; for(r in dungeon.lastIndex downTo 0) for(c in n-1 downTo 0){ val next=minOf(dp[c],dp[c+1]); dp[c]=maxOf(1,next-dungeon[r][c]) }; return dp[0] } }`,
`class Solution { public: int calculateMinimumHP(vector<vector<int>>& dungeon){ int n=dungeon[0].size(); vector<int> dp(n+1,INT_MAX); dp[n-1]=1; for(int r=dungeon.size()-1;r>=0;--r) for(int c=n-1;c>=0;--c){ int next=min(dp[c],dp[c+1]); dp[c]=max(1,next-dungeon[r][c]); } return dp[0]; } };`)],tests:{schemaVersion:1,mode:'function',method:'calculateMinimumHP',parameterTypes:['intMatrix'],returnType:'int',cases:[{name:'经典地下城',args:[[[-2,-3,3],[-5,-10,1],[10,30,-5]]],expected:7},{name:'单个正房间',args:[[[5]]],expected:1},{name:'单个负房间',args:[[[-8]]],expected:9}]}},
{id:187,slug:'repeated-dna-sequences',title:'重复的 DNA 序列',studyTags:['滑动窗口','哈希表','字符串'],summary:'找出 DNA 字符串中所有出现超过一次的长度为十的连续片段。',insight:'固定长度窗口从左到右扫描，用已见集合判断重复，并用另一集合保证每个答案只加入一次。',pitfalls:['窗口长度固定为十','重复片段只能输出一次','短于十的字符串没有答案'],solutions:[s('two-hash-sets','双集合滑动窗口','seen 记录首次出现，repeated 按首次重复顺序收集。',['枚举所有长度十窗口','加入 seen 失败时加入 repeated','返回 repeated 列表'],'O(n)','O(n)',
`class Solution { public List<String> findRepeatedDnaSequences(String s){ Set<String> seen=new HashSet<>(); Set<String> repeated=new LinkedHashSet<>(); for(int i=0;i+10<=s.length();i++){ String part=s.substring(i,i+10); if(!seen.add(part)) repeated.add(part); } return new ArrayList<>(repeated); } }`,
`class Solution { fun findRepeatedDnaSequences(s:String):List<String>{ val seen=hashSetOf<String>(); val repeated=linkedSetOf<String>(); for(i in 0..s.length-10){ val part=s.substring(i,i+10); if(!seen.add(part)) repeated.add(part) }; return repeated.toList() } }`,
`class Solution { public: vector<string> findRepeatedDnaSequences(string s){ unordered_set<string> seen,added; vector<string> answer; for(int i=0;i+10<=(int)s.size();++i){ string part=s.substr(i,10); if(!seen.insert(part).second && added.insert(part).second) answer.push_back(part); } return answer; } };`)],tests:{schemaVersion:1,mode:'function',method:'findRepeatedDnaSequences',parameterTypes:['string'],returnType:'stringList',cases:[{name:'两个重复片段',args:['AAAAACCCCCAAAAACCCCCCAAAAAGGGTTT'],expected:['AAAAACCCCC','CCCCCAAAAA']},{name:'高度重复',args:['AAAAAAAAAAAAA'],expected:['AAAAAAAAAA']},{name:'长度不足',args:['ACGT'],expected:[]}]}},
{id:188,slug:'best-time-to-buy-and-sell-stock-iv',title:'买卖股票的最佳时机 IV',studyTags:['动态规划','股票','状态压缩'],summary:'在最多完成 k 笔买卖且同一时间最多持有一股时，求最大利润。',insight:'按交易次数维护买入和卖出后的最大余额；当 k 足够大时退化为不限次数交易。',pitfalls:['一次交易包含买入和卖出','k 大于天数一半时应走贪心捷径','买入状态依赖前一次卖出'],solutions:[s('transaction-dp','交易次数滚动动态规划','sell[t] 表示完成至多 t 笔交易且空仓的最大利润。',['处理不限交易情形','初始化 buy 为极小值','逐价格按交易次数更新 buy 和 sell'],'O(nk)','O(k)',
`class Solution { public int maxProfit(int k,int[] prices){ if(k>=prices.length/2){int p=0;for(int i=1;i<prices.length;i++)p+=Math.max(0,prices[i]-prices[i-1]);return p;} int[] buy=new int[k+1],sell=new int[k+1];Arrays.fill(buy,Integer.MIN_VALUE/2);for(int price:prices)for(int t=1;t<=k;t++){buy[t]=Math.max(buy[t],sell[t-1]-price);sell[t]=Math.max(sell[t],buy[t]+price);}return sell[k];} }`,
`class Solution { fun maxProfit(k:Int,prices:IntArray):Int{ if(k>=prices.size/2){var p=0;for(i in 1 until prices.size)p+=maxOf(0,prices[i]-prices[i-1]);return p};val buy=IntArray(k+1){Int.MIN_VALUE/2};val sell=IntArray(k+1);for(price in prices)for(t in 1..k){buy[t]=maxOf(buy[t],sell[t-1]-price);sell[t]=maxOf(sell[t],buy[t]+price)};return sell[k]} }`,
`class Solution { public: int maxProfit(int k,vector<int>& prices){if(k>=(int)prices.size()/2){int p=0;for(int i=1;i<(int)prices.size();++i)p+=max(0,prices[i]-prices[i-1]);return p;}vector<int> buy(k+1,INT_MIN/2),sell(k+1);for(int price:prices)for(int t=1;t<=k;++t){buy[t]=max(buy[t],sell[t-1]-price);sell[t]=max(sell[t],buy[t]+price);}return sell[k];} };`)],tests:{schemaVersion:1,mode:'function',method:'maxProfit',parameterTypes:['int','intArray'],returnType:'int',cases:[{name:'一笔交易',args:[2,[2,4,1]],expected:2},{name:'两笔交易',args:[2,[3,2,6,5,0,3]],expected:7},{name:'没有价格',args:[3,[]],expected:0}]}},
{id:201,slug:'bitwise-and-of-numbers-range',title:'数字范围按位与',studyTags:['位运算','公共前缀','右移'],summary:'计算闭区间内所有整数按位与的结果。',insight:'只要区间两端某个高位以下发生变化，低位在区间中必然出现零；答案就是两端二进制公共前缀。',pitfalls:['需包含区间两端','低位差异全部归零','右移次数决定最后左移位数'],solutions:[s('common-prefix','二进制公共前缀','同步右移直到两端相等，再左移恢复公共高位。',['shift 初始化零','left 与 right 不等时都右移','相等值左移 shift 位'],'O(log right)','O(1)',
`class Solution { public int rangeBitwiseAnd(int left,int right){int shift=0;while(left!=right){left>>=1;right>>=1;shift++;}return left<<shift;} }`,
`class Solution { fun rangeBitwiseAnd(leftValue:Int,rightValue:Int):Int{var left=leftValue;var right=rightValue;var shift=0;while(left!=right){left=left shr 1;right=right shr 1;shift++};return left shl shift} }`,
`class Solution { public: int rangeBitwiseAnd(int left,int right){int shift=0;while(left!=right){left>>=1;right>>=1;++shift;}return left<<shift;} };`)],tests:{schemaVersion:1,mode:'function',method:'rangeBitwiseAnd',parameterTypes:['int','int'],returnType:'int',cases:[{name:'五到七',args:[5,7],expected:4},{name:'单点区间',args:[0,0],expected:0},{name:'跨越高位边界',args:[1,2147483647],expected:0}]}},
{id:204,slug:'count-primes',title:'计数质数',studyTags:['埃氏筛','数论','布尔数组'],summary:'统计严格小于 n 的所有质数数量。',insight:'从每个尚未被标记的质数 p 出发，只需从 p² 开始标记其倍数为合数。',pitfalls:['统计范围不包含 n','零和一不是质数','p² 可能越界，应以 long 判断循环条件'],solutions:[s('sieve-of-eratosthenes','埃拉托斯特尼筛','布尔数组标记合数，最后统计未标记且至少为二的数。',['创建 n 长度合数数组','对 p²<n 的未标记 p 筛去倍数','统计 2..n-1 中未标记项'],'O(n log log n)','O(n)',
`class Solution { public int countPrimes(int n){boolean[] composite=new boolean[n];for(int p=2;(long)p*p<n;p++)if(!composite[p])for(int value=p*p;value<n;value+=p)composite[value]=true;int count=0;for(int value=2;value<n;value++)if(!composite[value])count++;return count;} }`,
`class Solution { fun countPrimes(n:Int):Int{val composite=BooleanArray(n);var p=2;while(p.toLong()*p<n){if(!composite[p]){var value=p*p;while(value<n){composite[value]=true;value+=p}};p++};var count=0;for(value in 2 until n)if(!composite[value])count++;return count} }`,
`class Solution { public: int countPrimes(int n){vector<bool> composite(n);for(int p=2;(long long)p*p<n;++p)if(!composite[p])for(int value=p*p;value<n;value+=p)composite[value]=true;int count=0;for(int value=2;value<n;++value)if(!composite[value])++count;return count;} };`)],tests:{schemaVersion:1,mode:'function',method:'countPrimes',parameterTypes:['int'],returnType:'int',cases:[{name:'十以内四个质数',args:[10],expected:4},{name:'边界零',args:[0],expected:0},{name:'一百以内',args:[100],expected:25}]}}
]}
