const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-014',problems:[
{id:960,slug:'delete-columns-to-make-sorted-iii',title:'删列造序 III',studyTags:['数组','字符串','动态规划'],summary:'删除公共列，使每个字符串自身从左到右非递减，求最少删除列数。',insight:'选择保留列的最长子序列：若列 i 能在列 j 前保留，必须对每一行都有 strs[row][i]≤strs[row][j]；在列上做最长上升子序列动态规划。',pitfalls:['约束发生在每个字符串内部，不是字符串数组之间','两列的兼容性要对所有行成立','答案是总列数减最长可保留列数'],solutions:[s('column-subsequence-dp','列子序列动态规划','把兼容列关系视作偏序上的最长链。',['dp[j]=1 表示只保留列 j','对 i<j，若所有行的 i 列字符不大于 j 列字符，则 dp[j]=max(dp[j],dp[i]+1)','返回 columns-max(dp)'],'O(rows·cols²)','O(cols)',
`class Solution { public int minDeletionSize(String[] strs){int columns=strs[0].length();int[] dp=new int[columns];Arrays.fill(dp,1);int longest=1;for(int j=0;j<columns;j++)for(int i=0;i<j;i++){boolean compatible=true;for(String word:strs)if(word.charAt(i)>word.charAt(j)){compatible=false;break;}if(compatible)dp[j]=Math.max(dp[j],dp[i]+1);longest=Math.max(longest,dp[j]);}return columns-longest;} }`,
`class Solution { fun minDeletionSize(strs:Array<String>):Int{val columns=strs[0].length;val dp=IntArray(columns){1};var longest=1;for(j in 0 until columns){for(i in 0 until j){var compatible=true;for(word in strs)if(word[i]>word[j]){compatible=false;break};if(compatible)dp[j]=maxOf(dp[j],dp[i]+1)};longest=maxOf(longest,dp[j])};return columns-longest} }`,
`class Solution { public: int minDeletionSize(vector<string>& strs){int columns=strs[0].size(),longest=1;vector<int> dp(columns,1);for(int j=0;j<columns;++j){for(int i=0;i<j;++i){bool compatible=true;for(string& word:strs)if(word[i]>word[j]){compatible=false;break;}if(compatible)dp[j]=max(dp[j],dp[i]+1);}longest=max(longest,dp[j]);}return columns-longest;} };`)],tests:{schemaVersion:1,mode:'function',method:'minDeletionSize',parameterTypes:['stringArray'],returnType:'int',cases:[{name:'保留两列',args:[['babca','bbazb']],expected:3},{name:'单行严格递减',args:[['edcba']],expected:4},{name:'所有列可保留',args:[['ghi','def','abc']],expected:0}]}},
{id:961,slug:'n-repeated-element-in-size-2n-array',title:'在长度 2N 的数组中找出重复 N 次的元素',studyTags:['数组','哈希集合'],summary:'长度 2n 的数组含 n+1 个不同元素，其中一个恰出现 n 次，其余各一次，返回重复元素。',insight:'扫描时第一个无法加入集合的元素必然就是唯一重复元素。',pitfalls:['n 可能为二，重复元素只出现两次','无需统计完整频次','题目保证存在且唯一'],solutions:[s('first-duplicate-set','首个重复集合检测','用已见集合识别第二次出现的元素。',['创建空集合 seen','依次尝试加入 nums 中元素','若 add 返回 false 就立即返回该值'],'O(n)','O(n)',
`class Solution { public int repeatedNTimes(int[] nums){Set<Integer> seen=new HashSet<>();for(int value:nums)if(!seen.add(value))return value;throw new IllegalArgumentException();} }`,
`class Solution { fun repeatedNTimes(nums:IntArray):Int{val seen=mutableSetOf<Int>();for(value in nums)if(!seen.add(value))return value;error("invalid input")} }`,
`class Solution { public: int repeatedNTimes(vector<int>& nums){unordered_set<int> seen;for(int value:nums)if(!seen.insert(value).second)return value;return -1;} };`)],tests:{schemaVersion:1,mode:'function',method:'repeatedNTimes',parameterTypes:['intArray'],returnType:'int',cases:[{name:'二重复两次',args:[[1,2,3,3]],expected:3},{name:'三重复三次',args:[[2,1,2,5,3,2]],expected:2},{name:'五重复四次',args:[[5,1,5,2,5,3,5,4]],expected:5}]}},
{id:962,slug:'maximum-width-ramp',title:'最大宽度坡',studyTags:['数组','单调栈'],summary:'求满足 i<j 且 nums[i]≤nums[j] 的最大 j-i。',insight:'左端只可能是从左看出现的新低值，先把这些下标压成严格递减栈；再从右向左扫描，能匹配当前右端的栈顶都可结算并永久弹出。',pitfalls:['条件允许两端值相等','右向左扫描保证某左端首次匹配到的是最远右端','栈保存下标且对应值严格递减'],solutions:[s('decreasing-left-index-stack','递减左端栈','筛选候选左端后从最远右端批量匹配。',['从左到右，若栈空或 nums[i]<nums[stack.top] 则压入 i','j 从 n-1 降到零','当栈非空且 nums[stack.top]≤nums[j]，更新 j-stack.top 并弹栈；返回最大值'],'O(n)','O(n)',
`class Solution { public int maxWidthRamp(int[] nums){Deque<Integer> stack=new ArrayDeque<>();for(int i=0;i<nums.length;i++)if(stack.isEmpty()||nums[i]<nums[stack.peek()])stack.push(i);int answer=0;for(int j=nums.length-1;j>=0;j--)while(!stack.isEmpty()&&nums[stack.peek()]<=nums[j])answer=Math.max(answer,j-stack.pop());return answer;} }`,
`class Solution { fun maxWidthRamp(nums:IntArray):Int{val stack=java.util.ArrayDeque<Int>();for(i in nums.indices)if(stack.isEmpty()||nums[i]<nums[stack.peek()])stack.push(i);var answer=0;for(j in nums.lastIndex downTo 0)while(stack.isNotEmpty()&&nums[stack.peek()]<=nums[j])answer=maxOf(answer,j-stack.pop());return answer} }`,
`class Solution { public: int maxWidthRamp(vector<int>& nums){vector<int> stack;for(int i=0;i<(int)nums.size();++i)if(stack.empty()||nums[i]<nums[stack.back()])stack.push_back(i);int answer=0;for(int j=nums.size()-1;j>=0;--j)while(!stack.empty()&&nums[stack.back()]<=nums[j]){answer=max(answer,j-stack.back());stack.pop_back();}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'maxWidthRamp',parameterTypes:['intArray'],returnType:'int',cases:[{name:'最大宽度四',args:[[6,0,8,2,1,5]],expected:4},{name:'最大宽度七',args:[[9,8,1,0,1,9,4,0,4,1]],expected:7},{name:'两元素递增',args:[[1,2]],expected:1}]}},
{id:963,slug:'minimum-area-rectangle-ii',title:'最小面积矩形 II',studyTags:['数组','哈希表','几何'],summary:'给定平面点集，寻找边可任意倾斜且四个顶点都在点集中的最小正面积矩形，不存在返回零。',insight:'矩形两条对角线中点相同且长度相等；按端点坐标和与平方距离给所有点对分组，同组任意两条不同对角线构成矩形。',pitfalls:['坐标和等于中点的两倍，可避免浮点键','还要把对角线平方长度加入分组键','面积用从一条对角线端点到另一条对角线两端的叉积绝对值'],solutions:[s('equal-diagonal-grouping','等中点等长对角线分组','枚举同组对角线对并计算矩形面积。',['枚举点对 i<j，按 sumX,sumY,distanceSquared 加入分组','对每个分组枚举两条对角线','取第一条一个端点 p 和第二条两端 q,r，面积为 |(q-p)×(r-p)|，更新最小正值'],'O(n⁴) worst case','O(n²)',
`class Solution { public double minAreaFreeRect(int[][] points){Map<String,List<int[]>> groups=new HashMap<>();for(int i=0;i<points.length;i++)for(int j=i+1;j<points.length;j++){long dx=points[i][0]-points[j][0],dy=points[i][1]-points[j][1];String key=(points[i][0]+points[j][0])+","+(points[i][1]+points[j][1])+","+(dx*dx+dy*dy);groups.computeIfAbsent(key,k->new ArrayList<>()).add(new int[]{i,j});}double answer=Double.MAX_VALUE;for(List<int[]> group:groups.values())for(int a=0;a<group.size();a++)for(int b=a+1;b<group.size();b++){int[] p=points[group.get(a)[0]],q=points[group.get(b)[0]],r=points[group.get(b)[1]];long area=Math.abs((long)(q[0]-p[0])*(r[1]-p[1])-(long)(q[1]-p[1])*(r[0]-p[0]));if(area>0)answer=Math.min(answer,area);}return answer==Double.MAX_VALUE?0:answer;} }`,
`class Solution { fun minAreaFreeRect(points:Array<IntArray>):Double{val groups=mutableMapOf<String,MutableList<IntArray>>();for(i in points.indices)for(j in i+1 until points.size){val dx=points[i][0].toLong()-points[j][0];val dy=points[i][1].toLong()-points[j][1];val key=(points[i][0]+points[j][0]).toString()+","+(points[i][1]+points[j][1])+","+(dx*dx+dy*dy);groups.getOrPut(key){mutableListOf()}.add(intArrayOf(i,j))};var answer=Double.MAX_VALUE;for(group in groups.values)for(a in group.indices)for(b in a+1 until group.size){val p=points[group[a][0]];val q=points[group[b][0]];val r=points[group[b][1]];val area=kotlin.math.abs((q[0]-p[0]).toLong()*(r[1]-p[1])-(q[1]-p[1]).toLong()*(r[0]-p[0]));if(area>0)answer=minOf(answer,area.toDouble())};return if(answer==Double.MAX_VALUE)0.0 else answer} }`,
`class Solution { public: double minAreaFreeRect(vector<vector<int>>& points){unordered_map<string,vector<pair<int,int>>> groups;for(int i=0;i<(int)points.size();++i)for(int j=i+1;j<(int)points.size();++j){long long dx=points[i][0]-points[j][0],dy=points[i][1]-points[j][1];string key=to_string(points[i][0]+points[j][0])+","+to_string(points[i][1]+points[j][1])+","+to_string(dx*dx+dy*dy);groups[key].push_back({i,j});}double answer=DBL_MAX;for(auto& entry:groups){auto& group=entry.second;for(int a=0;a<(int)group.size();++a)for(int b=a+1;b<(int)group.size();++b){auto& p=points[group[a].first];auto& q=points[group[b].first];auto& r=points[group[b].second];long long area=llabs((long long)(q[0]-p[0])*(r[1]-p[1])-(long long)(q[1]-p[1])*(r[0]-p[0]));if(area)answer=min(answer,(double)area);}}return answer==DBL_MAX?0:answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'minAreaFreeRect',parameterTypes:['intMatrix'],returnType:'double',cases:[{name:'菱形面积二',args:[[[1,2],[2,1],[1,0],[0,1]]],expected:2.0},{name:'单位正方形',args:[[[0,0],[1,0],[1,1],[0,1]]],expected:1.0},{name:'三点无矩形',args:[[[0,0],[1,1],[2,0]]],expected:0.0}]}},
{id:964,slug:'least-operators-to-express-number',title:'表示数字的最少运算符',studyTags:['数学','动态规划','进制'],summary:'只使用若干个 x 和加减乘除运算且不加括号，构造 target，求最少运算符数量。',insight:'把 target 按 x 进制逐位处理；每位既可正向使用 digit 个 x^k，也可向高位借一后使用 x-digit 个负项，维护两种最小代价。',pitfalls:['最低位的 1 要写成 x/x，代价与高位幂不同','最终负状态还需补一个更高位 x^k','结果中的首项不需要前导加号，因此最后减一'],solutions:[s('base-x-carry-dp','x 进制进借位动态规划','逐位维护正表示与向高位借位表示的运算符代价。',['positive=negative=0,k=0，逐位取 digit=target%x','k=0 时 positive=2*digit，negative=2*(x-digit)','高位更新 positive=min(oldPositive+digit*k,oldNegative+(digit+1)*k)，negative=min(oldPositive+(x-digit)*k,oldNegative+(x-digit-1)*k)','处理完返回 min(positive,negative+k)-1'],'O(log_x target)','O(1)',
`class Solution { public int leastOpsExpressTarget(int x,int target){int positive=0,negative=0,k=0;while(target>0){int digit=target%x;target/=x;if(k==0){positive=2*digit;negative=2*(x-digit);}else{int nextPositive=Math.min(positive+digit*k,negative+(digit+1)*k);int nextNegative=Math.min(positive+(x-digit)*k,negative+(x-digit-1)*k);positive=nextPositive;negative=nextNegative;}k++;}return Math.min(positive,negative+k)-1;} }`,
`class Solution { fun leastOpsExpressTarget(x:Int,targetInput:Int):Int{var target=targetInput;var positive=0;var negative=0;var k=0;while(target>0){val digit=target%x;target/=x;if(k==0){positive=2*digit;negative=2*(x-digit)}else{val nextPositive=minOf(positive+digit*k,negative+(digit+1)*k);val nextNegative=minOf(positive+(x-digit)*k,negative+(x-digit-1)*k);positive=nextPositive;negative=nextNegative};k++};return minOf(positive,negative+k)-1} }`,
`class Solution { public: int leastOpsExpressTarget(int x,int target){int positive=0,negative=0,k=0;while(target>0){int digit=target%x;target/=x;if(k==0){positive=2*digit;negative=2*(x-digit);}else{int nextPositive=min(positive+digit*k,negative+(digit+1)*k);int nextNegative=min(positive+(x-digit)*k,negative+(x-digit-1)*k);positive=nextPositive;negative=nextNegative;}++k;}return min(positive,negative+k)-1;} };`)],tests:{schemaVersion:1,mode:'function',method:'leastOpsExpressTarget',parameterTypes:['int','int'],returnType:'int',cases:[{name:'三表示十九',args:[3,19],expected:5},{name:'五表示五百零一',args:[5,501],expected:8},{name:'一百的四次方',args:[100,100000000],expected:3}]}}
]}
