const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-010',problems:[
{id:787,slug:'cheapest-flights-within-k-stops',title:'K 站中转内最便宜的航班',studyTags:['图论','动态规划','Bellman-Ford'],summary:'在有向带权航班图中，求从 src 到 dst 且至多经过 k 个中转站的最低价格，不可达返回负一。',insight:'至多 k 个中转等价于至多 k+1 条边；做 k+1 轮 Bellman-Ford，每轮只从上一轮距离松弛，确保边数限制。',pitfalls:['轮内不能原地更新，否则会使用超过当前轮数的边','中转站数比边数少一','松弛前检查起点可达以避免无穷值加权'],solutions:[s('bounded-bellman-ford','限制轮数的 Bellman-Ford','使用滚动距离数组严格控制最多使用的边数。',['cost[src]=0，其余为无穷大','重复 k+1 轮，每轮复制 cost 为 next，再用旧 cost 松弛所有航班到 next','令 cost=next，最终 dst 无穷则返回 -1，否则返回费用'],'O((k+1)e)','O(n)',
`class Solution { public int findCheapestPrice(int n,int[][] flights,int src,int dst,int k){int infinity=1000000000;int[] cost=new int[n];Arrays.fill(cost,infinity);cost[src]=0;for(int step=0;step<=k;step++){int[] next=cost.clone();for(int[] flight:flights)if(cost[flight[0]]<infinity)next[flight[1]]=Math.min(next[flight[1]],cost[flight[0]]+flight[2]);cost=next;}return cost[dst]==infinity?-1:cost[dst];} }`,
`class Solution { fun findCheapestPrice(n:Int,flights:Array<IntArray>,src:Int,dst:Int,k:Int):Int{val infinity=1000000000;var cost=IntArray(n){infinity};cost[src]=0;for(step in 0..k){val next=cost.copyOf();for(flight in flights)if(cost[flight[0]]<infinity)next[flight[1]]=minOf(next[flight[1]],cost[flight[0]]+flight[2]);cost=next};return if(cost[dst]==infinity)-1 else cost[dst]} }`,
`class Solution { public: int findCheapestPrice(int n,vector<vector<int>>& flights,int src,int dst,int k){const int infinity=1000000000;vector<int> cost(n,infinity);cost[src]=0;for(int step=0;step<=k;++step){vector<int> next=cost;for(auto& flight:flights)if(cost[flight[0]]<infinity)next[flight[1]]=min(next[flight[1]],cost[flight[0]]+flight[2]);cost.swap(next);}return cost[dst]==infinity?-1:cost[dst];} };`)],tests:{schemaVersion:1,mode:'function',method:'findCheapestPrice',parameterTypes:['int','intMatrix','int','int','int'],returnType:'int',cases:[{name:'允许一次中转',args:[3,[[0,1,100],[1,2,100],[0,2,500]],0,2,1],expected:200},{name:'不允许中转',args:[3,[[0,1,100],[1,2,100],[0,2,500]],0,2,0],expected:500},{name:'目的地不可达',args:[3,[[0,1,100]],0,2,1],expected:-1}]}},
{id:788,slug:'rotated-digits',title:'旋转数字',studyTags:['数学','数位','枚举'],summary:'把数字每一位旋转 180 度，若仍是有效数字且与原数不同则为好数，统计 1..n 的好数数量。',insight:'数位 3、4、7 会使旋转无效；其余有效数中必须至少含一个 2、5、6、9 才会发生变化。',pitfalls:['0、1、8 有效但旋转后不变','只要含一个无效数位整个数字就无效','至少一个变化数位是必要条件'],solutions:[s('digit-valid-and-changed','数位有效性与变化标记','逐数检查所有十进制位。',['枚举 value=1..n','逐位取 digit；遇 3/4/7 标记无效，遇 2/5/6/9 标记 changed','valid 且 changed 时计入答案'],'O(n log n)','O(1)',
`class Solution { public int rotatedDigits(int n){int answer=0;for(int value=1;value<=n;value++){int current=value;boolean valid=true,changed=false;while(current>0){int digit=current%10;current/=10;if(digit==3||digit==4||digit==7){valid=false;break;}if(digit==2||digit==5||digit==6||digit==9)changed=true;}if(valid&&changed)answer++;}return answer;} }`,
`class Solution { fun rotatedDigits(n:Int):Int{var answer=0;for(value in 1..n){var current=value;var valid=true;var changed=false;while(current>0){val digit=current%10;current/=10;if(digit==3||digit==4||digit==7){valid=false;break};if(digit==2||digit==5||digit==6||digit==9)changed=true};if(valid&&changed)answer++};return answer} }`,
`class Solution { public: int rotatedDigits(int n){int answer=0;for(int value=1;value<=n;++value){int current=value;bool valid=true,changed=false;while(current){int digit=current%10;current/=10;if(digit==3||digit==4||digit==7){valid=false;break;}if(digit==2||digit==5||digit==6||digit==9)changed=true;}answer+=valid&&changed;}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'rotatedDigits',parameterTypes:['int'],returnType:'int',cases:[{name:'一到十',args:[10],expected:4},{name:'一不是好数',args:[1],expected:0},{name:'一到二十',args:[20],expected:9}]}},
{id:789,slug:'escape-the-ghosts',title:'逃脱阻碍者',studyTags:['数组','数学','曼哈顿距离'],summary:'玩家从原点走向 target，多个幽灵也每步四向移动；判断玩家是否能保证先于幽灵到达目标。',insight:'在无障碍网格中最短路就是曼哈顿距离；只要任一幽灵到目标的距离不大于玩家距离，它就能在目标等待或同时抵达并阻止玩家。',pitfalls:['幽灵与玩家同时到达也算玩家失败','只需比较到目标的距离，无需模拟追逐','坐标可为负数，使用绝对值'],solutions:[s('compare-manhattan-distance','比较到目标的曼哈顿距离','判断玩家是否严格早于所有幽灵。',['计算 playerDistance=abs(tx)+abs(ty)','对每个 ghost 计算到 target 的曼哈顿距离','若 ghostDistance<=playerDistance 返回假；全部更远则返回真'],'O(g)','O(1)',
`class Solution { public boolean escapeGhosts(int[][] ghosts,int[] target){int player=Math.abs(target[0])+Math.abs(target[1]);for(int[] ghost:ghosts)if(Math.abs(ghost[0]-target[0])+Math.abs(ghost[1]-target[1])<=player)return false;return true;} }`,
`class Solution { fun escapeGhosts(ghosts:Array<IntArray>,target:IntArray):Boolean{val player=kotlin.math.abs(target[0])+kotlin.math.abs(target[1]);for(ghost in ghosts)if(kotlin.math.abs(ghost[0]-target[0])+kotlin.math.abs(ghost[1]-target[1])<=player)return false;return true} }`,
`class Solution { public: bool escapeGhosts(vector<vector<int>>& ghosts,vector<int>& target){int player=abs(target[0])+abs(target[1]);for(auto& ghost:ghosts)if(abs(ghost[0]-target[0])+abs(ghost[1]-target[1])<=player)return false;return true;} };`)],tests:{schemaVersion:1,mode:'function',method:'escapeGhosts',parameterTypes:['intMatrix','intArray'],returnType:'boolean',cases:[{name:'玩家严格更近',args:[[[1,0],[0,3]],[0,1]],expected:true},{name:'幽灵先到目标',args:[[[1,0]],[2,0]],expected:false},{name:'同时到达也失败',args:[[[2,0]],[1,0]],expected:false}]}},
{id:790,slug:'domino-and-tromino-tiling',title:'多米诺和托米诺平铺',studyTags:['动态规划','递推','状态机'],summary:'用 2×1 多米诺和 L 形托米诺平铺 2×n 面板，求方案数对 1e9+7 取模。',insight:'消去带缺口的辅助状态后，完整平铺数满足 dp[n]=2·dp[n-1]+dp[n-3]，初值 dp0=1、dp1=1、dp2=2。',pitfalls:['递推从 n=3 开始','乘二前使用长整型避免溢出','空面板 dp0=1 是递推所需边界'],solutions:[s('compressed-tiling-recurrence','压缩后的三项递推','滚动保存 dp[i-3..i-1] 计算下一项。',['处理 n=1、n=2','令 a=dp0,b=dp1,c=dp2','i 从 3 到 n，next=(2*c+a)%MOD，然后 a=b,b=c,c=next；返回 c'],'O(n)','O(1)',
`class Solution { public int numTilings(int n){if(n==1)return 1;if(n==2)return 2;long a=1,b=1,c=2,mod=1000000007L;for(int i=3;i<=n;i++){long next=(2*c+a)%mod;a=b;b=c;c=next;}return(int)c;} }`,
`class Solution { fun numTilings(n:Int):Int{if(n==1)return 1;if(n==2)return 2;var a=1L;var b=1L;var c=2L;val mod=1000000007L;for(i in 3..n){val next=(2*c+a)%mod;a=b;b=c;c=next};return c.toInt()} }`,
`class Solution { public: int numTilings(int n){if(n==1)return 1;if(n==2)return 2;long long a=1,b=1,c=2,mod=1000000007;for(int i=3;i<=n;++i){long long next=(2*c+a)%mod;a=b;b=c;c=next;}return c;} };`)],tests:{schemaVersion:1,mode:'function',method:'numTilings',parameterTypes:['int'],returnType:'int',cases:[{name:'长度三',args:[3],expected:5},{name:'长度一',args:[1],expected:1},{name:'长度五',args:[5],expected:24}]}},
{id:791,slug:'custom-sort-string',title:'自定义字符串排序',studyTags:['字符串','哈希表','计数排序'],summary:'order 给出部分字符的相对次序，重排 s 使其中出现在 order 的字符遵循该顺序，其余字符位置任意。',insight:'统计 s 中各字符频次，按 order 依次取尽；再输出未指定字符。为使结果稳定，可按字符升序追加剩余字符。',pitfalls:['order 中字符互不重复','s 中不在 order 的字符也必须保留','同一字符可能重复多次'],solutions:[s('frequency-custom-order','频次表按自定义次序输出','先消费 order 字符，再有序追加余量。',['统计 s 的 26 个小写字母频次','扫描 order，对每个字符追加 frequency 次并清零','按 a 到 z 追加所有剩余字符'],'O(|s|+|order|)','O(1)',
`class Solution { public String customSortString(String order,String s){int[] frequency=new int[26];for(char c:s.toCharArray())frequency[c-'a']++;StringBuilder answer=new StringBuilder();for(char c:order.toCharArray())while(frequency[c-'a']>0){answer.append(c);frequency[c-'a']--;}for(int i=0;i<26;i++)while(frequency[i]>0){answer.append((char)('a'+i));frequency[i]--;}return answer.toString();} }`,
`class Solution { fun customSortString(order:String,s:String):String{val frequency=IntArray(26);for(c in s)frequency[c-'a']++;val answer=StringBuilder();for(c in order)while(frequency[c-'a']>0){answer.append(c);frequency[c-'a']--};for(i in 0 until 26)while(frequency[i]>0){answer.append(('a'.code+i).toChar());frequency[i]--};return answer.toString()} }`,
`class Solution { public: string customSortString(string order,string s){int frequency[26]{};for(char c:s)++frequency[c-'a'];string answer;for(char c:order)while(frequency[c-'a']>0){answer+=c;--frequency[c-'a'];}for(int i=0;i<26;++i)while(frequency[i]>0){answer+=char('a'+i);--frequency[i];}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'customSortString',parameterTypes:['string','string'],returnType:'string',cases:[{name:'反向前三字符',args:['cba','abcd'],expected:'cbad'},{name:'部分顺序字符缺失',args:['bcafg','abcd'],expected:'bcad'},{name:'重复字符',args:['kqep','pekeq'],expected:'kqeep'}]}}
]}
