const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})

export default {batchId:'batch-016',problems:[
{id:1145,slug:'binary-tree-coloring-game',title:'二叉树着色游戏',studyTags:['树','深度优先搜索','子树大小'],summary:'先手给节点 x 着色，后手选择另一节点；双方轮流扩展相邻未着色节点，判断后手是否能保证占据更多节点。',insight:'删除 x 后树被分成左子树、右子树和父节点方向三块。后手只要选择最大的一块，就能封住唯一入口；当这块节点数超过一半时必胜。',pitfalls:['父节点方向大小为 n-1-left-right','必须严格超过 n/2 才能保证胜利','需要找到 x 并统计其左右子树大小'],solutions:[s('three-region-subtree-count','三分区子树计数','统计删除 x 后三个连通块并判断最大块是否过半。',['深度优先计算每棵子树大小；遇到值为 x 的节点记录其左右大小','计算 parent=n-1-left-right','若 max(left,right,parent)>n/2 返回真，否则返回假'],'O(n)','O(height)',
`class Solution { private int leftSize,rightSize,target;public boolean btreeGameWinningMove(TreeNode root,int n,int x){target=x;size(root);int parent=n-1-leftSize-rightSize;return Math.max(parent,Math.max(leftSize,rightSize))>n/2;}private int size(TreeNode node){if(node==null)return 0;int left=size(node.left),right=size(node.right);if(node.val==target){leftSize=left;rightSize=right;}return left+right+1;} }`,
`class Solution { private var leftSize=0;private var rightSize=0;private var target=0;fun btreeGameWinningMove(root:TreeNode?,n:Int,x:Int):Boolean{target=x;size(root);val parent=n-1-leftSize-rightSize;return maxOf(parent,leftSize,rightSize)>n/2};private fun size(node:TreeNode?):Int{node?:return 0;val left=size(node.left);val right=size(node.right);if(node.\`val\`==target){leftSize=left;rightSize=right};return left+right+1} }`,
`class Solution { int leftSize=0,rightSize=0,target=0;int size(TreeNode* node){if(!node)return 0;int left=size(node->left),right=size(node->right);if(node->val==target){leftSize=left;rightSize=right;}return left+right+1;}public:bool btreeGameWinningMove(TreeNode* root,int n,int x){target=x;size(root);int parent=n-1-leftSize-rightSize;return max({parent,leftSize,rightSize})>n/2;} };`)],tests:{schemaVersion:1,mode:'function',method:'btreeGameWinningMove',parameterTypes:['treeNode','int','int'],returnType:'boolean',cases:[{name:'选择父方向获胜',args:[[1,2,3,4,5,6,7],7,3],expected:true},{name:'先手选择根后无法过半',args:[[1,2,3,4,5,6,7],7,1],expected:false},{name:'单节点无可选点',args:[[1],1,1],expected:false}]}},

{id:1146,slug:'snapshot-array',title:'快照数组',studyTags:['数组','设计','二分查找','有序映射'],summary:'设计支持 set、生成快照和按快照编号读取历史值的数组。',insight:'每个下标只记录发生变更的快照编号和值；读取时查找不大于目标 snap_id 的最后一次变更，无需为每次快照复制整张数组。',pitfalls:['同一快照内多次 set 应覆盖同一记录','snap 返回当前编号后再递增','从未修改的下标在任意快照中都为零'],solutions:[s('per-index-version-map','逐下标版本映射','为每个位置维护从快照号到值的稀疏历史。',['构造时每个位置写入版本 0 的默认值零，currentSnap=0','set(index,val) 写 history[index][currentSnap]=val；snap 返回 currentSnap 并自增','get(index,id) 查找键不大于 id 的最大记录并返回其值'],'set/snap O(log u)，get O(log u)','O(变更次数+n)',
`class SnapshotArray { private final List<TreeMap<Integer,Integer>> history=new ArrayList<>();private int currentSnap=0;public SnapshotArray(int length){for(int i=0;i<length;i++){TreeMap<Integer,Integer> versions=new TreeMap<>();versions.put(0,0);history.add(versions);}}public void set(int index,int val){history.get(index).put(currentSnap,val);}public int snap(){return currentSnap++;}public int get(int index,int snapId){return history.get(index).floorEntry(snapId).getValue();} }`,
`class SnapshotArray(length:Int) { private val history=MutableList(length){java.util.TreeMap<Int,Int>().apply{put(0,0)}};private var currentSnap=0;fun set(index:Int,\`val\`:Int){history[index][currentSnap]=\`val\`};fun snap():Int=currentSnap++;fun get(index:Int,snapId:Int):Int=history[index].floorEntry(snapId).value }`,
`class SnapshotArray { vector<map<int,int>> history;int currentSnap=0;public:SnapshotArray(int length):history(length){for(auto& versions:history)versions[0]=0;}void set(int index,int val){history[index][currentSnap]=val;}int snap(){return currentSnap++;}int get(int index,int snapId){auto it=history[index].upper_bound(snapId);return prev(it)->second;} };`)],tests:{schemaVersion:1,mode:'design',className:'SnapshotArray',constructorTypes:['int'],cases:[{name:'快照隔离后续修改',constructorArgs:[3],calls:[{method:'set',parameterTypes:['int','int'],args:[0,5]},{method:'snap',parameterTypes:[],args:[],returnType:'int',expected:0},{method:'set',parameterTypes:['int','int'],args:[0,6]},{method:'get',parameterTypes:['int','int'],args:[0,0],returnType:'int',expected:5}]},{name:'同一版本覆盖',constructorArgs:[1],calls:[{method:'set',parameterTypes:['int','int'],args:[0,4]},{method:'set',parameterTypes:['int','int'],args:[0,7]},{method:'snap',parameterTypes:[],args:[],returnType:'int',expected:0},{method:'get',parameterTypes:['int','int'],args:[0,0],returnType:'int',expected:7}]},{name:'默认零跨快照',constructorArgs:[2],calls:[{method:'snap',parameterTypes:[],args:[],returnType:'int',expected:0},{method:'snap',parameterTypes:[],args:[],returnType:'int',expected:1},{method:'get',parameterTypes:['int','int'],args:[1,1],returnType:'int',expected:0}]}]}},

{id:1147,slug:'longest-chunked-palindrome-decomposition',title:'段式回文',studyTags:['字符串','贪心','递归'],summary:'把字符串分成尽量多的非空片段，使从两端向内对应的片段内容相同，返回最大片段数。',insight:'从最短长度开始寻找相同前缀和后缀；一旦匹配，尽早切下它们一定不劣，因为任何更粗的合法外层还可由这些更短块组成，随后递归处理中间。',pitfalls:['片段相等要求字符串内容一致而非长度一致','没有外层匹配时整个剩余串作为一段','空的中间部分贡献零段'],solutions:[s('shortest-matching-ends-greedy','最短相同首尾贪心','递归切掉最短的相同前缀和后缀。',['若 text 为空返回零','从 length=1 到 floor(n/2) 比较等长前缀和后缀','首次相等时返回 2+递归中间子串；若始终不等返回一'],'O(n²)','O(n)',
`class Solution { public int longestDecomposition(String text){int n=text.length();if(n==0)return 0;for(int length=1;length*2<=n;length++)if(text.regionMatches(0,text,n-length,length))return 2+longestDecomposition(text.substring(length,n-length));return 1;} }`,
`class Solution { fun longestDecomposition(text:String):Int{val n=text.length;if(n==0)return 0;for(length in 1..n/2)if(text.regionMatches(0,text,n-length,length))return 2+longestDecomposition(text.substring(length,n-length));return 1} }`,
`class Solution { public: int longestDecomposition(string text){int n=text.size();if(!n)return 0;for(int length=1;length*2<=n;++length)if(text.compare(0,length,text,n-length,length)==0)return 2+longestDecomposition(text.substr(length,n-2*length));return 1;} };`)],tests:{schemaVersion:1,mode:'function',method:'longestDecomposition',parameterTypes:['string'],returnType:'int',cases:[{name:'七段经典串',args:['ghiabcdefhelloadamhelloabcdefghi'],expected:7},{name:'无法再分',args:['merchant'],expected:1},{name:'十一段对称串',args:['antaprezatepzapreanta'],expected:11}]}},

{id:1154,slug:'day-of-the-year',title:'一年中的第几天',studyTags:['字符串','数学','日期'],summary:'给定 YYYY-MM-DD 格式日期，返回它是该年的第几天。',insight:'累加目标月份之前各月天数，再加日期；若年份为闰年且月份晚于二月，额外加一天。',pitfalls:['能被 400 整除或能被 4 但不能被 100 整除才是闰年','一月没有前置月份','日期序号从一开始'],solutions:[s('month-prefix-and-leap-day','月份前缀与闰日','解析年月日并累计月长。',['从固定位置解析 year、month、day','累加 days[0..month-2]','若 month>2 且年份满足闰年规则再加一，返回总数'],'O(1)','O(1)',
`class Solution { public int dayOfYear(String date){int year=Integer.parseInt(date.substring(0,4)),month=Integer.parseInt(date.substring(5,7)),day=Integer.parseInt(date.substring(8));int[] days={31,28,31,30,31,30,31,31,30,31,30,31};for(int i=1;i<month;i++)day+=days[i-1];if(month>2&&(year%400==0||year%4==0&&year%100!=0))day++;return day;} }`,
`class Solution { fun dayOfYear(date:String):Int{val year=date.substring(0,4).toInt();val month=date.substring(5,7).toInt();var day=date.substring(8).toInt();val days=intArrayOf(31,28,31,30,31,30,31,31,30,31,30,31);for(i in 0 until month-1)day+=days[i];if(month>2&&(year%400==0||year%4==0&&year%100!=0))day++;return day} }`,
`class Solution { public: int dayOfYear(string date){int year=stoi(date.substr(0,4)),month=stoi(date.substr(5,2)),day=stoi(date.substr(8));int days[]={31,28,31,30,31,30,31,31,30,31,30,31};for(int i=0;i<month-1;++i)day+=days[i];if(month>2&&(year%400==0||year%4==0&&year%100!=0))++day;return day;} };`)],tests:{schemaVersion:1,mode:'function',method:'dayOfYear',parameterTypes:['string'],returnType:'int',cases:[{name:'一月九日',args:['2019-01-09'],expected:9},{name:'平年二月十日',args:['2019-02-10'],expected:41},{name:'世纪闰年三月一日',args:['2000-03-01'],expected:61}]}},

{id:1155,slug:'number-of-dice-rolls-with-target-sum',title:'掷骰子等于目标和的方法数',studyTags:['动态规划','计数','滚动数组'],summary:'有 n 个各含 k 个面的骰子，统计点数之和等于 target 的方案数，结果对 10^9+7 取模。',insight:'逐个加入骰子，dp[sum] 表示当前骰子数量凑出 sum 的方案数；新骰子的每个面都从上一层较小的和转移而来。',pitfalls:['不同骰子的结果序列视为不同方案','每次骰子迭代必须使用新数组避免层内重复','中间加法使用长整型并取模'],solutions:[s('dice-count-rolling-dp','骰子计数滚动动态规划','按骰子数和目标和累计所有面值转移。',['dp[0]=1，其余为零','重复 n 次：创建 next；对 sum=1..target，累加 dp[sum-face]，face=1..k 且非负','每项对模数取余，用 next 替换 dp，最终返回 dp[target]'],'O(n·k·target)','O(target)',
`class Solution { public int numRollsToTarget(int n,int k,int target){final int MOD=1000000007;long[] dp=new long[target+1];dp[0]=1;for(int dice=0;dice<n;dice++){long[] next=new long[target+1];for(int sum=1;sum<=target;sum++)for(int face=1;face<=k&&face<=sum;face++)next[sum]=(next[sum]+dp[sum-face])%MOD;dp=next;}return (int)dp[target];} }`,
`class Solution { fun numRollsToTarget(n:Int,k:Int,target:Int):Int{val mod=1000000007L;var dp=LongArray(target+1);dp[0]=1;repeat(n){val next=LongArray(target+1);for(sum in 1..target)for(face in 1..minOf(k,sum))next[sum]=(next[sum]+dp[sum-face])%mod;dp=next};return dp[target].toInt()} }`,
`class Solution { public: int numRollsToTarget(int n,int k,int target){const int MOD=1000000007;vector<long long> dp(target+1);dp[0]=1;while(n--){vector<long long> next(target+1);for(int sum=1;sum<=target;++sum)for(int face=1;face<=k&&face<=sum;++face)next[sum]=(next[sum]+dp[sum-face])%MOD;dp.swap(next);}return dp[target];} };`)],tests:{schemaVersion:1,mode:'function',method:'numRollsToTarget',parameterTypes:['int','int','int'],returnType:'int',cases:[{name:'单骰唯一面值',args:[1,6,3],expected:1},{name:'双骰和为七',args:[2,6,7],expected:6},{name:'大规模取模',args:[30,30,500],expected:222616187}]}}
]}
