const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-018',problems:[
{id:1313,slug:'decompress-run-length-encoded-list',title:'解压缩编码列表',studyTags:['数组','模拟'],summary:'数组按 [频次,值] 成对编码，返回依次重复每个值对应次数后的完整数组。',insight:'先累加所有偶数下标的频次确定结果长度，再按每对频次连续写值，避免动态扩容。',pitfalls:['每对是频次在前、值在后','频次均为正数','输出顺序与编码对顺序一致'],solutions:[s('two-pass-sized-expansion','两遍定长展开','先求长度再顺序填充结果数组。',['遍历偶数下标累加 length','创建 answer[length]，write=0','每对 [frequency,value] 重复 frequency 次写入 answer，返回'],'O(输出长度)','O(1) 除结果',
`class Solution { public int[] decompressRLElist(int[] nums){int length=0;for(int i=0;i<nums.length;i+=2)length+=nums[i];int[] answer=new int[length];int write=0;for(int i=0;i<nums.length;i+=2)for(int count=0;count<nums[i];count++)answer[write++]=nums[i+1];return answer;} }`,
`class Solution { fun decompressRLElist(nums:IntArray):IntArray{var length=0;for(i in nums.indices step 2)length+=nums[i];val answer=IntArray(length);var write=0;for(i in nums.indices step 2)repeat(nums[i]){answer[write++]=nums[i+1]};return answer} }`,
`class Solution { public: vector<int> decompressRLElist(vector<int>& nums){vector<int> answer;for(int i=0;i<(int)nums.size();i+=2)answer.insert(answer.end(),nums[i],nums[i+1]);return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'decompressRLElist',parameterTypes:['intArray'],returnType:'intArray',cases:[{name:'两个二与一个四',args:[[1,2,3,4]],expected:[2,4,4,4]},{name:'多个编码对',args:[[1,1,2,3]],expected:[1,3,3]},{name:'单对重复三次',args:[[3,7]],expected:[7,7,7]}]}},
{id:1314,slug:'matrix-block-sum',title:'矩阵区域和',studyTags:['数组','矩阵','二维前缀和'],summary:'对矩阵每格返回以它为中心、行列距离不超过 k 且落在边界内的矩形区域元素和。',insight:'构造二维前缀和后，每格区域裁剪到合法上下左右边界，用四项公式常数时间求和。',pitfalls:['区域边界包含端点','靠边格的范围需要裁剪','结果矩阵与输入同形'],solutions:[s('clipped-rectangle-prefix-sum','裁剪矩形二维前缀和','预处理后常数时间求每个中心的区域和。',['构造 prefix[rows+1][cols+1]','每格计算 top=max(0,r-k)、bottom=min(rows-1,r+k)、left、right','answer[r][c]=prefix[bottom+1][right+1]-prefix[top][right+1]-prefix[bottom+1][left]+prefix[top][left]，返回'],'O(rows·cols)','O(rows·cols)',
`class Solution { public int[][] matrixBlockSum(int[][] mat,int k){int rows=mat.length,columns=mat[0].length;int[][] prefix=new int[rows+1][columns+1],answer=new int[rows][columns];for(int r=0;r<rows;r++)for(int c=0;c<columns;c++)prefix[r+1][c+1]=mat[r][c]+prefix[r][c+1]+prefix[r+1][c]-prefix[r][c];for(int r=0;r<rows;r++)for(int c=0;c<columns;c++){int top=Math.max(0,r-k),bottom=Math.min(rows-1,r+k),left=Math.max(0,c-k),right=Math.min(columns-1,c+k);answer[r][c]=prefix[bottom+1][right+1]-prefix[top][right+1]-prefix[bottom+1][left]+prefix[top][left];}return answer;} }`,
`class Solution { fun matrixBlockSum(mat:Array<IntArray>,k:Int):Array<IntArray>{val rows=mat.size;val columns=mat[0].size;val prefix=Array(rows+1){IntArray(columns+1)};for(r in 0 until rows)for(c in 0 until columns)prefix[r+1][c+1]=mat[r][c]+prefix[r][c+1]+prefix[r+1][c]-prefix[r][c];return Array(rows){r->IntArray(columns){c->val top=maxOf(0,r-k);val bottom=minOf(rows-1,r+k);val left=maxOf(0,c-k);val right=minOf(columns-1,c+k);prefix[bottom+1][right+1]-prefix[top][right+1]-prefix[bottom+1][left]+prefix[top][left]}}} }`,
`class Solution { public: vector<vector<int>> matrixBlockSum(vector<vector<int>>& mat,int k){int rows=mat.size(),columns=mat[0].size();vector<vector<int>> prefix(rows+1,vector<int>(columns+1)),answer(rows,vector<int>(columns));for(int r=0;r<rows;++r)for(int c=0;c<columns;++c)prefix[r+1][c+1]=mat[r][c]+prefix[r][c+1]+prefix[r+1][c]-prefix[r][c];for(int r=0;r<rows;++r)for(int c=0;c<columns;++c){int top=max(0,r-k),bottom=min(rows-1,r+k),left=max(0,c-k),right=min(columns-1,c+k);answer[r][c]=prefix[bottom+1][right+1]-prefix[top][right+1]-prefix[bottom+1][left]+prefix[top][left];}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'matrixBlockSum',parameterTypes:['intMatrix','int'],returnType:'intMatrix',cases:[{name:'三阶半径一',args:[[[1,2,3],[4,5,6],[7,8,9]],1],expected:[[12,21,16],[27,45,33],[24,39,28]]},{name:'半径覆盖全矩阵',args:[[[1,2],[3,4]],2],expected:[[10,10],[10,10]]},{name:'单格矩阵',args:[[[5]],0],expected:[[5]]}]}},
{id:1315,slug:'sum-of-nodes-with-even-valued-grandparent',title:'祖父节点值为偶数的节点和',studyTags:['树','深度优先搜索','递归'],summary:'返回二叉树中祖父节点值为偶数的所有节点值之和。',insight:'DFS 向下传递父节点值和祖父节点值；访问当前节点时若传入祖父值为偶数就累加，再把 parent、current 作为孩子的新祖父、父信息。',pitfalls:['根和第二层没有祖父节点不能计入','节点值均为正，可用 -1 表示不存在','判断的是祖父而非父节点'],solutions:[s('ancestor-value-dfs','祖先值深度优先搜索','沿递归栈携带两代祖先值。',['调用 dfs(root,-1,-1)','空节点返回零；grandparent>=0 且为偶数时贡献 node.val','递归左右孩子参数变为 parent=node.val、grandparent=旧 parent，返回三部分之和'],'O(n)','O(height)',
`class Solution { public int sumEvenGrandparent(TreeNode root){return dfs(root,-1,-1);}private int dfs(TreeNode node,int parent,int grandparent){if(node==null)return 0;int sum=grandparent>=0&&grandparent%2==0?node.val:0;return sum+dfs(node.left,node.val,parent)+dfs(node.right,node.val,parent);} }`,
`class Solution { fun sumEvenGrandparent(root:TreeNode?):Int=dfs(root,-1,-1);private fun dfs(node:TreeNode?,parent:Int,grandparent:Int):Int{node?:return 0;val sum=if(grandparent>=0&&grandparent%2==0)node.\`val\` else 0;return sum+dfs(node.left,node.\`val\`,parent)+dfs(node.right,node.\`val\`,parent)} }`,
`class Solution { int dfs(TreeNode* node,int parent,int grandparent){if(!node)return 0;int sum=grandparent>=0&&grandparent%2==0?node->val:0;return sum+dfs(node->left,node->val,parent)+dfs(node->right,node->val,parent);}public:int sumEvenGrandparent(TreeNode* root){return dfs(root,-1,-1);} };`)],tests:{schemaVersion:1,mode:'function',method:'sumEvenGrandparent',parameterTypes:['treeNode'],returnType:'int',cases:[{name:'经典树贡献十八',args:[[6,7,8,2,7,1,3,9,null,1,4,null,null,null,5]],expected:18},{name:'偶数根的孙子相加',args:[[2,1,3,4,5,6,7]],expected:22},{name:'不足三层没有贡献',args:[[2,1,3]],expected:0}]}},
{id:1316,slug:'distinct-echo-substrings',title:'不同的循环子字符串',studyTags:['字符串','滚动哈希','枚举'],summary:'统计字符串中形如 a+a 的不同非空子串数量。',insight:'枚举一半长度和起点，用双模滚动哈希常数时间比较相邻两半；相等时把半串的双哈希加入集合，半串唯一决定完整回声串。',pitfalls:['统计不同字符串而非出现次数','两个相邻半段长度必须相同','双模降低滚动哈希碰撞概率'],solutions:[s('double-rolling-hash-halves','双模滚动哈希比较半段','二次枚举所有相邻等长片段并对哈希去重。',['预处理两组 prefix 与 power','half 从一到 n/2，start 满足 start+2half<=n','比较两半在两个模数下哈希；均相等则把第一半双哈希编码进集合，返回集合大小'],'O(n²)','O(n²)',
`class Solution { private static final long MOD1=1000000007L,MOD2=1000000009L,BASE=911382323L;public int distinctEchoSubstrings(String text){int n=text.length();long[] p1=new long[n+1],p2=new long[n+1],pow1=new long[n+1],pow2=new long[n+1];pow1[0]=pow2[0]=1;for(int i=0;i<n;i++){p1[i+1]=(p1[i]*BASE+text.charAt(i))%MOD1;p2[i+1]=(p2[i]*BASE+text.charAt(i))%MOD2;pow1[i+1]=pow1[i]*BASE%MOD1;pow2[i+1]=pow2[i]*BASE%MOD2;}Set<Long> seen=new HashSet<>();for(int half=1;half*2<=n;half++)for(int start=0;start+2*half<=n;start++){long a1=hash(p1,pow1,start,start+half,MOD1),b1=hash(p1,pow1,start+half,start+2*half,MOD1);if(a1!=b1)continue;long a2=hash(p2,pow2,start,start+half,MOD2),b2=hash(p2,pow2,start+half,start+2*half,MOD2);if(a2==b2)seen.add(a1*MOD2+a2);}return seen.size();}private long hash(long[] prefix,long[] power,int left,int right,long mod){return (prefix[right]-prefix[left]*power[right-left]%mod+mod)%mod;} }`,
`class Solution { private val mod1=1000000007L;private val mod2=1000000009L;private val base=911382323L;fun distinctEchoSubstrings(text:String):Int{val n=text.length;val p1=LongArray(n+1);val p2=LongArray(n+1);val pow1=LongArray(n+1);val pow2=LongArray(n+1);pow1[0]=1;pow2[0]=1;for(i in text.indices){p1[i+1]=(p1[i]*base+text[i].code)%mod1;p2[i+1]=(p2[i]*base+text[i].code)%mod2;pow1[i+1]=pow1[i]*base%mod1;pow2[i+1]=pow2[i]*base%mod2};fun hash(prefix:LongArray,power:LongArray,left:Int,right:Int,mod:Long):Long{return (prefix[right]-prefix[left]*power[right-left]%mod+mod)%mod};val seen=mutableSetOf<Long>();for(half in 1..n/2)for(start in 0..n-2*half){val a1=hash(p1,pow1,start,start+half,mod1);val b1=hash(p1,pow1,start+half,start+2*half,mod1);if(a1!=b1)continue;val a2=hash(p2,pow2,start,start+half,mod2);val b2=hash(p2,pow2,start+half,start+2*half,mod2);if(a2==b2)seen.add(a1*mod2+a2)};return seen.size} }`,
`class Solution { public: int distinctEchoSubstrings(string text){const long long MOD1=1000000007,MOD2=1000000009,BASE=911382323;int n=text.size();vector<long long> p1(n+1),p2(n+1),pow1(n+1,1),pow2(n+1,1);for(int i=0;i<n;++i){p1[i+1]=(p1[i]*BASE+text[i])%MOD1;p2[i+1]=(p2[i]*BASE+text[i])%MOD2;pow1[i+1]=pow1[i]*BASE%MOD1;pow2[i+1]=pow2[i]*BASE%MOD2;}auto hash=[](vector<long long>& prefix,vector<long long>& power,int left,int right,long long mod){return (prefix[right]-prefix[left]*power[right-left]%mod+mod)%mod;};set<pair<long long,long long>> seen;for(int half=1;half*2<=n;++half)for(int start=0;start+2*half<=n;++start){long long a1=hash(p1,pow1,start,start+half,MOD1),b1=hash(p1,pow1,start+half,start+2*half,MOD1);if(a1!=b1)continue;long long a2=hash(p2,pow2,start,start+half,MOD2),b2=hash(p2,pow2,start+half,start+2*half,MOD2);if(a2==b2)seen.insert({a1,a2});}return seen.size();} };`)],tests:{schemaVersion:1,mode:'function',method:'distinctEchoSubstrings',parameterTypes:['string'],returnType:'int',cases:[{name:'abcabcabc 有三个不同回声串',args:['abcabcabc'],expected:3},{name:'leetcode 只有 ee',args:['leetcode'],expected:1},{name:'五个 a 有两个不同回声串',args:['aaaaa'],expected:2}]}},
{id:1317,slug:'convert-integer-to-the-sum-of-two-no-zero-integers',title:'将整数转换为两个无零整数的和',studyTags:['数学','枚举'],summary:'无零整数的十进制表示不含数字零；给定 n，返回两个正无零整数之和为 n。',insight:'题目保证解存在，直接从一枚举 a，令 b=n-a，检查两数十进制每一位是否都非零即可。',pitfalls:['数字本身不能含任何零','a 与 b 都必须为正','返回任一合法解'],solutions:[s('linear-no-zero-enumeration','线性无零枚举','枚举一个加数并验证两者数位。',['a 从一到 n-1','b=n-a，调用 noZero(a) 与 noZero(b)','两者都合法立即返回 [a,b]；保证能找到'],'O(n log n)','O(1)',
`class Solution { public int[] getNoZeroIntegers(int n){for(int a=1;a<n;a++)if(noZero(a)&&noZero(n-a))return new int[]{a,n-a};return new int[0];}private boolean noZero(int value){while(value>0){if(value%10==0)return false;value/=10;}return true;} }`,
`class Solution { fun getNoZeroIntegers(n:Int):IntArray{for(a in 1 until n)if(noZero(a)&&noZero(n-a))return intArrayOf(a,n-a);return intArrayOf()};private fun noZero(value:Int):Boolean{var number=value;while(number>0){if(number%10==0)return false;number/=10};return true} }`,
`class Solution { bool noZero(int value){while(value){if(value%10==0)return false;value/=10;}return true;}public:vector<int> getNoZeroIntegers(int n){for(int a=1;a<n;++a)if(noZero(a)&&noZero(n-a))return {a,n-a};return {};} };`)],tests:{schemaVersion:1,mode:'function',method:'getNoZeroIntegers',parameterTypes:['int'],returnType:'intArray',cases:[{name:'二拆为一加一',args:[2],expected:[1,1]},{name:'十一拆为二加九',args:[11],expected:[2,9]},{name:'一百零一拆为二加九十九',args:[101],expected:[2,99]}]}}
]}
