const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-019',problems:[
{id:1343,slug:'number-of-sub-arrays-of-size-k-and-average-greater-than-or-equal-to-threshold',title:'大小为 K 且平均值大于等于阈值的子数组数目',studyTags:['数组','滑动窗口'],summary:'统计长度恰为 k 且平均值至少 threshold 的连续子数组数量。',insight:'平均值条件等价于窗口和至少 k·threshold；维护固定长度滑动窗口和即可常数时间判断每个窗口。',pitfalls:['窗口长度必须恰好为 k','用乘法比较避免浮点误差','移动时先加新值再减超出窗口的旧值'],solutions:[s('fixed-window-sum','固定窗口和','在线性扫描中维护最近 k 个元素之和。',['sum=0,answer=0,target=k*threshold','right 扫描加 arr[right]，若 right>=k 则减 arr[right-k]','right>=k-1 且 sum>=target 时 answer++，返回'],'O(n)','O(1)',
`class Solution { public int numOfSubarrays(int[] arr,int k,int threshold){int sum=0,answer=0,target=k*threshold;for(int right=0;right<arr.length;right++){sum+=arr[right];if(right>=k)sum-=arr[right-k];if(right>=k-1&&sum>=target)answer++;}return answer;} }`,
`class Solution { fun numOfSubarrays(arr:IntArray,k:Int,threshold:Int):Int{var sum=0;var answer=0;val target=k*threshold;for(right in arr.indices){sum+=arr[right];if(right>=k)sum-=arr[right-k];if(right>=k-1&&sum>=target)answer++};return answer} }`,
`class Solution { public: int numOfSubarrays(vector<int>& arr,int k,int threshold){int sum=0,answer=0,target=k*threshold;for(int right=0;right<(int)arr.size();++right){sum+=arr[right];if(right>=k)sum-=arr[right-k];if(right>=k-1&&sum>=target)++answer;}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'numOfSubarrays',parameterTypes:['intArray','int','int'],returnType:'int',cases:[{name:'经典窗口三个',args:[[2,2,2,2,5,5,5,8],3,4],expected:3},{name:'所有单元素均达标',args:[[11,13,17,23,29,31,7,5,2,3],1,5],expected:8},{name:'没有窗口达标',args:[[1,1,1],2,2],expected:0}]}},
{id:1344,slug:'angle-between-hands-of-a-clock',title:'时钟指针的夹角',studyTags:['数学','几何'],summary:'给定整点小时与分钟，返回时针和分针之间较小的夹角。',insight:'分针每分钟转六度；时针每小时三十度且每分钟继续转半度。两角绝对差若超过一百八十，取三百六十减它。',pitfalls:['时针会随分钟连续移动','十二点按零小时角度处理','返回较小夹角'],solutions:[s('continuous-hand-angles','连续指针角度','直接计算两指针相对十二点角度。',['minuteAngle=minutes*6','hourAngle=(hour%12)*30+minutes*0.5','difference=abs(hourAngle-minuteAngle)，返回 min(difference,360-difference)'],'O(1)','O(1)',
`class Solution { public double angleClock(int hour,int minutes){double minuteAngle=minutes*6.0,hourAngle=(hour%12)*30.0+minutes*0.5,difference=Math.abs(hourAngle-minuteAngle);return Math.min(difference,360.0-difference);} }`,
`class Solution { fun angleClock(hour:Int,minutes:Int):Double{val minuteAngle=minutes*6.0;val hourAngle=(hour%12)*30.0+minutes*0.5;val difference=kotlin.math.abs(hourAngle-minuteAngle);return minOf(difference,360.0-difference)} }`,
`class Solution { public: double angleClock(int hour,int minutes){double minuteAngle=minutes*6.0,hourAngle=hour%12*30.0+minutes*0.5,difference=abs(hourAngle-minuteAngle);return min(difference,360.0-difference);} };`)],tests:{schemaVersion:1,mode:'function',method:'angleClock',parameterTypes:['int','int'],returnType:'double',cases:[{name:'十二点三十分一百六十五度',args:[12,30],expected:165.0},{name:'三点三十分七十五度',args:[3,30],expected:75.0},{name:'三点整九十度',args:[3,0],expected:90.0}]}},
{id:1345,slug:'jump-game-iv',title:'跳跃游戏 IV',studyTags:['数组','哈希表','广度优先搜索'],summary:'从下标零出发，每步可到相邻下标或任意相同值下标，求到末尾的最少跳跃次数。',insight:'BFS 保证最短路；按值预建下标列表。某个值的全部同值边第一次展开后即可清空，因为后续再展开不会产生新节点，避免平方级重复。',pitfalls:['相邻下标和同值下标都可跳','入队时立刻标记访问','同值列表处理一次后必须移除或清空'],solutions:[s('value-group-clearing-bfs','值分组清空广度优先搜索','把同值完全图的边压缩为一次批量扩展。',['valueIndices 映射每个值到下标列表，队列放 [0,0]，seen[0]','弹出 index，若末尾返回 distance；尝试 index-1、index+1 和 valueIndices[arr[index]] 中所有下标','未见下标入队 distance+1，随后删除该值列表；耗尽返回 -1'],'O(n)','O(n)',
`class Solution { public int minJumps(int[] arr){Map<Integer,List<Integer>> indices=new HashMap<>();for(int i=0;i<arr.length;i++)indices.computeIfAbsent(arr[i],key->new ArrayList<>()).add(i);Queue<int[]> queue=new ArrayDeque<>();boolean[] seen=new boolean[arr.length];queue.offer(new int[]{0,0});seen[0]=true;while(!queue.isEmpty()){int[] state=queue.poll();int index=state[0];if(index==arr.length-1)return state[1];List<Integer> next=new ArrayList<>();if(index>0)next.add(index-1);if(index+1<arr.length)next.add(index+1);next.addAll(indices.getOrDefault(arr[index],Collections.emptyList()));for(int value:next)if(!seen[value]){seen[value]=true;queue.offer(new int[]{value,state[1]+1});}indices.remove(arr[index]);}return -1;} }`,
`class Solution { fun minJumps(arr:IntArray):Int{val indices=mutableMapOf<Int,MutableList<Int>>();for(i in arr.indices)indices.getOrPut(arr[i]){mutableListOf()}.add(i);val queue=java.util.ArrayDeque<IntArray>();val seen=BooleanArray(arr.size);queue.addLast(intArrayOf(0,0));seen[0]=true;while(queue.isNotEmpty()){val state=queue.removeFirst();val index=state[0];if(index==arr.lastIndex)return state[1];val next=mutableListOf<Int>();if(index>0)next.add(index-1);if(index<arr.lastIndex)next.add(index+1);next.addAll(indices[arr[index]]?:emptyList());for(value in next)if(!seen[value]){seen[value]=true;queue.addLast(intArrayOf(value,state[1]+1))};indices.remove(arr[index])};return -1} }`,
`class Solution { public: int minJumps(vector<int>& arr){unordered_map<int,vector<int>> indices;for(int i=0;i<(int)arr.size();++i)indices[arr[i]].push_back(i);queue<pair<int,int>> pending;vector<bool> seen(arr.size());pending.push({0,0});seen[0]=true;while(!pending.empty()){auto [index,distance]=pending.front();pending.pop();if(index==(int)arr.size()-1)return distance;vector<int> next=move(indices[arr[index]]);indices.erase(arr[index]);next.push_back(index-1);next.push_back(index+1);for(int value:next)if(value>=0&&value<(int)arr.size()&&!seen[value]){seen[value]=true;pending.push({value,distance+1});}}return -1;} };`)],tests:{schemaVersion:1,mode:'function',method:'minJumps',parameterTypes:['intArray'],returnType:'int',cases:[{name:'经典数组三跳到末尾',args:[[100,-23,-23,404,100,23,23,23,3,404]],expected:3},{name:'单元素零跳',args:[[7]],expected:0},{name:'首尾同值一步到达',args:[[7,6,9,6,9,6,9,7]],expected:1}]}},
{id:1346,slug:'check-if-n-and-its-double-exist',title:'检查整数及其两倍数是否存在',studyTags:['数组','哈希表'],summary:'判断数组中是否存在不同下标 i、j，使 arr[i] 等于 arr[j] 的两倍。',insight:'从左到右维护已见集合；当前 value 若集合已有 2value，或 value 为偶数且集合已有 value/2，即找到一对。检查后再加入当前值确保下标不同。',pitfalls:['零需要出现至少两次才满足','除二检查只对偶数有效','先检查后插入当前值'],solutions:[s('seen-double-or-half','已见两倍或一半','单遍查找当前值与此前值的两种倍数关系。',['seen 为空','扫描 value；若 seen 含 2*value，或 value%2==0 且含 value/2，返回 true','把 value 加入 seen；扫描结束返回 false'],'O(n)','O(n)',
`class Solution { public boolean checkIfExist(int[] arr){Set<Integer> seen=new HashSet<>();for(int value:arr){if(seen.contains(value*2)||value%2==0&&seen.contains(value/2))return true;seen.add(value);}return false;} }`,
`class Solution { fun checkIfExist(arr:IntArray):Boolean{val seen=mutableSetOf<Int>();for(value in arr){if(value*2 in seen||value%2==0&&value/2 in seen)return true;seen.add(value)};return false} }`,
`class Solution { public: bool checkIfExist(vector<int>& arr){unordered_set<int> seen;for(int value:arr){if(seen.count(value*2)||(value%2==0&&seen.count(value/2)))return true;seen.insert(value);}return false;} };`)],tests:{schemaVersion:1,mode:'function',method:'checkIfExist',parameterTypes:['intArray'],returnType:'boolean',cases:[{name:'十与五满足倍数',args:[[10,2,5,3]],expected:true},{name:'三与六满足倍数',args:[[3,1,7,11,6]],expected:true},{name:'没有倍数对',args:[[7,1,11]],expected:false}]}},
{id:1347,slug:'minimum-number-of-steps-to-make-two-strings-anagram',title:'制造字母异位词的最小步骤数',studyTags:['字符串','计数'],summary:'等长小写字符串 s、t，每步可替换 t 中一个字符，求使 t 成为 s 的字母异位词的最少步骤。',insight:'统计 s 需要的字母数减去 t 已有字母数；所有正差之和就是 t 缺少、必须通过替换补入的字符数量。',pitfalls:['只需统计正差，负差对应可被替换掉的多余字符','两串长度相同保证正负差总量相等','字符位置不重要'],solutions:[s('letter-deficit-count','字母缺口计数','累计目标 s 相对 t 缺少的字符数量。',['count[26]，扫描 s 加一、t 减一','answer=0','对每个差值若大于零则累加，返回 answer'],'O(n)','O(1)',
`class Solution { public int minSteps(String s,String t){int[] count=new int[26];for(int i=0;i<s.length();i++){count[s.charAt(i)-'a']++;count[t.charAt(i)-'a']--;}int answer=0;for(int value:count)if(value>0)answer+=value;return answer;} }`,
`class Solution { fun minSteps(s:String,t:String):Int{val count=IntArray(26);for(i in s.indices){count[s[i]-'a']++;count[t[i]-'a']--};return count.sumOf{maxOf(0,it)}} }`,
`class Solution { public: int minSteps(string s,string t){int count[26]={};for(int i=0;i<(int)s.size();++i){++count[s[i]-'a'];--count[t[i]-'a'];}int answer=0;for(int value:count)answer+=max(0,value);return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'minSteps',parameterTypes:['string','string'],returnType:'int',cases:[{name:'bab 变 aba 一步',args:['bab','aba'],expected:1},{name:'leetcode 与 practice 五步',args:['leetcode','practice'],expected:5},{name:'两个异位词无需替换',args:['anagram','mangaar'],expected:0}]}}
]}
