const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-023',problems:[
{id:1584,slug:'min-cost-to-connect-all-points',title:'连接所有点的最小费用',studyTags:['数组','图论','最小生成树','Prim'],summary:'完全图中两点边权为曼哈顿距离，求连接所有点的最小总费用。',insight:'直接在隐式完全图上运行 Prim：每次选尚未加入树且到当前树距离最小的点，再用它更新其他点的最短连接边。',pitfalls:['无需显式存 O(n²) 条边','每轮恰加入一个新点','距离使用坐标差绝对值之和'],solutions:[s('dense-prim','稠密图 Prim','用数组实现 O(n²) 最小生成树。',['distance[0]=0，其余无穷，used 全 false','重复 n 次选未用且 distance 最小的 node，加入答案并标记','对每个未用 next，用曼哈顿距离松弛 distance[next]'],'O(n²)','O(n)',
`class Solution { public int minCostConnectPoints(int[][] points){int n=points.length,answer=0;int[] distance=new int[n];Arrays.fill(distance,Integer.MAX_VALUE);distance[0]=0;boolean[] used=new boolean[n];for(int count=0;count<n;count++){int node=-1;for(int i=0;i<n;i++)if(!used[i]&&(node==-1||distance[i]<distance[node]))node=i;used[node]=true;answer+=distance[node];for(int next=0;next<n;next++)if(!used[next]){int cost=Math.abs(points[node][0]-points[next][0])+Math.abs(points[node][1]-points[next][1]);distance[next]=Math.min(distance[next],cost);}}return answer;} }`,
`class Solution { fun minCostConnectPoints(points:Array<IntArray>):Int{val n=points.size;val distance=IntArray(n){Int.MAX_VALUE};distance[0]=0;val used=BooleanArray(n);var answer=0;repeat(n){var node=-1;for(i in 0 until n)if(!used[i]&&(node==-1||distance[i]<distance[node]))node=i;used[node]=true;answer+=distance[node];for(next in 0 until n)if(!used[next]){val cost=kotlin.math.abs(points[node][0]-points[next][0])+kotlin.math.abs(points[node][1]-points[next][1]);distance[next]=minOf(distance[next],cost)}};return answer} }`,
`class Solution { public: int minCostConnectPoints(vector<vector<int>>& points){int n=points.size(),answer=0;vector<int> distance(n,INT_MAX);vector<bool> used(n);distance[0]=0;for(int count=0;count<n;++count){int node=-1;for(int i=0;i<n;++i)if(!used[i]&&(node==-1||distance[i]<distance[node]))node=i;used[node]=true;answer+=distance[node];for(int next=0;next<n;++next)if(!used[next]){int cost=abs(points[node][0]-points[next][0])+abs(points[node][1]-points[next][1]);distance[next]=min(distance[next],cost);}}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'minCostConnectPoints',parameterTypes:['intMatrix'],returnType:'int',cases:[{name:'五个点最小费用二十',args:[[[0,0],[2,2],[3,10],[5,2],[7,0]]],expected:20},{name:'三个点最小费用十八',args:[[[3,12],[-2,5],[-4,1]]],expected:18},{name:'单点费用为零',args:[[[0,0]]],expected:0}]}},
{id:1585,slug:'check-if-string-is-transformable-with-substring-sort-operations',title:'检查字符串是否可通过排序子字符串得到另一个字符串',studyTags:['字符串','贪心','排序'],summary:'可任意次把 s 的一个子串升序排序，判断能否变成 t。',insight:'记录 s 中每个数字的下标队列。按 t 顺序取目标数字在 s 中最早未用位置；若有更小数字的最早位置在它之前，该小数字无法越过它，转换失败。',pitfalls:['只能通过升序排序让较小数字向左跨过较大数字','同数字必须按原位置顺序使用','每次选择对应数字的最早位置'],solutions:[s('digit-position-queues','数字位置队列贪心','按目标顺序验证每个数字能否越过此前未用数字。',['为 s 的 0..9 建下标队列','扫描 t 的 digit，队列空则 false，position=队首','若任一 smaller<digit 队首小于 position 则 false，否则弹出 digit 队首，结束 true'],'O(10n)','O(n)',
`class Solution { public boolean isTransformable(String s,String t){Deque<Integer>[] positions=new Deque[10];for(int digit=0;digit<10;digit++)positions[digit]=new ArrayDeque<>();for(int i=0;i<s.length();i++)positions[s.charAt(i)-'0'].addLast(i);for(char value:t.toCharArray()){int digit=value-'0';if(positions[digit].isEmpty())return false;int position=positions[digit].peekFirst();for(int smaller=0;smaller<digit;smaller++)if(!positions[smaller].isEmpty()&&positions[smaller].peekFirst()<position)return false;positions[digit].removeFirst();}return true;} }`,
`class Solution { fun isTransformable(s:String,t:String):Boolean{val positions=Array(10){java.util.ArrayDeque<Int>()};for(i in s.indices)positions[s[i]-'0'].addLast(i);for(value in t){val digit=value-'0';if(positions[digit].isEmpty())return false;val position=positions[digit].peekFirst();for(smaller in 0 until digit)if(positions[smaller].isNotEmpty()&&positions[smaller].peekFirst()<position)return false;positions[digit].removeFirst()};return true} }`,
`class Solution { public: bool isTransformable(string s,string t){array<queue<int>,10> positions;for(int i=0;i<(int)s.size();++i)positions[s[i]-'0'].push(i);for(char value:t){int digit=value-'0';if(positions[digit].empty())return false;int position=positions[digit].front();for(int smaller=0;smaller<digit;++smaller)if(!positions[smaller].empty()&&positions[smaller].front()<position)return false;positions[digit].pop();}return true;} };`)],tests:{schemaVersion:1,mode:'function',method:'isTransformable',parameterTypes:['string','string'],returnType:'boolean',cases:[{name:'84532 可变为 34852',args:['84532','34852'],expected:true},{name:'34521 无法变为 23415',args:['34521','23415'],expected:true},{name:'12345 无法逆序',args:['12345','12435'],expected:false}]}},
{id:1588,slug:'sum-of-all-odd-length-subarrays',title:'所有奇数长度子数组的和',studyTags:['数组','数学'],summary:'返回数组中所有奇数长度连续子数组的元素和总和。',insight:'元素 arr[i] 被包含在 (i+1)(n-i) 个子数组中，其中奇数长度数量是总数向上取半，即 (total+1)/2。按贡献累加。',pitfalls:['计数包含所有起止点组合','奇数子数组数量向上取半','每个元素按出现次数加权'],solutions:[s('per-index-contribution','逐元素贡献计数','计算每个位置参与奇数长度子数组的次数。',['对 i 计算 total=(i+1)*(n-i)','oddCount=(total+1)/2','answer+=arr[i]*oddCount'],'O(n)','O(1)',
`class Solution { public int sumOddLengthSubarrays(int[] arr){int answer=0,n=arr.length;for(int i=0;i<n;i++){int total=(i+1)*(n-i);answer+=arr[i]*((total+1)/2);}return answer;} }`,
`class Solution { fun sumOddLengthSubarrays(arr:IntArray):Int{var answer=0;for(i in arr.indices){val total=(i+1)*(arr.size-i);answer+=arr[i]*((total+1)/2)};return answer} }`,
`class Solution { public: int sumOddLengthSubarrays(vector<int>& arr){int answer=0,n=arr.size();for(int i=0;i<n;++i){int total=(i+1)*(n-i);answer+=arr[i]*((total+1)/2);}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'sumOddLengthSubarrays',parameterTypes:['intArray'],returnType:'int',cases:[{name:'五元素奇长子数组和五十八',args:[[1,4,2,5,3]],expected:58},{name:'两个元素只有单项子数组',args:[[1,2]],expected:3},{name:'十至十二总和六十六',args:[[10,11,12]],expected:66}]}},
{id:1589,slug:'maximum-sum-obtained-of-any-permutation',title:'所有排列中的最大和',studyTags:['数组','贪心','排序','前缀和'],summary:'可任意排列 nums，多条请求贡献指定区间元素和，求总请求和最大值取模。',insight:'差分数组计算每个下标被请求覆盖次数。重排不等式表明，把最大数分配给最大覆盖次数可使加权和最大。',pitfalls:['请求端点都包含','差分在 right+1 处减一需判边界','排序两个数组后同序相乘'],solutions:[s('coverage-count-rearrangement','覆盖频次与重排不等式','把元素值与位置权重各自排序后配对。',['difference[n+1]，每请求 left++、right+1--','前缀得到 frequency[n]','排序 nums 与 frequency，累加 nums[i]*frequency[i] 取模'],'O(n log n+q)','O(n)',
`class Solution { public int maxSumRangeQuery(int[] nums,int[][] requests){int n=nums.length;int[] frequency=new int[n+1];for(int[] request:requests){frequency[request[0]]++;frequency[request[1]+1]--;}for(int i=1;i<n;i++)frequency[i]+=frequency[i-1];Arrays.sort(nums);Arrays.sort(frequency,0,n);long answer=0;for(int i=0;i<n;i++)answer=(answer+(long)nums[i]*frequency[i])%1_000_000_007L;return (int)answer;} }`,
`class Solution { fun maxSumRangeQuery(nums:IntArray,requests:Array<IntArray>):Int{val n=nums.size;val frequency=IntArray(n+1);for(request in requests){frequency[request[0]]++;frequency[request[1]+1]--};for(i in 1 until n)frequency[i]+=frequency[i-1];nums.sort();frequency.sort(0,n);var answer=0L;for(i in 0 until n)answer=(answer+nums[i].toLong()*frequency[i])%1_000_000_007L;return answer.toInt()} }`,
`class Solution { public: int maxSumRangeQuery(vector<int>& nums,vector<vector<int>>& requests){int n=nums.size();vector<int> frequency(n+1);for(auto& request:requests){++frequency[request[0]];--frequency[request[1]+1];}for(int i=1;i<n;++i)frequency[i]+=frequency[i-1];sort(nums.begin(),nums.end());sort(frequency.begin(),frequency.begin()+n);long long answer=0;for(int i=0;i<n;++i)answer=(answer+1LL*nums[i]*frequency[i])%1000000007;return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'maxSumRangeQuery',parameterTypes:['intArray','intMatrix'],returnType:'int',cases:[{name:'两个请求最大和十九',args:[[1,2,3,4,5],[[1,3],[0,1]]],expected:19},{name:'五个重叠请求最大和二十九',args:[[1,2,3,4,5],[[0,1],[1,2],[2,3],[3,4],[4,4]]],expected:29},{name:'单请求全数组保持总和',args:[[1,2,3],[[0,2]]],expected:6}]}},
{id:1590,slug:'make-sum-divisible-by-p',title:'使数组和能被 P 整除',studyTags:['数组','哈希表','前缀和'],summary:'移除一个最短连续子数组，使剩余元素和可被 p 整除；不能移除整个数组，不可行返回负一。',insight:'总余数 remainder。需找子数组和模 p 等于 remainder；若当前前缀模为 prefix，之前需要模为 prefix-remainder。哈希表保存每个余数最新下标以最小化长度。',pitfalls:['总和已整除时返回零','前缀和用 long 后规范取模','答案等于 n 时不允许'],solutions:[s('latest-prefix-modulo','最新前缀余数哈希','用模差匹配待移除区间并保留最近起点。',['remainder=total%p，零则返回 0','latest={0:-1},prefix=0,answer=n','扫描 i 更新 prefix，needed=(prefix-remainder+p)%p；若存在更新 i-latest[needed]；写 latest[prefix]=i，结束 answer==n?-1:answer'],'O(n)','O(n)',
`class Solution { public int minSubarray(int[] nums,int p){long total=0;for(int value:nums)total+=value;int remainder=(int)(total%p);if(remainder==0)return 0;Map<Integer,Integer> latest=new HashMap<>();latest.put(0,-1);int prefix=0,answer=nums.length;for(int i=0;i<nums.length;i++){prefix=(int)(((long)prefix+nums[i])%p);int needed=(prefix-remainder+p)%p;if(latest.containsKey(needed))answer=Math.min(answer,i-latest.get(needed));latest.put(prefix,i);}return answer==nums.length?-1:answer;} }`,
`class Solution { fun minSubarray(nums:IntArray,p:Int):Int{val remainder=(nums.sumOf{it.toLong()}%p).toInt();if(remainder==0)return 0;val latest=mutableMapOf(0 to -1);var prefix=0;var answer=nums.size;for(i in nums.indices){prefix=((prefix.toLong()+nums[i])%p).toInt();val needed=(prefix-remainder+p)%p;latest[needed]?.let{answer=minOf(answer,i-it)};latest[prefix]=i};return if(answer==nums.size)-1 else answer} }`,
`class Solution { public: int minSubarray(vector<int>& nums,int p){long long total=accumulate(nums.begin(),nums.end(),0LL);int remainder=total%p;if(!remainder)return 0;unordered_map<int,int> latest{{0,-1}};int prefix=0,answer=nums.size();for(int i=0;i<(int)nums.size();++i){prefix=(prefix+(long long)nums[i])%p;int needed=(prefix-remainder+p)%p;if(latest.count(needed))answer=min(answer,i-latest[needed]);latest[prefix]=i;}return answer==(int)nums.size()?-1:answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'minSubarray',parameterTypes:['intArray','int'],returnType:'int',cases:[{name:'移除四即可被六整除',args:[[3,1,4,2],6],expected:1},{name:'移除二六长度二',args:[[6,3,5,2],9],expected:2},{name:'总和已被三整除',args:[[1,2,3],3],expected:0}]}}
]}
