const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-025',problems:[
{id:1751,slug:'maximum-number-of-events-that-can-be-attended-ii',title:'最多可以参加的会议数目 II',studyTags:['数组','二分查找','动态规划','排序'],summary:'每个会议有起止日和价值，最多参加 k 个互不重叠会议，求最大价值；结束日与下一开始日相同也算重叠。',insight:'按开始日排序，为每个会议二分首个开始日严格大于其结束日的后继。记忆化 DP 在跳过当前会议和参加后跳到后继之间取最大。',pitfalls:['下一会议开始日必须严格大于当前结束日','最多而非恰好参加 k 个','会议原顺序无关，先排序'],solutions:[s('sorted-next-index-dp','排序后二分后继动态规划','预计算或在线二分不重叠后继并做选取 DP。',['events 按 start 排序','dfs(index,remaining)：跳过为 dfs(index+1,remaining)','二分 next 的 start>end，参加为 value+dfs(next,remaining-1)，取最大并缓存'],'O(nk log n)','O(nk)',
`class Solution { private int[][] events,memo;private int next(int end){int left=0,right=events.length;while(left<right){int mid=(left+right)>>>1;if(events[mid][0]<=end)left=mid+1;else right=mid;}return left;}private int dfs(int index,int remaining){if(index==events.length||remaining==0)return 0;if(memo[index][remaining]!=-1)return memo[index][remaining];return memo[index][remaining]=Math.max(dfs(index+1,remaining),events[index][2]+dfs(next(events[index][1]),remaining-1));}public int maxValue(int[][] events,int k){Arrays.sort(events,Comparator.comparingInt(event->event[0]));this.events=events;memo=new int[events.length][k+1];for(int[] row:memo)Arrays.fill(row,-1);return dfs(0,k);} }`,
`class Solution { private lateinit var events:Array<IntArray>;private lateinit var memo:Array<IntArray>;private fun next(end:Int):Int{var left=0;var right=events.size;while(left<right){val mid=(left+right) ushr 1;if(events[mid][0]<=end)left=mid+1 else right=mid};return left};private fun dfs(index:Int,remaining:Int):Int{if(index==events.size||remaining==0)return 0;if(memo[index][remaining]>=0)return memo[index][remaining];memo[index][remaining]=maxOf(dfs(index+1,remaining),events[index][2]+dfs(next(events[index][1]),remaining-1));return memo[index][remaining]};fun maxValue(events:Array<IntArray>,k:Int):Int{events.sortBy{it[0]};this.events=events;memo=Array(events.size){IntArray(k+1){-1}};return dfs(0,k)} }`,
`class Solution { vector<vector<int>> events,memo;int nextIndex(int end){int left=0,right=events.size();while(left<right){int mid=(left+right)/2;if(events[mid][0]<=end)left=mid+1;else right=mid;}return left;}int dfs(int index,int remaining){if(index==(int)events.size()||!remaining)return 0;int& answer=memo[index][remaining];if(answer>=0)return answer;return answer=max(dfs(index+1,remaining),events[index][2]+dfs(nextIndex(events[index][1]),remaining-1));}public:int maxValue(vector<vector<int>>& input,int k){events=input;sort(events.begin(),events.end());memo.assign(events.size(),vector<int>(k+1,-1));return dfs(0,k);} };`)],tests:{schemaVersion:1,mode:'function',method:'maxValue',parameterTypes:['intMatrix','int'],returnType:'int',cases:[{name:'参加两个不重叠会议价值七',args:[[[1,2,4],[3,4,3],[2,3,1]],2],expected:7},{name:'高价值重叠会议单独最优',args:[[[1,2,4],[3,4,3],[2,3,10]],2],expected:10},{name:'四个单日会议选最高三个',args:[[[1,1,1],[2,2,2],[3,3,3],[4,4,4]],3],expected:9}]}},
{id:1752,slug:'check-if-array-is-sorted-and-rotated',title:'检查数组是否经排序和轮转得到',studyTags:['数组'],summary:'判断数组是否能由一个非降序数组轮转若干位置得到，数组可含重复值。',insight:'沿环比较相邻元素，非降序轮转数组最多只有一个严格下降断点；把末尾到开头也纳入比较。',pitfalls:['相等不算下降','需要检查 nums[n-1] 到 nums[0]','零次轮转也合法'],solutions:[s('circular-drop-count','环形下降点计数','用唯一可能的轮转接缝刻画合法数组。',['drops=0','i 从零到 n-1，比较 nums[i] 与 nums[(i+1)%n]','前者大于后者则 drops++，返回 drops<=1'],'O(n)','O(1)',
`class Solution { public boolean check(int[] nums){int drops=0;for(int i=0;i<nums.length;i++)if(nums[i]>nums[(i+1)%nums.length])drops++;return drops<=1;} }`,
`class Solution { fun check(nums:IntArray):Boolean=nums.indices.count{nums[it]>nums[(it+1)%nums.size]}<=1 }`,
`class Solution { public: bool check(vector<int>& nums){int drops=0;for(int i=0;i<(int)nums.size();++i)drops+=nums[i]>nums[(i+1)%nums.size()];return drops<=1;} };`)],tests:{schemaVersion:1,mode:'function',method:'check',parameterTypes:['intArray'],returnType:'boolean',cases:[{name:'排序数组轮转两位',args:[[3,4,5,1,2]],expected:true},{name:'存在两个下降点不合法',args:[[2,1,3,4]],expected:false},{name:'原数组已排序',args:[[1,2,3]],expected:true}]}},
{id:1753,slug:'maximum-score-from-removing-stones',title:'移除石子的最大得分',studyTags:['数学','贪心','堆（优先队列）'],summary:'三堆石子每步从两堆非空堆各取一颗得一分，求最大得分。',insight:'若最大堆大于其余两堆总和，只能做其余总和步；否则总石子每步消耗两颗，能做到 floor(total/2) 步。',pitfalls:['每步必须来自两个不同非空堆','最大堆可能成为瓶颈','答案公式为 min(total-maximum,total/2)'],solutions:[s('pile-balance-formula','石堆平衡公式','用资源总量与非最大堆数量给出双重上界且均可达。',['total=a+b+c','maximum=max(a,b,c)','返回 min(total-maximum,total/2)'],'O(1)','O(1)',
`class Solution { public int maximumScore(int a,int b,int c){int total=a+b+c,maximum=Math.max(a,Math.max(b,c));return Math.min(total-maximum,total/2);} }`,
`class Solution { fun maximumScore(a:Int,b:Int,c:Int):Int{val total=a+b+c;val maximum=maxOf(a,b,c);return minOf(total-maximum,total/2)} }`,
`class Solution { public: int maximumScore(int a,int b,int c){int total=a+b+c,maximum=max({a,b,c});return min(total-maximum,total/2);} };`)],tests:{schemaVersion:1,mode:'function',method:'maximumScore',parameterTypes:['int','int','int'],returnType:'int',cases:[{name:'二四六可得六分',args:[2,4,6],expected:6},{name:'四四六可得七分',args:[4,4,6],expected:7},{name:'一八八可得八分',args:[1,8,8],expected:8}]}},
{id:1754,slug:'largest-merge-of-two-strings',title:'构造字典序最大的合并字符串',studyTags:['双指针','字符串','贪心'],summary:'每次从 word1 或 word2 的首字符取一个追加到 merge，直到两串为空，求字典序最大的合并结果。',insight:'每一步应从当前剩余后缀字典序更大的一侧取首字符；若首字符相同，后续第一个差异决定当前选择。',pitfalls:['不能只比较当前首字符','一侧用尽后直接追加另一侧剩余','相同后缀任选一侧都可'],solutions:[s('suffix-comparison-greedy','后缀比较贪心','在每个位置选择能产生更大剩余合并的字符串。',['i=j=0，builder 为空','两侧均未结束时比较 word1.substring(i) 与 word2.substring(j)','从更大后缀取一个字符；最后追加任一剩余后缀'],'O((m+n)²)','O(m+n)',
`class Solution { public String largestMerge(String word1,String word2){StringBuilder answer=new StringBuilder();int first=0,second=0;while(first<word1.length()&&second<word2.length())if(word1.substring(first).compareTo(word2.substring(second))>0)answer.append(word1.charAt(first++));else answer.append(word2.charAt(second++));return answer.append(word1.substring(first)).append(word2.substring(second)).toString();} }`,
`class Solution { fun largestMerge(word1:String,word2:String):String{val answer=StringBuilder();var first=0;var second=0;while(first<word1.length&&second<word2.length)if(word1.substring(first)>word2.substring(second))answer.append(word1[first++]) else answer.append(word2[second++]);answer.append(word1.substring(first));answer.append(word2.substring(second));return answer.toString()} }`,
`class Solution { public: string largestMerge(string word1,string word2){string answer;int first=0,second=0;while(first<(int)word1.size()&&second<(int)word2.size())if(word1.compare(first,string::npos,word2,second,string::npos)>0)answer+=word1[first++];else answer+=word2[second++];return answer+word1.substr(first)+word2.substr(second);} };`)],tests:{schemaVersion:1,mode:'function',method:'largestMerge',parameterTypes:['string','string'],returnType:'string',cases:[{name:'经典两串最大合并',args:['cabaa','bcaaa'],expected:'cbcabaaaaa'},{name:'相同前缀需比较完整后缀',args:['abcabc','abdcaba'],expected:'abdcabcabcaba'},{name:'较大首字符先取',args:['a','z'],expected:'za'}]}},
{id:1755,slug:'closest-subsequence-sum',title:'最接近目标值的子序列和',studyTags:['数组','双指针','二分查找','分治'],summary:'从数组任选元素形成子序列，使其和与 goal 的绝对差最小，返回最小差值。',insight:'把数组分成两半，分别枚举所有子集和。排序右半和后，对每个左半和二分寻找最接近 goal-leftSum 的右半和。',pitfalls:['空子序列合法，子集和零必须包含','元素可为负数','答案可能为零，可提前结束'],solutions:[s('meet-in-the-middle-subset-sums','折半枚举子集和','把指数规模从 2^n 降为两组 2^(n/2)。',['生成左右半部全部 subset sums','右半 sums 排序','对每个 leftSum 二分 target=goal-leftSum，检查 lower_bound 位置及前一位置，更新最小绝对差'],'O(2^(n/2) log 2^(n/2))','O(2^(n/2))',
`class Solution { private int[] sums(int[] nums,int start,int length){int[] sums=new int[1<<length];for(int mask=1;mask<sums.length;mask++){int bit=Integer.numberOfTrailingZeros(mask);sums[mask]=sums[mask^(1<<bit)]+nums[start+bit];}return sums;}public int minAbsDifference(int[] nums,int goal){int middle=nums.length/2;int[] left=sums(nums,0,middle),right=sums(nums,middle,nums.length-middle);Arrays.sort(right);int answer=Math.abs(goal);for(int value:left){int target=goal-value,index=Arrays.binarySearch(right,target);if(index>=0)return 0;index=-index-1;if(index<right.length)answer=Math.min(answer,Math.abs(value+right[index]-goal));if(index>0)answer=Math.min(answer,Math.abs(value+right[index-1]-goal));}return answer;} }`,
`class Solution { private fun sums(nums:IntArray,start:Int,length:Int):IntArray{val sums=IntArray(1 shl length);for(mask in 1 until sums.size){val bit=Integer.numberOfTrailingZeros(mask);sums[mask]=sums[mask xor (1 shl bit)]+nums[start+bit]};return sums};fun minAbsDifference(nums:IntArray,goal:Int):Int{val middle=nums.size/2;val left=sums(nums,0,middle);val right=sums(nums,middle,nums.size-middle);right.sort();var answer=kotlin.math.abs(goal);for(value in left){val target=goal-value;var index=right.binarySearch(target);if(index>=0)return 0;index=-index-1;if(index<right.size)answer=minOf(answer,kotlin.math.abs(value+right[index]-goal));if(index>0)answer=minOf(answer,kotlin.math.abs(value+right[index-1]-goal))};return answer} }`,
`class Solution { vector<int> sums(vector<int>& nums,int start,int length){vector<int> values(1<<length);for(int mask=1;mask<(1<<length);++mask){int bit=__builtin_ctz(mask);values[mask]=values[mask^(1<<bit)]+nums[start+bit];}return values;}public:int minAbsDifference(vector<int>& nums,int goal){int middle=nums.size()/2;auto left=sums(nums,0,middle),right=sums(nums,middle,nums.size()-middle);sort(right.begin(),right.end());int answer=abs(goal);for(int value:left){int target=goal-value;auto it=lower_bound(right.begin(),right.end(),target);if(it!=right.end())answer=min(answer,abs(value+*it-goal));if(it!=right.begin())answer=min(answer,abs(value+*prev(it)-goal));}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'minAbsDifference',parameterTypes:['intArray','int'],returnType:'int',cases:[{name:'存在子序列和恰好为六',args:[[5,-7,3,5],6],expected:0},{name:'最接近负五相差一',args:[[7,-9,15,-2],-5],expected:1},{name:'目标小于所有子集和相差七',args:[[1,2,3],-7],expected:7}]}}
]}
