const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})

export default {batchId:'batch-017',problems:[
{id:1206,slug:'design-skiplist',title:'设计跳表',studyTags:['设计','链表','跳表','随机化'],summary:'实现支持 search、add 和 erase 的跳表，允许重复元素。',insight:'每层都是底层有序链表的稀疏索引。查找时从最高层向右走到不能再走后下降；插入记录各层前驱并随机决定节点高度，删除在所有层绕过一个目标节点。',pitfalls:['重复值可以分别插入，erase 每次只删除一个','寻找前驱时使用严格小于目标','头节点覆盖所有最大层级'],solutions:[s('random-level-skip-list','随机层级跳表','用多层前向指针获得期望对数时间操作。',['固定 MAX_LEVEL，Node 保存 value 与 next 数组；findPredecessors 从最高层下降并记录每层前驱','add 随机生成 level，新节点在 0..level-1 层接入前驱与后继之间','search 检查第零层后继；erase 找到前驱和目标后，在所有指向该目标的层绕过它'],'期望 O(log n)','O(n log n) 指针上界',
`class Skiplist { private static final int MAX_LEVEL=16;private static class Node{int value;Node[] next;Node(int value){this.value=value;next=new Node[MAX_LEVEL];}}private final Node head=new Node(-1);private int seed=1;private Node[] predecessors(int target){Node[] update=new Node[MAX_LEVEL];Node node=head;for(int level=MAX_LEVEL-1;level>=0;level--){while(node.next[level]!=null&&node.next[level].value<target)node=node.next[level];update[level]=node;}return update;}private int randomLevel(){int level=1;while(level<MAX_LEVEL){seed=seed*1103515245+12345;if((seed&1)!=0)break;level++;}return level;}public boolean search(int target){Node node=predecessors(target)[0].next[0];return node!=null&&node.value==target;}public void add(int num){Node[] update=predecessors(num);Node node=new Node(num);int limit=randomLevel();for(int level=0;level<limit;level++){node.next[level]=update[level].next[level];update[level].next[level]=node;}}public boolean erase(int num){Node[] update=predecessors(num);Node target=update[0].next[0];if(target==null||target.value!=num)return false;for(int level=0;level<MAX_LEVEL&&update[level].next[level]==target;level++)update[level].next[level]=target.next[level];return true;} }`,
`class Skiplist { private companion object{const val MAX_LEVEL=16};private class Node(val value:Int){val next=arrayOfNulls<Node>(MAX_LEVEL)};private val head=Node(-1);private var seed=1;private fun predecessors(target:Int):Array<Node>{val update=Array(MAX_LEVEL){head};var node=head;for(level in MAX_LEVEL-1 downTo 0){while(node.next[level]!=null&&node.next[level]!!.value<target)node=node.next[level]!!;update[level]=node};return update};private fun randomLevel():Int{var level=1;while(level<MAX_LEVEL){seed=seed*1103515245+12345;if(seed and 1!=0)break;level++};return level};fun search(target:Int):Boolean{val node=predecessors(target)[0].next[0];return node!=null&&node.value==target};fun add(num:Int){val update=predecessors(num);val node=Node(num);for(level in 0 until randomLevel()){node.next[level]=update[level].next[level];update[level].next[level]=node}};fun erase(num:Int):Boolean{val update=predecessors(num);val target=update[0].next[0];if(target==null||target.value!=num)return false;for(level in 0 until MAX_LEVEL){if(update[level].next[level]!==target)break;update[level].next[level]=target.next[level]};return true} }`,
`class Skiplist { static const int MAX_LEVEL=16;struct Node{int value;array<Node*,MAX_LEVEL> next{};Node(int value):value(value){}};Node* head=new Node(-1);unsigned seed=1;array<Node*,MAX_LEVEL> predecessors(int target){array<Node*,MAX_LEVEL> update;Node* node=head;for(int level=MAX_LEVEL-1;level>=0;--level){while(node->next[level]&&node->next[level]->value<target)node=node->next[level];update[level]=node;}return update;}int randomLevel(){int level=1;while(level<MAX_LEVEL){seed=seed*1103515245u+12345u;if(seed&1u)break;++level;}return level;}public:bool search(int target){Node* node=predecessors(target)[0]->next[0];return node&&node->value==target;}void add(int num){auto update=predecessors(num);Node* node=new Node(num);for(int level=0,limit=randomLevel();level<limit;++level){node->next[level]=update[level]->next[level];update[level]->next[level]=node;}}bool erase(int num){auto update=predecessors(num);Node* target=update[0]->next[0];if(!target||target->value!=num)return false;for(int level=0;level<MAX_LEVEL&&update[level]->next[level]==target;++level)update[level]->next[level]=target->next[level];delete target;return true;} };`)],tests:{schemaVersion:1,mode:'design',className:'Skiplist',constructorTypes:[],cases:[{name:'经典增查删流程',constructorArgs:[],calls:[{method:'add',parameterTypes:['int'],args:[1]},{method:'add',parameterTypes:['int'],args:[2]},{method:'add',parameterTypes:['int'],args:[3]},{method:'search',parameterTypes:['int'],args:[0],returnType:'boolean',expected:false},{method:'add',parameterTypes:['int'],args:[4]},{method:'search',parameterTypes:['int'],args:[1],returnType:'boolean',expected:true},{method:'erase',parameterTypes:['int'],args:[0],returnType:'boolean',expected:false},{method:'erase',parameterTypes:['int'],args:[1],returnType:'boolean',expected:true},{method:'search',parameterTypes:['int'],args:[1],returnType:'boolean',expected:false}]},{name:'重复值只删除一个',constructorArgs:[],calls:[{method:'add',parameterTypes:['int'],args:[5]},{method:'add',parameterTypes:['int'],args:[5]},{method:'erase',parameterTypes:['int'],args:[5],returnType:'boolean',expected:true},{method:'search',parameterTypes:['int'],args:[5],returnType:'boolean',expected:true},{method:'erase',parameterTypes:['int'],args:[5],returnType:'boolean',expected:true},{method:'search',parameterTypes:['int'],args:[5],returnType:'boolean',expected:false}]},{name:'空表删除',constructorArgs:[],calls:[{method:'search',parameterTypes:['int'],args:[9],returnType:'boolean',expected:false},{method:'erase',parameterTypes:['int'],args:[9],returnType:'boolean',expected:false}]}]}},

{id:1207,slug:'unique-number-of-occurrences',title:'独一无二的出现次数',studyTags:['数组','哈希表','计数'],summary:'判断整数数组中每个不同数值的出现次数是否两两不同。',insight:'第一张哈希表统计每个值的频次，再把频次依次放入集合；若某个频次已存在，说明有两个值出现次数相同。',pitfalls:['比较的是不同数值的频次','负数可直接作为哈希键','空冲突集合不是问题'],solutions:[s('frequency-map-and-set','频次表与唯一集合','用集合检测频次数值重复。',['遍历 arr 统计 frequency[value]','创建 seenCounts 集合','遍历所有频次；若 add 返回假则立即返回 false，全部成功返回 true'],'O(n)','O(n)',
`class Solution { public boolean uniqueOccurrences(int[] arr){Map<Integer,Integer> frequency=new HashMap<>();for(int value:arr)frequency.merge(value,1,Integer::sum);Set<Integer> seen=new HashSet<>();for(int count:frequency.values())if(!seen.add(count))return false;return true;} }`,
`class Solution { fun uniqueOccurrences(arr:IntArray):Boolean{val frequency=mutableMapOf<Int,Int>();for(value in arr)frequency[value]=(frequency[value]?:0)+1;val seen=mutableSetOf<Int>();return frequency.values.all{seen.add(it)}} }`,
`class Solution { public: bool uniqueOccurrences(vector<int>& arr){unordered_map<int,int> frequency;for(int value:arr)++frequency[value];unordered_set<int> seen;for(auto [value,count]:frequency)if(!seen.insert(count).second)return false;return true;} };`)],tests:{schemaVersion:1,mode:'function',method:'uniqueOccurrences',parameterTypes:['intArray'],returnType:'boolean',cases:[{name:'次数一二三互异',args:[[1,2,2,1,1,3]],expected:true},{name:'两个值均一次',args:[[1,2]],expected:false},{name:'含负数仍互异',args:[[-3,0,1,-3,1,1,1,-3,10,0]],expected:true}]}},

{id:1208,slug:'get-equal-substrings-within-budget',title:'尽可能使字符串相等',studyTags:['字符串','滑动窗口','双指针'],summary:'把 s 的某个连续子串逐位改成 t 对应字符，每位代价为字符码差绝对值；预算内求最大子串长度。',insight:'每位代价非负，窗口总成本超过 maxCost 时不断移动左端并扣除代价，恢复可行后当前窗口就是以右端结尾的最长可行区间。',pitfalls:['空修改也合法但字符串长度至少一','窗口代价使用 s 与 t 同一位置','只在成本超限时收缩左端'],solutions:[s('cost-sliding-window','代价滑动窗口','维护总修改成本不超过预算的最长窗口。',['left=0,cost=0,best=0','right 从零扫描，加入 abs(s[right]-t[right])','while cost>maxCost，扣除 left 位置代价并 left++；更新 best=max(best,right-left+1)'],'O(n)','O(1)',
`class Solution { public int equalSubstring(String s,String t,int maxCost){int left=0,cost=0,best=0;for(int right=0;right<s.length();right++){cost+=Math.abs(s.charAt(right)-t.charAt(right));while(cost>maxCost){cost-=Math.abs(s.charAt(left)-t.charAt(left));left++;}best=Math.max(best,right-left+1);}return best;} }`,
`class Solution { fun equalSubstring(s:String,t:String,maxCost:Int):Int{var left=0;var cost=0;var best=0;for(right in s.indices){cost+=kotlin.math.abs(s[right]-t[right]);while(cost>maxCost){cost-=kotlin.math.abs(s[left]-t[left]);left++};best=maxOf(best,right-left+1)};return best} }`,
`class Solution { public: int equalSubstring(string s,string t,int maxCost){int left=0,cost=0,best=0;for(int right=0;right<(int)s.size();++right){cost+=abs(s[right]-t[right]);while(cost>maxCost)cost-=abs(s[left]-t[left]),++left;best=max(best,right-left+1);}return best;} };`)],tests:{schemaVersion:1,mode:'function',method:'equalSubstring',parameterTypes:['string','string','int'],returnType:'int',cases:[{name:'预算十覆盖三位',args:['abcd','bcdf',3],expected:3},{name:'预算三覆盖一位',args:['abcd','cdef',3],expected:1},{name:'零代价相同后缀',args:['abcd','acde',0],expected:1}]}},

{id:1209,slug:'remove-all-adjacent-duplicates-in-string-ii',title:'删除字符串中的所有相邻重复项 II',studyTags:['字符串','栈','计数'],summary:'反复删除字符串中相邻的 k 个相同字母，返回无法继续删除后的字符串。',insight:'把结果本身当栈，并为每个栈位置记录以该字符结尾的连续长度；新字符使长度达到 k 时立刻从栈尾删去 k 项，后续字符会自然与删除前缀重新相邻。',pitfalls:['删除可能引发跨边界级联','计数对应当前结果栈位置而非原串下标','k 至少为二'],solutions:[s('character-stack-with-run-count','字符栈与连续计数','在构造结果时即时消除达到 k 的尾部字符组。',['创建 StringBuilder stack 与长度为 s.length 的 counts','追加 ch 后，若前一栈顶相同则 count=前一位置+1，否则为一','若当前 count==k，将 StringBuilder 尾部 k 字符删除；扫描完返回栈字符串'],'O(n)','O(n)',
`class Solution { public String removeDuplicates(String s,int k){StringBuilder stack=new StringBuilder();int[] counts=new int[s.length()];for(char ch:s.toCharArray()){int index=stack.length();counts[index]=index>0&&stack.charAt(index-1)==ch?counts[index-1]+1:1;stack.append(ch);if(counts[index]==k)stack.delete(stack.length()-k,stack.length());}return stack.toString();} }`,
`class Solution { fun removeDuplicates(s:String,k:Int):String{val stack=StringBuilder();val counts=IntArray(s.length);for(ch in s){val index=stack.length;counts[index]=if(index>0&&stack[index-1]==ch)counts[index-1]+1 else 1;stack.append(ch);if(counts[index]==k)stack.delete(stack.length-k,stack.length)};return stack.toString()} }`,
`class Solution { public: string removeDuplicates(string s,int k){vector<pair<char,int>> stack;for(char ch:s){int count=!stack.empty()&&stack.back().first==ch?stack.back().second+1:1;stack.push_back({ch,count});if(count==k)for(int i=0;i<k;++i)stack.pop_back();}string answer;for(auto [ch,count]:stack)answer+=ch;return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'removeDuplicates',parameterTypes:['string','int'],returnType:'string',cases:[{name:'没有三连不删除',args:['abcd',2],expected:'abcd'},{name:'经典级联删除',args:['deeedbbcccbdaa',3],expected:'aa'},{name:'连续九个 p',args:['pbbcggttciiippooaais',2],expected:'ps'}]}},

{id:1210,slug:'minimum-moves-to-reach-target-with-rotations',title:'穿过迷宫的最少移动次数',studyTags:['数组','广度优先搜索','状态图','矩阵'],summary:'两格长蛇从左上横放出发，可平移或在空的二乘二区域旋转，求到右下目标横放状态的最少移动数。',insight:'状态由蛇包围盒左上坐标和方向唯一确定。所有操作代价为一，对这些状态做 BFS；按方向检查前方一格或二乘二区域即可生成合法后继。',pitfalls:['横向状态坐标表示左端，纵向表示上端','旋转要求对应二乘二方格的另外两格都为空','访问标记必须包含方向'],solutions:[s('orientation-state-bfs','方向状态广度优先搜索','在位置与横纵方向组成的无权状态图上求最短路。',['队列放 [0,0,横向,0]，seen[row][col][direction]','横向可向右；若下方两格空可向下且可顺时针旋转。纵向可向下；若右侧两格空可向右且可逆时针旋转','每个未访问合法状态以 distance+1 入队，首次到 [n-1,n-2,横向] 返回距离，耗尽返回 -1'],'O(n²)','O(n²)',
`class Solution { public int minimumMoves(int[][] grid){int n=grid.length;Queue<int[]> queue=new ArrayDeque<>();boolean[][][] seen=new boolean[n][n][2];queue.offer(new int[]{0,0,0,0});seen[0][0][0]=true;while(!queue.isEmpty()){int[] state=queue.poll();int r=state[0],c=state[1],orientation=state[2],distance=state[3];if(r==n-1&&c==n-2&&orientation==0)return distance;if(orientation==0){if(c+2<n&&grid[r][c+2]==0)add(queue,seen,r,c+1,0,distance+1);if(r+1<n&&grid[r+1][c]==0&&grid[r+1][c+1]==0){add(queue,seen,r+1,c,0,distance+1);add(queue,seen,r,c,1,distance+1);}}else{if(r+2<n&&grid[r+2][c]==0)add(queue,seen,r+1,c,1,distance+1);if(c+1<n&&grid[r][c+1]==0&&grid[r+1][c+1]==0){add(queue,seen,r,c+1,1,distance+1);add(queue,seen,r,c,0,distance+1);}}}return -1;}private void add(Queue<int[]> queue,boolean[][][] seen,int r,int c,int orientation,int distance){if(!seen[r][c][orientation]){seen[r][c][orientation]=true;queue.offer(new int[]{r,c,orientation,distance});}} }`,
`class Solution { fun minimumMoves(grid:Array<IntArray>):Int{val n=grid.size;val queue=java.util.ArrayDeque<IntArray>();val seen=Array(n){Array(n){BooleanArray(2)}};fun add(r:Int,c:Int,orientation:Int,distance:Int){if(!seen[r][c][orientation]){seen[r][c][orientation]=true;queue.addLast(intArrayOf(r,c,orientation,distance))}};add(0,0,0,0);while(queue.isNotEmpty()){val state=queue.removeFirst();val r=state[0];val c=state[1];val orientation=state[2];val distance=state[3];if(r==n-1&&c==n-2&&orientation==0)return distance;if(orientation==0){if(c+2<n&&grid[r][c+2]==0)add(r,c+1,0,distance+1);if(r+1<n&&grid[r+1][c]==0&&grid[r+1][c+1]==0){add(r+1,c,0,distance+1);add(r,c,1,distance+1)}}else{if(r+2<n&&grid[r+2][c]==0)add(r+1,c,1,distance+1);if(c+1<n&&grid[r][c+1]==0&&grid[r+1][c+1]==0){add(r,c+1,1,distance+1);add(r,c,0,distance+1)}}};return -1} }`,
`class Solution { public: int minimumMoves(vector<vector<int>>& grid){int n=grid.size();queue<array<int,4>> pending;vector<vector<array<bool,2>>> seen(n,vector<array<bool,2>>(n,{false,false}));auto add=[&](int r,int c,int orientation,int distance){if(!seen[r][c][orientation]){seen[r][c][orientation]=true;pending.push({r,c,orientation,distance});}};add(0,0,0,0);while(!pending.empty()){auto state=pending.front();pending.pop();int r=state[0],c=state[1],orientation=state[2],distance=state[3];if(r==n-1&&c==n-2&&!orientation)return distance;if(!orientation){if(c+2<n&&!grid[r][c+2])add(r,c+1,0,distance+1);if(r+1<n&&!grid[r+1][c]&&!grid[r+1][c+1]){add(r+1,c,0,distance+1);add(r,c,1,distance+1);}}else{if(r+2<n&&!grid[r+2][c])add(r+1,c,1,distance+1);if(c+1<n&&!grid[r][c+1]&&!grid[r+1][c+1]){add(r,c+1,1,distance+1);add(r,c,0,distance+1);}}}return -1;} };`)],tests:{schemaVersion:1,mode:'function',method:'minimumMoves',parameterTypes:['intMatrix'],returnType:'int',cases:[{name:'经典六阶迷宫',args:[[[0,0,0,0,0,1],[1,1,0,0,1,0],[0,0,0,0,1,1],[0,0,1,0,1,0],[0,1,1,0,0,0],[0,1,1,0,0,0]]],expected:11},{name:'二阶直接下移',args:[[[0,0],[0,0]]],expected:1},{name:'目标格被阻塞',args:[[[0,0],[1,0]]],expected:-1}]}}
]}
