const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-019',problems:[
{id:1383,slug:'maximum-performance-of-a-team',title:'最大的团队表现值',studyTags:['数组','贪心','排序','堆（优先队列）'],summary:'从 n 位工程师中选择最多 k 人，团队表现为速度和乘最低效率，求最大表现值取模。',insight:'按效率降序处理时，当前工程师就是所选团队效率下界；维护此前速度最大的至多 k 人，用最小堆及时移除最小速度。',pitfalls:['最大值比较必须在取模前完成','速度和及乘积使用 long','先加入当前工程师再把人数缩到 k'],solutions:[s('efficiency-sweep-min-heap','效率降序与速度小根堆','枚举最低效率并让同一阈值下速度和最大。',['将工程师按 efficiency 降序排序','扫描时把 speed 加入最小堆和 sum，堆超过 k 就移除最小速度','用 sum*当前 efficiency 更新最大值，最后取模'],'O(n log n+n log k)','O(n)',
`class Solution { public int maxPerformance(int n,int[] speed,int[] efficiency,int k){int[][] engineers=new int[n][2];for(int i=0;i<n;i++)engineers[i]=new int[]{efficiency[i],speed[i]};Arrays.sort(engineers,(a,b)->Integer.compare(b[0],a[0]));PriorityQueue<Integer> heap=new PriorityQueue<>();long sum=0,answer=0;for(int[] engineer:engineers){heap.offer(engineer[1]);sum+=engineer[1];if(heap.size()>k)sum-=heap.poll();answer=Math.max(answer,sum*engineer[0]);}return (int)(answer%1_000_000_007L);} }`,
`class Solution { fun maxPerformance(n:Int,speed:IntArray,efficiency:IntArray,k:Int):Int{val order=(0 until n).sortedByDescending{efficiency[it]};val heap=java.util.PriorityQueue<Int>();var sum=0L;var answer=0L;for(index in order){heap.add(speed[index]);sum+=speed[index];if(heap.size>k)sum-=heap.remove();answer=maxOf(answer,sum*efficiency[index])};return (answer%1_000_000_007L).toInt()} }`,
`class Solution { public: int maxPerformance(int n,vector<int>& speed,vector<int>& efficiency,int k){vector<int> order(n);iota(order.begin(),order.end(),0);sort(order.begin(),order.end(),[&](int a,int b){return efficiency[a]>efficiency[b];});priority_queue<int,vector<int>,greater<int>> heap;long long sum=0,answer=0;for(int index:order){heap.push(speed[index]);sum+=speed[index];if((int)heap.size()>k){sum-=heap.top();heap.pop();}answer=max(answer,sum*efficiency[index]);}return answer%1000000007;} };`)],tests:{schemaVersion:1,mode:'function',method:'maxPerformance',parameterTypes:['int','intArray','intArray','int'],returnType:'int',cases:[{name:'最多两人表现六十',args:[6,[2,10,3,1,5,8],[5,4,3,9,7,2],2],expected:60},{name:'最多三人表现六十八',args:[6,[2,10,3,1,5,8],[5,4,3,9,7,2],3],expected:68},{name:'最多四人表现七十二',args:[6,[2,10,3,1,5,8],[5,4,3,9,7,2],4],expected:72}]}},
{id:1385,slug:'find-the-distance-value-between-two-arrays',title:'两个数组间的距离值',studyTags:['数组','二分查找','排序'],summary:'统计 arr1 中有多少元素与 arr2 的每个元素之差绝对值都大于 d。',insight:'排序 arr2 后，对 arr1 的每个值二分其插入位置；距离最近的候选只可能是插入位置及其前一个元素。',pitfalls:['条件要求对 arr2 所有元素都大于 d','检查二分位置左右两个邻居','相等元素距离为零必不合法'],solutions:[s('sorted-neighbor-search','排序后二分邻居','用有序数组中相邻候选判断最近距离。',['排序 arr2','对每个 value 二分 lowerBound','若右邻或左邻距离不超过 d 则无效，否则计数'],'O(m log m+n log m)','O(log m)',
`class Solution { private int lowerBound(int[] values,int target){int left=0,right=values.length;while(left<right){int middle=left+(right-left)/2;if(values[middle]<target)left=middle+1;else right=middle;}return left;}public int findTheDistanceValue(int[] arr1,int[] arr2,int d){Arrays.sort(arr2);int answer=0;for(int value:arr1){int index=lowerBound(arr2,value);boolean close=index<arr2.length&&Math.abs(arr2[index]-value)<=d||index>0&&Math.abs(arr2[index-1]-value)<=d;if(!close)answer++;}return answer;} }`,
`class Solution { fun findTheDistanceValue(arr1:IntArray,arr2:IntArray,d:Int):Int{arr2.sort();var answer=0;for(value in arr1){val found=arr2.binarySearch(value);val index=if(found>=0)found else -found-1;val close=index<arr2.size&&kotlin.math.abs(arr2[index]-value)<=d||index>0&&kotlin.math.abs(arr2[index-1]-value)<=d;if(!close)answer++};return answer} }`,
`class Solution { public: int findTheDistanceValue(vector<int>& arr1,vector<int>& arr2,int d){sort(arr2.begin(),arr2.end());int answer=0;for(int value:arr1){auto it=lower_bound(arr2.begin(),arr2.end(),value);bool close=it!=arr2.end()&&abs(*it-value)<=d||it!=arr2.begin()&&abs(*prev(it)-value)<=d;if(!close)++answer;}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'findTheDistanceValue',parameterTypes:['intArray','intArray','int'],returnType:'int',cases:[{name:'三个值中两个满足距离',args:[[4,5,8],[10,9,1,8],2],expected:2},{name:'第二个经典示例',args:[[1,4,2,3],[-4,-3,6,10,20,30],3],expected:2},{name:'精确相同均无效',args:[[1,2],[1,2],0],expected:0}]}},
{id:1386,slug:'cinema-seat-allocation',title:'安排电影院座位',studyTags:['数组','哈希表','位运算','贪心'],summary:'每排十座，四人家庭只能坐 2-5、4-7 或 6-9，给定已预订座位，求最多可安排家庭数。',insight:'只有 2 到 9 号座位影响安排。未受影响的每排可坐两家；受影响行用位掩码检查左、中、右三段，左右都空可坐两家，否则任一段空可坐一家。',pitfalls:['一号和十号座位不影响家庭区块','中间区块与左右都重叠，不能和任一同时安排','只把有相关预订的行计入哈希表'],solutions:[s('reserved-row-bitmasks','预订行位掩码','稀疏记录受影响行并常数时间判断三个区块。',['为每个 2..9 号预订座位设置对应行 mask 位','answer=(n-affectedRows)*2','逐受影响行判断 left、middle、right 是否为空；左右都空加二，否则任一为空加一'],'O(r)','O(r)',
`class Solution { public int maxNumberOfFamilies(int n,int[][] reservedSeats){Map<Integer,Integer> rows=new HashMap<>();for(int[] seat:reservedSeats)if(seat[1]>=2&&seat[1]<=9)rows.merge(seat[0],1<<seat[1],(a,b)->a|b);int answer=(n-rows.size())*2;int left=0,middle=0,right=0;for(int seat=2;seat<=5;seat++)left|=1<<seat;for(int seat=4;seat<=7;seat++)middle|=1<<seat;for(int seat=6;seat<=9;seat++)right|=1<<seat;for(int mask:rows.values()){boolean leftFree=(mask&left)==0,middleFree=(mask&middle)==0,rightFree=(mask&right)==0;if(leftFree&&rightFree)answer+=2;else if(leftFree||middleFree||rightFree)answer++;}return answer;} }`,
`class Solution { fun maxNumberOfFamilies(n:Int,reservedSeats:Array<IntArray>):Int{val rows=mutableMapOf<Int,Int>();for(seat in reservedSeats)if(seat[1] in 2..9)rows[seat[0]]=(rows[seat[0]]?:0)or(1 shl seat[1]);var left=0;var middle=0;var right=0;for(seat in 2..5)left=left or(1 shl seat);for(seat in 4..7)middle=middle or(1 shl seat);for(seat in 6..9)right=right or(1 shl seat);var answer=(n-rows.size)*2;for(mask in rows.values){val leftFree=mask and left==0;val middleFree=mask and middle==0;val rightFree=mask and right==0;if(leftFree&&rightFree)answer+=2 else if(leftFree||middleFree||rightFree)answer++};return answer} }`,
`class Solution { public: int maxNumberOfFamilies(int n,vector<vector<int>>& reservedSeats){unordered_map<int,int> rows;for(auto& seat:reservedSeats)if(seat[1]>=2&&seat[1]<=9)rows[seat[0]]|=1<<seat[1];int left=0,middle=0,right=0;for(int seat=2;seat<=5;++seat)left|=1<<seat;for(int seat=4;seat<=7;++seat)middle|=1<<seat;for(int seat=6;seat<=9;++seat)right|=1<<seat;int answer=(n-rows.size())*2;for(auto [row,mask]:rows){bool leftFree=!(mask&left),middleFree=!(mask&middle),rightFree=!(mask&right);if(leftFree&&rightFree)answer+=2;else if(leftFree||middleFree||rightFree)++answer;}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'maxNumberOfFamilies',parameterTypes:['int','intMatrix'],returnType:'int',cases:[{name:'三排经典预订可坐四家',args:[3,[[1,2],[1,3],[1,8],[2,6],[3,1],[3,10]]],expected:4},{name:'两排预订可坐两家',args:[2,[[2,1],[1,8],[2,6]]],expected:2},{name:'四排无预订',args:[4,[]],expected:8}]}},
{id:1387,slug:'sort-integers-by-the-power-value',title:'将整数按权重排序',studyTags:['动态规划','记忆化','排序'],summary:'整数 x 的权重是按 Collatz 规则变为一所需步数；将 [lo,hi] 按权重和数值排序，返回第 k 个。',insight:'递归计算 power(x)，用哈希表缓存中间结果；排序键为（权重, 数值）。',pitfalls:['权重相同时按数值升序','区间端点都包含','缓存一的权重为零'],solutions:[s('memoized-collatz-sort','记忆化权重排序','复用 Collatz 链上已经计算的后缀步数。',['memo[1]=0，power(x)=1+power(x/2 或 3x+1)','生成 lo 到 hi 的整数列表','按 power、value 升序排序并返回索引 k-1'],'O(R log R+链长)','O(R+链上状态)',
`class Solution { private final Map<Integer,Integer> memo=new HashMap<>();private int power(int value){if(value==1)return 0;if(memo.containsKey(value))return memo.get(value);int answer=1+power(value%2==0?value/2:3*value+1);memo.put(value,answer);return answer;}public int getKth(int lo,int hi,int k){List<Integer> values=new ArrayList<>();for(int value=lo;value<=hi;value++)values.add(value);values.sort(Comparator.comparingInt((Integer value)->power(value)).thenComparingInt(value->value));return values.get(k-1);} }`,
`class Solution { private val memo=mutableMapOf(1 to 0);private fun power(value:Int):Int=memo.getOrPut(value){1+power(if(value%2==0)value/2 else 3*value+1)};fun getKth(lo:Int,hi:Int,k:Int):Int=(lo..hi).sortedWith(compareBy<Int>{power(it)}.thenBy{it})[k-1] }`,
`class Solution { unordered_map<int,int> memo{{1,0}};int power(int value){if(memo.count(value))return memo[value];return memo[value]=1+power(value%2==0?value/2:3*value+1);}public:int getKth(int lo,int hi,int k){vector<int> values(hi-lo+1);iota(values.begin(),values.end(),lo);sort(values.begin(),values.end(),[&](int a,int b){int pa=power(a),pb=power(b);return pa==pb?a<b:pa<pb;});return values[k-1];} };`)],tests:{schemaVersion:1,mode:'function',method:'getKth',parameterTypes:['int','int','int'],returnType:'int',cases:[{name:'十二到十五第二个为十三',args:[12,15,2],expected:13},{name:'七到十一第四个为七',args:[7,11,4],expected:7},{name:'单个一',args:[1,1,1],expected:1}]}},
{id:1388,slug:'pizza-with-3n-slices',title:'三的倍数份披萨',studyTags:['数组','动态规划'],summary:'环形披萨有 3n 块，每轮选择一块后相邻两块被他人拿走，求自己选 n 块可获得的最大总和。',insight:'等价于环上选择 n 个互不相邻元素。环形约束拆成不选末块与不选首块两个线性问题，每个用恰选 j 个非相邻元素的动态规划。',pitfalls:['必须恰好选择总长度三分之一块','首尾相邻，需拆为两个线性区间','不可达的 DP 状态要设为负无穷'],solutions:[s('two-linear-nonadjacent-dp','两段线性不相邻动态规划','分别排除环首或环尾并求线性最优。',['picks=slices.length/3','solve(start,end)：dp[i][j] 表示前 i 项恰选 j 项最大和，转移跳过或从 i-2 取','返回 max(solve(0,n-2),solve(1,n-1))'],'O(n²)','O(n²)',
`class Solution { private int solve(int[] slices,int start,int end,int picks){int length=end-start+1,negative=-1_000_000_000;int[][] dp=new int[length+1][picks+1];for(int[] row:dp)Arrays.fill(row,negative);for(int i=0;i<=length;i++)dp[i][0]=0;for(int i=1;i<=length;i++)for(int chosen=1;chosen<=picks;chosen++){dp[i][chosen]=dp[i-1][chosen];int previous=dp[Math.max(0,i-2)][chosen-1];if(previous!=negative)dp[i][chosen]=Math.max(dp[i][chosen],previous+slices[start+i-1]);}return dp[length][picks];}public int maxSizeSlices(int[] slices){int picks=slices.length/3;return Math.max(solve(slices,0,slices.length-2,picks),solve(slices,1,slices.length-1,picks));} }`,
`class Solution { private fun solve(slices:IntArray,start:Int,end:Int,picks:Int):Int{val length=end-start+1;val negative=-1_000_000_000;val dp=Array(length+1){IntArray(picks+1){negative}};for(i in 0..length)dp[i][0]=0;for(i in 1..length)for(chosen in 1..picks){dp[i][chosen]=dp[i-1][chosen];val previous=dp[maxOf(0,i-2)][chosen-1];if(previous!=negative)dp[i][chosen]=maxOf(dp[i][chosen],previous+slices[start+i-1])};return dp[length][picks]};fun maxSizeSlices(slices:IntArray):Int{val picks=slices.size/3;return maxOf(solve(slices,0,slices.size-2,picks),solve(slices,1,slices.size-1,picks))} }`,
`class Solution { int solve(vector<int>& slices,int start,int end,int picks){int length=end-start+1,negative=-1000000000;vector<vector<int>> dp(length+1,vector<int>(picks+1,negative));for(int i=0;i<=length;++i)dp[i][0]=0;for(int i=1;i<=length;++i)for(int chosen=1;chosen<=picks;++chosen){dp[i][chosen]=dp[i-1][chosen];int previous=dp[max(0,i-2)][chosen-1];if(previous!=negative)dp[i][chosen]=max(dp[i][chosen],previous+slices[start+i-1]);}return dp[length][picks];}public:int maxSizeSlices(vector<int>& slices){int picks=slices.size()/3;return max(solve(slices,0,slices.size()-2,picks),solve(slices,1,slices.size()-1,picks));} };`)],tests:{schemaVersion:1,mode:'function',method:'maxSizeSlices',parameterTypes:['intArray'],returnType:'int',cases:[{name:'递增六块取十',args:[[1,2,3,4,5,6]],expected:10},{name:'两个八可同时选择',args:[[8,9,8,6,1,1]],expected:16},{name:'九块经典示例',args:[[4,1,2,5,8,3,1,9,7]],expected:21}]}}
]}
