const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-008',problems:[
{id:594,slug:'longest-harmonious-subsequence',title:'最长和谐子序列',studyTags:['数组','哈希表','计数'],summary:'和谐数组的最大值和最小值恰好相差一，求原数组中最长和谐子序列长度。',insight:'子序列若和谐，只能由值 x 和 x+1 的全部出现项组成；统计频次后枚举相邻值对即可。',pitfalls:['必须同时存在两个不同且相差一的值','子序列不要求连续','只有同一个值时答案为零'],solutions:[s('frequency-neighbor-pairs','统计相邻值频次和','枚举哈希表中的每个值并与后一整数的频次合并。',['统计每个整数出现次数','对每个 value 检查 value+1 是否存在','存在时用两者频次之和更新答案'],'O(n)','O(n)',
`class Solution { public int findLHS(int[] nums){Map<Integer,Integer> counts=new HashMap<>();for(int value:nums)counts.put(value,counts.getOrDefault(value,0)+1);int best=0;for(Map.Entry<Integer,Integer> entry:counts.entrySet())if(counts.containsKey(entry.getKey()+1))best=Math.max(best,entry.getValue()+counts.get(entry.getKey()+1));return best;} }`,
`class Solution { fun findLHS(nums:IntArray):Int{val counts=hashMapOf<Int,Int>();for(value in nums)counts[value]=(counts[value]?:0)+1;var best=0;for((value,count) in counts){val next=counts[value+1];if(next!=null)best=maxOf(best,count+next)};return best} }`,
`class Solution { public: int findLHS(vector<int>& nums){unordered_map<int,int> counts;for(int value:nums)++counts[value];int best=0;for(auto [value,count]:counts)if(counts.count(value+1))best=max(best,count+counts[value+1]);return best;} };`)],tests:{schemaVersion:1,mode:'function',method:'findLHS',parameterTypes:['intArray'],returnType:'int',cases:[{name:'经典频次组合',args:[[1,3,2,2,5,2,3,7]],expected:5},{name:'每值只出现一次',args:[[1,2,3,4]],expected:2},{name:'只有一种值',args:[[1,1,1,1]],expected:0}]}},
{id:598,slug:'range-addition-ii',title:'范围求和 II',studyTags:['数组','数学','区间交集'],summary:'对 m×n 零矩阵执行若干左上角矩形加一操作，求最终最大元素的个数。',insight:'所有操作都覆盖的矩形元素被增加次数最多，其尺寸是所有操作行列范围的分别最小值。',pitfalls:['操作数组为空时整个矩阵都是最大值','每个操作范围从坐标零开始','只需维护行列最小边界而无需模拟矩阵'],solutions:[s('rectangle-intersection','求所有操作矩形交集','最大值区域就是所有左上矩形的公共交集。',['minimumRow=m、minimumColumn=n','遍历操作分别缩小两条边界','返回 minimumRow*minimumColumn'],'O(k)','O(1)',
`class Solution { public int maxCount(int m,int n,int[][] ops){int rows=m,columns=n;for(int[] operation:ops){rows=Math.min(rows,operation[0]);columns=Math.min(columns,operation[1]);}return rows*columns;} }`,
`class Solution { fun maxCount(m:Int,n:Int,ops:Array<IntArray>):Int{var rows=m;var columns=n;for(operation in ops){rows=minOf(rows,operation[0]);columns=minOf(columns,operation[1])};return rows*columns} }`,
`class Solution { public: int maxCount(int m,int n,vector<vector<int>>& ops){int rows=m,columns=n;for(auto& operation:ops){rows=min(rows,operation[0]);columns=min(columns,operation[1]);}return rows*columns;} };`)],tests:{schemaVersion:1,mode:'function',method:'maxCount',parameterTypes:['int','int','intMatrix'],returnType:'int',cases:[{name:'两个范围取交集',args:[3,3,[[2,2],[3,3]]],expected:4},{name:'没有操作',args:[3,3,[]],expected:9},{name:'单行交集',args:[4,5,[[3,4],[1,5],[2,2]]],expected:2}]}},
{id:599,slug:'minimum-index-sum-of-two-lists',title:'两个列表的最小索引总和',studyTags:['数组','哈希表','字符串'],summary:'两个无重复餐厅列表按喜好排序，找出在两列表中索引和最小的所有共同餐厅。',insight:'记录第一列表每个名称的索引，再扫描第二列表即可在线比较共同名称的索引和。',pitfalls:['可能有多个并列最优餐厅','只返回两个列表都出现的名称','结果顺序不影响原题判定'],solutions:[s('index-map-scan','索引哈希表与单次扫描','用第一列表索引表快速计算第二列表中共同项的索引和。',['建立 restaurant→index 映射','扫描 list2，遇共同项计算 indexSum','更小时清空结果，相等时追加，最终转数组'],'O(m+n)','O(m)',
`class Solution { public String[] findRestaurant(String[] list1,String[] list2){Map<String,Integer> indices=new HashMap<>();for(int i=0;i<list1.length;i++)indices.put(list1[i],i);List<String> answer=new ArrayList<>();int best=Integer.MAX_VALUE;for(int i=0;i<list2.length;i++){Integer first=indices.get(list2[i]);if(first==null)continue;int sum=first+i;if(sum<best){best=sum;answer.clear();answer.add(list2[i]);}else if(sum==best)answer.add(list2[i]);}return answer.toArray(new String[0]);} }`,
`class Solution { fun findRestaurant(list1:Array<String>,list2:Array<String>):Array<String>{val indices=list1.withIndex().associate{it.value to it.index};val answer=mutableListOf<String>();var best=Int.MAX_VALUE;for((index,name) in list2.withIndex()){val first=indices[name]?:continue;val sum=first+index;if(sum<best){best=sum;answer.clear();answer.add(name)}else if(sum==best)answer.add(name)};return answer.toTypedArray()} }`,
`class Solution { public: vector<string> findRestaurant(vector<string>& list1,vector<string>& list2){unordered_map<string,int> indices;for(int i=0;i<(int)list1.size();++i)indices[list1[i]]=i;vector<string> answer;int best=INT_MAX;for(int i=0;i<(int)list2.size();++i)if(indices.count(list2[i])){int sum=indices[list2[i]]+i;if(sum<best){best=sum;answer.clear();answer.push_back(list2[i]);}else if(sum==best)answer.push_back(list2[i]);}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'findRestaurant',parameterTypes:['stringArray','stringArray'],returnType:'stringArray',cases:[{name:'唯一共同首选',args:[['Shogun','Tapioca Express','Burger King','KFC'],['KFC','Shogun','Burger King']],expected:['Shogun']},{name:'列表完全相同',args:[['happy','sad','good'],['happy','sad','good']],expected:['happy']},{name:'两个并列答案',args:[['a','b'],['b','a']],expected:['b','a']}]}},
{id:600,slug:'non-negative-integers-without-consecutive-ones',title:'不含连续 1 的非负整数',studyTags:['动态规划','数位 DP','位运算'],summary:'给定非负整数 n，统计区间 [0,n] 中二进制表示不含连续两个 1 的整数数量。',insight:'长度为 k 的合法二进制后缀数量满足斐波那契递推；从高位扫描 n，遇到 1 时累计把该位改成 0 的所有合法数。',pitfalls:['需要把零计入答案','连续遇到两个 1 时后续无需再扫描','最终 n 本身合法时要额外加一'],solutions:[s('fibonacci-bit-dp','斐波那契位计数','预计算合法后缀数量并沿 n 的二进制前缀累加。',['fib[0]=1、fib[1]=2 并递推','从高位到低位，遇 1 加 fib[bit]','若前一位也是 1 则立即返回，否则扫描结束返回 answer+1'],'O(log n)','O(log n)',
`class Solution { public int findIntegers(int n){int[] fib=new int[31];fib[0]=1;fib[1]=2;for(int i=2;i<31;i++)fib[i]=fib[i-1]+fib[i-2];int answer=0,previous=0;for(int bit=30;bit>=0;bit--){if((n&(1<<bit))!=0){answer+=fib[bit];if(previous==1)return answer;previous=1;}else previous=0;}return answer+1;} }`,
`class Solution { fun findIntegers(n:Int):Int{val fib=IntArray(31);fib[0]=1;fib[1]=2;for(i in 2..30)fib[i]=fib[i-1]+fib[i-2];var answer=0;var previous=0;for(bit in 30 downTo 0){if(n and (1 shl bit)!=0){answer+=fib[bit];if(previous==1)return answer;previous=1}else previous=0};return answer+1} }`,
`class Solution { public: int findIntegers(int n){int fib[31]={1,2};for(int i=2;i<31;++i)fib[i]=fib[i-1]+fib[i-2];int answer=0,previous=0;for(int bit=30;bit>=0;--bit){if(n&(1<<bit)){answer+=fib[bit];if(previous)return answer;previous=1;}else previous=0;}return answer+1;} };`)],tests:{schemaVersion:1,mode:'function',method:'findIntegers',parameterTypes:['int'],returnType:'int',cases:[{name:'五以内合法数',args:[5],expected:5},{name:'上界为一',args:[1],expected:2},{name:'上界为二',args:[2],expected:3}]}},
{id:605,slug:'can-place-flowers',title:'种花问题',studyTags:['数组','贪心','模拟'],summary:'花坛中相邻位置不能同时种花，判断能否在现有布局中再种下 n 朵花。',insight:'从左到右遇到左右均为空的位置就立即种花，这个最早选择不会减少后续可用位置。',pitfalls:['边界外可视为空位','原有花朵之间保证不相邻','n 为零时必然可行'],solutions:[s('left-to-right-greedy','从左到右贪心种植','在每个当前合法空位种花并减少剩余需求。',['若 n=0 直接成功','扫描空位并检查左邻与右邻','合法时写入 1，n--；降到零即返回真，结束返回假'],'O(length)','O(1)',
`class Solution { public boolean canPlaceFlowers(int[] flowerbed,int n){if(n==0)return true;for(int i=0;i<flowerbed.length;i++)if(flowerbed[i]==0&&(i==0||flowerbed[i-1]==0)&&(i==flowerbed.length-1||flowerbed[i+1]==0)){flowerbed[i]=1;if(--n==0)return true;}return false;} }`,
`class Solution { fun canPlaceFlowers(flowerbed:IntArray,n:Int):Boolean{var remaining=n;if(remaining==0)return true;for(i in flowerbed.indices)if(flowerbed[i]==0&&(i==0||flowerbed[i-1]==0)&&(i==flowerbed.lastIndex||flowerbed[i+1]==0)){flowerbed[i]=1;if(--remaining==0)return true};return false} }`,
`class Solution { public: bool canPlaceFlowers(vector<int>& flowerbed,int n){if(n==0)return true;for(int i=0;i<(int)flowerbed.size();++i)if(flowerbed[i]==0&&(i==0||flowerbed[i-1]==0)&&(i+1==(int)flowerbed.size()||flowerbed[i+1]==0)){flowerbed[i]=1;if(--n==0)return true;}return false;} };`)],tests:{schemaVersion:1,mode:'function',method:'canPlaceFlowers',parameterTypes:['intArray','int'],returnType:'boolean',cases:[{name:'可以种一朵',args:[[1,0,0,0,1],1],expected:true},{name:'不能种两朵',args:[[1,0,0,0,1],2],expected:false},{name:'单空花坛',args:[[0],1],expected:true}]}}
]}
