const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-011',problems:[
{id:818,slug:'race-car',title:'赛车',studyTags:['动态规划','记忆化搜索','位运算'],summary:'赛车从位置零、速度一开始，A 指令按当前速度前进并把速度翻倍，R 指令原地反向并把速度重置为正负一，求到达 target 的最少指令数。',insight:'连续 n 次 A 到达 2^n-1；对目标可选择冲过后掉头，或先走 n-1 次再后退 m 次并继续解决剩余距离，记忆化比较所有方案。',pitfalls:['目标恰为 2^n-1 时直接用 n 次 A','欠冲方案的后退次数 m 从零到 n-2','每次 R 都计一条指令'],solutions:[s('binary-distance-memo-dp','二进制距离记忆化 DP','围绕最近的全加速位置枚举掉头策略。',['令 n 为最小满足 2^n-1>=target 的位数；若相等返回 n','超冲方案为 n+1+dp((2^n-1)-target)','欠冲到 2^(n-1)-1，掉头后后退 2^m-1，再掉头；枚举 m=0..n-2，代价 n+m+1+dp(target-(2^(n-1)-1)+(2^m-1))'],'O(target log target)','O(target)',
`class Solution { private Map<Integer,Integer> memo=new HashMap<>();public int racecar(int target){if(memo.containsKey(target))return memo.get(target);int n=32-Integer.numberOfLeadingZeros(target);if((1<<n)-1==target)return n;int answer=n+1+racecar((1<<n)-1-target);int forward=(1<<(n-1))-1;for(int m=0;m<n-1;m++){int backward=(1<<m)-1;answer=Math.min(answer,n+m+1+racecar(target-forward+backward));}memo.put(target,answer);return answer;} }`,
`class Solution { private val memo=mutableMapOf<Int,Int>();fun racecar(target:Int):Int{memo[target]?.let{return it};val n=32-Integer.numberOfLeadingZeros(target);if((1 shl n)-1==target)return n;var answer=n+1+racecar((1 shl n)-1-target);val forward=(1 shl(n-1))-1;for(m in 0 until n-1){val backward=(1 shl m)-1;answer=minOf(answer,n+m+1+racecar(target-forward+backward))};memo[target]=answer;return answer} }`,
`class Solution { unordered_map<int,int> memo;public:int racecar(int target){if(memo.count(target))return memo[target];int n=32-__builtin_clz(target);if((1<<n)-1==target)return n;int answer=n+1+racecar((1<<n)-1-target),forward=(1<<(n-1))-1;for(int m=0;m<n-1;++m){int backward=(1<<m)-1;answer=min(answer,n+m+1+racecar(target-forward+backward));}return memo[target]=answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'racecar',parameterTypes:['int'],returnType:'int',cases:[{name:'连续两次加速',args:[3],expected:2},{name:'目标六',args:[6],expected:5},{name:'目标一',args:[1],expected:1}]}},
{id:819,slug:'most-common-word',title:'最常见的单词',studyTags:['字符串','哈希表','计数'],summary:'忽略大小写和标点，返回段落中出现次数最多且不在禁用列表里的单词。',insight:'把禁用词放入集合，把段落转小写后按非字母切分，统计合法非空词并维护最高频。',pitfalls:['标点和空白都可作为分隔符','比较时不区分大小写','切分结果可能含空字符串'],solutions:[s('normalized-word-frequency','规范化词频统计','一次扫描切词并统计非禁用词。',['构建 bannedSet','paragraph 转小写并按非字母正则切分','跳过空词和禁用词，递增频次；严格超过最高值时更新答案'],'O(n)','O(vocabulary)',
`class Solution { public String mostCommonWord(String paragraph,String[] banned){Set<String> blocked=new HashSet<>(Arrays.asList(banned));Map<String,Integer> frequency=new HashMap<>();String answer="";int best=0;for(String word:paragraph.toLowerCase().split("[^a-z]+")){if(word.isEmpty()||blocked.contains(word))continue;int count=frequency.merge(word,1,Integer::sum);if(count>best){best=count;answer=word;}}return answer;} }`,
`class Solution { fun mostCommonWord(paragraph:String,banned:Array<String>):String{val blocked=banned.toSet();val frequency=mutableMapOf<String,Int>();var answer="";var best=0;for(word in paragraph.lowercase().split(Regex("[^a-z]+"))){if(word.isEmpty()||word in blocked)continue;val count=(frequency[word]?:0)+1;frequency[word]=count;if(count>best){best=count;answer=word}};return answer} }`,
`class Solution { public: string mostCommonWord(string paragraph,vector<string>& banned){unordered_set<string> blocked(banned.begin(),banned.end());unordered_map<string,int> frequency;string answer,word;int best=0;paragraph+=' ';for(char c:paragraph){if(isalpha(c))word+=tolower(c);else if(!word.empty()){if(!blocked.count(word)&&++frequency[word]>best){best=frequency[word];answer=word;}word.clear();}}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'mostCommonWord',parameterTypes:['string','stringArray'],returnType:'string',cases:[{name:'标点与禁用词',args:['Bob hit a ball, the hit BALL flew far after it was hit.',['hit']],expected:'ball'},{name:'单词后有标点',args:['a.',['']],expected:'a'},{name:'忽略大小写',args:['Cat cat dog.',['dog']],expected:'cat'}]}},
{id:820,slug:'short-encoding-of-words',title:'单词的压缩编码',studyTags:['数组','字符串','哈希集合','字典树'],summary:'用一个以井号分隔的字符串编码所有单词，使每个单词都是某个井号前缀段的后缀，求最短编码长度。',insight:'如果一个单词是另一单词的后缀，就无需单独编码；从集合中删除每个单词的所有真后缀，剩余词各贡献长度加一。',pitfalls:['重复单词只编码一次','只删除从下标一开始的真后缀，不能删除单词自身','每个保留词还要计一个井号'],solutions:[s('remove-all-proper-suffixes','集合删除真后缀','保留不属于任何更长单词后缀的词。',['把所有 words 放入集合去重','对每个原单词，依次删除 substring(1),substring(2)...','累加集合中每个词 length+1'],'O(total length²)','O(total length)',
`class Solution { public int minimumLengthEncoding(String[] words){Set<String> remaining=new HashSet<>(Arrays.asList(words));for(String word:words)for(int start=1;start<word.length();start++)remaining.remove(word.substring(start));int answer=0;for(String word:remaining)answer+=word.length()+1;return answer;} }`,
`class Solution { fun minimumLengthEncoding(words:Array<String>):Int{val remaining=words.toMutableSet();for(word in words)for(start in 1 until word.length)remaining.remove(word.substring(start));return remaining.sumOf{it.length+1}} }`,
`class Solution { public: int minimumLengthEncoding(vector<string>& words){unordered_set<string> remaining(words.begin(),words.end());for(string& word:words)for(int start=1;start<(int)word.size();++start)remaining.erase(word.substr(start));int answer=0;for(string word:remaining)answer+=word.size()+1;return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'minimumLengthEncoding',parameterTypes:['stringArray'],returnType:'int',cases:[{name:'me 是 time 后缀',args:[['time','me','bell']],expected:10},{name:'单字母',args:[['t']],expected:2},{name:'重复和后缀',args:[['time','time','me']],expected:5}]}},
{id:821,slug:'shortest-distance-to-a-character',title:'字符的最短距离',studyTags:['数组','字符串','双向扫描'],summary:'字符串中目标字符至少出现一次，返回每个位置到最近目标字符的距离。',insight:'从左到右记录最近左侧目标，从右到左记录最近右侧目标，两者距离取最小。',pitfalls:['初始最近位置要用足够远的负值','右扫直接与已有左侧距离取最小','目标位置距离为零'],solutions:[s('two-direction-nearest-pass','左右两次最近位置扫描','分别传播最近目标字符的影响。',['左扫维护 previous，遇目标更新为 i，answer[i]=i-previous','右扫维护 next，遇目标更新为 i','answer[i]=min(answer[i],next-i)，返回数组'],'O(n)','O(n)',
`class Solution { public int[] shortestToChar(String s,char c){int n=s.length(),previous=-n;int[] answer=new int[n];for(int i=0;i<n;i++){if(s.charAt(i)==c)previous=i;answer[i]=i-previous;}int next=2*n;for(int i=n-1;i>=0;i--){if(s.charAt(i)==c)next=i;answer[i]=Math.min(answer[i],next-i);}return answer;} }`,
`class Solution { fun shortestToChar(s:String,c:Char):IntArray{val n=s.length;var previous=-n;val answer=IntArray(n);for(i in 0 until n){if(s[i]==c)previous=i;answer[i]=i-previous};var next=2*n;for(i in n-1 downTo 0){if(s[i]==c)next=i;answer[i]=minOf(answer[i],next-i)};return answer} }`,
`class Solution { public: vector<int> shortestToChar(string s,char c){int n=s.size(),previous=-n;vector<int> answer(n);for(int i=0;i<n;++i){if(s[i]==c)previous=i;answer[i]=i-previous;}int next=2*n;for(int i=n-1;i>=0;--i){if(s[i]==c)next=i;answer[i]=min(answer[i],next-i);}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'shortestToChar',parameterTypes:['string','char'],returnType:'intArray',cases:[{name:'多个 e 的距离',args:['loveleetcode','e'],expected:[3,2,1,0,1,0,0,1,2,2,1,0]},{name:'目标在开头',args:['aaab','b'],expected:[3,2,1,0]},{name:'单字符',args:['a','a'],expected:[0]}]}},
{id:822,slug:'card-flipping-game',title:'翻转卡片游戏',studyTags:['数组','哈希集合','枚举'],summary:'每张卡片有正反面数字，可任意翻转；求能让某数字出现在一张正面且不出现在任何背面的最小正整数，不存在返回零。',insight:'若一张卡正反相同，该值无论怎样翻都必在背面，是禁用值；其他出现在任一面的非禁用值都可通过翻转安排成候选。',pitfalls:['只需把 fronts[i]==backs[i] 的值禁用','候选可来自正面或背面','无候选时返回零'],solutions:[s('forbidden-equal-pairs-scan','等值卡片禁用集合','先找不可能值，再扫描两面取最小候选。',['建立 forbidden，加入所有 fronts[i]==backs[i] 的值','answer 初始化最大整数','扫描 fronts 和 backs，非 forbidden 值更新最小值；最终无候选返回零'],'O(n)','O(n)',
`class Solution { public int flipgame(int[] fronts,int[] backs){Set<Integer> forbidden=new HashSet<>();for(int i=0;i<fronts.length;i++)if(fronts[i]==backs[i])forbidden.add(fronts[i]);int answer=Integer.MAX_VALUE;for(int value:fronts)if(!forbidden.contains(value))answer=Math.min(answer,value);for(int value:backs)if(!forbidden.contains(value))answer=Math.min(answer,value);return answer==Integer.MAX_VALUE?0:answer;} }`,
`class Solution { fun flipgame(fronts:IntArray,backs:IntArray):Int{val forbidden=mutableSetOf<Int>();for(i in fronts.indices)if(fronts[i]==backs[i])forbidden.add(fronts[i]);var answer=Int.MAX_VALUE;for(value in fronts)if(value !in forbidden)answer=minOf(answer,value);for(value in backs)if(value !in forbidden)answer=minOf(answer,value);return if(answer==Int.MAX_VALUE)0 else answer} }`,
`class Solution { public: int flipgame(vector<int>& fronts,vector<int>& backs){unordered_set<int> forbidden;for(int i=0;i<(int)fronts.size();++i)if(fronts[i]==backs[i])forbidden.insert(fronts[i]);int answer=INT_MAX;for(int value:fronts)if(!forbidden.count(value))answer=min(answer,value);for(int value:backs)if(!forbidden.count(value))answer=min(answer,value);return answer==INT_MAX?0:answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'flipgame',parameterTypes:['intArray','intArray'],returnType:'int',cases:[{name:'经典最小值二',args:[[1,2,4,4,7],[1,3,4,1,3]],expected:2},{name:'唯一值被禁用',args:[[1],[1]],expected:0},{name:'互换两张卡',args:[[1,2],[2,1]],expected:1}]}}
]}
