const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-020',problems:[
{id:1401,slug:'circle-and-rectangle-overlapping',title:'圆和矩形是否有重叠',studyTags:['数学','几何'],summary:'判断给定圆与轴对齐矩形是否至少共享一个点。',insight:'把圆心分别钳制到矩形横纵坐标区间，得到矩形中离圆心最近的点；其距离不超过半径即重叠。',pitfalls:['边界相切也算重叠','圆心在矩形内时最近点就是圆心','平方距离避免开方误差'],solutions:[s('closest-point-clamping','最近点坐标钳制','计算圆心到矩形最近点的平方距离。',['closestX=min(max(xCenter,x1),x2)，纵坐标同理','dx=xCenter-closestX，dy=yCenter-closestY','返回 dx²+dy²<=radius²'],'O(1)','O(1)',
`class Solution { public boolean checkOverlap(int radius,int xCenter,int yCenter,int x1,int y1,int x2,int y2){int closestX=Math.max(x1,Math.min(xCenter,x2)),closestY=Math.max(y1,Math.min(yCenter,y2));long dx=xCenter-closestX,dy=yCenter-closestY;return dx*dx+dy*dy<=(long)radius*radius;} }`,
`class Solution { fun checkOverlap(radius:Int,xCenter:Int,yCenter:Int,x1:Int,y1:Int,x2:Int,y2:Int):Boolean{val closestX=xCenter.coerceIn(x1,x2);val closestY=yCenter.coerceIn(y1,y2);val dx=(xCenter-closestX).toLong();val dy=(yCenter-closestY).toLong();return dx*dx+dy*dy<=radius.toLong()*radius} }`,
`class Solution { public: bool checkOverlap(int radius,int xCenter,int yCenter,int x1,int y1,int x2,int y2){int closestX=clamp(xCenter,x1,x2),closestY=clamp(yCenter,y1,y2);long long dx=xCenter-closestX,dy=yCenter-closestY;return dx*dx+dy*dy<=1LL*radius*radius;} };`)],tests:{schemaVersion:1,mode:'function',method:'checkOverlap',parameterTypes:['int','int','int','int','int','int','int'],returnType:'boolean',cases:[{name:'圆与矩形边界相切',args:[1,0,0,1,-1,3,1],expected:true},{name:'矩形位于圆的斜上方',args:[1,0,0,2,2,3,3],expected:false},{name:'较大圆仍未触及矩形',args:[2,5,5,1,1,3,3],expected:false}]}},
{id:1402,slug:'reducing-dishes',title:'做菜顺序获得最大满意度',studyTags:['数组','贪心','排序'],summary:'可选择部分菜并安排顺序，第 i 道菜贡献 satisfaction×完成时刻，求最大总和。',insight:'排序后从满意度最高的菜逆向加入。若当前选菜总和为正，把新菜放到最前会让所有已选菜时刻加一，总收益增加该总和。',pitfalls:['可以完全不做负收益的菜','逆向累加的 suffix 必须为正才继续','排序改变的是烹饪顺序选择'],solutions:[s('positive-suffix-greedy','正后缀贪心','从高到低扩张被选后缀并累计每次整体时移收益。',['升序排序 satisfaction','从末尾向前更新 suffix+=value','suffix<=0 时停止，否则 answer+=suffix'],'O(n log n)','O(log n)',
`class Solution { public int maxSatisfaction(int[] satisfaction){Arrays.sort(satisfaction);int suffix=0,answer=0;for(int i=satisfaction.length-1;i>=0;i--){suffix+=satisfaction[i];if(suffix<=0)break;answer+=suffix;}return answer;} }`,
`class Solution { fun maxSatisfaction(satisfaction:IntArray):Int{satisfaction.sort();var suffix=0;var answer=0;for(i in satisfaction.lastIndex downTo 0){suffix+=satisfaction[i];if(suffix<=0)break;answer+=suffix};return answer} }`,
`class Solution { public: int maxSatisfaction(vector<int>& satisfaction){sort(satisfaction.begin(),satisfaction.end());int suffix=0,answer=0;for(int i=satisfaction.size()-1;i>=0;--i){suffix+=satisfaction[i];if(suffix<=0)break;answer+=suffix;}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'maxSatisfaction',parameterTypes:['intArray'],returnType:'int',cases:[{name:'经典混合满意度',args:[[-1,-8,0,5,-9]],expected:14},{name:'全正数全部选择',args:[[4,3,2]],expected:20},{name:'全负数不做菜',args:[[-1,-4,-5]],expected:0}]}},
{id:1403,slug:'minimum-subsequence-in-non-increasing-order',title:'非递增顺序的最小子序列',studyTags:['数组','贪心','排序'],summary:'选择长度最短的子序列，使其元素和严格大于未选元素和，并按非递增顺序返回。',insight:'为用最少元素达到超过一半总和，应贪心选择最大元素；降序累加直到 selected>total-selected。',pitfalls:['要求严格大于','相同最短长度下选择总和最大的方案','返回顺序必须非递增'],solutions:[s('descending-prefix','降序前缀贪心','取排序后能超过剩余和的最短前缀。',['nums 升序排序并计算 total','从末尾向前加入 answer、更新 selected','首次 selected>total-selected 时返回'],'O(n log n)','O(n)',
`class Solution { public List<Integer> minSubsequence(int[] nums){Arrays.sort(nums);int total=Arrays.stream(nums).sum(),selected=0;List<Integer> answer=new ArrayList<>();for(int i=nums.length-1;i>=0;i--){answer.add(nums[i]);selected+=nums[i];if(selected>total-selected)break;}return answer;} }`,
`class Solution { fun minSubsequence(nums:IntArray):List<Int>{nums.sort();val total=nums.sum();var selected=0;val answer=mutableListOf<Int>();for(i in nums.lastIndex downTo 0){answer.add(nums[i]);selected+=nums[i];if(selected>total-selected)break};return answer} }`,
`class Solution { public: vector<int> minSubsequence(vector<int>& nums){sort(nums.begin(),nums.end());int total=accumulate(nums.begin(),nums.end(),0),selected=0;vector<int> answer;for(int i=nums.size()-1;i>=0;--i){answer.push_back(nums[i]);selected+=nums[i];if(selected>total-selected)break;}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'minSubsequence',parameterTypes:['intArray'],returnType:'intList',cases:[{name:'十和九已超过其余',args:[[4,3,10,9,8]],expected:[10,9]},{name:'需要三个最大元素',args:[[4,4,7,6,7]],expected:[7,7,6]},{name:'单元素必须选择',args:[[6]],expected:[6]}]}},
{id:1404,slug:'number-of-steps-to-reduce-a-number-in-binary-representation-to-one',title:'将二进制表示减到一的步骤数',studyTags:['字符串','位运算','模拟'],summary:'正整数以二进制字符串给出，偶数除二、奇数加一，求变成一的步骤数。',insight:'从最低位向最高位模拟进位：当前位加 carry 为一表示数为奇数，需要加一再除二共两步并保持进位；否则只除二一步。',pitfalls:['最高位一不直接处理，只在最后加 carry','加一可能连续向高位进位','输入为一时答案为零'],solutions:[s('right-to-left-carry','从右向左模拟进位','不构造大整数，仅跟踪加一产生的进位。',['steps=0,carry=0','从末位扫到索引一；bit+carry==1 时 steps+=2,carry=1，否则 steps++','返回 steps+carry'],'O(n)','O(1)',
`class Solution { public int numSteps(String binary){int steps=0,carry=0;for(int i=binary.length()-1;i>0;i--){int bit=binary.charAt(i)-'0'+carry;if(bit==1){steps+=2;carry=1;}else steps++;}return steps+carry;} }`,
`class Solution { fun numSteps(binary:String):Int{var steps=0;var carry=0;for(i in binary.lastIndex downTo 1){val bit=binary[i]-'0'+carry;if(bit==1){steps+=2;carry=1}else steps++};return steps+carry} }`,
`class Solution { public: int numSteps(string binary){int steps=0,carry=0;for(int i=binary.size()-1;i>0;--i){int bit=binary[i]-'0'+carry;if(bit==1){steps+=2;carry=1;}else ++steps;}return steps+carry;} };`)],tests:{schemaVersion:1,mode:'function',method:'numSteps',parameterTypes:['string'],returnType:'int',cases:[{name:'十三需要六步',args:['1101'],expected:6},{name:'二只需除二',args:['10'],expected:1},{name:'一无需操作',args:['1'],expected:0}]}},
{id:1405,slug:'longest-happy-string',title:'最长快乐字符串',studyTags:['字符串','贪心','堆（优先队列）'],summary:'使用不超过给定数量的 a、b、c 构造不含三个连续相同字符的最长字符串。',insight:'每步优先使用剩余最多的字符；若它会形成三连，就临时使用次多字符，次多不存在时已无法继续。',pitfalls:['字符数量只要求不超过给定值','使用次多字符后要把最大字符放回堆','同频时固定字母序以生成确定结果'],solutions:[s('max-heap-greedy','最大堆贪心','优先消耗数量最多且不会形成三连的字符。',['把正频次字符以数量降序、字母升序入堆','弹出最多字符；若答案末两位相同则改取次多字符并放回最多项','追加所选字符、频次减一后仍有剩余则放回，直到堆空或无法选择'],'O(a+b+c)','O(1)',
`class Solution { public String longestDiverseString(int a,int b,int c){PriorityQueue<int[]> heap=new PriorityQueue<>((x,y)->x[0]!=y[0]?Integer.compare(y[0],x[0]):Integer.compare(x[1],y[1]));if(a>0)heap.offer(new int[]{a,'a'});if(b>0)heap.offer(new int[]{b,'b'});if(c>0)heap.offer(new int[]{c,'c'});StringBuilder answer=new StringBuilder();while(!heap.isEmpty()){int[] first=heap.poll();int length=answer.length();if(length>=2&&answer.charAt(length-1)==first[1]&&answer.charAt(length-2)==first[1]){if(heap.isEmpty())break;int[] second=heap.poll();answer.append((char)second[1]);if(--second[0]>0)heap.offer(second);heap.offer(first);}else{answer.append((char)first[1]);if(--first[0]>0)heap.offer(first);}}return answer.toString();} }`,
`class Solution { fun longestDiverseString(a:Int,b:Int,c:Int):String{val heap=java.util.PriorityQueue<IntArray>{x,y->if(x[0]!=y[0])y[0]-x[0] else x[1]-y[1]};if(a>0)heap.add(intArrayOf(a,'a'.code));if(b>0)heap.add(intArrayOf(b,'b'.code));if(c>0)heap.add(intArrayOf(c,'c'.code));val answer=StringBuilder();while(heap.isNotEmpty()){val first=heap.remove();val length=answer.length;if(length>=2&&answer[length-1].code==first[1]&&answer[length-2].code==first[1]){if(heap.isEmpty())break;val second=heap.remove();answer.append(second[1].toChar());second[0]--;if(second[0]>0)heap.add(second);heap.add(first)}else{answer.append(first[1].toChar());first[0]--;if(first[0]>0)heap.add(first)}};return answer.toString()} }`,
`class Solution { struct Compare{bool operator()(const pair<int,char>& a,const pair<int,char>& b)const{return a.first!=b.first?a.first<b.first:a.second>b.second;}};public:string longestDiverseString(int a,int b,int c){priority_queue<pair<int,char>,vector<pair<int,char>>,Compare> heap;if(a)heap.push({a,'a'});if(b)heap.push({b,'b'});if(c)heap.push({c,'c'});string answer;while(!heap.empty()){auto first=heap.top();heap.pop();int length=answer.size();if(length>=2&&answer[length-1]==first.second&&answer[length-2]==first.second){if(heap.empty())break;auto second=heap.top();heap.pop();answer+=second.second;if(--second.first)heap.push(second);heap.push(first);}else{answer+=first.second;if(--first.first)heap.push(first);}}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'longestDiverseString',parameterTypes:['int','int','int'],returnType:'string',cases:[{name:'七个 c 只能使用六个',args:[1,1,7],expected:'ccaccbcc'},{name:'数量相近全部使用',args:[2,2,1],expected:'ababc'},{name:'大量 a 受三连限制',args:[7,1,0],expected:'aabaa'}]}}
]}
