const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-021',problems:[
{id:1491,slug:'average-salary-excluding-the-minimum-and-maximum-salary',title:'去掉最低和最高工资后的平均值',studyTags:['数组'],summary:'工资数组各不相同，去掉一个最小值和一个最大值后返回剩余工资平均值。',insight:'单遍计算总和、最小值、最大值，结果为 (sum-min-max)/(n-2)。',pitfalls:['除法必须使用浮点数','数组至少三个元素','只去掉各一个极值'],solutions:[s('sum-and-extremes','总和与极值','无需排序即可排除最低和最高工资。',['sum=0,minimum=+INF,maximum=-INF','扫描 salary 更新三者','返回 (sum-minimum-maximum)/(n-2.0)'],'O(n)','O(1)',
`class Solution { public double average(int[] salary){int sum=0,minimum=Integer.MAX_VALUE,maximum=Integer.MIN_VALUE;for(int value:salary){sum+=value;minimum=Math.min(minimum,value);maximum=Math.max(maximum,value);}return (sum-minimum-maximum)/(salary.length-2.0);} }`,
`class Solution { fun average(salary:IntArray):Double=(salary.sum()-salary.minOrNull()!!-salary.maxOrNull()!!)/(salary.size-2.0) }`,
`class Solution { public: double average(vector<int>& salary){int sum=accumulate(salary.begin(),salary.end(),0),minimum=*min_element(salary.begin(),salary.end()),maximum=*max_element(salary.begin(),salary.end());return (double)(sum-minimum-maximum)/(salary.size()-2);} };`)],tests:{schemaVersion:1,mode:'function',method:'average',parameterTypes:['intArray'],returnType:'double',cases:[{name:'排除一千和四千平均二千五',args:[[4000,3000,1000,2000]],expected:2500.0},{name:'三人只剩中间工资',args:[[1000,2000,3000]],expected:2000.0},{name:'六人工资平均三千五',args:[[6000,5000,4000,3000,2000,1000]],expected:3500.0}]}},
{id:1492,slug:'the-kth-factor-of-n',title:'N 的第 K 个因子',studyTags:['数学','数论'],summary:'按升序返回正整数 n 的第 k 个正因子，不足 k 个返回负一。',insight:'从一到 n 顺序枚举，整除时递减 k，归零的当前值就是第 k 个因子。',pitfalls:['一和 n 都是因子','k 从一开始','找不到返回负一'],solutions:[s('ascending-divisor-scan','升序因子扫描','按自然顺序计数整除 n 的整数。',['value 从一到 n','若 n%value==0 则 k--','k==0 返回 value；结束返回 -1'],'O(n)','O(1)',
`class Solution { public int kthFactor(int n,int k){for(int value=1;value<=n;value++)if(n%value==0&&--k==0)return value;return -1;} }`,
`class Solution { fun kthFactor(n:Int,kValue:Int):Int{var k=kValue;for(value in 1..n)if(n%value==0){k--;if(k==0)return value};return -1} }`,
`class Solution { public: int kthFactor(int n,int k){for(int value=1;value<=n;++value)if(n%value==0&&!--k)return value;return -1;} };`)],tests:{schemaVersion:1,mode:'function',method:'kthFactor',parameterTypes:['int','int'],returnType:'int',cases:[{name:'十二的第三因子是三',args:[12,3],expected:3},{name:'七的第二因子是七',args:[7,2],expected:7},{name:'四没有第四个因子',args:[4,4],expected:-1}]}},
{id:1493,slug:'longest-subarray-of-1s-after-deleting-one-element',title:'删掉一个元素后全为 1 的最长子数组',studyTags:['数组','滑动窗口'],summary:'必须删除数组中一个元素，求删除后只含一的最长非空连续子数组长度。',insight:'维护至多包含一个零的最长窗口；删除窗口中的那个零（或全一窗口中任意一个一）后，长度都等于窗口长度减一。',pitfalls:['必须删除恰好一个元素','全一数组答案为 n-1','窗口中零数超过一时移动左边界'],solutions:[s('at-most-one-zero-window','至多一个零滑窗','窗口长度减一就是删除一个元素后的全一长度。',['left=0,zeros=0,answer=0','right 扩展，遇零 zeros++；zeros>1 时移动 left 并减少离开的零','answer=max(answer,right-left)'],'O(n)','O(1)',
`class Solution { public int longestSubarray(int[] nums){int left=0,zeros=0,answer=0;for(int right=0;right<nums.length;right++){if(nums[right]==0)zeros++;while(zeros>1)if(nums[left++]==0)zeros--;answer=Math.max(answer,right-left);}return answer;} }`,
`class Solution { fun longestSubarray(nums:IntArray):Int{var left=0;var zeros=0;var answer=0;for(right in nums.indices){if(nums[right]==0)zeros++;while(zeros>1)if(nums[left++]==0)zeros--;answer=maxOf(answer,right-left)};return answer} }`,
`class Solution { public: int longestSubarray(vector<int>& nums){int left=0,zeros=0,answer=0;for(int right=0;right<(int)nums.size();++right){if(!nums[right])++zeros;while(zeros>1)if(!nums[left++])--zeros;answer=max(answer,right-left);}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'longestSubarray',parameterTypes:['intArray'],returnType:'int',cases:[{name:'删除中间零得到三个一',args:[[1,1,0,1]],expected:3},{name:'多个零时最长五',args:[[0,1,1,1,0,1,1,0,1]],expected:5},{name:'全一数组必须删一个',args:[[1,1,1]],expected:2}]}},
{id:1494,slug:'parallel-courses-ii',title:'并行课程 II',studyTags:['动态规划','位运算','图论','状态压缩'],summary:'有 n 门课和先修关系，每学期最多选 k 门所有先修已完成的课，求完成全部课程的最少学期数。',insight:'用 mask 表示已完成课程。计算当前所有可选课程 available；若不超过 k 门全选，否则枚举 available 中大小为 k 的子集作为本学期课程。',pitfalls:['关系课程编号从一开始','只有先修集合完全包含于 mask 才可选','可选超过 k 时没必要少于 k 门'],solutions:[s('available-subset-mask-dp','可选课程子集状态压缩','对已完成集合枚举下一学期最多 k 门的选择。',['构造 prerequisite[course] 位掩码，dp[0]=0','对 mask 计算未完成且 prerequisite 是 mask 子集的 available','bitCount<=k 时转移全部，否则枚举 available 子掩码且位数为 k，更新 dp[next]'],'O(3^n)','O(2^n)',
`class Solution { public int minNumberOfSemesters(int n,int[][] relations,int k){int[] prerequisite=new int[n];for(int[] relation:relations)prerequisite[relation[1]-1]|=1<<(relation[0]-1);int total=1<<n,inf=100;int[] dp=new int[total];Arrays.fill(dp,inf);dp[0]=0;for(int mask=0;mask<total;mask++){if(dp[mask]==inf)continue;int available=0;for(int course=0;course<n;course++)if((mask&(1<<course))==0&&(prerequisite[course]&mask)==prerequisite[course])available|=1<<course;if(Integer.bitCount(available)<=k)dp[mask|available]=Math.min(dp[mask|available],dp[mask]+1);else for(int subset=available;subset>0;subset=(subset-1)&available)if(Integer.bitCount(subset)==k)dp[mask|subset]=Math.min(dp[mask|subset],dp[mask]+1);}return dp[total-1];} }`,
`class Solution { fun minNumberOfSemesters(n:Int,relations:Array<IntArray>,k:Int):Int{val prerequisite=IntArray(n);for(relation in relations)prerequisite[relation[1]-1]=prerequisite[relation[1]-1]or(1 shl (relation[0]-1));val total=1 shl n;val dp=IntArray(total){100};dp[0]=0;for(mask in 0 until total){if(dp[mask]==100)continue;var available=0;for(course in 0 until n)if(mask and (1 shl course)==0&&prerequisite[course] and mask==prerequisite[course])available=available or(1 shl course);if(Integer.bitCount(available)<=k)dp[mask or available]=minOf(dp[mask or available],dp[mask]+1)else{var subset=available;while(subset>0){if(Integer.bitCount(subset)==k)dp[mask or subset]=minOf(dp[mask or subset],dp[mask]+1);subset=(subset-1)and available}}};return dp.last()} }`,
`class Solution { public: int minNumberOfSemesters(int n,vector<vector<int>>& relations,int k){vector<int> prerequisite(n);for(auto& relation:relations)prerequisite[relation[1]-1]|=1<<(relation[0]-1);int total=1<<n;vector<int> dp(total,100);dp[0]=0;for(int mask=0;mask<total;++mask){if(dp[mask]==100)continue;int available=0;for(int course=0;course<n;++course)if(!(mask&(1<<course))&&(prerequisite[course]&mask)==prerequisite[course])available|=1<<course;if(__builtin_popcount((unsigned)available)<=k)dp[mask|available]=min(dp[mask|available],dp[mask]+1);else for(int subset=available;subset;subset=(subset-1)&available)if(__builtin_popcount((unsigned)subset)==k)dp[mask|subset]=min(dp[mask|subset],dp[mask]+1);}return dp.back();} };`)],tests:{schemaVersion:1,mode:'function',method:'minNumberOfSemesters',parameterTypes:['int','intMatrix','int'],returnType:'int',cases:[{name:'四课依赖需三学期',args:[4,[[2,1],[3,1],[1,4]],2],expected:3},{name:'汇聚依赖链需四学期',args:[5,[[2,1],[3,1],[4,1],[1,5]],2],expected:4},{name:'无依赖四课两学期',args:[4,[],2],expected:2}]}},
{id:1496,slug:'path-crossing',title:'判断路径是否相交',studyTags:['哈希表','字符串'],summary:'从原点出发按 N、S、E、W 移动，判断是否曾到达一个已经访问过的位置。',insight:'用集合记录每一步后的坐标（包含原点）；新坐标若已存在则路径相交。',pitfalls:['原点必须预先加入集合','交叉可发生在终点回到原点','只需判断格点位置重复'],solutions:[s('visited-coordinate-set','访问坐标集合','逐步更新坐标并检测重复。',['x=0,y=0，seen 包含 0,0','按方向更新 x 或 y','若坐标键无法加入 seen 则返回 true，结束返回 false'],'O(n)','O(n)',
`class Solution { public boolean isPathCrossing(String path){int x=0,y=0;Set<String> seen=new HashSet<>();seen.add("0,0");for(char direction:path.toCharArray()){if(direction=='N')y++;else if(direction=='S')y--;else if(direction=='E')x++;else x--;if(!seen.add(x+","+y))return true;}return false;} }`,
`class Solution { fun isPathCrossing(path:String):Boolean{var x=0;var y=0;val seen=mutableSetOf("0,0");for(direction in path){when(direction){'N'->y++;'S'->y--;'E'->x++;else->x--};if(!seen.add("$x,$y"))return true};return false} }`,
`class Solution { public: bool isPathCrossing(string path){int x=0,y=0;set<pair<int,int>> seen{{0,0}};for(char direction:path){if(direction=='N')++y;else if(direction=='S')--y;else if(direction=='E')++x;else --x;if(!seen.insert({x,y}).second)return true;}return false;} };`)],tests:{schemaVersion:1,mode:'function',method:'isPathCrossing',parameterTypes:['string'],returnType:'boolean',cases:[{name:'北东南不重复',args:['NES'],expected:false},{name:'北南回到原点',args:['NS'],expected:true},{name:'绕行后访问旧位置',args:['NESWW'],expected:true}]}}
]}
