const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})

export default {batchId:'batch-017',problems:[
{id:1239,slug:'maximum-length-of-a-concatenated-string-with-unique-characters',title:'串联字符串的最大长度',studyTags:['数组','字符串','位运算','回溯'],summary:'从字符串数组中选择一个子序列并串联，使结果每个字符只出现一次，求最大长度。',insight:'每个合法字符串压成 26 位掩码。维护所有可达的不重复字符集合；新掩码与旧集合无交集时可合并，逐步扩展状态并取置位数最大值。',pitfalls:['单个字符串内部有重复字符时不能使用','选择顺序固定但字符集合足以表示状态','空选择长度为零'],solutions:[s('reachable-disjoint-masks','可达互斥掩码集合','逐字符串扩展所有不冲突字符集合。',['states 初始只含掩码零，answer=0','为每个 word 构造 mask；若内部字符重复则跳过','遍历加入前的 states 快照，若 state&mask==0 则加入 state|mask，并用 bitCount 更新 answer'],'O(2^26) 状态上界','O(2^26) 状态上界',
`class Solution { public int maxLength(List<String> arr){List<Integer> states=new ArrayList<>();states.add(0);int answer=0;for(String word:arr){int mask=0;boolean valid=true;for(char ch:word.toCharArray()){int bit=1<<(ch-'a');if((mask&bit)!=0){valid=false;break;}mask|=bit;}if(!valid)continue;int size=states.size();for(int i=0;i<size;i++)if((states.get(i)&mask)==0){int combined=states.get(i)|mask;states.add(combined);answer=Math.max(answer,Integer.bitCount(combined));}}return answer;} }`,
`class Solution { fun maxLength(arr:List<String>):Int{val states=mutableListOf(0);var answer=0;for(word in arr){var mask=0;var valid=true;for(ch in word){val bit=1 shl (ch-'a');if(mask and bit!=0){valid=false;break};mask=mask or bit};if(!valid)continue;val size=states.size;for(i in 0 until size)if(states[i] and mask==0){val combined=states[i] or mask;states.add(combined);answer=maxOf(answer,Integer.bitCount(combined))}};return answer} }`,
`class Solution { public: int maxLength(vector<string>& arr){vector<int> states{0};int answer=0;for(string& word:arr){int mask=0;bool valid=true;for(char ch:word){int bit=1<<(ch-'a');if(mask&bit){valid=false;break;}mask|=bit;}if(!valid)continue;int size=states.size();for(int i=0;i<size;++i)if(!(states[i]&mask)){int combined=states[i]|mask;states.push_back(combined);answer=max(answer,__builtin_popcount(combined));}}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'maxLength',parameterTypes:['stringList'],returnType:'int',cases:[{name:'un 与 iq 可串联',args:[['un','iq','ue']],expected:4},{name:'选择 chaers',args:[['cha','r','act','ers']],expected:6},{name:'覆盖完整字母表',args:[['abcdefghijklmnopqrstuvwxyz']],expected:26}]}},

{id:1240,slug:'tiling-a-rectangle-with-the-fewest-squares',title:'铺瓷砖',studyTags:['回溯','状态压缩','剪枝'],summary:'用整数边长正方形无重叠铺满 n×m 矩形，求最少正方形数量。',insight:'用每一列当前已铺高度组成天际线。每次选择最低且最靠左的列，从该处尝试能放下的最大到最小正方形；填满所有列即得到一个方案，分支限界取最少块数。',pitfalls:['正方形必须与矩形边界平行','只能在连续相同最低高度列上放置','已用块数不小于当前最优时立即剪枝'],solutions:[s('skyline-backtracking','天际线回溯','在规范的最低缺口处枚举方块边长避免重复铺法。',['heights[m] 全零，best=n*m','dfs(used)：找最小高度及其最左列；若高度等于 n，更新 best','计算从该列起连续同高度宽度，最大边长为 min(宽度,n-minHeight)；从大到小抬高对应列，递归 used+1 后恢复'],'指数级，强剪枝','O(m+搜索栈)',
`class Solution { private int rows,columns,best;private int[] heights;public int tilingRectangle(int n,int m){rows=Math.max(n,m);columns=Math.min(n,m);heights=new int[columns];best=rows*columns;dfs(0);return best;}private void dfs(int used){if(used>=best)return;int minimum=rows,start=-1;for(int i=0;i<columns;i++)if(heights[i]<minimum){minimum=heights[i];start=i;}if(minimum==rows){best=used;return;}int width=0;while(start+width<columns&&heights[start+width]==minimum)width++;int maximum=Math.min(width,rows-minimum);for(int size=maximum;size>=1;size--){for(int i=0;i<size;i++)heights[start+i]+=size;dfs(used+1);for(int i=0;i<size;i++)heights[start+i]-=size;}} }`,
`class Solution { private var rows=0;private var columns=0;private var best=0;private lateinit var heights:IntArray;fun tilingRectangle(n:Int,m:Int):Int{rows=maxOf(n,m);columns=minOf(n,m);heights=IntArray(columns);best=rows*columns;dfs(0);return best};private fun dfs(used:Int){if(used>=best)return;var minimum=rows;var start=-1;for(i in 0 until columns)if(heights[i]<minimum){minimum=heights[i];start=i};if(minimum==rows){best=used;return};var width=0;while(start+width<columns&&heights[start+width]==minimum)width++;val maximum=minOf(width,rows-minimum);for(size in maximum downTo 1){for(i in 0 until size)heights[start+i]+=size;dfs(used+1);for(i in 0 until size)heights[start+i]-=size}} }`,
`class Solution { int rows,columns,best;vector<int> heights;void dfs(int used){if(used>=best)return;int minimum=rows,start=-1;for(int i=0;i<columns;++i)if(heights[i]<minimum){minimum=heights[i];start=i;}if(minimum==rows){best=used;return;}int width=0;while(start+width<columns&&heights[start+width]==minimum)++width;int maximum=min(width,rows-minimum);for(int size=maximum;size>=1;--size){for(int i=0;i<size;++i)heights[start+i]+=size;dfs(used+1);for(int i=0;i<size;++i)heights[start+i]-=size;}}public:int tilingRectangle(int n,int m){rows=max(n,m);columns=min(n,m);heights.assign(columns,0);best=rows*columns;dfs(0);return best;} };`)],tests:{schemaVersion:1,mode:'function',method:'tilingRectangle',parameterTypes:['int','int'],returnType:'int',cases:[{name:'二乘三需三块',args:[2,3],expected:3},{name:'五乘八需五块',args:[5,8],expected:5},{name:'一乘四需四块',args:[1,4],expected:4}]}},

{id:1247,slug:'minimum-swaps-to-make-strings-equal',title:'交换字符使两个字符串相同',studyTags:['字符串','数学','贪心'],summary:'两个等长字符串只含 x、y，每次可跨字符串交换任意位置字符，求使两串相同的最少交换次数，不可能返回负一。',insight:'只统计不匹配类型 xy 和 yx。每两个同类型不匹配一次交换即可修复；若两类各剩一个，需要两次交换；总不匹配为奇数则无法配对。',pitfalls:['相同位置字符无需处理','xy 与 yx 是有方向的两种错配','剩余一对异类型错配需要两次而非一次'],solutions:[s('mismatch-type-counting','错配类型计数','按两类错配的奇偶性直接计算最少交换数。',['扫描位置，s1=x且s2=y 时 xy++，反向时 yx++','若 xy+yx 为奇数返回 -1','答案=xy/2+yx/2；若 xy 为奇数再加二，返回'],'O(n)','O(1)',
`class Solution { public int minimumSwap(String s1,String s2){int xy=0,yx=0;for(int i=0;i<s1.length();i++)if(s1.charAt(i)!=s2.charAt(i)){if(s1.charAt(i)=='x')xy++;else yx++;}if((xy+yx)%2==1)return -1;return xy/2+yx/2+(xy%2)*2;} }`,
`class Solution { fun minimumSwap(s1:String,s2:String):Int{var xy=0;var yx=0;for(i in s1.indices)if(s1[i]!=s2[i]){if(s1[i]=='x')xy++ else yx++};if((xy+yx)%2==1)return -1;return xy/2+yx/2+xy%2*2} }`,
`class Solution { public: int minimumSwap(string s1,string s2){int xy=0,yx=0;for(int i=0;i<(int)s1.size();++i)if(s1[i]!=s2[i])s1[i]=='x'?++xy:++yx;if((xy+yx)%2)return -1;return xy/2+yx/2+xy%2*2;} };`)],tests:{schemaVersion:1,mode:'function',method:'minimumSwap',parameterTypes:['string','string'],returnType:'int',cases:[{name:'两个同类错配一次',args:['xx','yy'],expected:1},{name:'异类错配需两次',args:['xy','yx'],expected:2},{name:'奇数错配无解',args:['xx','xy'],expected:-1}]}},

{id:1248,slug:'count-number-of-nice-subarrays',title:'统计优美子数组',studyTags:['数组','滑动窗口','前缀计数'],summary:'统计整数数组中恰好含 k 个奇数的连续子数组数量。',insight:'恰好 k 个等于“至多 k 个”减去“至多 k-1 个”。至多函数用滑动窗口维护奇数数目，每个右端点贡献 right-left+1 个合法子数组。',pitfalls:['偶数可以任意扩展子数组边界','atMost(-1) 应返回零','答案可能大于单个窗口长度但在整数范围内'],solutions:[s('difference-of-at-most-windows','两个至多窗口之差','把精确计数转换为两个单调窗口计数。',['定义 atMost(limit)，limit<0 返回零','右端扫描，遇奇数增加 odd；odd>limit 时移动 left 并扣除离开的奇数','每轮累加 right-left+1；返回 atMost(k)-atMost(k-1)'],'O(n)','O(1)',
`class Solution { public int numberOfSubarrays(int[] nums,int k){return atMost(nums,k)-atMost(nums,k-1);}private int atMost(int[] nums,int limit){if(limit<0)return 0;int left=0,odd=0,total=0;for(int right=0;right<nums.length;right++){odd+=nums[right]&1;while(odd>limit)odd-=nums[left++]&1;total+=right-left+1;}return total;} }`,
`class Solution { fun numberOfSubarrays(nums:IntArray,k:Int):Int=atMost(nums,k)-atMost(nums,k-1);private fun atMost(nums:IntArray,limit:Int):Int{if(limit<0)return 0;var left=0;var odd=0;var total=0;for(right in nums.indices){odd+=nums[right] and 1;while(odd>limit){odd-=nums[left] and 1;left++};total+=right-left+1};return total} }`,
`class Solution { int atMost(vector<int>& nums,int limit){if(limit<0)return 0;int left=0,odd=0,total=0;for(int right=0;right<(int)nums.size();++right){odd+=nums[right]&1;while(odd>limit)odd-=nums[left++]&1;total+=right-left+1;}return total;}public:int numberOfSubarrays(vector<int>& nums,int k){return atMost(nums,k)-atMost(nums,k-1);} };`)],tests:{schemaVersion:1,mode:'function',method:'numberOfSubarrays',parameterTypes:['intArray','int'],returnType:'int',cases:[{name:'五项恰三奇数有二段',args:[[1,1,2,1,1],3],expected:2},{name:'全偶数无优美段',args:[[2,4,6],1],expected:0},{name:'偶数边界产生十六段',args:[[2,2,2,1,2,2,1,2,2,2],2],expected:16}]}},

{id:1249,slug:'minimum-remove-to-make-valid-parentheses',title:'移除无效的括号',studyTags:['字符串','栈','标记'],summary:'删除最少数量的左右括号，使字符串括号匹配有效，字母保持原相对顺序，返回任一结果。',insight:'栈保存尚未匹配的左括号下标；右括号有栈可配就弹出，否则标记删除。扫描结束后栈中所有左括号也必须删除，保留其余字符。',pitfalls:['普通字母永远保留','多余右括号在扫描时立即确定','剩余左括号在扫描结束统一删除'],solutions:[s('unmatched-index-marking','未匹配下标标记','用栈找出恰好需要删除的所有括号位置。',['remove[n]=false，stack 保存左括号下标','遇 ( 压栈；遇 ) 时栈非空则弹出，否则 remove[i]=true','扫描后把栈内下标标记删除，拼接所有未标记字符并返回'],'O(n)','O(n)',
`class Solution { public String minRemoveToMakeValid(String s){boolean[] remove=new boolean[s.length()];Deque<Integer> stack=new ArrayDeque<>();for(int i=0;i<s.length();i++)if(s.charAt(i)=='(')stack.push(i);else if(s.charAt(i)==')'){if(stack.isEmpty())remove[i]=true;else stack.pop();}while(!stack.isEmpty())remove[stack.pop()]=true;StringBuilder answer=new StringBuilder();for(int i=0;i<s.length();i++)if(!remove[i])answer.append(s.charAt(i));return answer.toString();} }`,
`class Solution { fun minRemoveToMakeValid(s:String):String{val remove=BooleanArray(s.length);val stack=java.util.ArrayDeque<Int>();for(i in s.indices)if(s[i]=='(')stack.push(i)else if(s[i]==')'){if(stack.isEmpty())remove[i]=true else stack.pop()};while(stack.isNotEmpty())remove[stack.pop()]=true;return buildString{for(i in s.indices)if(!remove[i])append(s[i])}} }`,
`class Solution { public: string minRemoveToMakeValid(string s){vector<bool> remove(s.size());stack<int> opens;for(int i=0;i<(int)s.size();++i)if(s[i]=='(')opens.push(i);else if(s[i]==')'){if(opens.empty())remove[i]=true;else opens.pop();}while(!opens.empty()){remove[opens.top()]=true;opens.pop();}string answer;for(int i=0;i<(int)s.size();++i)if(!remove[i])answer+=s[i];return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'minRemoveToMakeValid',parameterTypes:['string'],returnType:'string',cases:[{name:'删除末尾右括号',args:['lee(t(c)o)de)'],expected:'lee(t(c)o)de'},{name:'删除中间多余右括号',args:['a)b(c)d'],expected:'ab(c)d'},{name:'全部括号都无匹配',args:['))(('],expected:''}]}}
]}
