const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-019',problems:[
{id:1366,slug:'rank-teams-by-votes',title:'通过投票对团队排名',studyTags:['数组','字符串','计数','排序'],summary:'每张选票给出全部队伍的名次，按各名次获得票数依次比较并排序队伍。',insight:'为每个字母统计它在每个位置出现的次数；比较两队时从第一名票数逐位比较，全部相同则字母序更小者优先。',pitfalls:['比较的是逐名次字典序而非总分','完全相同时按队名字母序','只有选票中出现的队伍参与输出'],solutions:[s('position-frequency-sort','名次频次排序','使用每队的名次票数向量作为降序排序键。',['统计 count[team][position]','对第一张选票中的队伍排序，逐 position 比较票数降序','所有票数相同时按字符升序并拼接'],'O(Vm+m² log m)','O(m²)',
`class Solution { public String rankTeams(String[] votes){int size=votes[0].length();int[][] count=new int[26][size];for(String vote:votes)for(int i=0;i<size;i++)count[vote.charAt(i)-'A'][i]++;Character[] teams=new Character[size];for(int i=0;i<size;i++)teams[i]=votes[0].charAt(i);Arrays.sort(teams,(a,b)->{for(int i=0;i<size;i++){int difference=count[b-'A'][i]-count[a-'A'][i];if(difference!=0)return difference;}return Character.compare(a,b);});StringBuilder answer=new StringBuilder();for(char team:teams)answer.append(team);return answer.toString();} }`,
`class Solution { fun rankTeams(votes:Array<String>):String{val size=votes[0].length;val count=Array(26){IntArray(size)};for(vote in votes)for(i in 0 until size)count[vote[i]-'A'][i]++;return votes[0].toList().sortedWith(Comparator{a,b->for(i in 0 until size){val difference=count[b-'A'][i]-count[a-'A'][i];if(difference!=0)return@Comparator difference};a.compareTo(b)}).joinToString("")} }`,
`class Solution { public: string rankTeams(vector<string>& votes){int size=votes[0].size();int count[26][26]={};for(auto& vote:votes)for(int i=0;i<size;++i)++count[vote[i]-'A'][i];string teams=votes[0];sort(teams.begin(),teams.end(),[&](char a,char b){for(int i=0;i<size;++i)if(count[a-'A'][i]!=count[b-'A'][i])return count[a-'A'][i]>count[b-'A'][i];return a<b;});return teams;} };`)],tests:{schemaVersion:1,mode:'function',method:'rankTeams',parameterTypes:['stringArray'],returnType:'string',cases:[{name:'五张选票决定 ACB',args:[['ABC','ACB','ABC','ACB','ACB']],expected:'ACB'},{name:'两张轮换选票',args:[['WXYZ','XYZW']],expected:'XWYZ'},{name:'同级继续比较后续名次',args:[['BCA','CAB','CBA']],expected:'CBA'}]}},
{id:1367,slug:'linked-list-in-binary-tree',title:'二叉树中的链表',studyTags:['链表','树','深度优先搜索'],summary:'判断链表的值序列是否对应二叉树中某个节点开始、持续向下的一条路径。',insight:'对树中每个节点尝试作为起点；匹配过程中链表和树节点值相同后，递归选择左或右孩子。',pitfalls:['路径只能向下但可在每层选择左右','匹配失败后仍要在子树寻找新起点','链表耗尽即匹配成功'],solutions:[s('start-and-match-dfs','起点枚举与路径匹配','外层遍历树节点，内层递归匹配链表路径。',['match(list,node)：list 为空成功，node 为空或值不同失败','值相同则匹配 node.left 或 node.right','search(root) 尝试当前节点并递归搜索左右子树'],'O(NL)','O(H+L)',
`class Solution { private boolean match(ListNode head,TreeNode node){if(head==null)return true;if(node==null||head.val!=node.val)return false;return match(head.next,node.left)||match(head.next,node.right);}public boolean isSubPath(ListNode head,TreeNode root){return root!=null&&(match(head,root)||isSubPath(head,root.left)||isSubPath(head,root.right));} }`,
`class Solution { private fun match(head:ListNode?,node:TreeNode?):Boolean{if(head==null)return true;if(node==null||head.\`val\`!=node.\`val\`)return false;return match(head.next,node.left)||match(head.next,node.right)};fun isSubPath(head:ListNode?,root:TreeNode?):Boolean=root!=null&&(match(head,root)||isSubPath(head,root.left)||isSubPath(head,root.right)) }`,
`class Solution { bool match(ListNode* head,TreeNode* node){if(!head)return true;if(!node||head->val!=node->val)return false;return match(head->next,node->left)||match(head->next,node->right);}public:bool isSubPath(ListNode* head,TreeNode* root){return root&&(match(head,root)||isSubPath(head,root->left)||isSubPath(head,root->right));} };`)],tests:{schemaVersion:1,mode:'function',method:'isSubPath',parameterTypes:['listNode','treeNode'],returnType:'boolean',cases:[{name:'四二八向下路径存在',args:[[4,2,8],[1,4,3,null,2,null,null,null,8]],expected:true},{name:'末尾六不匹配',args:[[1,4,2,6],[1,4,3,null,2,null,null,null,8]],expected:false},{name:'单节点匹配',args:[[1],[1]],expected:true}]}},
{id:1368,slug:'minimum-cost-to-make-at-least-one-valid-path-in-a-grid',title:'使网格图至少有一条有效路径的最小代价',studyTags:['数组','图论','最短路','广度优先搜索'],summary:'每个格子箭头指向一个方向，修改一个箭头代价一，求从左上到右下的最小修改次数。',insight:'把每个格子视为图节点：沿原箭头移动的边权为零，其余三个方向边权为一；用 0-1 BFS 求最短路。',pitfalls:['边权取决于离开当前格子的方向','零权边压入双端队列前端','只有距离变小时才更新'],solutions:[s('zero-one-bfs','零一广度优先搜索','使用双端队列在线性边数内求零一权最短路。',['dist 初始化无穷，起点为零并入队','枚举四邻，weight 为方向是否等于 grid[row][col]','松弛后零权 addFirst、一权 addLast；返回终点距离'],'O(mn)','O(mn)',
`class Solution { public int minCost(int[][] grid){int rows=grid.length,cols=grid[0].length;int[][] directions={{0,1},{0,-1},{1,0},{-1,0}},dist=new int[rows][cols];for(int[] row:dist)Arrays.fill(row,Integer.MAX_VALUE);Deque<int[]> deque=new ArrayDeque<>();dist[0][0]=0;deque.addFirst(new int[]{0,0});while(!deque.isEmpty()){int[] cell=deque.removeFirst();int row=cell[0],col=cell[1];for(int direction=0;direction<4;direction++){int nextRow=row+directions[direction][0],nextCol=col+directions[direction][1];if(nextRow<0||nextRow>=rows||nextCol<0||nextCol>=cols)continue;int weight=grid[row][col]==direction+1?0:1,newDistance=dist[row][col]+weight;if(newDistance<dist[nextRow][nextCol]){dist[nextRow][nextCol]=newDistance;if(weight==0)deque.addFirst(new int[]{nextRow,nextCol});else deque.addLast(new int[]{nextRow,nextCol});}}}return dist[rows-1][cols-1];} }`,
`class Solution { fun minCost(grid:Array<IntArray>):Int{val rows=grid.size;val cols=grid[0].size;val directions=arrayOf(intArrayOf(0,1),intArrayOf(0,-1),intArrayOf(1,0),intArrayOf(-1,0));val dist=Array(rows){IntArray(cols){Int.MAX_VALUE}};val deque=java.util.ArrayDeque<IntArray>();dist[0][0]=0;deque.addFirst(intArrayOf(0,0));while(deque.isNotEmpty()){val cell=deque.removeFirst();val row=cell[0];val col=cell[1];for(direction in 0..3){val nextRow=row+directions[direction][0];val nextCol=col+directions[direction][1];if(nextRow !in 0 until rows||nextCol !in 0 until cols)continue;val weight=if(grid[row][col]==direction+1)0 else 1;val newDistance=dist[row][col]+weight;if(newDistance<dist[nextRow][nextCol]){dist[nextRow][nextCol]=newDistance;if(weight==0)deque.addFirst(intArrayOf(nextRow,nextCol))else deque.addLast(intArrayOf(nextRow,nextCol))}}};return dist[rows-1][cols-1]} }`,
`class Solution { public: int minCost(vector<vector<int>>& grid){int rows=grid.size(),cols=grid[0].size();int directions[4][2]={{0,1},{0,-1},{1,0},{-1,0}};vector<vector<int>> dist(rows,vector<int>(cols,INT_MAX));deque<pair<int,int>> pending;dist[0][0]=0;pending.push_front({0,0});while(!pending.empty()){auto [row,col]=pending.front();pending.pop_front();for(int direction=0;direction<4;++direction){int nextRow=row+directions[direction][0],nextCol=col+directions[direction][1];if(nextRow<0||nextRow>=rows||nextCol<0||nextCol>=cols)continue;int weight=grid[row][col]==direction+1?0:1,newDistance=dist[row][col]+weight;if(newDistance<dist[nextRow][nextCol]){dist[nextRow][nextCol]=newDistance;if(weight)pending.push_back({nextRow,nextCol});else pending.push_front({nextRow,nextCol});}}}return dist.back().back();} };`)],tests:{schemaVersion:1,mode:'function',method:'minCost',parameterTypes:['intMatrix'],returnType:'int',cases:[{name:'箭头已形成有效路径',args:[[[1,1,3],[3,2,2],[1,1,4]]],expected:0},{name:'二乘二需要修改一次',args:[[[1,2],[4,3]]],expected:1},{name:'单个格子无需修改',args:[[[4]]],expected:0}]}},
{id:1370,slug:'increasing-decreasing-string',title:'上升下降字符串',studyTags:['字符串','计数','模拟'],summary:'反复按未使用字符从小到大各取一次、再从大到小各取一次，生成重排字符串。',insight:'只有二十六个小写字母；维护频次，每轮正向和反向扫描各取一个仍有剩余的字符即可。',pitfalls:['每次经过一个字符最多取一个','正向后立刻执行反向','重复直到输出长度等于输入长度'],solutions:[s('alternating-frequency-scan','交替扫描频次','在固定字母表上反复升序与降序取字符。',['统计 count[26]','答案未满时从 a 到 z 各取一个，再从 z 到 a 各取一个','频次取用后减一，返回字符串'],'O(26n)','O(1)',
`class Solution { public String sortString(String text){int[] count=new int[26];for(char value:text.toCharArray())count[value-'a']++;StringBuilder answer=new StringBuilder();while(answer.length()<text.length()){for(int i=0;i<26;i++)if(count[i]>0){answer.append((char)('a'+i));count[i]--;}for(int i=25;i>=0;i--)if(count[i]>0){answer.append((char)('a'+i));count[i]--;}}return answer.toString();} }`,
`class Solution { fun sortString(text:String):String{val count=IntArray(26);for(value in text)count[value-'a']++;val answer=StringBuilder();while(answer.length<text.length){for(i in 0..25)if(count[i]>0){answer.append(('a'.code+i).toChar());count[i]--};for(i in 25 downTo 0)if(count[i]>0){answer.append(('a'.code+i).toChar());count[i]--}};return answer.toString()} }`,
`class Solution { public: string sortString(string text){int count[26]={};for(char value:text)++count[value-'a'];string answer;while(answer.size()<text.size()){for(int i=0;i<26;++i)if(count[i]){answer+=char('a'+i);--count[i];}for(int i=25;i>=0;--i)if(count[i]){answer+=char('a'+i);--count[i];}}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'sortString',parameterTypes:['string'],returnType:'string',cases:[{name:'三组重复字母',args:['aaaabbbbcccc'],expected:'abccbaabccba'},{name:'三个不同字母',args:['rat'],expected:'art'},{name:'leetcode 重排',args:['leetcode'],expected:'cdelotee'}]}},
{id:1371,slug:'find-the-longest-substring-containing-vowels-in-even-counts',title:'每个元音包含偶数次的最长子字符串',studyTags:['字符串','位运算','前缀和'],summary:'求最长子字符串，使 a、e、i、o、u 五种元音的出现次数均为偶数。',insight:'用五位掩码表示前缀中各元音计数的奇偶性；两个相同掩码之间的子串令每一位异或为零，因此记录各状态最早位置。',pitfalls:['状态零的最早位置是 -1','只记录每个状态第一次出现的位置','辅音不改变掩码'],solutions:[s('parity-prefix-mask','奇偶前缀掩码','相同前缀状态的最远两位置构成合法子串。',['earliest[32] 初始化未见，earliest[0]=-1','扫描字符，遇元音翻转对应位','若 mask 已见则更新 i-earliest[mask]，否则记录 i'],'O(n)','O(1)',
`class Solution { public int findTheLongestSubstring(String text){int[] earliest=new int[32];Arrays.fill(earliest,-2);earliest[0]=-1;int mask=0,answer=0;for(int i=0;i<text.length();i++){int vowel="aeiou".indexOf(text.charAt(i));if(vowel>=0)mask^=1<<vowel;if(earliest[mask]!=-2)answer=Math.max(answer,i-earliest[mask]);else earliest[mask]=i;}return answer;} }`,
`class Solution { fun findTheLongestSubstring(text:String):Int{val earliest=IntArray(32){-2};earliest[0]=-1;var mask=0;var answer=0;for(i in text.indices){val vowel="aeiou".indexOf(text[i]);if(vowel>=0)mask=mask xor (1 shl vowel);if(earliest[mask]!=-2)answer=maxOf(answer,i-earliest[mask])else earliest[mask]=i};return answer} }`,
`class Solution { public: int findTheLongestSubstring(string text){int earliest[32];fill(begin(earliest),end(earliest),-2);earliest[0]=-1;int mask=0,answer=0;for(int i=0;i<(int)text.size();++i){auto vowel=string("aeiou").find(text[i]);if(vowel!=string::npos)mask^=1<<vowel;if(earliest[mask]!=-2)answer=max(answer,i-earliest[mask]);else earliest[mask]=i;}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'findTheLongestSubstring',parameterTypes:['string'],returnType:'int',cases:[{name:'经典字符串最长十三',args:['eleetminicoworoep'],expected:13},{name:'第二个示例最长五',args:['leetcodeisgreat'],expected:5},{name:'全是辅音',args:['bcbcbc'],expected:6}]}}
]}
