const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-006',problems:[
{id:459,slug:'repeated-substring-pattern',title:'重复的子字符串',studyTags:['KMP','字符串','周期'],summary:'判断非空字符串能否由某个比自身短的子串重复多次构成。',insight:'KMP 前缀函数给出最长相等真前后缀长度；若剩余的最小周期长度能整除总长度，就存在重复模式。',pitfalls:['重复次数至少为二','最长真前后缀长度必须大于零','总长度需能被候选周期整除'],solutions:[s('prefix-function-period','前缀函数求周期','利用 border 长度推导最小周期 n-prefix[n-1]。',['计算 KMP prefix 数组','period=n-prefix[n-1]','prefix 最后一项>0 且 n%period==0 时返回真'],'O(n)','O(n)',
`class Solution { public boolean repeatedSubstringPattern(String s){int[] prefix=new int[s.length()];for(int i=1;i<s.length();i++){int j=prefix[i-1];while(j>0&&s.charAt(i)!=s.charAt(j))j=prefix[j-1];if(s.charAt(i)==s.charAt(j))j++;prefix[i]=j;}int border=prefix[s.length()-1],period=s.length()-border;return border>0&&s.length()%period==0;} }`,
`class Solution { fun repeatedSubstringPattern(s:String):Boolean{val prefix=IntArray(s.length);for(i in 1 until s.length){var j=prefix[i-1];while(j>0&&s[i]!=s[j])j=prefix[j-1];if(s[i]==s[j])j++;prefix[i]=j};val border=prefix.last();val period=s.length-border;return border>0&&s.length%period==0} }`,
`class Solution { public: bool repeatedSubstringPattern(string s){vector<int> prefix(s.size());for(int i=1;i<(int)s.size();++i){int j=prefix[i-1];while(j>0&&s[i]!=s[j])j=prefix[j-1];if(s[i]==s[j])++j;prefix[i]=j;}int border=prefix.back(),period=s.size()-border;return border>0&&s.size()%period==0;} };`)],tests:{schemaVersion:1,mode:'function',method:'repeatedSubstringPattern',parameterTypes:['string'],returnType:'boolean',cases:[{name:'两次重复',args:['abab'],expected:true},{name:'没有完整周期',args:['aba'],expected:false},{name:'三次重复',args:['abcabcabc'],expected:true}]}},
{id:461,slug:'hamming-distance',title:'汉明距离',studyTags:['位运算','异或','位计数'],summary:'返回两个整数二进制表示中对应位不同的位置数量。',insight:'异或结果中为一的位恰好表示两数该位不同，因此答案就是异或值的置位数。',pitfalls:['比较的是固定整数二进制位','相同数距离为零','可直接使用位计数操作'],solutions:[s('xor-popcount','异或后统计一位','先用异或标记差异位，再计算置位数。',['difference=x XOR y','统计 difference 中的一','返回计数'],'O(1)','O(1)',
`class Solution { public int hammingDistance(int x,int y){return Integer.bitCount(x^y);} }`,
`class Solution { fun hammingDistance(x:Int,y:Int):Int=Integer.bitCount(x xor y) }`,
`class Solution { public: int hammingDistance(int x,int y){return __builtin_popcount((unsigned)(x^y));} };`)],tests:{schemaVersion:1,mode:'function',method:'hammingDistance',parameterTypes:['int','int'],returnType:'int',cases:[{name:'一与四',args:[1,4],expected:2},{name:'三与一',args:[3,1],expected:1},{name:'相同数字',args:[7,7],expected:0}]}},
{id:462,slug:'minimum-moves-to-equal-array-elements-ii',title:'最小操作次数使数组元素相等 II',studyTags:['中位数','排序','绝对距离'],summary:'每次可把一个数组元素加一或减一，求使所有元素相等的最少操作次数。',insight:'绝对距离和在任一中位数处取得最小值，因此排序后选择中间元素并累加距离。',pitfalls:['目标不一定是平均数','偶数长度时两个中位数之间任一点都最优','距离累加使用长整型更稳健'],solutions:[s('median-distance','到中位数的距离和','排序定位中位数后计算所有绝对差。',['数组排序','median=nums[n/2]','answer 累加 abs(value-median)'],'O(n log n)','O(log n)',
`class Solution { public int minMoves2(int[] nums){Arrays.sort(nums);int median=nums[nums.length/2];long answer=0;for(int value:nums)answer+=Math.abs((long)value-median);return(int)answer;} }`,
`class Solution { fun minMoves2(nums:IntArray):Int{nums.sort();val median=nums[nums.size/2];var answer=0L;for(value in nums)answer+=kotlin.math.abs(value.toLong()-median);return answer.toInt()} }`,
`class Solution { public: int minMoves2(vector<int>& nums){sort(nums.begin(),nums.end());int median=nums[nums.size()/2];long long answer=0;for(int value:nums)answer+=llabs((long long)value-median);return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'minMoves2',parameterTypes:['intArray'],returnType:'int',cases:[{name:'三个连续数',args:[[1,2,3]],expected:2},{name:'偶数长度',args:[[1,10,2,9]],expected:16},{name:'单元素',args:[[1]],expected:0}]}},
{id:463,slug:'island-perimeter',title:'岛屿的周长',studyTags:['矩阵','边计数','网格'],summary:'网格中一表示陆地、零表示水域，只有一个无湖岛屿，计算其周长。',insight:'每个陆地先贡献四条边；若与上方或左方陆地相邻，共享边被两块重复计算，应减去二。',pitfalls:['只需检查上和左即可避免重复','对每对相邻陆地减二','边界外视为水域'],solutions:[s('shared-edge-counting','陆地边减共享边','扫描网格累加每格基础周长并扣除已访问邻接。',['遇陆地 perimeter+=4','上方为陆地则 perimeter-=2','左方为陆地则 perimeter-=2'],'O(mn)','O(1)',
`class Solution { public int islandPerimeter(int[][] grid){int perimeter=0;for(int r=0;r<grid.length;r++)for(int c=0;c<grid[0].length;c++)if(grid[r][c]==1){perimeter+=4;if(r>0&&grid[r-1][c]==1)perimeter-=2;if(c>0&&grid[r][c-1]==1)perimeter-=2;}return perimeter;} }`,
`class Solution { fun islandPerimeter(grid:Array<IntArray>):Int{var perimeter=0;for(r in grid.indices)for(c in grid[0].indices)if(grid[r][c]==1){perimeter+=4;if(r>0&&grid[r-1][c]==1)perimeter-=2;if(c>0&&grid[r][c-1]==1)perimeter-=2};return perimeter} }`,
`class Solution { public: int islandPerimeter(vector<vector<int>>& grid){int perimeter=0;for(int r=0;r<(int)grid.size();++r)for(int c=0;c<(int)grid[0].size();++c)if(grid[r][c]){perimeter+=4;if(r>0&&grid[r-1][c])perimeter-=2;if(c>0&&grid[r][c-1])perimeter-=2;}return perimeter;} };`)],tests:{schemaVersion:1,mode:'function',method:'islandPerimeter',parameterTypes:['intMatrix'],returnType:'int',cases:[{name:'经典岛屿',args:[[[0,1,0,0],[1,1,1,0],[0,1,0,0],[1,1,0,0]]],expected:16},{name:'单块陆地',args:[[[1]]],expected:4},{name:'横向相邻两块',args:[[[1,1]]],expected:6}]}},
{id:485,slug:'max-consecutive-ones',title:'最大连续 1 的个数',studyTags:['数组','线性扫描','连续段'],summary:'给定只含零和一的数组，返回其中最长连续一段的长度。',insight:'遇到一就扩展当前连续段，遇到零清零，并持续维护历史最大长度。',pitfalls:['只统计连续元素','全零数组答案为零','数组末尾的连续段也需更新'],solutions:[s('running-streak','当前连续段计数','单次扫描维护 current 和 best。',['current=best=0','value==1 时 current++，否则 current=0','best=max(best,current)'],'O(n)','O(1)',
`class Solution { public int findMaxConsecutiveOnes(int[] nums){int current=0,best=0;for(int value:nums){current=value==1?current+1:0;best=Math.max(best,current);}return best;} }`,
`class Solution { fun findMaxConsecutiveOnes(nums:IntArray):Int{var current=0;var best=0;for(value in nums){current=if(value==1)current+1 else 0;best=maxOf(best,current)};return best} }`,
`class Solution { public: int findMaxConsecutiveOnes(vector<int>& nums){int current=0,best=0;for(int value:nums){current=value?current+1:0;best=max(best,current);}return best;} };`)],tests:{schemaVersion:1,mode:'function',method:'findMaxConsecutiveOnes',parameterTypes:['intArray'],returnType:'int',cases:[{name:'最长连续段三',args:[[1,1,0,1,1,1]],expected:3},{name:'多个短段',args:[[1,0,1,1,0,1]],expected:2},{name:'全零',args:[[0,0]],expected:0}]}}
]}
