const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-025',problems:[
{id:1744,slug:'can-you-eat-your-favorite-candy-on-your-favorite-day',title:'你能在你最喜欢的那天吃到你最喜欢的糖果吗',studyTags:['数组','前缀和'],summary:'必须按类型顺序吃糖，每天至少一颗且至多 dailyCap 颗；对每个查询判断 favoriteDay 能否吃到 favoriteType。',insight:'该日结束前最多能吃 (day+1)*cap 颗，开始前至少已吃 day 颗。favoriteType 在全局糖果序号区间 (prefix[type],prefix[type+1]] 内，两区间相交即可能。',pitfalls:['天数从零开始','每天至少吃一颗','数量乘积使用 long'],solutions:[s('consumption-interval-overlap','消费区间重叠','用前缀和表示每类糖果在总序列中的位置范围。',['计算 long prefix','查询的最少累计吃糖数为 day+1，最多为 (day+1)*cap','若 maximum>prefix[type] 且 minimum<=prefix[type+1] 则可吃到'],'O(n+q)','O(n)',
`class Solution { public List<Boolean> canEat(int[] candiesCount,int[][] queries){long[] prefix=new long[candiesCount.length+1];for(int i=0;i<candiesCount.length;i++)prefix[i+1]=prefix[i]+candiesCount[i];List<Boolean> answer=new ArrayList<>();for(int[] query:queries){long minimum=(long)query[1]+1,maximum=minimum*query[2];int type=query[0];answer.add(maximum>prefix[type]&&minimum<=prefix[type+1]);}return answer;} }`,
`class Solution { fun canEat(candiesCount:IntArray,queries:Array<IntArray>):List<Boolean>{val prefix=LongArray(candiesCount.size+1);for(i in candiesCount.indices)prefix[i+1]=prefix[i]+candiesCount[i];return queries.map{query->val minimum=query[1].toLong()+1;val maximum=minimum*query[2];val type=query[0];maximum>prefix[type]&&minimum<=prefix[type+1]}} }`,
`class Solution { public: vector<bool> canEat(vector<int>& candiesCount,vector<vector<int>>& queries){vector<long long> prefix(candiesCount.size()+1);for(int i=0;i<(int)candiesCount.size();++i)prefix[i+1]=prefix[i]+candiesCount[i];vector<bool> answer;for(auto& query:queries){long long minimum=query[1]+1LL,maximum=minimum*query[2];int type=query[0];answer.push_back(maximum>prefix[type]&&minimum<=prefix[type+1]);}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'canEat',parameterTypes:['intArray','intMatrix'],returnType:'booleanList',cases:[{name:'三组经典查询',args:[[7,4,5,3,8],[[0,2,2],[4,2,4],[2,13,1000000000]]],expected:[true,false,true]},{name:'第一天可吃第一类糖',args:[[1],[[0,0,1]]],expected:[true]},{name:'太早无法吃到第二类',args:[[10,1],[[1,0,5]]],expected:[false]}]}},
{id:1745,slug:'palindrome-partitioning-iv',title:'回文串分割 IV',studyTags:['字符串','动态规划'],summary:'判断字符串能否恰好分成三个非空连续回文子串。',insight:'预处理 palindrome[left][right]，再枚举两条切分线；三个区间都为回文时立即返回真。',pitfalls:['必须恰好三段且每段非空','回文表按区间长度递增计算','切分线位置需留出第三段'],solutions:[s('palindrome-table-two-cuts','回文表与双切点枚举','常数时间验证任意候选三段。',['构造 palindrome：字符相等且内部长度<=2或内部回文','firstEnd 从零到 n-3','secondEnd 从 firstEnd+1 到 n-2，检查三段回文性'],'O(n²)','O(n²)',
`class Solution { public boolean checkPartitioning(String text){int n=text.length();boolean[][] palindrome=new boolean[n][n];for(int length=1;length<=n;length++)for(int left=0;left+length<=n;left++){int right=left+length-1;palindrome[left][right]=text.charAt(left)==text.charAt(right)&&(length<=2||palindrome[left+1][right-1]);}for(int first=0;first<n-2;first++)for(int second=first+1;second<n-1;second++)if(palindrome[0][first]&&palindrome[first+1][second]&&palindrome[second+1][n-1])return true;return false;} }`,
`class Solution { fun checkPartitioning(text:String):Boolean{val n=text.length;val palindrome=Array(n){BooleanArray(n)};for(length in 1..n)for(left in 0..n-length){val right=left+length-1;palindrome[left][right]=text[left]==text[right]&&(length<=2||palindrome[left+1][right-1])};for(first in 0 until n-2)for(second in first+1 until n-1)if(palindrome[0][first]&&palindrome[first+1][second]&&palindrome[second+1][n-1])return true;return false} }`,
`class Solution { public: bool checkPartitioning(string text){int n=text.size();vector<vector<bool>> palindrome(n,vector<bool>(n));for(int length=1;length<=n;++length)for(int left=0;left+length<=n;++left){int right=left+length-1;palindrome[left][right]=text[left]==text[right]&&(length<=2||palindrome[left+1][right-1]);}for(int first=0;first<n-2;++first)for(int second=first+1;second<n-1;++second)if(palindrome[0][first]&&palindrome[first+1][second]&&palindrome[second+1][n-1])return true;return false;} };`)],tests:{schemaVersion:1,mode:'function',method:'checkPartitioning',parameterTypes:['string'],returnType:'boolean',cases:[{name:'a bcb dd 三段均回文',args:['abcbdd'],expected:true},{name:'无法切成三个回文段',args:['bcbddxy'],expected:false},{name:'三个单字符均为回文',args:['aaa'],expected:true}]}},
{id:1748,slug:'sum-of-unique-elements',title:'唯一元素的和',studyTags:['数组','哈希表','计数'],summary:'若一个元素在数组中恰好出现一次则为唯一元素，返回所有唯一元素之和。',insight:'先统计每个值频次，再累加频次等于一的键。',pitfalls:['重复两次或更多都不计入','累加数值而非唯一元素数量','数组元素均为正数'],solutions:[s('frequency-then-sum','频次统计后求和','用哈希表区分恰好出现一次的元素。',['哈希表统计 frequency','answer=0','遍历键值对，count==1 时 answer+=value'],'O(n)','O(n)',
`class Solution { public int sumOfUnique(int[] nums){Map<Integer,Integer> frequency=new HashMap<>();for(int value:nums)frequency.put(value,frequency.getOrDefault(value,0)+1);int answer=0;for(Map.Entry<Integer,Integer> entry:frequency.entrySet())if(entry.getValue()==1)answer+=entry.getKey();return answer;} }`,
`class Solution { fun sumOfUnique(nums:IntArray):Int=nums.toList().groupingBy{it}.eachCount().filterValues{it==1}.keys.sum() }`,
`class Solution { public: int sumOfUnique(vector<int>& nums){unordered_map<int,int> frequency;for(int value:nums)++frequency[value];int answer=0;for(auto [value,count]:frequency)if(count==1)answer+=value;return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'sumOfUnique',parameterTypes:['intArray'],returnType:'int',cases:[{name:'一二三唯一元素和四',args:[[1,2,3,2]],expected:4},{name:'所有元素重复和为零',args:[[1,1,1,1,1]],expected:0},{name:'全部唯一求总和六',args:[[1,2,3]],expected:6}]}},
{id:1749,slug:'maximum-absolute-sum-of-any-subarray',title:'任意子数组和的绝对值的最大值',studyTags:['数组','动态规划','前缀和'],summary:'在所有可能为空的连续子数组中，求子数组和绝对值的最大值。',insight:'任意子数组和是两个前缀和之差，绝对值最大值就是扫描过程中全局最大前缀和与最小前缀和之差。',pitfalls:['空子数组保证答案至少为零','前缀和包含初始零','同时更新最大与最小前缀'],solutions:[s('prefix-extreme-gap','前缀和极差','用所有前缀和中的最大差覆盖正负两类子数组。',['prefix=minimum=maximum=0','扫描 value：prefix+=value','minimum=min(minimum,prefix)，maximum=max(maximum,prefix)，返回 maximum-minimum'],'O(n)','O(1)',
`class Solution { public int maxAbsoluteSum(int[] nums){int prefix=0,minimum=0,maximum=0;for(int value:nums){prefix+=value;minimum=Math.min(minimum,prefix);maximum=Math.max(maximum,prefix);}return maximum-minimum;} }`,
`class Solution { fun maxAbsoluteSum(nums:IntArray):Int{var prefix=0;var minimum=0;var maximum=0;for(value in nums){prefix+=value;minimum=minOf(minimum,prefix);maximum=maxOf(maximum,prefix)};return maximum-minimum} }`,
`class Solution { public: int maxAbsoluteSum(vector<int>& nums){int prefix=0,minimum=0,maximum=0;for(int value:nums){prefix+=value;minimum=min(minimum,prefix);maximum=max(maximum,prefix);}return maximum-minimum;} };`)],tests:{schemaVersion:1,mode:'function',method:'maxAbsoluteSum',parameterTypes:['intArray'],returnType:'int',cases:[{name:'最大绝对子数组和五',args:[[1,-3,2,3,-4]],expected:5},{name:'负和子数组绝对值八',args:[[2,-5,1,-4,3,-2]],expected:8},{name:'单个零答案零',args:[[0]],expected:0}]}},
{id:1750,slug:'minimum-length-of-string-after-deleting-similar-ends',title:'删除字符串两端相同字符后的最短长度',studyTags:['双指针','字符串'],summary:'若字符串首尾字符相同，可同时删除非空且不重叠的同字符前缀和后缀，反复操作后求最短长度。',insight:'当两端字符相等时，最优一次删掉两端该字符的整段。双指针跳过左端连续段和右端连续段，直到两端不同或相遇。',pitfalls:['前后缀不能重叠','一次操作的前后缀都由同一字符组成','全部删完时返回零'],solutions:[s('two-end-run-removal','两端同字符段双指针','每轮最大化删除当前可删的两侧连续段。',['left=0,right=n-1','while left<right 且 chars 相同，记 target','while left<=right 且 text[left]==target 左移；同理从右跳过 target','返回 max(0,right-left+1)'],'O(n)','O(1)',
`class Solution { public int minimumLength(String text){int left=0,right=text.length()-1;while(left<right&&text.charAt(left)==text.charAt(right)){char target=text.charAt(left);while(left<=right&&text.charAt(left)==target)left++;while(left<=right&&text.charAt(right)==target)right--;}return Math.max(0,right-left+1);} }`,
`class Solution { fun minimumLength(text:String):Int{var left=0;var right=text.lastIndex;while(left<right&&text[left]==text[right]){val target=text[left];while(left<=right&&text[left]==target)left++;while(left<=right&&text[right]==target)right--};return maxOf(0,right-left+1)} }`,
`class Solution { public: int minimumLength(string text){int left=0,right=text.size()-1;while(left<right&&text[left]==text[right]){char target=text[left];while(left<=right&&text[left]==target)++left;while(left<=right&&text[right]==target)--right;}return max(0,right-left+1);} };`)],tests:{schemaVersion:1,mode:'function',method:'minimumLength',parameterTypes:['string'],returnType:'int',cases:[{name:'两端不同无法删除',args:['ca'],expected:2},{name:'多轮删除后全部清空',args:['cabaabac'],expected:0},{name:'删除两端 a 后剩余 bccab',args:['aabccabba'],expected:3}]}}
]}
