const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-006',problems:[
{id:451,slug:'sort-characters-by-frequency',title:'根据字符出现频率排序',studyTags:['字符计数','排序','字符串'],summary:'把字符串字符按出现频率从高到低重排；同频顺序不限，本实现按字符码升序稳定输出。',insight:'先计数不同字符，再只对字符种类排序，最后按频次重复追加。',pitfalls:['相同字符必须聚集输出','同频可任意但稳定规则便于测试','大小写视为不同字符'],solutions:[s('frequency-sort','频次排序字符种类','固定 ASCII 计数后按频次降序、字符升序排列。',['统计每个字符频次','收集出现过的字符并排序','按排序顺序重复追加 count 次'],'O(n+σ log σ)','O(σ)',
`class Solution { public String frequencySort(String s){int[] counts=new int[128];List<Integer> chars=new ArrayList<>();for(char c:s.toCharArray())counts[c]++;for(int c=0;c<counts.length;c++)if(counts[c]>0)chars.add(c);chars.sort((a,b)->counts[a]!=counts[b]?Integer.compare(counts[b],counts[a]):Integer.compare(a,b));StringBuilder answer=new StringBuilder();for(int c:chars)for(int i=0;i<counts[c];i++)answer.append((char)c);return answer.toString();} }`,
`class Solution { fun frequencySort(s:String):String{val counts=IntArray(128);for(c in s)counts[c.code]++;val chars=(counts.indices.filter{counts[it]>0}).sortedWith(compareByDescending<Int>{counts[it]}.thenBy{it});val answer=StringBuilder();for(c in chars)repeat(counts[c]){answer.append(c.toChar())};return answer.toString()} }`,
`class Solution { public: string frequencySort(string s){array<int,128> counts{};for(unsigned char c:s)++counts[c];vector<int> chars;for(int c=0;c<128;++c)if(counts[c])chars.push_back(c);sort(chars.begin(),chars.end(),[&](int a,int b){return counts[a]!=counts[b]?counts[a]>counts[b]:a<b;});string answer;for(int c:chars)answer.append(counts[c],char(c));return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'frequencySort',parameterTypes:['string'],returnType:'string',cases:[{name:'最高频字符前置',args:['tree'],expected:'eert'},{name:'同频按字符升序',args:['cccaaa'],expected:'aaaccc'},{name:'区分大小写',args:['Aabb'],expected:'bbAa'}]}},
{id:452,slug:'minimum-number-of-arrows-to-burst-balloons',title:'用最少数量的箭引爆气球',studyTags:['贪心','区间排序','活动选择'],summary:'每支竖直箭能引爆横坐标区间包含该位置的所有气球，求引爆全部气球的最少箭数。',insight:'按区间右端点升序，在当前箭位置无法覆盖下一个区间时，才在该区间右端点新增一支箭。',pitfalls:['端点相接可被同一支箭引爆','坐标可能接近整数边界','输入至少有一个气球'],solutions:[s('earliest-end-arrow','按最早右端点放箭','每支箭放在当前可覆盖区间的最早右端点，最大化后续覆盖。',['按 end 升序排序','arrows=1, position=第一个 end','若 interval.start>position 则新增箭并更新 position'],'O(n log n)','O(log n)',
`class Solution { public int findMinArrowShots(int[][] points){Arrays.sort(points,(a,b)->Integer.compare(a[1],b[1]));int arrows=1;long position=points[0][1];for(int i=1;i<points.length;i++)if(points[i][0]>position){arrows++;position=points[i][1];}return arrows;} }`,
`class Solution { fun findMinArrowShots(points:Array<IntArray>):Int{points.sortWith(Comparator.comparingInt{it[1]});var arrows=1;var position=points[0][1].toLong();for(i in 1 until points.size)if(points[i][0]>position){arrows++;position=points[i][1].toLong()};return arrows} }`,
`class Solution { public: int findMinArrowShots(vector<vector<int>>& points){sort(points.begin(),points.end(),[](const auto& a,const auto& b){return a[1]<b[1];});int arrows=1;long long position=points[0][1];for(int i=1;i<(int)points.size();++i)if(points[i][0]>position){++arrows;position=points[i][1];}return arrows;} };`)],tests:{schemaVersion:1,mode:'function',method:'findMinArrowShots',parameterTypes:['intMatrix'],returnType:'int',cases:[{name:'两支箭覆盖四区间',args:[[[10,16],[2,8],[1,6],[7,12]]],expected:2},{name:'互不重叠',args:[[[1,2],[3,4],[5,6],[7,8]]],expected:4},{name:'端点相接可共用',args:[[[1,2],[2,3],[3,4],[4,5]]],expected:2}]}},
{id:453,slug:'minimum-moves-to-equal-array-elements',title:'最小操作次数使数组元素相等',studyTags:['数学','等价变换','数组'],summary:'每次可把除一个元素外的所有元素加一，求使所有元素相等的最少操作次数。',insight:'给 n-1 个元素加一等价于给被排除元素减一并忽略整体平移，因此最优是把所有值降到最小值。',pitfalls:['不是把元素都增到最大值','答案为 sum-min*n','中间和用长整型更稳健'],solutions:[s('sum-minus-minimum','等价为单元素减一','计算每个元素到数组最小值的差之和。',['扫描求 min 与 sum','计算 sum-min*length','返回结果'],'O(n)','O(1)',
`class Solution { public int minMoves(int[] nums){long sum=0;int minimum=Integer.MAX_VALUE;for(int value:nums){sum+=value;minimum=Math.min(minimum,value);}return(int)(sum-(long)minimum*nums.length);} }`,
`class Solution { fun minMoves(nums:IntArray):Int{var sum=0L;var minimum=Int.MAX_VALUE;for(value in nums){sum+=value;minimum=minOf(minimum,value)};return(sum-minimum.toLong()*nums.size).toInt()} }`,
`class Solution { public: int minMoves(vector<int>& nums){long long sum=0;int minimum=INT_MAX;for(int value:nums){sum+=value;minimum=min(minimum,value);}return sum-1LL*minimum*nums.size();} };`)],tests:{schemaVersion:1,mode:'function',method:'minMoves',parameterTypes:['intArray'],returnType:'int',cases:[{name:'一二三',args:[[1,2,3]],expected:3},{name:'单元素',args:[[1]],expected:0},{name:'含负数',args:[[-1,1]],expected:2}]}},
{id:454,slug:'4sum-ii',title:'四数相加 II',studyTags:['哈希表','分组求和','计数'],summary:'从四个等长整数数组中各选一个元素，统计四数之和为零的下标四元组数量。',insight:'把四数组分成两组，统计前两数组每种和的频次，再查询后两数组和的相反数。',pitfalls:['统计的是下标组合而非不同数值组合','相同和需要记录频次','无需排序数组'],solutions:[s('pair-sum-frequency','两两分组哈希计数','将四重枚举拆成两个二重枚举。',['枚举 nums1/nums2 并统计 sum 频次','枚举 nums3/nums4 的 sum','answer 累加 counts[-sum]'],'O(n²)','O(n²)',
`class Solution { public int fourSumCount(int[] nums1,int[] nums2,int[] nums3,int[] nums4){Map<Integer,Integer> counts=new HashMap<>();for(int a:nums1)for(int b:nums2)counts.put(a+b,counts.getOrDefault(a+b,0)+1);int answer=0;for(int c:nums3)for(int d:nums4)answer+=counts.getOrDefault(-c-d,0);return answer;} }`,
`class Solution { fun fourSumCount(nums1:IntArray,nums2:IntArray,nums3:IntArray,nums4:IntArray):Int{val counts=hashMapOf<Int,Int>();for(a in nums1)for(b in nums2)counts[a+b]=(counts[a+b]?:0)+1;var answer=0;for(c in nums3)for(d in nums4)answer+=counts[-c-d]?:0;return answer} }`,
`class Solution { public: int fourSumCount(vector<int>& nums1,vector<int>& nums2,vector<int>& nums3,vector<int>& nums4){unordered_map<int,int> counts;for(int a:nums1)for(int b:nums2)++counts[a+b];int answer=0;for(int c:nums3)for(int d:nums4)answer+=counts[-c-d];return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'fourSumCount',parameterTypes:['intArray','intArray','intArray','intArray'],returnType:'int',cases:[{name:'两个四元组',args:[[1,2],[-2,-1],[-1,2],[0,2]],expected:2},{name:'全零单元素',args:[[0],[0],[0],[0]],expected:1},{name:'重复零产生十六组',args:[[0,0],[0,0],[0,0],[0,0]],expected:16}]}},
{id:455,slug:'assign-cookies',title:'分发饼干',studyTags:['贪心','排序','双指针'],summary:'每个孩子有胃口值、每块饼干有尺寸，一块饼干最多给一个孩子，求最多满足多少孩子。',insight:'按胃口和尺寸升序，用当前最小能满足的饼干喂当前最小胃口孩子，避免浪费大饼干。',pitfalls:['每块饼干只能用一次','尺寸必须不小于胃口','无法满足当前孩子时换更大的饼干'],solutions:[s('sorted-two-pointers','排序后最小可行匹配','双指针贪心匹配孩子与饼干。',['g 和 s 升序排序','若 cookie>=appetite 则孩子指针前进','每轮饼干指针前进，返回已满足孩子数'],'O(m log m+n log n)','O(log m+log n)',
`class Solution { public int findContentChildren(int[] g,int[] s){Arrays.sort(g);Arrays.sort(s);int child=0;for(int cookie:s)if(child<g.length&&cookie>=g[child])child++;return child;} }`,
`class Solution { fun findContentChildren(g:IntArray,s:IntArray):Int{g.sort();s.sort();var child=0;for(cookie in s)if(child<g.size&&cookie>=g[child])child++;return child} }`,
`class Solution { public: int findContentChildren(vector<int>& g,vector<int>& s){sort(g.begin(),g.end());sort(s.begin(),s.end());int child=0;for(int cookie:s)if(child<(int)g.size()&&cookie>=g[child])++child;return child;} };`)],tests:{schemaVersion:1,mode:'function',method:'findContentChildren',parameterTypes:['intArray','intArray'],returnType:'int',cases:[{name:'一块饼干满足一个',args:[[1,2,3],[1,1]],expected:1},{name:'两块饼干满足两个',args:[[1,2],[1,2,3]],expected:2},{name:'没有足够大饼干',args:[[5],[1,2,3]],expected:0}]}}
]}
