const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-006',problems:[
{id:441,slug:'arranging-coins',title:'排列硬币',studyTags:['二分查找','数学','三角数'],summary:'用 n 枚硬币排列阶梯，第 k 行需要 k 枚，求能完整排出的行数。',insight:'完成 k 行需要 k(k+1)/2 枚硬币，该需求随 k 单调增加，可二分最大可行值。',pitfalls:['最后一行不完整不能计入','乘法使用长整型','寻找的是最后一个满足条件的 k'],solutions:[s('binary-search-rows','二分最大完整行','在零到 n 中判断三角数是否不超过硬币数。',['left=0,right=n','middle 取上中位避免死循环','need<=n 时保留 middle 并右移，否则左移 right'],'O(log n)','O(1)',
`class Solution { public int arrangeCoins(int n){long left=0,right=n;while(left<right){long middle=left+(right-left+1)/2;if(middle*(middle+1)/2<=n)left=middle;else right=middle-1;}return(int)left;} }`,
`class Solution { fun arrangeCoins(n:Int):Int{var left=0L;var right=n.toLong();while(left<right){val middle=left+(right-left+1)/2;if(middle*(middle+1)/2<=n)left=middle else right=middle-1};return left.toInt()} }`,
`class Solution { public: int arrangeCoins(int n){long long left=0,right=n;while(left<right){long long middle=left+(right-left+1)/2;if(middle*(middle+1)/2<=n)left=middle;else right=middle-1;}return left;} };`)],tests:{schemaVersion:1,mode:'function',method:'arrangeCoins',parameterTypes:['int'],returnType:'int',cases:[{name:'五枚硬币两行',args:[5],expected:2},{name:'八枚硬币三行',args:[8],expected:3},{name:'一枚硬币',args:[1],expected:1}]}},
{id:442,slug:'find-all-duplicates-in-an-array',title:'数组中重复的数据',studyTags:['原地标记','数组','下标映射'],summary:'数组长度为 n、值在一到 n 且每个值出现一或两次，返回所有出现两次的值。',insight:'把值 value 映射到下标 value-1，首次访问将该位置取负，第二次发现已为负即可确认重复。',pitfalls:['读取当前值时要取绝对值','修改数组符号不影响值域映射','结果顺序不限，本实现排序后返回'],solutions:[s('sign-marking','符号原地标记','利用输入值域与下标一一映射，把数组本身作为访问位图。',['遍历 nums 并取 value=abs(item)','index=value-1','nums[index]<0 时记录 value，否则取负，最后排序'],'O(n+k log k)','O(1) excluding output',
`class Solution { public List<Integer> findDuplicates(int[] nums){List<Integer> answer=new ArrayList<>();for(int item:nums){int value=Math.abs(item),index=value-1;if(nums[index]<0)answer.add(value);else nums[index]=-nums[index];}Collections.sort(answer);return answer;} }`,
`class Solution { fun findDuplicates(nums:IntArray):List<Int>{val answer=mutableListOf<Int>();for(item in nums){val value=kotlin.math.abs(item);val index=value-1;if(nums[index]<0)answer.add(value)else nums[index]=-nums[index]};answer.sort();return answer} }`,
`class Solution { public: vector<int> findDuplicates(vector<int>& nums){vector<int> answer;for(int item:nums){int value=abs(item),index=value-1;if(nums[index]<0)answer.push_back(value);else nums[index]=-nums[index];}sort(answer.begin(),answer.end());return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'findDuplicates',parameterTypes:['intArray'],returnType:'intList',cases:[{name:'两个重复值',args:[[4,3,2,7,8,2,3,1]],expected:[2,3]},{name:'一个重复值',args:[[1,1,2]],expected:[1]},{name:'没有重复值',args:[[1]],expected:[]}]}},
{id:445,slug:'add-two-numbers-ii',title:'两数相加 II',studyTags:['链表','栈','进位'],summary:'两个链表按最高位到最低位保存非负整数，在不修改输入的情况下返回它们的和链表。',insight:'先把两条链表的数字压栈，再从低位弹出做加法，每个新节点头插到结果前方。',pitfalls:['输入顺序与加法处理顺序相反','最高位可能产生额外进位','结果仍需按最高位在前'],solutions:[s('two-stacks-head-insert','双栈逆序加法','栈提供低位优先顺序，头插恢复高位在前的链表。',['遍历两链表分别压栈','弹栈数字加 carry','创建 sum%10 节点并指向当前结果头，更新 carry'],'O(m+n)','O(m+n)',
`class Solution { public ListNode addTwoNumbers(ListNode l1,ListNode l2){Deque<Integer> first=new ArrayDeque<>(),second=new ArrayDeque<>();for(;l1!=null;l1=l1.next)first.push(l1.val);for(;l2!=null;l2=l2.next)second.push(l2.val);ListNode head=null;int carry=0;while(!first.isEmpty()||!second.isEmpty()||carry>0){int sum=carry+(first.isEmpty()?0:first.pop())+(second.isEmpty()?0:second.pop());head=new ListNode(sum%10,head);carry=sum/10;}return head;} }`,
`class Solution { fun addTwoNumbers(firstNode:ListNode?,secondNode:ListNode?):ListNode?{val first=ArrayDeque<Int>();val second=ArrayDeque<Int>();var l1=firstNode;var l2=secondNode;while(l1!=null){first.addLast(l1.\`val\`);l1=l1.next};while(l2!=null){second.addLast(l2.\`val\`);l2=l2.next};var head:ListNode?=null;var carry=0;while(first.isNotEmpty()||second.isNotEmpty()||carry>0){val sum=carry+(if(first.isEmpty())0 else first.removeLast())+(if(second.isEmpty())0 else second.removeLast());val node=ListNode(sum%10);node.next=head;head=node;carry=sum/10};return head} }`,
`class Solution { public: ListNode* addTwoNumbers(ListNode* l1,ListNode* l2){vector<int> first,second;for(;l1;l1=l1->next)first.push_back(l1->val);for(;l2;l2=l2->next)second.push_back(l2->val);ListNode* head=nullptr;int carry=0;while(!first.empty()||!second.empty()||carry){int sum=carry;if(!first.empty()){sum+=first.back();first.pop_back();}if(!second.empty()){sum+=second.back();second.pop_back();}head=new ListNode(sum%10,head);carry=sum/10;}return head;} };`)],tests:{schemaVersion:1,mode:'function',method:'addTwoNumbers',parameterTypes:['listNode','listNode'],returnType:'listNode',cases:[{name:'不同长度相加',args:[[7,2,4,3],[5,6,4]],expected:[7,8,0,7]},{name:'产生最高位进位',args:[[9,9,9],[1]],expected:[1,0,0,0]},{name:'两个零',args:[[0],[0]],expected:[0]}]}},
{id:447,slug:'number-of-boomerangs',title:'回旋镖的数量',studyTags:['哈希表','几何','计数'],summary:'统计有序点三元组 (i,j,k) 的数量，使 j 与 k 到 i 的距离相等且下标互不相同。',insight:'固定中心 i，按平方距离分组；每遇到同距离的第 count 个点，会与此前 count 个点形成两个有序排列。',pitfalls:['三元组有顺序，j/k 交换算不同','使用平方距离无需开方','每个中心都要清空频次表'],solutions:[s('distance-frequency','按中心统计距离频次','逐中心累加同距离点的有序配对数量。',['枚举 center','建立 distance 到 count 映射','每个新点贡献 2*已有 count，再递增 count'],'O(n²)','O(n)',
`class Solution { public int numberOfBoomerangs(int[][] points){int answer=0;for(int[] center:points){Map<Long,Integer> counts=new HashMap<>();for(int[] point:points){long dx=(long)center[0]-point[0],dy=(long)center[1]-point[1],distance=dx*dx+dy*dy;int count=counts.getOrDefault(distance,0);answer+=2*count;counts.put(distance,count+1);}}return answer;} }`,
`class Solution { fun numberOfBoomerangs(points:Array<IntArray>):Int{var answer=0;for(center in points){val counts=hashMapOf<Long,Int>();for(point in points){val dx=center[0].toLong()-point[0];val dy=center[1].toLong()-point[1];val distance=dx*dx+dy*dy;val count=counts[distance]?:0;answer+=2*count;counts[distance]=count+1}};return answer} }`,
`class Solution { public: int numberOfBoomerangs(vector<vector<int>>& points){int answer=0;for(auto& center:points){unordered_map<long long,int> counts;for(auto& point:points){long long dx=(long long)center[0]-point[0],dy=(long long)center[1]-point[1],distance=dx*dx+dy*dy;int count=counts[distance];answer+=2*count;counts[distance]=count+1;}}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'numberOfBoomerangs',parameterTypes:['intMatrix'],returnType:'int',cases:[{name:'三个共线点',args:[[[0,0],[1,0],[2,0]]],expected:2},{name:'单点',args:[[[1,1]]],expected:0},{name:'正方形四点',args:[[[0,0],[0,1],[1,0],[1,1]]],expected:8}]}},
{id:448,slug:'find-all-numbers-disappeared-in-an-array',title:'找到所有数组中消失的数字',studyTags:['原地标记','数组','下标映射'],summary:'长度为 n 的数组值都在一到 n，返回该范围中没有出现的所有数字。',insight:'把出现过的 value 映射到 value-1 下标并将该位置取负，最终仍为正的位置对应缺失值。',pitfalls:['标记时对当前值取绝对值','重复出现只需保持负号','扫描下标升序自然得到升序答案'],solutions:[s('sign-presence-marking','符号存在性标记','利用数组本身记录每个一到 n 的值是否出现。',['遍历 value=abs(item)','令 nums[value-1] 为负','再次扫描，正值下标 index 对应缺失 index+1'],'O(n)','O(1) excluding output',
`class Solution { public List<Integer> findDisappearedNumbers(int[] nums){for(int item:nums){int index=Math.abs(item)-1;nums[index]=-Math.abs(nums[index]);}List<Integer> answer=new ArrayList<>();for(int i=0;i<nums.length;i++)if(nums[i]>0)answer.add(i+1);return answer;} }`,
`class Solution { fun findDisappearedNumbers(nums:IntArray):List<Int>{for(item in nums){val index=kotlin.math.abs(item)-1;nums[index]=-kotlin.math.abs(nums[index])};val answer=mutableListOf<Int>();for(i in nums.indices)if(nums[i]>0)answer.add(i+1);return answer} }`,
`class Solution { public: vector<int> findDisappearedNumbers(vector<int>& nums){for(int item:nums){int index=abs(item)-1;nums[index]=-abs(nums[index]);}vector<int> answer;for(int i=0;i<(int)nums.size();++i)if(nums[i]>0)answer.push_back(i+1);return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'findDisappearedNumbers',parameterTypes:['intArray'],returnType:'intList',cases:[{name:'缺失五和六',args:[[4,3,2,7,8,2,3,1]],expected:[5,6]},{name:'缺失二',args:[[1,1]],expected:[2]},{name:'没有缺失',args:[[1,2,3]],expected:[]}]}}
]}
