const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-008',problems:[
{id:665,slug:'non-decreasing-array',title:'非递减数列',studyTags:['数组','贪心','一次扫描'],summary:'最多修改数组中一个元素，判断能否使整个数组变成非递减序列。',insight:'遇到 nums[i-1]>nums[i] 时必须修改其中一个；若 nums[i] 仍不小于 nums[i-2]，优先降低前者，否则只能抬高当前值。',pitfalls:['第二次逆序立即失败','修改方向要兼顾前一个与后续关系','数组前两个位置的逆序可直接降低第一个'],solutions:[s('greedy-local-repair','局部逆序贪心修复','扫描时原地修复唯一可能的逆序，保持已扫描前缀非递减。',['violations=0','若 nums[i-1]>nums[i]，计数并在超过一时失败','若 i<2 或 nums[i]>=nums[i-2] 则令 nums[i-1]=nums[i]，否则令 nums[i]=nums[i-1]；结束返回真'],'O(n)','O(1)',
`class Solution { public boolean checkPossibility(int[] nums){int violations=0;for(int i=1;i<nums.length;i++)if(nums[i-1]>nums[i]){if(++violations>1)return false;if(i<2||nums[i]>=nums[i-2])nums[i-1]=nums[i];else nums[i]=nums[i-1];}return true;} }`,
`class Solution { fun checkPossibility(nums:IntArray):Boolean{var violations=0;for(i in 1 until nums.size)if(nums[i-1]>nums[i]){if(++violations>1)return false;if(i<2||nums[i]>=nums[i-2])nums[i-1]=nums[i] else nums[i]=nums[i-1]};return true} }`,
`class Solution { public: bool checkPossibility(vector<int>& nums){int violations=0;for(int i=1;i<(int)nums.size();++i)if(nums[i-1]>nums[i]){if(++violations>1)return false;if(i<2||nums[i]>=nums[i-2])nums[i-1]=nums[i];else nums[i]=nums[i-1];}return true;} };`)],tests:{schemaVersion:1,mode:'function',method:'checkPossibility',parameterTypes:['intArray'],returnType:'boolean',cases:[{name:'降低四即可',args:[[4,2,3]],expected:true},{name:'存在两处逆序',args:[[4,2,1]],expected:false},{name:'需要抬高当前值',args:[[3,4,2,3]],expected:false}]}},
{id:667,slug:'beautiful-arrangement-ii',title:'优美的排列 II',studyTags:['数组','数学','构造'],summary:'构造 1 到 n 的排列，使相邻元素绝对差恰好有 k 种不同取值。',insight:'在区间 [1,k+1] 内交替取最小和最大，可依次产生 k,k-1,...,1；剩余数字按升序追加只重复差值 1。',pitfalls:['k 范围是 1 到 n-1','每个 1 到 n 的数字必须恰好出现一次','追加部分不能引入新的差值'],solutions:[s('alternating-low-high','低高交替构造前缀','先制造全部 k 种差，再平滑追加剩余整数。',['left=1、right=k+1，轮流加入 left++ 与 right-- 直到相遇','前缀相邻差依次为 k 到 1','把 k+2 到 n 升序追加并返回'],'O(n)','O(n)',
`class Solution { public int[] constructArray(int n,int k){int[] answer=new int[n];int index=0,left=1,right=k+1;while(left<=right){answer[index++]=left++;if(left<=right)answer[index++]=right--;}for(int value=k+2;value<=n;value++)answer[index++]=value;return answer;} }`,
`class Solution { fun constructArray(n:Int,k:Int):IntArray{val answer=IntArray(n);var index=0;var left=1;var right=k+1;while(left<=right){answer[index++]=left++;if(left<=right)answer[index++]=right--};for(value in k+2..n)answer[index++]=value;return answer} }`,
`class Solution { public: vector<int> constructArray(int n,int k){vector<int> answer;int left=1,right=k+1;while(left<=right){answer.push_back(left++);if(left<=right)answer.push_back(right--);}for(int value=k+2;value<=n;++value)answer.push_back(value);return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'constructArray',parameterTypes:['int','int'],returnType:'intArray',cases:[{name:'一种差值',args:[3,1],expected:[1,2,3]},{name:'两种差值',args:[5,2],expected:[1,3,2,4,5]},{name:'差值种类取最大',args:[5,4],expected:[1,5,2,4,3]}]}},
{id:668,slug:'kth-smallest-number-in-multiplication-table',title:'乘法表中第 k 小的数',studyTags:['数学','二分查找','答案二分'],summary:'m×n 乘法表第 i 行第 j 列为 i×j，求表中第 k 小的数。',insight:'对候选值 x，每行不大于 x 的元素数是 min(n,x/row)，总数随 x 单调不减，因此可二分最小满足 count≥k 的 x。',pitfalls:['乘法表中相同数按不同单元格重复计数','二分寻找第一个计数达到 k 的值','搜索上界是 m*n'],solutions:[s('binary-search-value','按值域二分计数','用每行整除结果计算不大于中点的表格元素数量。',['left=1、right=m*n','计算 middle，并求 count=Σmin(n,middle/row)','count>=k 时保留 middle 收缩右界，否则左界右移；返回 left'],'O(m log(mn))','O(1)',
`class Solution { public int findKthNumber(int m,int n,int k){int left=1,right=m*n;while(left<right){int middle=left+(right-left)/2;int count=0;for(int row=1;row<=m;row++)count+=Math.min(n,middle/row);if(count>=k)right=middle;else left=middle+1;}return left;} }`,
`class Solution { fun findKthNumber(m:Int,n:Int,k:Int):Int{var left=1;var right=m*n;while(left<right){val middle=left+(right-left)/2;var count=0;for(row in 1..m)count+=minOf(n,middle/row);if(count>=k)right=middle else left=middle+1};return left} }`,
`class Solution { public: int findKthNumber(int m,int n,int k){int left=1,right=m*n;while(left<right){int middle=left+(right-left)/2,count=0;for(int row=1;row<=m;++row)count+=min(n,middle/row);if(count>=k)right=middle;else left=middle+1;}return left;} };`)],tests:{schemaVersion:1,mode:'function',method:'findKthNumber',parameterTypes:['int','int','int'],returnType:'int',cases:[{name:'三乘三第五小',args:[3,3,5],expected:3},{name:'二乘三最大项',args:[2,3,6],expected:6},{name:'单行乘法表',args:[1,10,7],expected:7}]}},
{id:669,slug:'trim-a-binary-search-tree',title:'修剪二叉搜索树',studyTags:['二叉搜索树','递归','树修改'],summary:'修剪二叉搜索树，使所有节点值都在闭区间 [low,high] 内，并保持剩余节点相对结构。',insight:'若节点值小于 low，其左子树也全部过小，只需递归修剪右子树；大于 high 时对称处理左子树。',pitfalls:['被删除节点的合法子树要向上接回','区间端点值需要保留','可原地修改孩子指针'],solutions:[s('bst-pruning-recursion','利用 BST 有序性剪枝','根据当前值与区间关系整棵跳过不可能的一侧。',['空节点返回空','node.val<low 返回 trim(node.right)，node.val>high 返回 trim(node.left)','区间内节点递归修剪两个孩子后返回自身'],'O(n)','O(h)',
`class Solution { public TreeNode trimBST(TreeNode root,int low,int high){if(root==null)return null;if(root.val<low)return trimBST(root.right,low,high);if(root.val>high)return trimBST(root.left,low,high);root.left=trimBST(root.left,low,high);root.right=trimBST(root.right,low,high);return root;} }`,
`class Solution { fun trimBST(root:TreeNode?,low:Int,high:Int):TreeNode?{if(root==null)return null;if(root.\`val\`<low)return trimBST(root.right,low,high);if(root.\`val\`>high)return trimBST(root.left,low,high);root.left=trimBST(root.left,low,high);root.right=trimBST(root.right,low,high);return root} }`,
`class Solution { public: TreeNode* trimBST(TreeNode* root,int low,int high){if(!root)return nullptr;if(root->val<low)return trimBST(root->right,low,high);if(root->val>high)return trimBST(root->left,low,high);root->left=trimBST(root->left,low,high);root->right=trimBST(root->right,low,high);return root;} };`)],tests:{schemaVersion:1,mode:'function',method:'trimBST',parameterTypes:['treeNode','int','int'],returnType:'treeNode',cases:[{name:'删除过小节点',args:[[1,0,2],1,2],expected:[1,null,2]},{name:'两侧都需修剪',args:[[3,0,4,null,2,null,null,1],1,3],expected:[3,2,null,1]},{name:'整棵树超出区间',args:[[1],2,3],expected:[]}]}},
{id:670,slug:'maximum-swap',title:'最大交换',studyTags:['数学','贪心','数字'],summary:'最多交换非负整数中的两个十进制数字一次，得到能形成的最大数。',insight:'记录每个数字最后出现位置，从高位开始寻找右侧存在的最大更大数字；第一次可交换位置决定最高有效位，立即交换最优。',pitfalls:['同一较大数字应选择最右出现位置','已经最大时不交换','允许交换零但不能制造前导零，因为只用更大数字换高位'],solutions:[s('last-position-greedy','数字最后位置贪心','优先提升最靠左的可提升位，并换入右侧最大数字。',['记录 0 到 9 的最后下标','从左到右扫描当前位置 digit','从 9 递减寻找 digit 更大且最后位置在右侧的数字，找到即交换并返回；无则返回原数'],'O(d)','O(1)',
`class Solution { public int maximumSwap(int num){char[] digits=String.valueOf(num).toCharArray();int[] last=new int[10];for(int i=0;i<digits.length;i++)last[digits[i]-'0']=i;for(int i=0;i<digits.length;i++)for(int digit=9;digit>digits[i]-'0';digit--)if(last[digit]>i){char value=digits[i];digits[i]=(char)('0'+digit);digits[last[digit]]=value;return Integer.parseInt(new String(digits));}return num;} }`,
`class Solution { fun maximumSwap(num:Int):Int{val digits=num.toString().toCharArray();val last=IntArray(10);for(i in digits.indices)last[digits[i]-'0']=i;for(i in digits.indices)for(digit in 9 downTo digits[i]-'0'+1)if(last[digit]>i){val value=digits[i];digits[i]=('0'.code+digit).toChar();digits[last[digit]]=value;return String(digits).toInt()};return num} }`,
`class Solution { public: int maximumSwap(int num){string digits=to_string(num);int last[10]{};for(int i=0;i<(int)digits.size();++i)last[digits[i]-'0']=i;for(int i=0;i<(int)digits.size();++i)for(int digit=9;digit>digits[i]-'0';--digit)if(last[digit]>i){swap(digits[i],digits[last[digit]]);return stoi(digits);}return num;} };`)],tests:{schemaVersion:1,mode:'function',method:'maximumSwap',parameterTypes:['int'],returnType:'int',cases:[{name:'提升最高位',args:[2736],expected:7236},{name:'已经最大',args:[9973],expected:9973},{name:'选择最右侧相同大数字',args:[98368],expected:98863}]}}
]}
