const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-009',problems:[
{id:671,slug:'second-minimum-node-in-a-binary-tree',title:'二叉树中第二小的节点',studyTags:['二叉树','深度优先搜索','剪枝'],summary:'特殊二叉树中每个非叶节点值等于两个孩子的较小值，找出整棵树第二小的不同值，不存在返回 -1。',insight:'根值就是全局最小值；遍历时第一次遇到大于根值的节点后，其后代不可能提供更小候选，可直接返回该值。',pitfalls:['第二小值必须严格大于根值','节点值可能超过有符号整数候选初始化范围','不存在不同值时返回 -1'],solutions:[s('dfs-prune-at-greater','利用特殊树性质 DFS 剪枝','对等于根值的节点继续深入，对更大节点直接作为候选。',['minimum=root.val','dfs 空节点返回无穷大，node.val>minimum 直接返回 node.val','否则取左右递归结果较小者，仍无穷大则返回 -1'],'O(n)','O(h)',
`class Solution { public int findSecondMinimumValue(TreeNode root){long answer=dfs(root,root.val);return answer==Long.MAX_VALUE?-1:(int)answer;}private long dfs(TreeNode node,int minimum){if(node==null)return Long.MAX_VALUE;if(node.val>minimum)return node.val;return Math.min(dfs(node.left,minimum),dfs(node.right,minimum));} }`,
`class Solution { fun findSecondMinimumValue(root:TreeNode?):Int{fun dfs(node:TreeNode?,minimum:Int):Long{if(node==null)return Long.MAX_VALUE;if(node.\`val\`>minimum)return node.\`val\`.toLong();return minOf(dfs(node.left,minimum),dfs(node.right,minimum))};val answer=dfs(root,root!!.\`val\`);return if(answer==Long.MAX_VALUE)-1 else answer.toInt()} }`,
`class Solution { long long dfs(TreeNode* node,int minimum){if(!node)return LLONG_MAX;if(node->val>minimum)return node->val;return min(dfs(node->left,minimum),dfs(node->right,minimum));}public:int findSecondMinimumValue(TreeNode* root){long long answer=dfs(root,root->val);return answer==LLONG_MAX?-1:answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'findSecondMinimumValue',parameterTypes:['treeNode'],returnType:'int',cases:[{name:'次小值为五',args:[[2,2,5,null,null,5,7]],expected:5},{name:'所有值相同',args:[[2,2,2]],expected:-1},{name:'次小值在深层',args:[[1,1,3,1,2]],expected:2}]}},
{id:672,slug:'bulb-switcher-ii',title:'灯泡开关 Ⅱ',studyTags:['数学','状态枚举','位运算'],summary:'n 个初始开启的灯泡，四种固定翻转操作恰好执行 presses 次，求可能得到的不同灯泡状态数量。',insight:'操作模式每两次抵消，且前六盏灯已决定后续周期状态；枚举四个按钮按下奇偶性并筛选总次数奇偶与上限。',pitfalls:['按钮可重复按，最终只看每个按钮次数奇偶','奇数按钮数不能超过 presses 且同奇偶','只需模拟 min(n,6) 盏灯'],solutions:[s('enumerate-button-parity','枚举四按钮奇偶组合','16 种奇偶掩码筛选后模拟灯泡状态并去重。',['枚举 mask 从 0 到 15，令 used=bitCount(mask)','要求 used<=presses 且 (presses-used)%2==0','模拟前 min(n,6) 盏灯受四按钮影响后的位状态，加入集合；返回集合大小'],'O(1)','O(1)',
`class Solution { public int flipLights(int n,int presses){Set<Integer> states=new HashSet<>();int lamps=Math.min(n,6);for(int mask=0;mask<16;mask++){int used=Integer.bitCount(mask);if(used>presses||((presses-used)&1)!=0)continue;int state=0;for(int index=1;index<=lamps;index++){boolean on=true;if((mask&1)!=0)on=!on;if((mask&2)!=0&&index%2==0)on=!on;if((mask&4)!=0&&index%2==1)on=!on;if((mask&8)!=0&&(index-1)%3==0)on=!on;if(on)state|=1<<(index-1);}states.add(state);}return states.size();} }`,
`class Solution { fun flipLights(n:Int,presses:Int):Int{val states=hashSetOf<Int>();val lamps=minOf(n,6);for(mask in 0 until 16){val used=Integer.bitCount(mask);if(used>presses||(presses-used)%2!=0)continue;var state=0;for(index in 1..lamps){var on=true;if(mask and 1!=0)on=!on;if(mask and 2!=0&&index%2==0)on=!on;if(mask and 4!=0&&index%2==1)on=!on;if(mask and 8!=0&&(index-1)%3==0)on=!on;if(on)state=state or (1 shl index-1)};states.add(state)};return states.size} }`,
`class Solution { public: int flipLights(int n,int presses){set<int> states;int lamps=min(n,6);for(int mask=0;mask<16;++mask){int used=__builtin_popcount(mask);if(used>presses||(presses-used)%2)continue;int state=0;for(int index=1;index<=lamps;++index){bool on=true;if(mask&1)on=!on;if((mask&2)&&index%2==0)on=!on;if((mask&4)&&index%2==1)on=!on;if((mask&8)&&(index-1)%3==0)on=!on;if(on)state|=1<<(index-1);}states.insert(state);}return states.size();} };`)],tests:{schemaVersion:1,mode:'function',method:'flipLights',parameterTypes:['int','int'],returnType:'int',cases:[{name:'一盏灯一次操作',args:[1,1],expected:2},{name:'两盏灯一次操作',args:[2,1],expected:3},{name:'三盏灯一次操作',args:[3,1],expected:4}]}},
{id:673,slug:'number-of-longest-increasing-subsequence',title:'最长递增子序列的个数',studyTags:['数组','动态规划','最长递增子序列'],summary:'统计数组中最长严格递增子序列的数量，不同下标选择视为不同子序列。',insight:'对每个结尾 i 同时维护最长长度 length[i] 和达到该长度的方案数 count[i]；从所有更小前驱转移。',pitfalls:['递增条件是严格小于','相同长度前驱的方案数要累加','最终要汇总所有达到全局最长长度的结尾'],solutions:[s('length-and-count-dp','结尾长度与方案数 DP','二重循环同时维护 LIS 长度和计数。',['length、count 初始化为一','对 i 枚举 j<i 且 nums[j]<nums[i]；更长则覆盖长度和计数，同长则累加计数','维护全局最长值，最后累加所有对应 count'],'O(n²)','O(n)',
`class Solution { public int findNumberOfLIS(int[] nums){int n=nums.length;int[] length=new int[n],count=new int[n];Arrays.fill(length,1);Arrays.fill(count,1);int longest=1;for(int i=0;i<n;i++){for(int j=0;j<i;j++)if(nums[j]<nums[i]){if(length[j]+1>length[i]){length[i]=length[j]+1;count[i]=count[j];}else if(length[j]+1==length[i])count[i]+=count[j];}longest=Math.max(longest,length[i]);}int answer=0;for(int i=0;i<n;i++)if(length[i]==longest)answer+=count[i];return answer;} }`,
`class Solution { fun findNumberOfLIS(nums:IntArray):Int{val length=IntArray(nums.size){1};val count=IntArray(nums.size){1};var longest=1;for(i in nums.indices){for(j in 0 until i)if(nums[j]<nums[i]){if(length[j]+1>length[i]){length[i]=length[j]+1;count[i]=count[j]}else if(length[j]+1==length[i])count[i]+=count[j]};longest=maxOf(longest,length[i])};var answer=0;for(i in nums.indices)if(length[i]==longest)answer+=count[i];return answer} }`,
`class Solution { public: int findNumberOfLIS(vector<int>& nums){int n=nums.size();vector<int> length(n,1),count(n,1);int longest=1;for(int i=0;i<n;++i){for(int j=0;j<i;++j)if(nums[j]<nums[i]){if(length[j]+1>length[i]){length[i]=length[j]+1;count[i]=count[j];}else if(length[j]+1==length[i])count[i]+=count[j];}longest=max(longest,length[i]);}int answer=0;for(int i=0;i<n;++i)if(length[i]==longest)answer+=count[i];return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'findNumberOfLIS',parameterTypes:['intArray'],returnType:'int',cases:[{name:'两个最长递增子序列',args:[[1,3,5,4,7]],expected:2},{name:'五个等值单元素序列',args:[[2,2,2,2,2]],expected:5},{name:'唯一最长序列',args:[[1,2,4,3,5,4,7,2]],expected:3}]}},
{id:674,slug:'longest-continuous-increasing-subsequence',title:'最长连续递增序列',studyTags:['数组','一次扫描','动态规划'],summary:'找出整数数组中最长严格连续递增子数组的长度。',insight:'当前元素大于前一个时连续长度加一，否则从当前元素重新开始；扫描中维护最大值。',pitfalls:['要求连续而非一般子序列','相等会中断严格递增','非空数组答案至少为一'],solutions:[s('running-streak','连续递增长度扫描','用一个变量记录以当前位置结尾的递增长度。',['current=best=1','从下标一开始，若 nums[i]>nums[i-1] 则 current++，否则 current=1','best=max(best,current)，结束返回 best'],'O(n)','O(1)',
`class Solution { public int findLengthOfLCIS(int[] nums){int current=1,best=1;for(int i=1;i<nums.length;i++){current=nums[i]>nums[i-1]?current+1:1;best=Math.max(best,current);}return best;} }`,
`class Solution { fun findLengthOfLCIS(nums:IntArray):Int{var current=1;var best=1;for(i in 1 until nums.size){current=if(nums[i]>nums[i-1])current+1 else 1;best=maxOf(best,current)};return best} }`,
`class Solution { public: int findLengthOfLCIS(vector<int>& nums){int current=1,best=1;for(int i=1;i<(int)nums.size();++i){current=nums[i]>nums[i-1]?current+1:1;best=max(best,current);}return best;} };`)],tests:{schemaVersion:1,mode:'function',method:'findLengthOfLCIS',parameterTypes:['intArray'],returnType:'int',cases:[{name:'前三项连续递增',args:[[1,3,5,4,7]],expected:3},{name:'所有元素相同',args:[[2,2,2,2,2]],expected:1},{name:'完整递增',args:[[1,2,3,4]],expected:4}]}},
{id:675,slug:'cut-off-trees-for-golf-event',title:'为高尔夫比赛砍树',studyTags:['矩阵','广度优先搜索','最短路'],summary:'森林网格中零不可通行，大于一的格子是树；必须按树高升序依次砍掉所有树，求最少步数，不可完成返回 -1。',insight:'树的顺序由高度唯一确定；每两个连续目标之间用 BFS 求网格最短路，砍树后该格仍可通行。',pitfalls:['起点固定为左上角','高度各不相同','某一段目标不可达时立即返回 -1'],solutions:[s('sorted-targets-bfs','树高排序与分段 BFS','对固定目标顺序逐段计算无权网格最短距离。',['收集 [height,row,column] 并按 height 排序','从当前位置 BFS 到下一棵树','不可达返回 -1，否则累计距离并更新当前位置；全部完成返回总步数'],'O(t·mn)','O(mn)',
`class Solution { public int cutOffTree(List<List<Integer>> forest){List<int[]> trees=new ArrayList<>();for(int r=0;r<forest.size();r++)for(int c=0;c<forest.get(0).size();c++)if(forest.get(r).get(c)>1)trees.add(new int[]{forest.get(r).get(c),r,c});trees.sort(Comparator.comparingInt(tree->tree[0]));int row=0,column=0,total=0;for(int[] tree:trees){int distance=bfs(forest,row,column,tree[1],tree[2]);if(distance<0)return -1;total+=distance;row=tree[1];column=tree[2];}return total;}private int bfs(List<List<Integer>> forest,int sr,int sc,int tr,int tc){if(sr==tr&&sc==tc)return 0;int rows=forest.size(),columns=forest.get(0).size();boolean[][] seen=new boolean[rows][columns];Queue<int[]> queue=new ArrayDeque<>();queue.offer(new int[]{sr,sc});seen[sr][sc]=true;int steps=0;int[][] directions={{1,0},{-1,0},{0,1},{0,-1}};while(!queue.isEmpty()){steps++;for(int size=queue.size();size>0;size--){int[] cell=queue.poll();for(int[] d:directions){int r=cell[0]+d[0],c=cell[1]+d[1];if(r<0||r>=rows||c<0||c>=columns||seen[r][c]||forest.get(r).get(c)==0)continue;if(r==tr&&c==tc)return steps;seen[r][c]=true;queue.offer(new int[]{r,c});}}}return -1;} }`,
`class Solution { fun cutOffTree(forest:List<List<Int>>):Int{val trees=mutableListOf<IntArray>();for(r in forest.indices)for(c in forest[0].indices)if(forest[r][c]>1)trees.add(intArrayOf(forest[r][c],r,c));trees.sortBy{it[0]};var row=0;var column=0;var total=0;fun bfs(sr:Int,sc:Int,tr:Int,tc:Int):Int{if(sr==tr&&sc==tc)return 0;val seen=Array(forest.size){BooleanArray(forest[0].size)};val queue=java.util.ArrayDeque<IntArray>();queue.add(intArrayOf(sr,sc));seen[sr][sc]=true;val directions=arrayOf(intArrayOf(1,0),intArrayOf(-1,0),intArrayOf(0,1),intArrayOf(0,-1));var steps=0;while(queue.isNotEmpty()){steps++;repeat(queue.size){val cell=queue.remove();for(d in directions){val r=cell[0]+d[0];val c=cell[1]+d[1];if(r !in forest.indices||c !in forest[0].indices||seen[r][c]||forest[r][c]==0)continue;if(r==tr&&c==tc)return steps;seen[r][c]=true;queue.add(intArrayOf(r,c))}}};return -1};for(tree in trees){val distance=bfs(row,column,tree[1],tree[2]);if(distance<0)return -1;total+=distance;row=tree[1];column=tree[2]};return total} }`,
`class Solution { int bfs(vector<vector<int>>& forest,int sr,int sc,int tr,int tc){if(sr==tr&&sc==tc)return 0;int rows=forest.size(),columns=forest[0].size();vector<vector<bool>> seen(rows,vector<bool>(columns));queue<pair<int,int>> pending;pending.push({sr,sc});seen[sr][sc]=true;int directions[4][2]={{1,0},{-1,0},{0,1},{0,-1}},steps=0;while(!pending.empty()){++steps;for(int size=pending.size();size>0;--size){auto [row,column]=pending.front();pending.pop();for(auto& d:directions){int r=row+d[0],c=column+d[1];if(r<0||r>=rows||c<0||c>=columns||seen[r][c]||forest[r][c]==0)continue;if(r==tr&&c==tc)return steps;seen[r][c]=true;pending.push({r,c});}}}return -1;}public:int cutOffTree(vector<vector<int>>& forest){vector<array<int,3>> trees;for(int r=0;r<(int)forest.size();++r)for(int c=0;c<(int)forest[0].size();++c)if(forest[r][c]>1)trees.push_back({forest[r][c],r,c});sort(trees.begin(),trees.end());int row=0,column=0,total=0;for(auto tree:trees){int distance=bfs(forest,row,column,tree[1],tree[2]);if(distance<0)return -1;total+=distance;row=tree[1];column=tree[2];}return total;} };`)],tests:{schemaVersion:1,mode:'function',method:'cutOffTree',parameterTypes:['intListMatrix'],returnType:'int',cases:[{name:'按高度绕行六步',args:[[[1,2,3],[0,0,4],[7,6,5]]],expected:6},{name:'目标区域不可达',args:[[[1,2,3],[0,0,0],[7,6,5]]],expected:-1},{name:'需要回绕到高树',args:[[[2,3,4],[0,0,5],[8,7,6]]],expected:6}]}}
]}
