const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-013',problems:[
{id:930,slug:'binary-subarrays-with-sum',title:'和相同的二元子数组',studyTags:['数组','滑动窗口','前缀和'],summary:'统计二进制数组中元素和恰好等于 goal 的非空连续子数组数量。',insight:'非负数组中，和恰为 goal 的数量等于和至多 goal 的子数组数减去和至多 goal-1 的子数组数；两次滑动窗口即可。',pitfalls:['goal 为零时第二个上界为负应返回零','窗口左端仅在和超上界时移动','每个右端贡献 right-left+1 个至多上界子数组'],solutions:[s('difference-of-at-most-windows','两个至多滑窗作差','把精确和转化为两个单调窗口计数之差。',['定义 atMost(limit)，limit<0 返回零','右指针扩展并累加 nums[right]，和超过 limit 时移动 left','每个 right 累加 right-left+1；返回 atMost(goal)-atMost(goal-1)'],'O(n)','O(1)',
`class Solution { public int numSubarraysWithSum(int[] nums,int goal){return atMost(nums,goal)-atMost(nums,goal-1);}private int atMost(int[] nums,int limit){if(limit<0)return 0;int left=0,sum=0,count=0;for(int right=0;right<nums.length;right++){sum+=nums[right];while(sum>limit)sum-=nums[left++];count+=right-left+1;}return count;} }`,
`class Solution { fun numSubarraysWithSum(nums:IntArray,goal:Int):Int=atMost(nums,goal)-atMost(nums,goal-1);private fun atMost(nums:IntArray,limit:Int):Int{if(limit<0)return 0;var left=0;var sum=0;var count=0;for(right in nums.indices){sum+=nums[right];while(sum>limit)sum-=nums[left++];count+=right-left+1};return count} }`,
`class Solution { int atMost(vector<int>& nums,int limit){if(limit<0)return 0;int left=0,sum=0,count=0;for(int right=0;right<(int)nums.size();++right){sum+=nums[right];while(sum>limit)sum-=nums[left++];count+=right-left+1;}return count;}public:int numSubarraysWithSum(vector<int>& nums,int goal){return atMost(nums,goal)-atMost(nums,goal-1);} };`)],tests:{schemaVersion:1,mode:'function',method:'numSubarraysWithSum',parameterTypes:['intArray','int'],returnType:'int',cases:[{name:'三个一选两个',args:[[1,0,1,0,1],2],expected:4},{name:'全零子数组',args:[[0,0,0,0,0],0],expected:15},{name:'三个一选相邻两个',args:[[1,1,1],2],expected:2}]}},
{id:931,slug:'minimum-falling-path-sum',title:'下降路径最小和',studyTags:['数组','矩阵','动态规划'],summary:'在方阵中从首行出发，每步走到下一行同列或相邻列，求到末行的最小路径和。',insight:'逐行动态规划；到达当前格的最优值是自身加上一行三个可达位置的最小值，可用一维数组滚动。',pitfalls:['左右边界只有两个或一个前驱','矩阵值可能为负','不能原地更新同一行的一维状态'],solutions:[s('row-rolling-dp','逐行滚动动态规划','每行从上一行状态生成全新状态。',['dp 初始化为首行','对每个后续行和每列，取 dp[col]、dp[col-1]、dp[col+1] 中合法项最小值加 matrix[row][col]','用 next 替换 dp，最后返回 dp 最小值'],'O(n²)','O(n)',
`class Solution { public int minFallingPathSum(int[][] matrix){int[] dp=matrix[0].clone();for(int row=1;row<matrix.length;row++){int[] next=new int[matrix.length];for(int col=0;col<matrix.length;col++){int best=dp[col];if(col>0)best=Math.min(best,dp[col-1]);if(col+1<matrix.length)best=Math.min(best,dp[col+1]);next[col]=matrix[row][col]+best;}dp=next;}return Arrays.stream(dp).min().getAsInt();} }`,
`class Solution { fun minFallingPathSum(matrix:Array<IntArray>):Int{var dp=matrix[0].clone();for(row in 1 until matrix.size){val next=IntArray(matrix.size);for(col in matrix.indices){var best=dp[col];if(col>0)best=minOf(best,dp[col-1]);if(col+1<matrix.size)best=minOf(best,dp[col+1]);next[col]=matrix[row][col]+best};dp=next};return dp.minOrNull()!!} }`,
`class Solution { public: int minFallingPathSum(vector<vector<int>>& matrix){vector<int> dp=matrix[0];for(int row=1;row<(int)matrix.size();++row){vector<int> next(matrix.size());for(int col=0;col<(int)matrix.size();++col){int best=dp[col];if(col)best=min(best,dp[col-1]);if(col+1<(int)matrix.size())best=min(best,dp[col+1]);next[col]=matrix[row][col]+best;}dp.swap(next);}return *min_element(dp.begin(),dp.end());} };`)],tests:{schemaVersion:1,mode:'function',method:'minFallingPathSum',parameterTypes:['intMatrix'],returnType:'int',cases:[{name:'三阶方阵',args:[[[2,1,3],[6,5,4],[7,8,9]]],expected:13},{name:'含负数',args:[[[-19,57],[-40,-5]]],expected:-59},{name:'单格',args:[[[1]]],expected:1}]}},
{id:932,slug:'beautiful-array',title:'漂亮数组',studyTags:['数组','分治','数学'],summary:'构造 1 到 n 的排列，使任意 i<k<j 都不存在 2*nums[k]=nums[i]+nums[j]。',insight:'若数组漂亮，把所有元素映射为奇数 2x-1 或偶数 2x 后性质仍成立；奇偶之间又不可能形成等式，因此可迭代扩展。',pitfalls:['只保留不超过 n 的映射值','先奇后偶可得到确定结果','返回值必须是 1 到 n 的完整排列'],solutions:[s('odd-even-constructive-expansion','奇偶映射构造','从单元素漂亮数组反复扩张到目标范围。',['answer 从 [1] 开始','依次加入每个 x 的 2x-1，若不超过 n','再依次加入每个 x 的 2x，若不超过 n；重复直到长度为 n'],'O(n log n)','O(n)',
`class Solution { public int[] beautifulArray(int n){List<Integer> values=new ArrayList<>();values.add(1);while(values.size()<n){List<Integer> next=new ArrayList<>();for(int x:values)if(2*x-1<=n)next.add(2*x-1);for(int x:values)if(2*x<=n)next.add(2*x);values=next;}return values.stream().mapToInt(Integer::intValue).toArray();} }`,
`class Solution { fun beautifulArray(n:Int):IntArray{var values=listOf(1);while(values.size<n){val next=mutableListOf<Int>();for(x in values)if(2*x-1<=n)next.add(2*x-1);for(x in values)if(2*x<=n)next.add(2*x);values=next};return values.toIntArray()} }`,
`class Solution { public: vector<int> beautifulArray(int n){vector<int> values{1};while((int)values.size()<n){vector<int> next;for(int x:values)if(2*x-1<=n)next.push_back(2*x-1);for(int x:values)if(2*x<=n)next.push_back(2*x);values.swap(next);}return values;} };`)],tests:{schemaVersion:1,mode:'function',method:'beautifulArray',parameterTypes:['int'],returnType:'intArray',cases:[{name:'四个数',args:[4],expected:[1,3,2,4]},{name:'五个数',args:[5],expected:[1,5,3,2,4]},{name:'单元素',args:[1],expected:[1]}]}},
{id:933,slug:'number-of-recent-calls',title:'最近的请求次数',studyTags:['设计','队列','数据流'],summary:'实现计数器，ping(t) 返回闭区间 [t-3000,t] 内收到的请求数，调用时间严格递增。',insight:'递增时间让过期请求永远不会再次有效；队列保存窗口内时间，每次弹出小于 t-3000 的队首即可。',pitfalls:['左边界 t-3000 包含在窗口内','先加入当前请求再清理也可','时间递增保证队列有序'],solutions:[s('monotonic-time-queue','单调时间队列','只保留最近三千毫秒的请求时间。',['队列初始为空','ping 时把 t 入队','弹出所有 queue.front<t-3000 的时间，返回队列大小'],'O(1) amortized','O(window calls)',
`class RecentCounter { private final Deque<Integer> times=new ArrayDeque<>();public RecentCounter(){}public int ping(int t){times.offerLast(t);while(times.peekFirst()<t-3000)times.pollFirst();return times.size();} }`,
`class RecentCounter { private val times=java.util.ArrayDeque<Int>();fun ping(t:Int):Int{times.addLast(t);while(times.first<t-3000)times.removeFirst();return times.size} }`,
`class RecentCounter { queue<int> times;public:RecentCounter(){}int ping(int t){times.push(t);while(times.front()<t-3000)times.pop();return times.size();} };`)],tests:{schemaVersion:1,mode:'design',className:'RecentCounter',constructorTypes:[],cases:[{name:'经典请求序列',constructorArgs:[],calls:[{method:'ping',parameterTypes:['int'],args:[1],returnType:'int',expected:1},{method:'ping',parameterTypes:['int'],args:[100],returnType:'int',expected:2},{method:'ping',parameterTypes:['int'],args:[3001],returnType:'int',expected:3},{method:'ping',parameterTypes:['int'],args:[3002],returnType:'int',expected:3}]},{name:'边界包含三千毫秒',constructorArgs:[],calls:[{method:'ping',parameterTypes:['int'],args:[1],returnType:'int',expected:1},{method:'ping',parameterTypes:['int'],args:[3001],returnType:'int',expected:2}]},{name:'旧请求全部过期',constructorArgs:[],calls:[{method:'ping',parameterTypes:['int'],args:[10],returnType:'int',expected:1},{method:'ping',parameterTypes:['int'],args:[20],returnType:'int',expected:2},{method:'ping',parameterTypes:['int'],args:[4000],returnType:'int',expected:1}]}]}},
{id:934,slug:'shortest-bridge',title:'最短的桥',studyTags:['数组','深度优先搜索','广度优先搜索','矩阵'],summary:'二进制方阵恰有两座岛，求最少把多少个零翻成一才能连接它们。',insight:'先洪泛标记第一座岛并把其所有格作为多源 BFS 起点；逐层扩张海水，首次碰到第二座岛的层数就是最短桥长。',pitfalls:['第一座岛的全部边界都应作为搜索源','已访问海水要立即标记避免重复','碰到未标记的一才是第二座岛'],solutions:[s('island-marking-multisource-bfs','岛屿标记与多源 BFS','从第一座岛同时向外扩张。',['找到第一个一，用队列洪泛其连通岛并标记为二，所有岛格加入 frontier','从 frontier 按层 BFS；零格标记为二并入队','若邻居仍是一则返回当前 distance，扩完一层 distance++'],'O(n²)','O(n²)',
`class Solution { public int shortestBridge(int[][] grid){int n=grid.length;Deque<int[]> flood=new ArrayDeque<>(),frontier=new ArrayDeque<>();outer:for(int r=0;r<n;r++)for(int c=0;c<n;c++)if(grid[r][c]==1){flood.offer(new int[]{r,c});grid[r][c]=2;break outer;}int[][] directions={{1,0},{-1,0},{0,1},{0,-1}};while(!flood.isEmpty()){int[] cell=flood.poll();frontier.offer(cell);for(int[] d:directions){int r=cell[0]+d[0],c=cell[1]+d[1];if(r>=0&&r<n&&c>=0&&c<n&&grid[r][c]==1){grid[r][c]=2;flood.offer(new int[]{r,c});}}}int distance=0;while(!frontier.isEmpty()){for(int size=frontier.size();size>0;size--){int[] cell=frontier.poll();for(int[] d:directions){int r=cell[0]+d[0],c=cell[1]+d[1];if(r<0||r>=n||c<0||c>=n||grid[r][c]==2)continue;if(grid[r][c]==1)return distance;grid[r][c]=2;frontier.offer(new int[]{r,c});}}distance++;}return -1;} }`,
`class Solution { fun shortestBridge(grid:Array<IntArray>):Int{val n=grid.size;val flood=java.util.ArrayDeque<IntArray>();val frontier=java.util.ArrayDeque<IntArray>();loop@for(r in 0 until n)for(c in 0 until n)if(grid[r][c]==1){flood.addLast(intArrayOf(r,c));grid[r][c]=2;break@loop};val directions=arrayOf(intArrayOf(1,0),intArrayOf(-1,0),intArrayOf(0,1),intArrayOf(0,-1));while(flood.isNotEmpty()){val cell=flood.removeFirst();frontier.addLast(cell);for(d in directions){val r=cell[0]+d[0];val c=cell[1]+d[1];if(r in 0 until n&&c in 0 until n&&grid[r][c]==1){grid[r][c]=2;flood.addLast(intArrayOf(r,c))}}};var distance=0;while(frontier.isNotEmpty()){repeat(frontier.size){val cell=frontier.removeFirst();for(d in directions){val r=cell[0]+d[0];val c=cell[1]+d[1];if(r !in 0 until n||c !in 0 until n||grid[r][c]==2)continue;if(grid[r][c]==1)return distance;grid[r][c]=2;frontier.addLast(intArrayOf(r,c))}};distance++};return -1} }`,
`class Solution { public: int shortestBridge(vector<vector<int>>& grid){int n=grid.size();queue<pair<int,int>> flood,frontier;bool found=false;for(int r=0;r<n&&!found;++r)for(int c=0;c<n;++c)if(grid[r][c]==1){flood.push({r,c});grid[r][c]=2;found=true;break;}int directions[4][2]={{1,0},{-1,0},{0,1},{0,-1}};while(!flood.empty()){auto cell=flood.front();flood.pop();frontier.push(cell);for(auto& d:directions){int r=cell.first+d[0],c=cell.second+d[1];if(r>=0&&r<n&&c>=0&&c<n&&grid[r][c]==1){grid[r][c]=2;flood.push({r,c});}}}int distance=0;while(!frontier.empty()){for(int size=frontier.size();size;--size){auto cell=frontier.front();frontier.pop();for(auto& d:directions){int r=cell.first+d[0],c=cell.second+d[1];if(r<0||r>=n||c<0||c>=n||grid[r][c]==2)continue;if(grid[r][c]==1)return distance;grid[r][c]=2;frontier.push({r,c});}}++distance;}return -1;} };`)],tests:{schemaVersion:1,mode:'function',method:'shortestBridge',parameterTypes:['intMatrix'],returnType:'int',cases:[{name:'对角两岛',args:[[[0,1],[1,0]]],expected:1},{name:'相距两个海格',args:[[[0,1,0],[0,0,0],[0,0,1]]],expected:2},{name:'内岛与外环',args:[[[1,1,1,1,1],[1,0,0,0,1],[1,0,1,0,1],[1,0,0,0,1],[1,1,1,1,1]]],expected:1}]}}
]}
