const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-020',problems:[
{id:1447,slug:'simplified-fractions',title:'最简分数',studyTags:['数学','字符串','数论'],summary:'返回分母不超过 n、位于零和一之间的所有最简分数。',insight:'枚举分母 2..n 与分子 1..denominator-1；最大公约数为一恰好表示分数已经最简。',pitfalls:['不包含零和一','不同未约分表示不能重复输出','本实现按分母再按分子升序'],solutions:[s('gcd-enumeration','最大公约数枚举','用互质条件过滤所有候选分子分母对。',['denominator 从二到 n','numerator 从一到 denominator-1','gcd(numerator,denominator)==1 时加入 numerator/denominator'],'O(n² log n)','O(n²)',
`class Solution { private int gcd(int a,int b){while(b!=0){int remainder=a%b;a=b;b=remainder;}return a;}public List<String> simplifiedFractions(int n){List<String> answer=new ArrayList<>();for(int denominator=2;denominator<=n;denominator++)for(int numerator=1;numerator<denominator;numerator++)if(gcd(numerator,denominator)==1)answer.add(numerator+"/"+denominator);return answer;} }`,
`class Solution { private fun gcd(a:Int,b:Int):Int=if(b==0)a else gcd(b,a%b);fun simplifiedFractions(n:Int):List<String>{val answer=mutableListOf<String>();for(denominator in 2..n)for(numerator in 1 until denominator)if(gcd(numerator,denominator)==1)answer.add("$numerator/$denominator");return answer} }`,
`class Solution { public: vector<string> simplifiedFractions(int n){vector<string> answer;for(int denominator=2;denominator<=n;++denominator)for(int numerator=1;numerator<denominator;++numerator)if(gcd(numerator,denominator)==1)answer.push_back(to_string(numerator)+"/"+to_string(denominator));return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'simplifiedFractions',parameterTypes:['int'],returnType:'stringList',cases:[{name:'分母最大二',args:[2],expected:['1/2']},{name:'分母最大三',args:[3],expected:['1/2','1/3','2/3']},{name:'没有零一之间分数',args:[1],expected:[]}]}},
{id:1448,slug:'count-good-nodes-in-binary-tree',title:'统计二叉树中好节点的数目',studyTags:['树','深度优先搜索'],summary:'若根到某节点路径上没有值比该节点更大，则该节点是好节点，统计数量。',insight:'DFS 携带路径最大值；node.val>=maximum 时当前节点为好节点，并以更新后的最大值继续访问孩子。',pitfalls:['比较包含当前路径全部祖先','相等值也算好节点','根节点必然是好节点'],solutions:[s('path-maximum-dfs','路径最大值深搜','把祖先最大值作为递归参数传递。',['dfs(node,maximum)，空节点返回零','good=node.val>=maximum ? 1:0，nextMax=max(maximum,node.val)','返回 good+左右子树结果'],'O(n)','O(h)',
`class Solution { private int dfs(TreeNode node,int maximum){if(node==null)return 0;int good=node.val>=maximum?1:0,nextMaximum=Math.max(maximum,node.val);return good+dfs(node.left,nextMaximum)+dfs(node.right,nextMaximum);}public int goodNodes(TreeNode root){return dfs(root,Integer.MIN_VALUE);} }`,
`class Solution { private fun dfs(node:TreeNode?,maximum:Int):Int{if(node==null)return 0;val good=if(node.\`val\`>=maximum)1 else 0;val nextMaximum=maxOf(maximum,node.\`val\`);return good+dfs(node.left,nextMaximum)+dfs(node.right,nextMaximum)};fun goodNodes(root:TreeNode?):Int=dfs(root,Int.MIN_VALUE) }`,
`class Solution { int dfs(TreeNode* node,int maximum){if(!node)return 0;int good=node->val>=maximum,nextMaximum=max(maximum,node->val);return good+dfs(node->left,nextMaximum)+dfs(node->right,nextMaximum);}public:int goodNodes(TreeNode* root){return dfs(root,INT_MIN);} };`)],tests:{schemaVersion:1,mode:'function',method:'goodNodes',parameterTypes:['treeNode'],returnType:'int',cases:[{name:'经典树四个好节点',args:[[3,1,4,3,null,1,5]],expected:4},{name:'左子树三个好节点',args:[[3,3,null,4,2]],expected:3},{name:'单根节点',args:[[1]],expected:1}]}},
{id:1449,slug:'form-largest-integer-with-digits-that-add-up-to-target',title:'数位成本和为目标值的最大数字',studyTags:['数组','动态规划','完全背包'],summary:'数字一到九各有成本，可重复选数位使总成本恰为 target，返回数值最大的整数；无解返回零。',insight:'数字位数越多数值越大，先用完全背包最大化位数；再从九到一贪心选择仍保持最优位数的数位，得到字典序最大结果。',pitfalls:['必须恰好用完 target 成本','无解返回字符串 0','重建时同一数字可重复选择'],solutions:[s('max-length-knapsack-reconstruction','最大位数背包与降序重建','以位数为第一目标、数位字典序为第二目标。',['dp[0]=0，其余负无穷；total 从一到 target 枚举 digit 更新最大位数','dp[target]<0 返回 0','digit 从九降到一，只要 dp[remain]==dp[remain-cost]+1 就追加并减少 remain，直到不能再选'],'O(9·target)','O(target)',
`class Solution { public String largestNumber(int[] cost,int target){int negative=-1_000_000;int[] dp=new int[target+1];Arrays.fill(dp,negative);dp[0]=0;for(int total=1;total<=target;total++)for(int digit=1;digit<=9;digit++)if(total>=cost[digit-1]&&dp[total-cost[digit-1]]!=negative)dp[total]=Math.max(dp[total],dp[total-cost[digit-1]]+1);if(dp[target]<0)return "0";StringBuilder answer=new StringBuilder();int remaining=target;for(int digit=9;digit>=1;digit--)while(remaining>=cost[digit-1]&&dp[remaining]==dp[remaining-cost[digit-1]]+1){answer.append(digit);remaining-=cost[digit-1];}return answer.toString();} }`,
`class Solution { fun largestNumber(cost:IntArray,target:Int):String{val negative=-1_000_000;val dp=IntArray(target+1){negative};dp[0]=0;for(total in 1..target)for(digit in 1..9)if(total>=cost[digit-1]&&dp[total-cost[digit-1]]!=negative)dp[total]=maxOf(dp[total],dp[total-cost[digit-1]]+1);if(dp[target]<0)return "0";val answer=StringBuilder();var remaining=target;for(digit in 9 downTo 1)while(remaining>=cost[digit-1]&&dp[remaining]==dp[remaining-cost[digit-1]]+1){answer.append(digit);remaining-=cost[digit-1]};return answer.toString()} }`,
`class Solution { public: string largestNumber(vector<int>& cost,int target){const int negative=-1000000;vector<int> dp(target+1,negative);dp[0]=0;for(int total=1;total<=target;++total)for(int digit=1;digit<=9;++digit)if(total>=cost[digit-1]&&dp[total-cost[digit-1]]!=negative)dp[total]=max(dp[total],dp[total-cost[digit-1]]+1);if(dp[target]<0)return "0";string answer;int remaining=target;for(int digit=9;digit>=1;--digit)while(remaining>=cost[digit-1]&&dp[remaining]==dp[remaining-cost[digit-1]]+1){answer+=char('0'+digit);remaining-=cost[digit-1];}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'largestNumber',parameterTypes:['intArray','int'],returnType:'string',cases:[{name:'成本九组成七七七二',args:[[4,3,2,5,6,7,2,5,5],9],expected:'7772'},{name:'成本十二组成八五',args:[[7,6,5,5,5,6,8,7,8],12],expected:'85'},{name:'奇数目标无法恰好组成',args:[[2,4,6,2,4,6,4,4,4],5],expected:'0'}]}},
{id:1450,slug:'number-of-students-doing-homework-at-a-given-time',title:'在既定时间做作业的学生人数',studyTags:['数组'],summary:'每名学生在闭区间 [startTime[i],endTime[i]] 做作业，统计 queryTime 时正在做作业的人数。',insight:'逐学生检查 start<=query<=end 并计数。',pitfalls:['起止时间都包含在区间内','两个数组相同长度且按学生对应','无需排序'],solutions:[s('interval-membership-count','区间包含计数','对每个闭区间独立判断查询时刻。',['answer=0','遍历 i','若 startTime[i]<=queryTime 且 queryTime<=endTime[i] 则 answer++'],'O(n)','O(1)',
`class Solution { public int busyStudent(int[] startTime,int[] endTime,int queryTime){int answer=0;for(int i=0;i<startTime.length;i++)if(startTime[i]<=queryTime&&queryTime<=endTime[i])answer++;return answer;} }`,
`class Solution { fun busyStudent(startTime:IntArray,endTime:IntArray,queryTime:Int):Int=startTime.indices.count{startTime[it]<=queryTime&&queryTime<=endTime[it]} }`,
`class Solution { public: int busyStudent(vector<int>& startTime,vector<int>& endTime,int queryTime){int answer=0;for(int i=0;i<(int)startTime.size();++i)answer+=startTime[i]<=queryTime&&queryTime<=endTime[i];return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'busyStudent',parameterTypes:['intArray','intArray','int'],returnType:'int',cases:[{name:'查询时三个学生都在做作业',args:[[1,2,3],[3,2,7],4],expected:1},{name:'边界时刻包含两个学生',args:[[4],[4],4],expected:1},{name:'查询时无人做作业',args:[[1,1,1,1],[1,3,2,4],7],expected:0}]}},
{id:1451,slug:'rearrange-words-in-a-sentence',title:'重新排列句子中的单词',studyTags:['字符串','排序'],summary:'把句子单词按长度非递减稳定排序，结果仅首字母大写。',insight:'先将原首字母转小写，使所有词统一；使用稳定排序保持同长度词原相对顺序，再把结果首字符大写。',pitfalls:['同长度单词必须保持原顺序','输入仅原句首字母大写','输出词之间恰好一个空格'],solutions:[s('stable-length-sort','按长度稳定排序','规范化大小写后稳定排列单词。',['把 text 首字符改为小写并按空格拆词','按 word.length 稳定排序','用空格拼接并把结果首字符改为大写'],'O(n log n)','O(n)',
`class Solution { public String arrangeWords(String text){text=Character.toLowerCase(text.charAt(0))+text.substring(1);List<String> words=new ArrayList<>(Arrays.asList(text.split(" ")));words.sort(Comparator.comparingInt(String::length));String joined=String.join(" ",words);return Character.toUpperCase(joined.charAt(0))+joined.substring(1);} }`,
`class Solution { fun arrangeWords(text:String):String{val normalized=text.replaceFirstChar{it.lowercaseChar()};val joined=normalized.split(' ').sortedBy{it.length}.joinToString(" ");return joined.replaceFirstChar{it.uppercaseChar()}} }`,
`class Solution { public: string arrangeWords(string text){text[0]=tolower(text[0]);stringstream stream(text);vector<string> words;string word;while(stream>>word)words.push_back(word);stable_sort(words.begin(),words.end(),[](const string& a,const string& b){return a.size()<b.size();});string answer;for(auto& value:words){if(!answer.empty())answer+=' ';answer+=value;}answer[0]=toupper(answer[0]);return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'arrangeWords',parameterTypes:['string'],returnType:'string',cases:[{name:'按二三八长度排序',args:['Leetcode is cool'],expected:'Is cool leetcode'},{name:'相同四字母词保持顺序',args:['Keep calm and code on'],expected:'On and keep calm code'},{name:'二字母词保持相对顺序',args:['To be or not to be'],expected:'To be or to be not'}]}}
]}
