const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-024',problems:[
{id:1657,slug:'determine-if-two-strings-are-close',title:'确定两个字符串是否接近',studyTags:['哈希表','字符串','排序'],summary:'允许交换任意字符位置，或把字符串中两种已存在字符的所有出现互换，判断两字符串能否互相转换。',insight:'位置交换意味着顺序无关，全局字符互换意味着频次可在共同的字符集合中任意置换。因此需字符集合相同且频次数值多重集相同。',pitfalls:['不存在的字符不能通过操作新建','比较频次排序结果而非字符对应频次','长度不同必不接近'],solutions:[s('character-set-and-frequency-multiset','字符集合与频次多重集','提取两种操作保持不变的必要充分条件。',['分别统计 26 个字母频次','检查每个字母是否出现的布尔值一致','排序两个频次数组并判断完全相等'],'O(n)','O(1)',
`class Solution { public boolean closeStrings(String word1,String word2){if(word1.length()!=word2.length())return false;int[] first=new int[26],second=new int[26];for(char letter:word1.toCharArray())first[letter-'a']++;for(char letter:word2.toCharArray())second[letter-'a']++;for(int i=0;i<26;i++)if((first[i]==0)!=(second[i]==0))return false;Arrays.sort(first);Arrays.sort(second);return Arrays.equals(first,second);} }`,
`class Solution { fun closeStrings(word1:String,word2:String):Boolean{if(word1.length!=word2.length)return false;val first=IntArray(26);val second=IntArray(26);for(letter in word1)first[letter-'a']++;for(letter in word2)second[letter-'a']++;for(i in 0 until 26)if((first[i]==0)!=(second[i]==0))return false;first.sort();second.sort();return first.contentEquals(second)} }`,
`class Solution { public: bool closeStrings(string word1,string word2){if(word1.size()!=word2.size())return false;array<int,26> first{},second{};for(char letter:word1)++first[letter-'a'];for(char letter:word2)++second[letter-'a'];for(int i=0;i<26;++i)if((first[i]==0)!=(second[i]==0))return false;sort(first.begin(),first.end());sort(second.begin(),second.end());return first==second;} };`)],tests:{schemaVersion:1,mode:'function',method:'closeStrings',parameterTypes:['string','string'],returnType:'boolean',cases:[{name:'abc 可通过位置交换变换',args:['abc','bca'],expected:true},{name:'不同字符集合无法变换',args:['a','aa'],expected:false},{name:'相同字符集和频次多重集可变换',args:['cabbba','abbccc'],expected:true}]}},
{id:1658,slug:'minimum-operations-to-reduce-x-to-zero',title:'将 x 减到 0 的最小操作数',studyTags:['数组','哈希表','前缀和','滑动窗口'],summary:'每次只能移除数组最左或最右元素并从 x 减去该值，求把 x 恰好减为零的最少操作数。',insight:'移除两端等价于保留一个连续中段。要让移除和为 x，应保留和为 total-x 的最长子数组，答案为 n-最长长度。正数数组可用滑动窗口。',pitfalls:['target 为零时保留空数组，答案为 n','target 小于零时不可能','需要最长而非最短目标和窗口'],solutions:[s('longest-kept-window','最长保留滑动窗口','把两端删除问题转成中间连续子数组。',['target=sum(nums)-x；小于零返回 -1，等于零返回 n','right 扩张并累加，sum>target 时移动 left','sum==target 时更新 longest，结束返回 n-longest 或 -1'],'O(n)','O(1)',
`class Solution { public int minOperations(int[] nums,int x){int target=Arrays.stream(nums).sum()-x;if(target<0)return -1;if(target==0)return nums.length;int left=0,sum=0,longest=-1;for(int right=0;right<nums.length;right++){sum+=nums[right];while(sum>target)sum-=nums[left++];if(sum==target)longest=Math.max(longest,right-left+1);}return longest<0?-1:nums.length-longest;} }`,
`class Solution { fun minOperations(nums:IntArray,x:Int):Int{val target=nums.sum()-x;if(target<0)return -1;if(target==0)return nums.size;var left=0;var sum=0;var longest=-1;for(right in nums.indices){sum+=nums[right];while(sum>target)sum-=nums[left++];if(sum==target)longest=maxOf(longest,right-left+1)};return if(longest<0)-1 else nums.size-longest} }`,
`class Solution { public: int minOperations(vector<int>& nums,int x){int target=accumulate(nums.begin(),nums.end(),0)-x;if(target<0)return -1;if(!target)return nums.size();int left=0,sum=0,longest=-1;for(int right=0;right<(int)nums.size();++right){sum+=nums[right];while(sum>target)sum-=nums[left++];if(sum==target)longest=max(longest,right-left+1);}return longest<0?-1:nums.size()-longest;} };`)],tests:{schemaVersion:1,mode:'function',method:'minOperations',parameterTypes:['intArray','int'],returnType:'int',cases:[{name:'左右各移除一个得到五',args:[[1,1,4,2,3],5],expected:2},{name:'任何两端组合都无法得到四',args:[[5,6,7,8,9],4],expected:-1},{name:'保留最长中段最少操作五次',args:[[3,2,20,1,1,3],10],expected:5}]}},
{id:1659,slug:'maximize-grid-happiness',title:'最大化网格幸福感',studyTags:['动态规划','状态压缩'],summary:'在 m×n 网格放置有限数量内向与外向的人；每人有基础幸福值，并受上下左右邻居类型影响，求最大总幸福值。',insight:'按行展开格子，用三进制滚动状态保存前 n 个格子的类型。放置新人时只需结算与上方、左方已放置邻居的双向影响，再记忆化搜索剩余格子和人数。',pitfalls:['每对相邻人的影响只结算一次但包含双方变化','空格也是一种可选状态','滚动三进制状态需正确移出最老格子'],solutions:[s('ternary-profile-dp','三进制轮廓记忆化 DP','用前一行轮廓压缩尚会影响未来的放置状态。',['mask 保存最近 n 格类型：0 空、1 内向、2 外向','dfs(position,mask,intro,extro) 尝试空、内向、外向；up=mask/3^(n-1)，left=列首?0:mask%3','放人时加基础分及与 up、left 的配对分，滚动 mask 并记忆最大值'],'O(mn·3^n·I·E)','O(mn·3^n·I·E)',
`class Solution { private int rows,cols,stateBase;private final Map<Long,Integer> memo=new HashMap<>();private int pair(int first,int second){if(first==0||second==0)return 0;if(first==1&&second==1)return -60;if(first==2&&second==2)return 40;return -10;}private int dfs(int position,int mask,int intro,int extro){if(position==rows*cols)return 0;long key=(((long)position*stateBase+mask)*7+intro)*7+extro;Integer cached=memo.get(key);if(cached!=null)return cached;int divisor=stateBase/3,up=mask/divisor,left=position%cols==0?0:mask%3,nextBase=mask%divisor*3;int best=dfs(position+1,nextBase,intro,extro);if(intro>0)best=Math.max(best,120+pair(1,up)+pair(1,left)+dfs(position+1,nextBase+1,intro-1,extro));if(extro>0)best=Math.max(best,40+pair(2,up)+pair(2,left)+dfs(position+1,nextBase+2,intro,extro-1));memo.put(key,best);return best;}public int getMaxGridHappiness(int m,int n,int introvertsCount,int extrovertsCount){rows=m;cols=n;stateBase=1;for(int i=0;i<n;i++)stateBase*=3;return dfs(0,0,introvertsCount,extrovertsCount);} }`,
`class Solution { private var rows=0;private var cols=0;private var stateBase=0;private val memo=mutableMapOf<Long,Int>();private fun pair(first:Int,second:Int):Int=when{first==0||second==0->0;first==1&&second==1->-60;first==2&&second==2->40;else->-10};private fun dfs(position:Int,mask:Int,intro:Int,extro:Int):Int{if(position==rows*cols)return 0;val key=(((position.toLong()*stateBase+mask)*7+intro)*7+extro);memo[key]?.let{return it};val divisor=stateBase/3;val up=mask/divisor;val left=if(position%cols==0)0 else mask%3;val nextBase=mask%divisor*3;var best=dfs(position+1,nextBase,intro,extro);if(intro>0)best=maxOf(best,120+pair(1,up)+pair(1,left)+dfs(position+1,nextBase+1,intro-1,extro));if(extro>0)best=maxOf(best,40+pair(2,up)+pair(2,left)+dfs(position+1,nextBase+2,intro,extro-1));memo[key]=best;return best};fun getMaxGridHappiness(m:Int,n:Int,introvertsCount:Int,extrovertsCount:Int):Int{rows=m;cols=n;stateBase=1;repeat(n){stateBase*=3};memo.clear();return dfs(0,0,introvertsCount,extrovertsCount)} }`,
`class Solution { int rows,cols,stateBase;unordered_map<long long,int> memo;int pairScore(int first,int second){if(!first||!second)return 0;if(first==1&&second==1)return -60;if(first==2&&second==2)return 40;return -10;}int dfs(int position,int mask,int intro,int extro){if(position==rows*cols)return 0;long long key=(((1LL*position*stateBase+mask)*7+intro)*7+extro);if(memo.count(key))return memo[key];int divisor=stateBase/3,up=mask/divisor,left=position%cols?mask%3:0,nextBase=mask%divisor*3;int best=dfs(position+1,nextBase,intro,extro);if(intro)best=max(best,120+pairScore(1,up)+pairScore(1,left)+dfs(position+1,nextBase+1,intro-1,extro));if(extro)best=max(best,40+pairScore(2,up)+pairScore(2,left)+dfs(position+1,nextBase+2,intro,extro-1));return memo[key]=best;}public:int getMaxGridHappiness(int m,int n,int introvertsCount,int extrovertsCount){rows=m;cols=n;stateBase=1;for(int i=0;i<n;++i)stateBase*=3;memo.clear();return dfs(0,0,introvertsCount,extrovertsCount);} };`)],tests:{schemaVersion:1,mode:'function',method:'getMaxGridHappiness',parameterTypes:['int','int','int','int'],returnType:'int',cases:[{name:'二乘三网格一内向两外向',args:[2,3,1,2],expected:240},{name:'三乘一网格两内向一外向',args:[3,1,2,1],expected:260},{name:'二乘二全放内向者',args:[2,2,4,0],expected:240}]}},
{id:1662,slug:'check-if-two-string-arrays-are-equivalent',title:'检查两个字符串数组是否相等',studyTags:['数组','字符串'],summary:'分别按顺序连接两个字符串数组，判断所得完整字符串是否相同。',insight:'数组分块不影响连接结果，直接连接每侧全部片段后比较即可。',pitfalls:['片段边界不参与比较','保持数组和片段原顺序','空片段也不影响结果'],solutions:[s('join-and-compare','连接后比较','把两侧规范化为完整字符串。',['分别创建 StringBuilder','顺序追加每个片段','比较两个完整字符串'],'O(total length)','O(total length)',
`class Solution { public boolean arrayStringsAreEqual(String[] word1,String[] word2){return String.join("",word1).equals(String.join("",word2));} }`,
`class Solution { fun arrayStringsAreEqual(word1:Array<String>,word2:Array<String>):Boolean=word1.joinToString("")==word2.joinToString("") }`,
`class Solution { public: bool arrayStringsAreEqual(vector<string>& word1,vector<string>& word2){return accumulate(word1.begin(),word1.end(),string())==accumulate(word2.begin(),word2.end(),string());} };`)],tests:{schemaVersion:1,mode:'function',method:'arrayStringsAreEqual',parameterTypes:['stringArray','stringArray'],returnType:'boolean',cases:[{name:'不同分块连接后均为 abc',args:[['ab','c'],['a','bc']],expected:true},{name:'连接结果字符顺序不同',args:[['a','cb'],['ab','c']],expected:false},{name:'多个片段连接结果相同',args:[['abc','d','defg'],['abcddefg']],expected:true}]}},
{id:1663,slug:'smallest-string-with-a-given-numeric-value',title:'具有给定数值的最小字符串',studyTags:['字符串','贪心'],summary:'长度 n 的小写字符串数值为各字母位置值之和，构造数值为 k 的字典序最小字符串。',insight:'先把所有位置设为最小的 a，剩余 k-n 点数应尽量加到右侧；从末尾每次最多增加 25，能让前缀保持最小。',pitfalls:['字母值从 a=1 到 z=26','必须固定长度 n','从右向左分配额外数值'],solutions:[s('right-to-left-greedy','从右向左填充贪心','把较大字母推到尽可能靠后的位置。',['chars 全部填 a，remaining=k-n','index 从 n-1 向前，add=min(25,remaining)','chars[index]+=add，扣减 remaining，返回字符串'],'O(n)','O(n)',
`class Solution { public String getSmallestString(int n,int k){char[] letters=new char[n];Arrays.fill(letters,'a');int remaining=k-n;for(int index=n-1;index>=0&&remaining>0;index--){int add=Math.min(25,remaining);letters[index]+=add;remaining-=add;}return new String(letters);} }`,
`class Solution { fun getSmallestString(n:Int,k:Int):String{val letters=CharArray(n){'a'};var remaining=k-n;for(index in n-1 downTo 0){val add=minOf(25,remaining);letters[index]=(letters[index].code+add).toChar();remaining-=add};return String(letters)} }`,
`class Solution { public: string getSmallestString(int n,int k){string letters(n,'a');int remaining=k-n;for(int index=n-1;index>=0&&remaining;--index){int add=min(25,remaining);letters[index]+=add;remaining-=add;}return letters;} };`)],tests:{schemaVersion:1,mode:'function',method:'getSmallestString',parameterTypes:['int','int'],returnType:'string',cases:[{name:'三字符数值二十七的最小串',args:[3,27],expected:'aay'},{name:'五字符数值七十三',args:[5,73],expected:'aaszz'},{name:'单字符最大值为 z',args:[1,26],expected:'z'}]}}
]}
