const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-011',problems:[
{id:823,slug:'binary-trees-with-factors',title:'带因子的二叉树',studyTags:['数组','动态规划','哈希表','排序'],summary:'用数组中的互异大于一整数构造二叉树，每个非叶节点等于两子节点乘积，求不同树数量。',insight:'排序后，以 value 为根的树只依赖更小因子；枚举左因子，若配对右因子已出现，就累加左右方案数乘积，有序子树顺序自然分别计数。',pitfalls:['每个值作为单节点树先贡献一','左右子树交换通常是不同树，枚举每个左因子会自动覆盖','计数乘法使用长整型并取模'],solutions:[s('sorted-factor-product-dp','排序因子乘积 DP','按根值从小到大累计所有因子组合。',['排序 arr，ways[value] 初始为一','对每个 i 枚举 j<i；若 arr[i]%arr[j]==0 且 quotient 已在 ways 中，累加 ways[left]*ways[right]','把 dp[i] 写入映射并累加总答案，全部对模取余'],'O(n²)','O(n)',
`class Solution { public int numFactoredBinaryTrees(int[] arr){Arrays.sort(arr);long mod=1000000007L,answer=0;Map<Integer,Long> ways=new HashMap<>();for(int i=0;i<arr.length;i++){long count=1;for(int j=0;j<i;j++)if(arr[i]%arr[j]==0&&ways.containsKey(arr[i]/arr[j]))count=(count+ways.get(arr[j])*ways.get(arr[i]/arr[j]))%mod;ways.put(arr[i],count);answer=(answer+count)%mod;}return(int)answer;} }`,
`class Solution { fun numFactoredBinaryTrees(arr:IntArray):Int{arr.sort();val mod=1000000007L;var answer=0L;val ways=mutableMapOf<Int,Long>();for(i in arr.indices){var count=1L;for(j in 0 until i)if(arr[i]%arr[j]==0&&ways.containsKey(arr[i]/arr[j]))count=(count+ways[arr[j]]!!*ways[arr[i]/arr[j]]!!)%mod;ways[arr[i]]=count;answer=(answer+count)%mod};return answer.toInt()} }`,
`class Solution { public: int numFactoredBinaryTrees(vector<int>& arr){sort(arr.begin(),arr.end());const long long mod=1000000007;long long answer=0;unordered_map<int,long long> ways;for(int i=0;i<(int)arr.size();++i){long long count=1;for(int j=0;j<i;++j)if(arr[i]%arr[j]==0&&ways.count(arr[i]/arr[j]))count=(count+ways[arr[j]]*ways[arr[i]/arr[j]])%mod;ways[arr[i]]=count;answer=(answer+count)%mod;}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'numFactoredBinaryTrees',parameterTypes:['intArray'],returnType:'int',cases:[{name:'二和四共三棵',args:[[2,4]],expected:3},{name:'四个数共七棵',args:[[2,4,5,10]],expected:7},{name:'单元素',args:[[2]],expected:1}]}},
{id:824,slug:'goat-latin',title:'山羊拉丁文',studyTags:['字符串','模拟'],summary:'按单词首字母是否为元音转换句子，并为第 i 个单词追加 i 个 a，返回转换后的句子。',insight:'元音开头保留单词，辅音开头把首字母移到末尾；两者再追加 ma 和随位置递增的 a。',pitfalls:['元音判断不区分大小写','单词下标从一开始','输出单词之间只有一个空格'],solutions:[s('word-by-word-transformation','逐词规则模拟','按位置转换每个单词后重新连接。',['按空格切分 sentence','若首字母不是元音，改为 substring(1)+first','追加 ma，再追加 index+1 个 a；用空格连接'],'O(total length + words²)','O(output)',
`class Solution { public String toGoatLatin(String sentence){Set<Character> vowels=new HashSet<>(Arrays.asList('a','e','i','o','u','A','E','I','O','U'));String[] words=sentence.split(" ");StringBuilder answer=new StringBuilder();for(int i=0;i<words.length;i++){if(i>0)answer.append(' ');String word=words[i];if(!vowels.contains(word.charAt(0)))word=word.substring(1)+word.charAt(0);answer.append(word).append("ma");for(int count=0;count<=i;count++)answer.append('a');}return answer.toString();} }`,
`class Solution { fun toGoatLatin(sentence:String):String{val vowels="aeiouAEIOU".toSet();return sentence.split(' ').mapIndexed{index,input->var word=input;if(word[0] !in vowels)word=word.substring(1)+word[0];word+"ma"+"a".repeat(index+1)}.joinToString(" ")} }`,
`class Solution { public: string toGoatLatin(string sentence){unordered_set<char> vowels={'a','e','i','o','u','A','E','I','O','U'};stringstream stream(sentence);string word,answer;int index=1;while(stream>>word){if(!vowels.count(word[0]))word=word.substr(1)+word[0];if(!answer.empty())answer+=' ';answer+=word+"ma"+string(index++,'a');}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'toGoatLatin',parameterTypes:['string'],returnType:'string',cases:[{name:'三个短词',args:['I speak Goat Latin'],expected:'Imaa peaksmaaa oatGmaaaa atinLmaaaaa'},{name:'元音与辅音',args:['The quick brown fox jumped over the lazy dog'],expected:'heTmaa uickqmaaa rownbmaaaa oxfmaaaaa umpedjmaaaaaa overmaaaaaaa hetmaaaaaaaa azylmaaaaaaaaa ogdmaaaaaaaaaa'},{name:'单个元音词',args:['Apple'],expected:'Applemaa'}]}},
{id:825,slug:'friends-of-appropriate-ages',title:'适龄的朋友',studyTags:['数组','计数','枚举'],summary:'每个人不会向年龄 y 满足 y<=x/2+7、y>x 或 y>100 且 x<100 的人发送请求，求所有有序好友请求数量。',insight:'年龄范围仅 1..120，统计每个年龄人数，再枚举发送者与接收者年龄；合法年龄对贡献 count[x]*count[y]，同龄时排除自己。',pitfalls:['请求有方向','同一人不能向自己发送','年龄条件使用整数比较可写成 2*y<=x+14'],solutions:[s('age-frequency-pair-enumeration','年龄频次数对枚举','在固定小年龄域上聚合计算请求数。',['统计 ages[1..120]','枚举 sender、receiver 且频次非零，按三条规则跳过不合法年龄对','贡献 count[sender]*count[receiver]，同龄再减 count[sender] 排除自请求'],'O(n+120²)','O(120)',
`class Solution { public int numFriendRequests(int[] ages){int[] count=new int[121];for(int age:ages)count[age]++;int answer=0;for(int sender=1;sender<=120;sender++)for(int receiver=1;receiver<=120;receiver++){if(count[sender]==0||count[receiver]==0||2*receiver<=sender+14||receiver>sender||receiver>100&&sender<100)continue;answer+=count[sender]*count[receiver]-(sender==receiver?count[sender]:0);}return answer;} }`,
`class Solution { fun numFriendRequests(ages:IntArray):Int{val count=IntArray(121);for(age in ages)count[age]++;var answer=0;for(sender in 1..120)for(receiver in 1..120){if(count[sender]==0||count[receiver]==0||2*receiver<=sender+14||receiver>sender||receiver>100&&sender<100)continue;answer+=count[sender]*count[receiver]-if(sender==receiver)count[sender] else 0};return answer} }`,
`class Solution { public: int numFriendRequests(vector<int>& ages){int count[121]{};for(int age:ages)++count[age];int answer=0;for(int sender=1;sender<=120;++sender)for(int receiver=1;receiver<=120;++receiver){if(!count[sender]||!count[receiver]||2*receiver<=sender+14||receiver>sender||(receiver>100&&sender<100))continue;answer+=count[sender]*count[receiver]-(sender==receiver?count[sender]:0);}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'numFriendRequests',parameterTypes:['intArray'],returnType:'int',cases:[{name:'两个十六岁互发',args:[[16,16]],expected:2},{name:'连续三个年龄',args:[[16,17,18]],expected:2},{name:'跨百岁条件',args:[[20,30,100,110,120]],expected:3}]}},
{id:826,slug:'most-profit-assigning-work',title:'安排工作以达到最大收益',studyTags:['数组','排序','双指针','贪心'],summary:'每个工人至多完成一份难度不超过其能力的工作，同类工作可重复安排，求总最大收益。',insight:'按难度排序工作、按能力排序工人；扫描工人时持续纳入可完成工作并维护历史最高利润，每人取该最高值。',pitfalls:['工作可被多个工人重复选择','利润不保证随难度递增，要维护前缀最大','能力不足任何工作时贡献零'],solutions:[s('sorted-workers-job-sweep','排序工人与工作双指针','一次扫描维护当前能力可达的最高利润。',['把 difficulty/profit 配对并按难度排序，worker 排序','对每个 ability，推进 job 指针纳入 difficulty<=ability 的工作，更新 bestProfit','answer+=bestProfit，返回总和'],'O((j+w) log(j+w))','O(j)',
`class Solution { public int maxProfitAssignment(int[] difficulty,int[] profit,int[] worker){int n=difficulty.length;int[][] jobs=new int[n][2];for(int i=0;i<n;i++){jobs[i][0]=difficulty[i];jobs[i][1]=profit[i];}Arrays.sort(jobs,Comparator.comparingInt(a->a[0]));Arrays.sort(worker);int answer=0,best=0,index=0;for(int ability:worker){while(index<n&&jobs[index][0]<=ability){best=Math.max(best,jobs[index][1]);index++;}answer+=best;}return answer;} }`,
`class Solution { fun maxProfitAssignment(difficulty:IntArray,profit:IntArray,worker:IntArray):Int{val jobs=difficulty.indices.map{intArrayOf(difficulty[it],profit[it])}.sortedBy{it[0]};worker.sort();var answer=0;var best=0;var index=0;for(ability in worker){while(index<jobs.size&&jobs[index][0]<=ability){best=maxOf(best,jobs[index][1]);index++};answer+=best};return answer} }`,
`class Solution { public: int maxProfitAssignment(vector<int>& difficulty,vector<int>& profit,vector<int>& worker){vector<pair<int,int>> jobs;for(int i=0;i<(int)difficulty.size();++i)jobs.push_back({difficulty[i],profit[i]});sort(jobs.begin(),jobs.end());sort(worker.begin(),worker.end());int answer=0,best=0,index=0;for(int ability:worker){while(index<(int)jobs.size()&&jobs[index].first<=ability){best=max(best,jobs[index].second);++index;}answer+=best;}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'maxProfitAssignment',parameterTypes:['intArray','intArray','intArray'],returnType:'int',cases:[{name:'五名工人总收益',args:[[2,4,6,8,10],[10,20,30,40,50],[4,5,6,7]],expected:100},{name:'都无法完成',args:[[85,47,57],[24,66,99],[40,25,25]],expected:0},{name:'重复分配最高收益',args:[[1,2],[5,10],[2,2]],expected:20}]}},
{id:827,slug:'making-a-large-island',title:'最大人工岛',studyTags:['数组','深度优先搜索','哈希集合','矩阵'],summary:'至多把一个零改成一，求四向相连的一岛屿可达到的最大面积。',insight:'先把每个已有岛屿染成唯一编号并记录面积；枚举零格时，把它和四邻不同编号岛屿面积相加，集合避免同一岛重复计算。',pitfalls:['四个邻居可能属于同一岛，只能加一次','全一网格答案是总格数','翻转零自身贡献一'],solutions:[s('label-islands-and-merge-neighbors','岛屿编号与邻接合并','预处理连通块后常数邻居数评估每个零。',['DFS 把每个一岛染成 id>=2，并记录 area[id]','答案先取已有岛最大值','枚举零格，以 one=1 开始，用集合收集四邻不同 id 并累加对应面积，更新答案'],'O(n²)','O(n²)',
`class Solution { public int largestIsland(int[][] grid){int n=grid.length,id=2,answer=0;Map<Integer,Integer> area=new HashMap<>();for(int r=0;r<n;r++)for(int c=0;c<n;c++)if(grid[r][c]==1){int size=paint(grid,r,c,id);area.put(id,size);answer=Math.max(answer,size);id++;}int[] directions={-1,0,1,0,-1};for(int r=0;r<n;r++)for(int c=0;c<n;c++)if(grid[r][c]==0){int size=1;Set<Integer> seen=new HashSet<>();for(int d=0;d<4;d++){int nr=r+directions[d],nc=c+directions[d+1];if(nr>=0&&nr<n&&nc>=0&&nc<n&&grid[nr][nc]>1&&seen.add(grid[nr][nc]))size+=area.get(grid[nr][nc]);}answer=Math.max(answer,size);}return answer;}private int paint(int[][] grid,int r,int c,int id){if(r<0||r>=grid.length||c<0||c>=grid.length||grid[r][c]!=1)return 0;grid[r][c]=id;return 1+paint(grid,r+1,c,id)+paint(grid,r-1,c,id)+paint(grid,r,c+1,id)+paint(grid,r,c-1,id);} }`,
`class Solution { fun largestIsland(grid:Array<IntArray>):Int{val n=grid.size;var id=2;var answer=0;val area=mutableMapOf<Int,Int>();for(r in 0 until n)for(c in 0 until n)if(grid[r][c]==1){val size=paint(grid,r,c,id);area[id]=size;answer=maxOf(answer,size);id++};val directions=intArrayOf(-1,0,1,0,-1);for(r in 0 until n)for(c in 0 until n)if(grid[r][c]==0){var size=1;val seen=mutableSetOf<Int>();for(d in 0 until 4){val nr=r+directions[d];val nc=c+directions[d+1];if(nr in 0 until n&&nc in 0 until n&&grid[nr][nc]>1&&seen.add(grid[nr][nc]))size+=area[grid[nr][nc]]!!};answer=maxOf(answer,size)};return answer};private fun paint(grid:Array<IntArray>,r:Int,c:Int,id:Int):Int{if(r !in grid.indices||c !in grid.indices||grid[r][c]!=1)return 0;grid[r][c]=id;return 1+paint(grid,r+1,c,id)+paint(grid,r-1,c,id)+paint(grid,r,c+1,id)+paint(grid,r,c-1,id)} }`,
`class Solution { int paint(vector<vector<int>>& grid,int r,int c,int id){int n=grid.size();if(r<0||r>=n||c<0||c>=n||grid[r][c]!=1)return 0;grid[r][c]=id;return 1+paint(grid,r+1,c,id)+paint(grid,r-1,c,id)+paint(grid,r,c+1,id)+paint(grid,r,c-1,id);}public:int largestIsland(vector<vector<int>>& grid){int n=grid.size(),id=2,answer=0;unordered_map<int,int> area;for(int r=0;r<n;++r)for(int c=0;c<n;++c)if(grid[r][c]==1){int size=paint(grid,r,c,id);area[id]=size;answer=max(answer,size);++id;}int directions[5]={-1,0,1,0,-1};for(int r=0;r<n;++r)for(int c=0;c<n;++c)if(grid[r][c]==0){int size=1;unordered_set<int> seen;for(int d=0;d<4;++d){int nr=r+directions[d],nc=c+directions[d+1];if(nr>=0&&nr<n&&nc>=0&&nc<n&&grid[nr][nc]>1&&seen.insert(grid[nr][nc]).second)size+=area[grid[nr][nc]];}answer=max(answer,size);}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'largestIsland',parameterTypes:['intMatrix'],returnType:'int',cases:[{name:'连接两座对角岛',args:[[[1,0],[0,1]]],expected:3},{name:'填补角落成为全岛',args:[[[1,1],[1,0]]],expected:4},{name:'已经全是岛',args:[[[1,1],[1,1]]],expected:4}]}}
]}
