const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-007',problems:[
{id:509,slug:'fibonacci-number',title:'斐波那契数',studyTags:['动态规划','迭代','数学'],summary:'按 F(0)=0、F(1)=1、F(n)=F(n-1)+F(n-2) 计算第 n 个斐波那契数。',insight:'每次只依赖前两项，用两个变量滚动更新即可，不需要保存整个数组。',pitfalls:['零和一是递推边界','更新时需保留旧的后项','题目范围内结果适合 32 位整数'],solutions:[s('two-variable-iteration','双变量滚动递推','从 F0/F1 开始逐步推进到 Fn。',['first=0,second=1','重复 n 次令 next=first+second','first=second,second=next，返回 first'],'O(n)','O(1)',
`class Solution { public int fib(int n){int first=0,second=1;for(int i=0;i<n;i++){int next=first+second;first=second;second=next;}return first;} }`,
`class Solution { fun fib(n:Int):Int{var first=0;var second=1;repeat(n){val next=first+second;first=second;second=next};return first} }`,
`class Solution { public: int fib(int n){int first=0,second=1;while(n--){int next=first+second;first=second;second=next;}return first;} };`)],tests:{schemaVersion:1,mode:'function',method:'fib',parameterTypes:['int'],returnType:'int',cases:[{name:'零',args:[0],expected:0},{name:'第二项',args:[2],expected:1},{name:'第十项',args:[10],expected:55}]}},
{id:513,slug:'find-bottom-left-tree-value',title:'找树左下角的值',studyTags:['二叉树','广度优先搜索','层序遍历'],summary:'返回二叉树最深一层最左侧节点的值。',insight:'层序遍历每层开始时记录队首节点值；正常按左后右入队，最后一次记录就是答案。',pitfalls:['目标是最深层而非整棵树最小值','每层只记录第一个节点','题目保证根节点非空'],solutions:[s('level-first-node','层序记录每层首节点','队列逐层处理并覆盖 answer 为当前层第一个值。',['根入队','每轮 size 固定当前层，answer=queue.peek.val','依次出队并按左、右孩子入队，结束返回 answer'],'O(n)','O(w)',
`class Solution { public int findBottomLeftValue(TreeNode root){Queue<TreeNode> queue=new ArrayDeque<>();queue.offer(root);int answer=root.val;while(!queue.isEmpty()){int size=queue.size();answer=queue.peek().val;while(size-->0){TreeNode node=queue.poll();if(node.left!=null)queue.offer(node.left);if(node.right!=null)queue.offer(node.right);}}return answer;} }`,
`class Solution { fun findBottomLeftValue(root:TreeNode?):Int{val nodeRoot=root!!;val queue=ArrayDeque<TreeNode>();queue.addLast(nodeRoot);var answer=nodeRoot.\`val\`;while(queue.isNotEmpty()){val size=queue.size;answer=queue.first().\`val\`;repeat(size){val node=queue.removeFirst();node.left?.let{queue.addLast(it)};node.right?.let{queue.addLast(it)}}};return answer} }`,
`class Solution { public: int findBottomLeftValue(TreeNode* root){queue<TreeNode*> nodes;nodes.push(root);int answer=root->val;while(!nodes.empty()){int size=nodes.size();answer=nodes.front()->val;while(size--){TreeNode* node=nodes.front();nodes.pop();if(node->left)nodes.push(node->left);if(node->right)nodes.push(node->right);}}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'findBottomLeftValue',parameterTypes:['treeNode'],returnType:'int',cases:[{name:'第二层左节点',args:[[2,1,3]],expected:1},{name:'最深层左节点',args:[[1,2,3,4,null,5,6,null,null,7]],expected:7},{name:'单节点',args:[[1]],expected:1}]}},
{id:515,slug:'find-largest-value-in-each-tree-row',title:'在每个树行中找最大值',studyTags:['二叉树','广度优先搜索','层序遍历'],summary:'返回二叉树每一层的最大节点值。',insight:'层序遍历固定每层队列长度，在出队该层全部节点时同步更新最大值。',pitfalls:['节点值可能全为负数，初值应为整数最小值','每层单独重置最大值','空树返回空列表'],solutions:[s('level-order-maximum','层序逐层求最大值','BFS 每轮恰好处理一层并追加该层最大值。',['根非空时入队','每层 maximum 初始化为最小整数','处理 size 个节点并扩展孩子，追加 maximum'],'O(n)','O(w)',
`class Solution { public List<Integer> largestValues(TreeNode root){List<Integer> answer=new ArrayList<>();if(root==null)return answer;Queue<TreeNode> queue=new ArrayDeque<>();queue.offer(root);while(!queue.isEmpty()){int maximum=Integer.MIN_VALUE;for(int size=queue.size();size>0;size--){TreeNode node=queue.poll();maximum=Math.max(maximum,node.val);if(node.left!=null)queue.offer(node.left);if(node.right!=null)queue.offer(node.right);}answer.add(maximum);}return answer;} }`,
`class Solution { fun largestValues(root:TreeNode?):List<Int>{if(root==null)return emptyList();val answer=mutableListOf<Int>();val queue=ArrayDeque<TreeNode>();queue.addLast(root);while(queue.isNotEmpty()){var maximum=Int.MIN_VALUE;repeat(queue.size){val node=queue.removeFirst();maximum=maxOf(maximum,node.\`val\`);node.left?.let{queue.addLast(it)};node.right?.let{queue.addLast(it)}};answer.add(maximum)};return answer} }`,
`class Solution { public: vector<int> largestValues(TreeNode* root){if(!root)return{};vector<int> answer;queue<TreeNode*> nodes;nodes.push(root);while(!nodes.empty()){int maximum=INT_MIN;for(int size=nodes.size();size>0;--size){TreeNode* node=nodes.front();nodes.pop();maximum=max(maximum,node->val);if(node->left)nodes.push(node->left);if(node->right)nodes.push(node->right);}answer.push_back(maximum);}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'largestValues',parameterTypes:['treeNode'],returnType:'intList',cases:[{name:'三层最大值',args:[[1,3,2,5,3,null,9]],expected:[1,3,9]},{name:'含负值',args:[[-1,-2,-3]],expected:[-1,-2]},{name:'空树',args:[[]],expected:[]}]}},
{id:516,slug:'longest-palindromic-subsequence',title:'最长回文子序列',studyTags:['动态规划','字符串','区间'],summary:'返回字符串中最长回文子序列的长度，子序列不要求连续。',insight:'区间两端字符相等时可同时加入最优子序列，否则舍弃左端或右端取较大值；一维数组可滚动压缩。',pitfalls:['子序列不要求连续','更新 dp[j] 前需保存旧 dp[j] 作为下一格对角值','i 从右向左遍历'],solutions:[s('one-dimensional-interval-dp','一维区间动态规划','dp[j] 在处理 i 时表示区间 s[i..j] 的最长回文子序列。',['i 从 n-1 降到零且 dp[i]=1','prev 保存旧 dp[j-1] 对角状态','若字符相等 dp[j]=prev+2，否则 dp[j]=max(dp[j],dp[j-1])'],'O(n²)','O(n)',
`class Solution { public int longestPalindromeSubseq(String s){int[] dp=new int[s.length()];for(int i=s.length()-1;i>=0;i--){dp[i]=1;int previous=0;for(int j=i+1;j<s.length();j++){int old=dp[j];dp[j]=s.charAt(i)==s.charAt(j)?previous+2:Math.max(dp[j],dp[j-1]);previous=old;}}return dp[s.length()-1];} }`,
`class Solution { fun longestPalindromeSubseq(s:String):Int{val dp=IntArray(s.length);for(i in s.lastIndex downTo 0){dp[i]=1;var previous=0;for(j in i+1 until s.length){val old=dp[j];dp[j]=if(s[i]==s[j])previous+2 else maxOf(dp[j],dp[j-1]);previous=old}};return dp.last()} }`,
`class Solution { public: int longestPalindromeSubseq(string s){vector<int> dp(s.size());for(int i=s.size()-1;i>=0;--i){dp[i]=1;int previous=0;for(int j=i+1;j<(int)s.size();++j){int old=dp[j];dp[j]=s[i]==s[j]?previous+2:max(dp[j],dp[j-1]);previous=old;}}return dp.back();} };`)],tests:{schemaVersion:1,mode:'function',method:'longestPalindromeSubseq',parameterTypes:['string'],returnType:'int',cases:[{name:'四长度回文子序列',args:['bbbab'],expected:4},{name:'两长度回文子序列',args:['cbbd'],expected:2},{name:'单字符',args:['a'],expected:1}]}},
{id:518,slug:'coin-change-ii',title:'零钱兑换 II',studyTags:['完全背包','动态规划','组合计数'],summary:'给定不同面额硬币且每种可无限使用，统计凑成 amount 的不同组合数，顺序不同不另算。',insight:'硬币外层、金额内层正序更新会让每种组合只在其最大面额被处理时计入一次。',pitfalls:['统计组合而非排列','dp[0]=1','金额需要正序更新以允许重复使用当前硬币'],solutions:[s('complete-knapsack-count','一维完全背包计数','按硬币顺序逐种扩展可达金额的组合数。',['ways[0]=1','对每个 coin','sum 从 coin 到 amount 正序：ways[sum]+=ways[sum-coin]'],'O(amount·coins)','O(amount)',
`class Solution { public int change(int amount,int[] coins){int[] ways=new int[amount+1];ways[0]=1;for(int coin:coins)for(int sum=coin;sum<=amount;sum++)ways[sum]+=ways[sum-coin];return ways[amount];} }`,
`class Solution { fun change(amount:Int,coins:IntArray):Int{val ways=IntArray(amount+1);ways[0]=1;for(coin in coins)for(sum in coin..amount)ways[sum]+=ways[sum-coin];return ways[amount]} }`,
`class Solution { public: int change(int amount,vector<int>& coins){vector<int> ways(amount+1);ways[0]=1;for(int coin:coins)for(int sum=coin;sum<=amount;++sum)ways[sum]+=ways[sum-coin];return ways[amount];} };`)],tests:{schemaVersion:1,mode:'function',method:'change',parameterTypes:['int','intArray'],returnType:'int',cases:[{name:'五元四种组合',args:[5,[1,2,5]],expected:4},{name:'无法凑出',args:[3,[2]],expected:0},{name:'零金额',args:[0,[1,2]],expected:1}]}}
]}
