const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-012',problems:[
{id:885,slug:'spiral-matrix-iii',title:'螺旋矩阵 III',studyTags:['数组','矩阵','模拟'],summary:'从网格内指定位置开始，按东南西北方向向外螺旋行走，返回按访问顺序遇到的全部网格坐标。',insight:'移动长度序列为一、一、二、二、三、三；即每走两个方向后步长加一，途中只记录落在网格内的坐标，网格外仍继续走。',pitfalls:['起点首先加入答案','走出网格不能停止或截断该方向','收集满 rows*cols 个坐标后立即返回'],solutions:[s('expanding-spiral-simulation','递增长度螺旋模拟','按固定四方向和每两次增加的步长行走。',['answer 加入起点，direction=0,steps=1','循环两次：沿当前方向走 steps 个单位，每步若在界内加入；方向顺时针更新','两方向后 steps++，直到收满网格坐标'],'O(path length)','O(rows·cols)',
`class Solution { public int[][] spiralMatrixIII(int rows,int cols,int rStart,int cStart){int[][] answer=new int[rows*cols][2];int count=0;answer[count++]=new int[]{rStart,cStart};int[][] directions={{0,1},{1,0},{0,-1},{-1,0}};int direction=0,steps=1,row=rStart,column=cStart;while(count<answer.length){for(int twice=0;twice<2;twice++){for(int move=0;move<steps;move++){row+=directions[direction][0];column+=directions[direction][1];if(row>=0&&row<rows&&column>=0&&column<cols)answer[count++]=new int[]{row,column};}direction=(direction+1)%4;}steps++;}return answer;} }`,
`class Solution { fun spiralMatrixIII(rows:Int,cols:Int,rStart:Int,cStart:Int):Array<IntArray>{val answer=Array(rows*cols){IntArray(2)};var count=0;answer[count++]=intArrayOf(rStart,cStart);val directions=arrayOf(intArrayOf(0,1),intArrayOf(1,0),intArrayOf(0,-1),intArrayOf(-1,0));var direction=0;var steps=1;var row=rStart;var column=cStart;while(count<answer.size){repeat(2){repeat(steps){row+=directions[direction][0];column+=directions[direction][1];if(row in 0 until rows&&column in 0 until cols)answer[count++]=intArrayOf(row,column)};direction=(direction+1)%4};steps++};return answer} }`,
`class Solution { public: vector<vector<int>> spiralMatrixIII(int rows,int cols,int rStart,int cStart){vector<vector<int>> answer{{rStart,cStart}};int directions[4][2]={{0,1},{1,0},{0,-1},{-1,0}},direction=0,steps=1,row=rStart,column=cStart;while((int)answer.size()<rows*cols){for(int twice=0;twice<2;++twice){for(int move=0;move<steps;++move){row+=directions[direction][0];column+=directions[direction][1];if(row>=0&&row<rows&&column>=0&&column<cols)answer.push_back({row,column});}direction=(direction+1)%4;}++steps;}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'spiralMatrixIII',parameterTypes:['int','int','int','int'],returnType:'intMatrix',cases:[{name:'单行四列',args:[1,4,0,0],expected:[[0,0],[0,1],[0,2],[0,3]]},{name:'二阶网格',args:[2,2,0,0],expected:[[0,0],[0,1],[1,1],[1,0]]},{name:'单列从中间开始',args:[3,1,1,0],expected:[[1,0],[2,0],[0,0]]}]}},
{id:886,slug:'possible-bipartition',title:'可能的二分法',studyTags:['图论','广度优先搜索','二分图'],summary:'n 个人之间有互相不喜欢的无向关系，判断能否分成两组，使每对不喜欢的人都在不同组。',insight:'问题等价于无向图是否二分图；对每个未染色连通分量 BFS 双色染色，若相邻节点同色则失败。',pitfalls:['图可能不连通','人员编号从一开始','孤立节点可任意分组'],solutions:[s('component-two-color-bfs','连通分量双色 BFS','逐分量染成正负两色并检查冲突。',['建立 1..n 无向邻接表，color 初始零','对每个未染色 person 设一并入队','弹出节点，对邻居：未染色设为相反色；若已同色返回假，全部完成返回真'],'O(n+e)','O(n+e)',
`class Solution { public boolean possibleBipartition(int n,int[][] dislikes){List<Integer>[] graph=new List[n+1];for(int i=1;i<=n;i++)graph[i]=new ArrayList<>();for(int[] edge:dislikes){graph[edge[0]].add(edge[1]);graph[edge[1]].add(edge[0]);}int[] color=new int[n+1];for(int start=1;start<=n;start++)if(color[start]==0){Queue<Integer> queue=new ArrayDeque<>();queue.offer(start);color[start]=1;while(!queue.isEmpty()){int node=queue.poll();for(int next:graph[node])if(color[next]==0){color[next]=-color[node];queue.offer(next);}else if(color[next]==color[node])return false;}}return true;} }`,
`class Solution { fun possibleBipartition(n:Int,dislikes:Array<IntArray>):Boolean{val graph=Array(n+1){mutableListOf<Int>()};for(edge in dislikes){graph[edge[0]].add(edge[1]);graph[edge[1]].add(edge[0])};val color=IntArray(n+1);for(start in 1..n)if(color[start]==0){val queue=java.util.ArrayDeque<Int>();queue.addLast(start);color[start]=1;while(queue.isNotEmpty()){val node=queue.removeFirst();for(next in graph[node])if(color[next]==0){color[next]=-color[node];queue.addLast(next)}else if(color[next]==color[node])return false}};return true} }`,
`class Solution { public: bool possibleBipartition(int n,vector<vector<int>>& dislikes){vector<vector<int>> graph(n+1);for(auto& edge:dislikes){graph[edge[0]].push_back(edge[1]);graph[edge[1]].push_back(edge[0]);}vector<int> color(n+1);for(int start=1;start<=n;++start)if(!color[start]){queue<int> pending;pending.push(start);color[start]=1;while(!pending.empty()){int node=pending.front();pending.pop();for(int next:graph[node])if(!color[next]){color[next]=-color[node];pending.push(next);}else if(color[next]==color[node])return false;}}return true;} };`)],tests:{schemaVersion:1,mode:'function',method:'possibleBipartition',parameterTypes:['int','intMatrix'],returnType:'boolean',cases:[{name:'四人可二分',args:[4,[[1,2],[1,3],[2,4]]],expected:true},{name:'三角冲突',args:[3,[[1,2],[1,3],[2,3]]],expected:false},{name:'五人奇环',args:[5,[[1,2],[2,3],[3,4],[4,5],[1,5]]],expected:false}]}},
{id:887,slug:'super-egg-drop',title:'鸡蛋掉落',studyTags:['数学','动态规划'],summary:'有 k 枚相同鸡蛋和 n 层楼，求最坏情况下确定临界楼层所需的最少操作次数。',insight:'反向定义 reachable[e] 为给定操作次数和 e 枚蛋可判定的最大楼层数；多一次操作可覆盖碎裂侧、当前层和未碎侧，共 reachable[e-1]+1+reachable[e]。',pitfalls:['鸡蛋维度必须倒序更新','零次操作可覆盖零层','当 reachable[k]>=n 时当前 moves 即答案'],solutions:[s('moves-to-reachable-floors-dp','操作次数对应可测楼层 DP','逐次增加操作数直到覆盖全部楼层。',['reachable[0..k]=0,moves=0','while reachable[k]<n：moves++','eggs 从 k 到一倒序，reachable[eggs]=reachable[eggs]+reachable[eggs-1]+1；返回 moves'],'O(k log n)','O(k)',
`class Solution { public int superEggDrop(int k,int n){long[] reachable=new long[k+1];int moves=0;while(reachable[k]<n){moves++;for(int eggs=k;eggs>=1;eggs--)reachable[eggs]=reachable[eggs]+reachable[eggs-1]+1;}return moves;} }`,
`class Solution { fun superEggDrop(k:Int,n:Int):Int{val reachable=LongArray(k+1);var moves=0;while(reachable[k]<n){moves++;for(eggs in k downTo 1)reachable[eggs]=reachable[eggs]+reachable[eggs-1]+1};return moves} }`,
`class Solution { public: int superEggDrop(int k,int n){vector<long long> reachable(k+1);int moves=0;while(reachable[k]<n){++moves;for(int eggs=k;eggs>=1;--eggs)reachable[eggs]=reachable[eggs]+reachable[eggs-1]+1;}return moves;} };`)],tests:{schemaVersion:1,mode:'function',method:'superEggDrop',parameterTypes:['int','int'],returnType:'int',cases:[{name:'一蛋两层',args:[1,2],expected:2},{name:'两蛋六层',args:[2,6],expected:3},{name:'三蛋十四层',args:[3,14],expected:4}]}},
{id:888,slug:'fair-candy-swap',title:'公平的糖果交换',studyTags:['数组','哈希集合','数学'],summary:'两人各交换一盒糖果，使交换后双方糖果总数相等，返回要交换的两盒数量。',insight:'设 Alice 给 a、Bob 给 b，则 a-b=(sumA-sumB)/2；把 Bob 数量放集合，扫描 Alice 找到 b=a-difference 即可。',pitfalls:['差值可为负数','题目保证存在答案','返回顺序是 Alice 的盒子、Bob 的盒子'],solutions:[s('sum-difference-complement-set','总和差与补数集合','把公平条件化为一次集合查询。',['计算 difference=(sumA-sumB)/2','建立 Bob 盒子大小集合','扫描 a，令 b=a-difference；若集合包含则返回 [a,b]'],'O(a+b)','O(b)',
`class Solution { public int[] fairCandySwap(int[] aliceSizes,int[] bobSizes){int difference=(Arrays.stream(aliceSizes).sum()-Arrays.stream(bobSizes).sum())/2;Set<Integer> bob=new HashSet<>();for(int value:bobSizes)bob.add(value);for(int alice:aliceSizes)if(bob.contains(alice-difference))return new int[]{alice,alice-difference};return new int[0];} }`,
`class Solution { fun fairCandySwap(aliceSizes:IntArray,bobSizes:IntArray):IntArray{val difference=(aliceSizes.sum()-bobSizes.sum())/2;val bob=bobSizes.toSet();for(alice in aliceSizes)if(alice-difference in bob)return intArrayOf(alice,alice-difference);return intArrayOf()} }`,
`class Solution { public: vector<int> fairCandySwap(vector<int>& aliceSizes,vector<int>& bobSizes){int difference=(accumulate(aliceSizes.begin(),aliceSizes.end(),0)-accumulate(bobSizes.begin(),bobSizes.end(),0))/2;unordered_set<int> bob(bobSizes.begin(),bobSizes.end());for(int alice:aliceSizes)if(bob.count(alice-difference))return{alice,alice-difference};return{};} };`)],tests:{schemaVersion:1,mode:'function',method:'fairCandySwap',parameterTypes:['intArray','intArray'],returnType:'intArray',cases:[{name:'一与二交换',args:[[1,1],[2,2]],expected:[1,2]},{name:'不同总和交换',args:[[1,2],[2,3]],expected:[1,2]},{name:'单盒与三交换',args:[[2],[1,3]],expected:[2,3]}]}},
{id:889,slug:'construct-binary-tree-from-preorder-and-postorder-traversal',title:'根据前序和后序遍历构造二叉树',studyTags:['数组','树','递归','哈希表'],summary:'给定一棵二叉树互异节点值的前序与后序遍历，返回任意一棵符合遍历结果的树。',insight:'前序区间首项是根；若还有节点，下一前序值是左子树根，在后序中的位置决定左子树大小，随后递归切分左右区间。',pitfalls:['树可能不唯一，返回任意合法结构','单节点区间直接返回','用后序值到下标映射避免反复查找'],solutions:[s('recursive-traversal-intervals','遍历区间递归构造','由左子树根在后序中的位置确定切分点。',['建立 postIndex[value]','build(preLeft,preRight,postLeft)：创建 preorder[preLeft] 根；单节点返回','leftRoot=preorder[preLeft+1]，leftSize=postIndex[leftRoot]-postLeft+1；递归构造左区间和剩余右区间'],'O(n)','O(n)',
`class Solution { private int[] preorder;private Map<Integer,Integer> postIndex=new HashMap<>();public TreeNode constructFromPrePost(int[] preorder,int[] postorder){this.preorder=preorder;for(int i=0;i<postorder.length;i++)postIndex.put(postorder[i],i);return build(0,preorder.length-1,0);}private TreeNode build(int preLeft,int preRight,int postLeft){if(preLeft>preRight)return null;TreeNode root=new TreeNode(preorder[preLeft]);if(preLeft==preRight)return root;int leftSize=postIndex.get(preorder[preLeft+1])-postLeft+1;root.left=build(preLeft+1,preLeft+leftSize,postLeft);root.right=build(preLeft+leftSize+1,preRight,postLeft+leftSize);return root;} }`,
`class Solution { private lateinit var preorder:IntArray;private lateinit var postIndex:Map<Int,Int>;fun constructFromPrePost(preorder:IntArray,postorder:IntArray):TreeNode?{this.preorder=preorder;postIndex=postorder.indices.associateBy{postorder[it]};return build(0,preorder.lastIndex,0)};private fun build(preLeft:Int,preRight:Int,postLeft:Int):TreeNode?{if(preLeft>preRight)return null;val root=TreeNode(preorder[preLeft]);if(preLeft==preRight)return root;val leftSize=postIndex[preorder[preLeft+1]]!!-postLeft+1;root.left=build(preLeft+1,preLeft+leftSize,postLeft);root.right=build(preLeft+leftSize+1,preRight,postLeft+leftSize);return root} }`,
`class Solution { vector<int> preorder;unordered_map<int,int> postIndex;TreeNode* build(int preLeft,int preRight,int postLeft){if(preLeft>preRight)return nullptr;TreeNode* root=new TreeNode(preorder[preLeft]);if(preLeft==preRight)return root;int leftSize=postIndex[preorder[preLeft+1]]-postLeft+1;root->left=build(preLeft+1,preLeft+leftSize,postLeft);root->right=build(preLeft+leftSize+1,preRight,postLeft+leftSize);return root;}public:TreeNode* constructFromPrePost(vector<int>& pre,vector<int>& postorder){preorder=pre;for(int i=0;i<(int)postorder.size();++i)postIndex[postorder[i]]=i;return build(0,preorder.size()-1,0);} };`)],tests:{schemaVersion:1,mode:'function',method:'constructFromPrePost',parameterTypes:['intArray','intArray'],returnType:'treeNode',cases:[{name:'完整七节点树',args:[[1,2,4,5,3,6,7],[4,5,2,6,7,3,1]],expected:[1,2,3,4,5,6,7]},{name:'单节点',args:[[1],[1]],expected:[1]},{name:'单链选择左孩子',args:[[1,2,3],[3,2,1]],expected:[1,2,null,3]}]}}
]}
