const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-005',problems:[
{id:307,slug:'range-sum-query-mutable',title:'区域和检索 - 数组可修改',studyTags:['树状数组','设计','前缀和'],summary:'维护可修改整数数组，支持单点更新和多次闭区间求和查询。',insight:'树状数组保存若干低位块的和，单点差值沿父索引更新，前缀查询沿低位跳转累加。',pitfalls:['更新需要先求新旧值差','树状数组使用一基下标','区间和等于两个前缀和之差'],solutions:[s('fenwick-tree','树状数组','构造时逐点加入，更新和查询都只访问对数个节点。',['values 保存当前元素','add(index+1,delta) 更新树状数组','sumRange=prefix(right+1)-prefix(left)'],'build O(n log n), operation O(log n)','O(n)',
`class NumArray { private final int[] values,tree;public NumArray(int[] nums){values=nums.clone();tree=new int[nums.length+1];for(int i=0;i<nums.length;i++)add(i+1,nums[i]);}private void add(int index,int delta){for(;index<tree.length;index+=index&-index)tree[index]+=delta;}private int prefix(int index){int sum=0;for(;index>0;index-=index&-index)sum+=tree[index];return sum;}public void update(int index,int val){int delta=val-values[index];values[index]=val;add(index+1,delta);}public int sumRange(int left,int right){return prefix(right+1)-prefix(left);} }`,
`class NumArray(nums:IntArray){private val values=nums.clone();private val tree=IntArray(nums.size+1);init{for(i in nums.indices)add(i+1,nums[i])}private fun add(start:Int,delta:Int){var index=start;while(index<tree.size){tree[index]+=delta;index+=index and -index}}private fun prefix(start:Int):Int{var index=start;var sum=0;while(index>0){sum+=tree[index];index-=index and -index};return sum}fun update(index:Int,value:Int){val delta=value-values[index];values[index]=value;add(index+1,delta)}fun sumRange(left:Int,right:Int):Int=prefix(right+1)-prefix(left) }`,
`class NumArray { vector<int> values,tree;void add(int index,int delta){for(;index<(int)tree.size();index+=index&-index)tree[index]+=delta;}int prefix(int index){int sum=0;for(;index>0;index-=index&-index)sum+=tree[index];return sum;}public:NumArray(vector<int>& nums):values(nums),tree(nums.size()+1){for(int i=0;i<(int)nums.size();++i)add(i+1,nums[i]);}void update(int index,int value){int delta=value-values[index];values[index]=value;add(index+1,delta);}int sumRange(int left,int right){return prefix(right+1)-prefix(left);} };`)],tests:{schemaVersion:1,mode:'design',className:'NumArray',constructorTypes:['intArray'],cases:[{name:'更新后重新查询',constructorArgs:[[1,3,5]],calls:[{method:'sumRange',parameterTypes:['int','int'],args:[0,2],returnType:'int',expected:9},{method:'update',parameterTypes:['int','int'],args:[1,2]},{method:'sumRange',parameterTypes:['int','int'],args:[0,2],returnType:'int',expected:8}]},{name:'单元素更新',constructorArgs:[[7]],calls:[{method:'update',parameterTypes:['int','int'],args:[0,-2]},{method:'sumRange',parameterTypes:['int','int'],args:[0,0],returnType:'int',expected:-2}]},{name:'局部区间',constructorArgs:[[2,4,6,8]],calls:[{method:'sumRange',parameterTypes:['int','int'],args:[1,2],returnType:'int',expected:10}]}]}},
{id:310,slug:'minimum-height-trees',title:'最小高度树',studyTags:['图论','拓扑剥离','树中心'],summary:'给定一棵无向树，找出作为根时能得到最小高度的所有节点。',insight:'树的中心最多两个；像剥洋葱一样同步删除所有叶子，最后剩下的节点就是中心。',pitfalls:['单节点树直接返回零号节点','必须按层同时移除叶子','无向边需要建立双向邻接表'],solutions:[s('trim-leaves','逐层剥离叶子','维护度数和叶子队列，每轮删除当前所有叶子直到剩余不超过两个节点。',['构建邻接表与 degree','所有度为一的节点入队','按层减少邻居度数，新叶入队，最终排序返回'],'O(n)','O(n)',
`class Solution { public List<Integer> findMinHeightTrees(int n,int[][] edges){if(n==1)return Arrays.asList(0);List<List<Integer>> graph=new ArrayList<>();for(int i=0;i<n;i++)graph.add(new ArrayList<>());int[] degree=new int[n];for(int[] edge:edges){graph.get(edge[0]).add(edge[1]);graph.get(edge[1]).add(edge[0]);degree[edge[0]]++;degree[edge[1]]++;}Queue<Integer> leaves=new ArrayDeque<>();for(int i=0;i<n;i++)if(degree[i]==1)leaves.offer(i);int remaining=n;while(remaining>2){int size=leaves.size();remaining-=size;while(size-->0){int leaf=leaves.poll();for(int neighbor:graph.get(leaf))if(--degree[neighbor]==1)leaves.offer(neighbor);}}List<Integer> answer=new ArrayList<>(leaves);Collections.sort(answer);return answer;} }`,
`class Solution { fun findMinHeightTrees(n:Int,edges:Array<IntArray>):List<Int>{if(n==1)return listOf(0);val graph=List(n){mutableListOf<Int>()};val degree=IntArray(n);for(edge in edges){graph[edge[0]].add(edge[1]);graph[edge[1]].add(edge[0]);degree[edge[0]]++;degree[edge[1]]++};val leaves=ArrayDeque<Int>();for(i in 0 until n)if(degree[i]==1)leaves.addLast(i);var remaining=n;while(remaining>2){val size=leaves.size;remaining-=size;repeat(size){val leaf=leaves.removeFirst();for(neighbor in graph[leaf])if(--degree[neighbor]==1)leaves.addLast(neighbor)}};return leaves.sorted()} }`,
`class Solution { public: vector<int> findMinHeightTrees(int n,vector<vector<int>>& edges){if(n==1)return{0};vector<vector<int>> graph(n);vector<int> degree(n);for(auto& edge:edges){graph[edge[0]].push_back(edge[1]);graph[edge[1]].push_back(edge[0]);++degree[edge[0]];++degree[edge[1]];}queue<int> leaves;for(int i=0;i<n;++i)if(degree[i]==1)leaves.push(i);int remaining=n;while(remaining>2){int size=leaves.size();remaining-=size;while(size--){int leaf=leaves.front();leaves.pop();for(int neighbor:graph[leaf])if(--degree[neighbor]==1)leaves.push(neighbor);}}vector<int> answer;while(!leaves.empty()){answer.push_back(leaves.front());leaves.pop();}sort(answer.begin(),answer.end());return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'findMinHeightTrees',parameterTypes:['int','intMatrix'],returnType:'intList',cases:[{name:'唯一中心',args:[4,[[1,0],[1,2],[1,3]]],expected:[1]},{name:'两个中心',args:[6,[[3,0],[3,1],[3,2],[3,4],[5,4]]],expected:[3,4]},{name:'单节点',args:[1,[]],expected:[0]}]}},
{id:313,slug:'super-ugly-number',title:'超级丑数',studyTags:['动态规划','多指针','有序合并'],summary:'给定一组质数，返回质因数都来自该集合的正整数序列中的第 n 个数。',insight:'每个质数形成一条已生成丑数乘该质数的递增序列，用一个指针维护各序列的下一候选。',pitfalls:['第一项是 1','多个质数可能生成相同候选，所有对应指针都要前进','乘法中间值用长整型'],solutions:[s('multi-pointer-merge','多路有序序列合并','每轮取所有质数候选的最小值，并推进所有命中该值的指针。',['ugly[0]=1，pointers 全零','计算每个 ugly[pointer[i]]*primes[i] 的最小值','写入 next 并推进相等候选的所有指针'],'O(nk)','O(n+k)',
`class Solution { public int nthSuperUglyNumber(int n,int[] primes){int[] ugly=new int[n],pointers=new int[primes.length];ugly[0]=1;for(int index=1;index<n;index++){long next=Long.MAX_VALUE;for(int i=0;i<primes.length;i++)next=Math.min(next,(long)ugly[pointers[i]]*primes[i]);ugly[index]=(int)next;for(int i=0;i<primes.length;i++)if((long)ugly[pointers[i]]*primes[i]==next)pointers[i]++;}return ugly[n-1];} }`,
`class Solution { fun nthSuperUglyNumber(n:Int,primes:IntArray):Int{val ugly=IntArray(n);val pointers=IntArray(primes.size);ugly[0]=1;for(index in 1 until n){var next=Long.MAX_VALUE;for(i in primes.indices)next=minOf(next,ugly[pointers[i]].toLong()*primes[i]);ugly[index]=next.toInt();for(i in primes.indices)if(ugly[pointers[i]].toLong()*primes[i]==next)pointers[i]++};return ugly.last()} }`,
`class Solution { public: int nthSuperUglyNumber(int n,vector<int>& primes){vector<int> ugly(n),pointers(primes.size());ugly[0]=1;for(int index=1;index<n;++index){long long next=LLONG_MAX;for(int i=0;i<(int)primes.size();++i)next=min(next,1LL*ugly[pointers[i]]*primes[i]);ugly[index]=next;for(int i=0;i<(int)primes.size();++i)if(1LL*ugly[pointers[i]]*primes[i]==next)++pointers[i];}return ugly.back();} };`)],tests:{schemaVersion:1,mode:'function',method:'nthSuperUglyNumber',parameterTypes:['int','intArray'],returnType:'int',cases:[{name:'四个质因数',args:[12,[2,7,13,19]],expected:32},{name:'第一项',args:[1,[2,3,5]],expected:1},{name:'二和十一',args:[5,[2,11]],expected:11}]}},
{id:316,slug:'remove-duplicate-letters',title:'去除重复字母',studyTags:['单调栈','贪心','字符串'],summary:'删除重复字母使每个字母只出现一次，并在所有可行结果中获得字典序最小的字符串。',insight:'字符仍会在后面出现时，栈顶若比当前字符大就可安全弹出；每个字符只保留一次。',pitfalls:['只能弹出后续仍有剩余次数的字符','已经在栈中的字符直接跳过','弹出时要同步清除在栈标记'],solutions:[s('monotonic-stack','单调栈贪心','剩余计数保证删除可恢复，栈保持尽可能小的字典序。',['统计每个字符剩余次数','扫描时减少剩余次数，已入栈则跳过','弹出更大且仍会出现的栈顶，再压入当前字符'],'O(n)','O(1)',
`class Solution { public String removeDuplicateLetters(String s){int[] remaining=new int[26];boolean[] used=new boolean[26];for(char c:s.toCharArray())remaining[c-'a']++;StringBuilder stack=new StringBuilder();for(char c:s.toCharArray()){int index=c-'a';remaining[index]--;if(used[index])continue;while(stack.length()>0&&stack.charAt(stack.length()-1)>c&&remaining[stack.charAt(stack.length()-1)-'a']>0){used[stack.charAt(stack.length()-1)-'a']=false;stack.deleteCharAt(stack.length()-1);}stack.append(c);used[index]=true;}return stack.toString();} }`,
`class Solution { fun removeDuplicateLetters(s:String):String{val remaining=IntArray(26);val used=BooleanArray(26);for(c in s)remaining[c-'a']++;val stack=StringBuilder();for(c in s){val index=c-'a';remaining[index]--;if(used[index])continue;while(stack.isNotEmpty()&&stack.last()>c&&remaining[stack.last()-'a']>0){used[stack.last()-'a']=false;stack.deleteCharAt(stack.lastIndex)};stack.append(c);used[index]=true};return stack.toString()} }`,
`class Solution { public: string removeDuplicateLetters(string s){array<int,26> remaining{};array<bool,26> used{};for(char c:s)++remaining[c-'a'];string stack;for(char c:s){int index=c-'a';--remaining[index];if(used[index])continue;while(!stack.empty()&&stack.back()>c&&remaining[stack.back()-'a']>0){used[stack.back()-'a']=false;stack.pop_back();}stack.push_back(c);used[index]=true;}return stack;} };`)],tests:{schemaVersion:1,mode:'function',method:'removeDuplicateLetters',parameterTypes:['string'],returnType:'string',cases:[{name:'可弹出前导字符',args:['bcabc'],expected:'abc'},{name:'复杂单调栈',args:['cbacdcbc'],expected:'acdb'},{name:'重复段',args:['bbcaac'],expected:'bac'}]}},
{id:318,slug:'maximum-product-of-word-lengths',title:'最大单词长度乘积',studyTags:['位掩码','字符串','两两枚举'],summary:'从小写单词数组中选两个没有公共字母的单词，使长度乘积最大。',insight:'把每个单词出现的字母压缩成 26 位掩码，两词无公共字母等价于掩码按位与为零。',pitfalls:['同一单词内重复字母不影响掩码','必须选择两个不同下标','无合法正乘积时返回零'],solutions:[s('letter-bitmasks','字母位掩码','预处理每词掩码后两两检查交集并更新乘积。',['为每个单词构造 mask','枚举 i<j','mask[i]&mask[j]==0 时更新长度乘积'],'O(total chars+n²)','O(n)',
`class Solution { public int maxProduct(String[] words){int[] masks=new int[words.length];for(int i=0;i<words.length;i++)for(char c:words[i].toCharArray())masks[i]|=1<<(c-'a');int answer=0;for(int i=0;i<words.length;i++)for(int j=i+1;j<words.length;j++)if((masks[i]&masks[j])==0)answer=Math.max(answer,words[i].length()*words[j].length());return answer;} }`,
`class Solution { fun maxProduct(words:Array<String>):Int{val masks=IntArray(words.size);for(i in words.indices)for(c in words[i])masks[i]=masks[i] or (1 shl (c-'a'));var answer=0;for(i in words.indices)for(j in i+1 until words.size)if(masks[i] and masks[j]==0)answer=maxOf(answer,words[i].length*words[j].length);return answer} }`,
`class Solution { public: int maxProduct(vector<string>& words){vector<int> masks(words.size());for(int i=0;i<(int)words.size();++i)for(char c:words[i])masks[i]|=1<<(c-'a');int answer=0;for(int i=0;i<(int)words.size();++i)for(int j=i+1;j<(int)words.size();++j)if((masks[i]&masks[j])==0)answer=max(answer,(int)(words[i].size()*words[j].size()));return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'maxProduct',parameterTypes:['stringArray'],returnType:'int',cases:[{name:'最大乘积十六',args:[['abcw','baz','foo','bar','xtfn','abcdef']],expected:16},{name:'不同长度组合',args:[['a','ab','abc','d','cd','bcd','abcd']],expected:4},{name:'都有公共字母',args:[['a','aa','aaa','aaaa']],expected:0}]}}
]}
