const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-018',problems:[
{id:1296,slug:'divide-array-in-sets-of-k-consecutive-numbers',title:'划分数组为连续数字的集合',studyTags:['数组','哈希表','贪心','有序映射'],summary:'判断数组能否划分成若干大小为 k 的集合，每组数字是连续整数且每个元素恰用一次。',insight:'当前剩余最小值无法由更小值作为组中间元素，只能作为新组起点；因此每次从最小键开始，连续消耗 k 个频次是唯一贪心选择。',pitfalls:['数组长度必须能被 k 整除','重复数字通过频次处理','任一连续值缺失即无解'],solutions:[s('smallest-frequency-greedy','最小值频次贪心','用有序频次表反复组装最小起点的连续组。',['若 nums.length%k!=0 返回 false，建立 TreeMap 频次','当 map 非空，start=firstKey','对 value=start..start+k-1，若无频次返回 false，否则减一，为零删除；全部耗尽返回 true'],'O(n log n)','O(n)',
`class Solution { public boolean isPossibleDivide(int[] nums,int k){if(nums.length%k!=0)return false;TreeMap<Integer,Integer> frequency=new TreeMap<>();for(int value:nums)frequency.merge(value,1,Integer::sum);while(!frequency.isEmpty()){int start=frequency.firstKey();for(int value=start;value<start+k;value++){Integer count=frequency.get(value);if(count==null)return false;if(count==1)frequency.remove(value);else frequency.put(value,count-1);}}return true;} }`,
`class Solution { fun isPossibleDivide(nums:IntArray,k:Int):Boolean{if(nums.size%k!=0)return false;val frequency=java.util.TreeMap<Int,Int>();for(value in nums)frequency[value]=(frequency[value]?:0)+1;while(frequency.isNotEmpty()){val start=frequency.firstKey();for(value in start until start+k){val count=frequency[value]?:return false;if(count==1)frequency.remove(value)else frequency[value]=count-1}};return true} }`,
`class Solution { public: bool isPossibleDivide(vector<int>& nums,int k){if(nums.size()%k)return false;map<int,int> frequency;for(int value:nums)++frequency[value];while(!frequency.empty()){int start=frequency.begin()->first;for(int value=start;value<start+k;++value){auto it=frequency.find(value);if(it==frequency.end())return false;if(!--it->second)frequency.erase(it);}}return true;} };`)],tests:{schemaVersion:1,mode:'function',method:'isPossibleDivide',parameterTypes:['intArray','int'],returnType:'boolean',cases:[{name:'可分两组连续四数',args:[[1,2,3,3,4,4,5,6],4],expected:true},{name:'缺少连续数字',args:[[1,2,3,4],3],expected:false},{name:'三组连续三数',args:[[3,3,2,2,1,1],3],expected:true}]}},
{id:1297,slug:'maximum-number-of-occurrences-of-a-substring',title:'子串的最大出现次数',studyTags:['字符串','滑动窗口','哈希表','计数'],summary:'在长度介于 minSize 与 maxSize、不同字符数不超 maxLetters 的子串中，返回某个子串的最大出现次数。',insight:'任何较长合法子串的每次出现都包含其长度 minSize 的前缀出现，且前缀不同字符不会更多；因此只需统计固定长度 minSize 的合法窗口。',pitfalls:['相同子串的重叠出现也计数','maxSize 无需枚举','窗口不同字符数通过频次数组维护'],solutions:[s('minimum-size-window-frequency','最小长度窗口频次','只统计固定 minSize 合法子串并取最高频次。',['维护长度 minSize 的滑动窗口、26 频次与 distinct','每加入右字符，窗口过长时移除左字符并更新 distinct','窗口长度等于 minSize 且 distinct<=maxLetters 时对 substring 计数并更新 answer'],'O(n·minSize) 含构造子串','O(n)',
`class Solution { public int maxFreq(String s,int maxLetters,int minSize,int maxSize){int[] frequency=new int[26];int left=0,distinct=0,answer=0;Map<String,Integer> counts=new HashMap<>();for(int right=0;right<s.length();right++){if(frequency[s.charAt(right)-'a']++==0)distinct++;if(right-left+1>minSize){if(--frequency[s.charAt(left++)-'a']==0)distinct--;}if(right-left+1==minSize&&distinct<=maxLetters){String value=s.substring(left,right+1);int count=counts.getOrDefault(value,0)+1;counts.put(value,count);answer=Math.max(answer,count);}}return answer;} }`,
`class Solution { fun maxFreq(s:String,maxLetters:Int,minSize:Int,maxSize:Int):Int{val frequency=IntArray(26);var left=0;var distinct=0;var answer=0;val counts=mutableMapOf<String,Int>();for(right in s.indices){if(frequency[s[right]-'a']++==0)distinct++;if(right-left+1>minSize){if(--frequency[s[left++]-'a']==0)distinct--};if(right-left+1==minSize&&distinct<=maxLetters){val value=s.substring(left,right+1);val count=(counts[value]?:0)+1;counts[value]=count;answer=maxOf(answer,count)}};return answer} }`,
`class Solution { public: int maxFreq(string s,int maxLetters,int minSize,int maxSize){int frequency[26]={},left=0,distinct=0,answer=0;unordered_map<string,int> counts;for(int right=0;right<(int)s.size();++right){if(!frequency[s[right]-'a']++)++distinct;if(right-left+1>minSize)if(!--frequency[s[left++]-'a'])--distinct;if(right-left+1==minSize&&distinct<=maxLetters)answer=max(answer,++counts[s.substr(left,minSize)]);}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'maxFreq',parameterTypes:['string','int','int','int'],returnType:'int',cases:[{name:'aab 出现两次',args:['aababcaab',2,3,4],expected:2},{name:'aaa 重叠两次',args:['aaaa',1,3,3],expected:2},{name:'字符种类超限',args:['abcde',2,3,3],expected:0}]}},
{id:1298,slug:'maximum-candies-you-can-get-from-boxes',title:'你能从盒子里获得的最大糖果数',studyTags:['数组','广度优先搜索','状态模拟'],summary:'盒子可能锁住，打开后获得糖果、钥匙与其他盒子；从初始拥有盒子出发，求最终最多糖果数。',insight:'盒子能打开需同时满足已拥有和本身开放或已取得钥匙。每次获得钥匙或盒子时重新把可能变为可打开的盒子入队，用 opened 防止重复计糖。',pitfalls:['拥有锁盒不等于能打开','钥匙可能在获得对应盒子之前或之后取得','同一盒子只打开一次'],solutions:[s('owned-key-open-queue','所有权与钥匙状态队列','事件驱动处理新获得盒子与钥匙。',['owned、key、opened 布尔数组；初始盒子标 owned 并入队','弹出 box，若已开或未拥有或既关闭又无钥匙则跳过；否则标 opened 并加 candies','把其中 keys 标记并在对应盒已拥有时入队；把 containedBoxes 标 owned 并入队，队列耗尽返回总糖果'],'O(盒子数+关系数)','O(盒子数)',
`class Solution { public int maxCandies(int[] status,int[] candies,int[][] keys,int[][] containedBoxes,int[] initialBoxes){int n=status.length,total=0;boolean[] owned=new boolean[n],hasKey=new boolean[n],opened=new boolean[n];Queue<Integer> queue=new ArrayDeque<>();for(int box:initialBoxes){owned[box]=true;queue.offer(box);}while(!queue.isEmpty()){int box=queue.poll();if(opened[box]||!owned[box]||status[box]==0&&!hasKey[box])continue;opened[box]=true;total+=candies[box];for(int key:keys[box]){hasKey[key]=true;if(owned[key])queue.offer(key);}for(int child:containedBoxes[box]){owned[child]=true;queue.offer(child);}}return total;} }`,
`class Solution { fun maxCandies(status:IntArray,candies:IntArray,keys:Array<IntArray>,containedBoxes:Array<IntArray>,initialBoxes:IntArray):Int{val n=status.size;val owned=BooleanArray(n);val hasKey=BooleanArray(n);val opened=BooleanArray(n);val queue=java.util.ArrayDeque<Int>();for(box in initialBoxes){owned[box]=true;queue.addLast(box)};var total=0;while(queue.isNotEmpty()){val box=queue.removeFirst();if(opened[box]||!owned[box]||status[box]==0&&!hasKey[box])continue;opened[box]=true;total+=candies[box];for(key in keys[box]){hasKey[key]=true;if(owned[key])queue.addLast(key)};for(child in containedBoxes[box]){owned[child]=true;queue.addLast(child)}};return total} }`,
`class Solution { public: int maxCandies(vector<int>& status,vector<int>& candies,vector<vector<int>>& keys,vector<vector<int>>& containedBoxes,vector<int>& initialBoxes){int n=status.size(),total=0;vector<bool> owned(n),hasKey(n),opened(n);queue<int> pending;for(int box:initialBoxes){owned[box]=true;pending.push(box);}while(!pending.empty()){int box=pending.front();pending.pop();if(opened[box]||!owned[box]||(!status[box]&&!hasKey[box]))continue;opened[box]=true;total+=candies[box];for(int key:keys[box]){hasKey[key]=true;if(owned[key])pending.push(key);}for(int child:containedBoxes[box]){owned[child]=true;pending.push(child);}}return total;} };`)],tests:{schemaVersion:1,mode:'function',method:'maxCandies',parameterTypes:['intArray','intArray','intMatrix','intMatrix','intArray'],returnType:'int',cases:[{name:'经典盒子链获得十六',args:[[1,0,1,0],[7,5,4,100],[[],[],[1],[]],[[1,2],[3],[],[]],[0]],expected:16},{name:'先从开放盒取得锁盒钥匙',args:[[1,0],[5,10],[[1],[]],[[1],[]],[0]],expected:15},{name:'只有锁盒且没有钥匙',args:[[0],[9],[[]],[[]],[0]],expected:0}]}},
{id:1299,slug:'replace-elements-with-greatest-element-on-right-side',title:'将每个元素替换为右侧最大元素',studyTags:['数组','逆序扫描'],summary:'把数组每个元素替换为其右侧所有元素中的最大值，最后一个元素替换为负一。',insight:'从右向左维护已经看过元素的最大值；写入当前格前先保存原值，当前格变成 rightMaximum，再用原值更新最大值。',pitfalls:['右侧不包含当前元素','最后一项固定为负一','原地覆盖前必须保存原值'],solutions:[s('reverse-running-maximum','逆序运行最大值','从右边界向左原地写入后缀最大值。',['maximum=-1','i 从末尾到零：original=arr[i]，arr[i]=maximum','maximum=max(maximum,original)，结束返回 arr'],'O(n)','O(1)',
`class Solution { public int[] replaceElements(int[] arr){int maximum=-1;for(int i=arr.length-1;i>=0;i--){int original=arr[i];arr[i]=maximum;maximum=Math.max(maximum,original);}return arr;} }`,
`class Solution { fun replaceElements(arr:IntArray):IntArray{var maximum=-1;for(i in arr.lastIndex downTo 0){val original=arr[i];arr[i]=maximum;maximum=maxOf(maximum,original)};return arr} }`,
`class Solution { public: vector<int> replaceElements(vector<int>& arr){int maximum=-1;for(int i=arr.size()-1;i>=0;--i){int original=arr[i];arr[i]=maximum;maximum=max(maximum,original);}return arr;} };`)],tests:{schemaVersion:1,mode:'function',method:'replaceElements',parameterTypes:['intArray'],returnType:'intArray',cases:[{name:'经典后缀最大值',args:[[17,18,5,4,6,1]],expected:[18,6,6,6,1,-1]},{name:'单元素变负一',args:[[400]],expected:[-1]},{name:'严格递减数组',args:[[5,4,3]],expected:[4,3,-1]}]}},
{id:1300,slug:'sum-of-mutated-array-closest-to-target',title:'转变数组后最接近目标值的数组和',studyTags:['数组','二分查找','单调性'],summary:'选择整数 value，把数组中大于 value 的元素改为 value，求使新数组和最接近 target 的 value；并列取较小值。',insight:'截断和随 value 单调不减。二分首个截断和不小于 target 的值，再比较它和前一个值的误差即可。',pitfalls:['答案可能等于零','并列误差必须选较小值','数组元素不超过十万，和用长整型更稳妥'],solutions:[s('binary-search-cap-and-neighbor','二分截断值与相邻比较','定位目标和两侧的两个整数候选。',['left=0,right=max(arr)，二分首个 mutatedSum(value)>=target','计算 left 与 max(0,left-1) 的截断和误差','若较小候选误差不大于 left 则返回 left-1，否则返回 left'],'O(n log maxValue)','O(1)',
`class Solution { public int findBestValue(int[] arr,int target){int left=0,right=0;for(int value:arr)right=Math.max(right,value);while(left<right){int middle=(left+right)/2;if(sum(arr,middle)>=target)right=middle;else left=middle+1;}int lower=Math.max(0,left-1);return Math.abs(sum(arr,lower)-target)<=Math.abs(sum(arr,left)-target)?lower:left;}private long sum(int[] arr,int cap){long total=0;for(int value:arr)total+=Math.min(value,cap);return total;} }`,
`class Solution { fun findBestValue(arr:IntArray,target:Int):Int{var left=0;var right=arr.max();fun sum(cap:Int):Long{return arr.sumOf{minOf(it,cap).toLong()}};while(left<right){val middle=(left+right)/2;if(sum(middle)>=target)right=middle else left=middle+1};val lower=maxOf(0,left-1);return if(kotlin.math.abs(sum(lower)-target)<=kotlin.math.abs(sum(left)-target))lower else left} }`,
`class Solution { long long sum(vector<int>& arr,int cap){long long total=0;for(int value:arr)total+=min(value,cap);return total;}public:int findBestValue(vector<int>& arr,int target){int left=0,right=*max_element(arr.begin(),arr.end());while(left<right){int middle=(left+right)/2;if(sum(arr,middle)>=target)right=middle;else left=middle+1;}int lower=max(0,left-1);return llabs(sum(arr,lower)-target)<=llabs(sum(arr,left)-target)?lower:left;} };`)],tests:{schemaVersion:1,mode:'function',method:'findBestValue',parameterTypes:['intArray','int'],returnType:'int',cases:[{name:'并列时选择三',args:[[4,9,3],10],expected:3},{name:'无需截断选择五',args:[[2,3,5],10],expected:5},{name:'目标远大于总和取最大值',args:[[1,2,3],100],expected:3}]}}
]}
