const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-012',problems:[
{id:890,slug:'find-and-replace-pattern',title:'查找和替换模式',studyTags:['数组','哈希表','字符串'],summary:'返回单词列表中能通过字符一一映射变成 pattern 的所有单词。',insight:'一一映射要求双向一致：单词字符到模式字符、模式字符到单词字符都不能冲突；逐位置建立两张映射即可验证。',pitfalls:['映射必须是双射而非单向函数','同一字符重复位置必须保持一致','按输入顺序返回匹配单词'],solutions:[s('bidirectional-character-map','双向字符映射','为每个候选词同步验证两方向对应关系。',['对 word 建立 forward、backward 映射','逐下标读取 a=word[i],b=pattern[i]；已有映射不等则失败','否则写入两方向映射，全部通过则加入答案'],'O(total characters)','O(alphabet)',
`class Solution { public List<String> findAndReplacePattern(String[] words,String pattern){List<String> answer=new ArrayList<>();for(String word:words)if(matches(word,pattern))answer.add(word);return answer;}private boolean matches(String word,String pattern){Map<Character,Character> forward=new HashMap<>(),backward=new HashMap<>();for(int i=0;i<word.length();i++){char a=word.charAt(i),b=pattern.charAt(i);if(forward.containsKey(a)&&forward.get(a)!=b||backward.containsKey(b)&&backward.get(b)!=a)return false;forward.put(a,b);backward.put(b,a);}return true;} }`,
`class Solution { fun findAndReplacePattern(words:Array<String>,pattern:String):List<String> = words.filter{matches(it,pattern)};private fun matches(word:String,pattern:String):Boolean{val forward=mutableMapOf<Char,Char>();val backward=mutableMapOf<Char,Char>();for(i in word.indices){val a=word[i];val b=pattern[i];if(forward.containsKey(a)&&forward[a]!=b||backward.containsKey(b)&&backward[b]!=a)return false;forward[a]=b;backward[b]=a};return true} }`,
`class Solution { bool matches(string& word,string& pattern){unordered_map<char,char> forward,backward;for(int i=0;i<(int)word.size();++i){char a=word[i],b=pattern[i];if((forward.count(a)&&forward[a]!=b)||(backward.count(b)&&backward[b]!=a))return false;forward[a]=b;backward[b]=a;}return true;}public:vector<string> findAndReplacePattern(vector<string>& words,string pattern){vector<string> answer;for(string& word:words)if(matches(word,pattern))answer.push_back(word);return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'findAndReplacePattern',parameterTypes:['stringArray','string'],returnType:'stringList',cases:[{name:'经典两个匹配词',args:[['abc','deq','mee','aqq','dkd','ccc'],'abb'],expected:['mee','aqq']},{name:'三个互异字符',args:[['abc','deq','mee'],'abc'],expected:['abc','deq']},{name:'重复模式不匹配互异词',args:[['xyz'],'aaa'],expected:[]}]}},
{id:891,slug:'sum-of-subsequence-widths',title:'子序列宽度之和',studyTags:['数组','数学','排序'],summary:'非空子序列宽度是最大值减最小值，求所有子序列宽度之和对 1e9+7 取模。',insight:'排序后 nums[i] 作为最大值出现在 2^i 个子序列，作为最小值出现在 2^(n-1-i) 个子序列；净贡献乘 nums[i] 后求和。',pitfalls:['子序列按下标选择，重复值仍分别计数','模减法可能为负，最终加模规范化','乘法使用长整型'],solutions:[s('sorted-extreme-contributions','排序后极值贡献计数','分别计算每个元素作为最大和最小的出现次数。',['排序 nums，预计算 powers[i]=2^i mod MOD','answer 累加 nums[i]*(powers[i]-powers[n-1-i])','每步取模，最终 (answer+MOD)%MOD 返回'],'O(n log n)','O(n)',
`class Solution { public int sumSubseqWidths(int[] nums){Arrays.sort(nums);long mod=1000000007L,answer=0;long[] powers=new long[nums.length];powers[0]=1;for(int i=1;i<nums.length;i++)powers[i]=powers[i-1]*2%mod;for(int i=0;i<nums.length;i++)answer=(answer+nums[i]*(powers[i]-powers[nums.length-1-i]))%mod;return(int)((answer+mod)%mod);} }`,
`class Solution { fun sumSubseqWidths(nums:IntArray):Int{nums.sort();val mod=1000000007L;val powers=LongArray(nums.size);powers[0]=1;for(i in 1 until nums.size)powers[i]=powers[i-1]*2%mod;var answer=0L;for(i in nums.indices)answer=(answer+nums[i]*(powers[i]-powers[nums.lastIndex-i]))%mod;return((answer+mod)%mod).toInt()} }`,
`class Solution { public: int sumSubseqWidths(vector<int>& nums){sort(nums.begin(),nums.end());const long long mod=1000000007;vector<long long> powers(nums.size());powers[0]=1;for(int i=1;i<(int)nums.size();++i)powers[i]=powers[i-1]*2%mod;long long answer=0;for(int i=0;i<(int)nums.size();++i)answer=(answer+nums[i]*(powers[i]-powers[nums.size()-1-i]))%mod;return(answer+mod)%mod;} };`)],tests:{schemaVersion:1,mode:'function',method:'sumSubseqWidths',parameterTypes:['intArray'],returnType:'int',cases:[{name:'一二三宽度和六',args:[[2,1,3]],expected:6},{name:'单元素宽度零',args:[[2]],expected:0},{name:'一到四宽度和二十三',args:[[1,2,3,4]],expected:23}]}},
{id:892,slug:'surface-area-of-3d-shapes',title:'三维形体的表面积',studyTags:['数组','数学','矩阵'],summary:'网格每格堆叠若干单位立方体，求组合形体暴露在外的总表面积。',insight:'高度 h 的独立柱贡献 4h+2；与上方和左方相邻柱每重叠一层会遮住两个面，减去 2·min(height1,height2)。',pitfalls:['高度零的柱没有顶底面','每对相邻柱只处理一次','上下左右四面通过两方向邻接扣减即可'],solutions:[s('column-surfaces-minus-shared-faces','柱体表面减共享面','逐格加入独立柱面积并扣除已扫描邻居重合面。',['对 h>0 加 4*h+2','若 row>0，减 2*min(h,grid[row-1][column])','若 column>0，对左邻同样扣减；返回总和'],'O(n²)','O(1)',
`class Solution { public int surfaceArea(int[][] grid){int answer=0;for(int r=0;r<grid.length;r++)for(int c=0;c<grid[0].length;c++){int height=grid[r][c];if(height>0)answer+=4*height+2;if(r>0)answer-=2*Math.min(height,grid[r-1][c]);if(c>0)answer-=2*Math.min(height,grid[r][c-1]);}return answer;} }`,
`class Solution { fun surfaceArea(grid:Array<IntArray>):Int{var answer=0;for(r in grid.indices)for(c in grid[0].indices){val height=grid[r][c];if(height>0)answer+=4*height+2;if(r>0)answer-=2*minOf(height,grid[r-1][c]);if(c>0)answer-=2*minOf(height,grid[r][c-1])};return answer} }`,
`class Solution { public: int surfaceArea(vector<vector<int>>& grid){int answer=0;for(int r=0;r<(int)grid.size();++r)for(int c=0;c<(int)grid[0].size();++c){int height=grid[r][c];if(height)answer+=4*height+2;if(r)answer-=2*min(height,grid[r-1][c]);if(c)answer-=2*min(height,grid[r][c-1]);}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'surfaceArea',parameterTypes:['intMatrix'],returnType:'int',cases:[{name:'二阶高度矩阵',args:[[[1,2],[3,4]]],expected:34},{name:'中空环形',args:[[[1,1,1],[1,0,1],[1,1,1]]],expected:32},{name:'单柱高度二',args:[[[2]]],expected:10}]}},
{id:893,slug:'groups-of-special-equivalent-strings',title:'特殊等价字符串组',studyTags:['数组','字符串','排序'],summary:'可反复交换同一字符串中两个偶数下标或两个奇数下标字符，求字符串数组中特殊等价组数量。',insight:'操作只会分别重排偶数位字符多重集和奇数位字符多重集；把两部分排序后拼成签名即可完整刻画等价类。',pitfalls:['下标从零开始','偶数位和奇数位不能互换','重复字符串属于同一组'],solutions:[s('sorted-even-odd-signature','奇偶位排序签名','分别规范化两类下标字符并用集合去重。',['收集 word 偶数下标字符到 even，奇数到 odd','分别排序','signature=even+# +odd，加入集合；返回集合大小'],'O(words·L log L)','O(words·L)',
`class Solution { public int numSpecialEquivGroups(String[] words){Set<String> signatures=new HashSet<>();for(String word:words){char[] even=new char[(word.length()+1)/2],odd=new char[word.length()/2];for(int i=0;i<word.length();i++)if(i%2==0)even[i/2]=word.charAt(i);else odd[i/2]=word.charAt(i);Arrays.sort(even);Arrays.sort(odd);signatures.add(new String(even)+"#"+new String(odd));}return signatures.size();} }`,
`class Solution { fun numSpecialEquivGroups(words:Array<String>):Int=words.map{word->val even=word.filterIndexed{index,_->index%2==0}.toCharArray().sorted().joinToString("");val odd=word.filterIndexed{index,_->index%2==1}.toCharArray().sorted().joinToString("");"$even#$odd"}.toSet().size }`,
`class Solution { public: int numSpecialEquivGroups(vector<string>& words){unordered_set<string> signatures;for(string& word:words){string even,odd;for(int i=0;i<(int)word.size();++i)(i%2?odd:even)+=word[i];sort(even.begin(),even.end());sort(odd.begin(),odd.end());signatures.insert(even+"#"+odd);}return signatures.size();} };`)],tests:{schemaVersion:1,mode:'function',method:'numSpecialEquivGroups',parameterTypes:['stringArray'],returnType:'int',cases:[{name:'六词分三组',args:[['abcd','cdab','cbad','xyzz','zzxy','zzyx']],expected:3},{name:'重复单字符',args:[['a','a']],expected:1},{name:'反转三字符仍等价',args:[['abc','cba']],expected:1}]}},
{id:894,slug:'all-possible-full-binary-trees',title:'所有可能的真二叉树',studyTags:['树','动态规划','递归','记忆化'],summary:'真二叉树每个节点恰有零或两个孩子，节点值均为零，返回由 n 个节点组成的所有不同真二叉树。',insight:'n 为偶数时无解；对奇数 n，根占一节点，枚举左子树奇数节点数，右侧取剩余节点数，递归结果做笛卡尔积并缓存。',pitfalls:['只有奇数 n 才可能构成真二叉树','n=1 返回单叶节点','不同左右结构顺序视为不同树'],solutions:[s('memoized-odd-size-composition','奇数规模递归组合','按左右子树节点数拆分并组合所有结构。',['trees(1)=[new TreeNode(0)]，偶数返回空','leftCount 从一到 n-2 每次加二，rightCount=n-1-leftCount','组合 trees(leftCount) 与 trees(rightCount)，为每对创建新根连接，缓存并返回'],'O(number of generated trees·n)','O(number of generated trees·n)',
`class Solution { private final Map<Integer,List<TreeNode>> memo=new HashMap<>();public List<TreeNode> allPossibleFBT(int n){if(n%2==0)return new ArrayList<>();if(n==1)return new ArrayList<>(Arrays.asList(new TreeNode(0)));if(memo.containsKey(n))return memo.get(n);List<TreeNode> answer=new ArrayList<>();for(int leftCount=1;leftCount<n;leftCount+=2)for(TreeNode left:allPossibleFBT(leftCount))for(TreeNode right:allPossibleFBT(n-1-leftCount)){TreeNode root=new TreeNode(0);root.left=left;root.right=right;answer.add(root);}memo.put(n,answer);return answer;} }`,
`class Solution { private val memo=mutableMapOf<Int,List<TreeNode>>();fun allPossibleFBT(n:Int):List<TreeNode>{if(n%2==0)return emptyList();if(n==1)return listOf(TreeNode(0));memo[n]?.let{return it};val answer=mutableListOf<TreeNode>();for(leftCount in 1 until n step 2)for(left in allPossibleFBT(leftCount))for(right in allPossibleFBT(n-1-leftCount)){val root=TreeNode(0);root.left=left;root.right=right;answer.add(root)};memo[n]=answer;return answer} }`,
`class Solution { unordered_map<int,vector<TreeNode*>> memo;public:vector<TreeNode*> allPossibleFBT(int n){if(n%2==0)return{};if(n==1)return{new TreeNode(0)};if(memo.count(n))return memo[n];vector<TreeNode*> answer;for(int leftCount=1;leftCount<n;leftCount+=2)for(TreeNode* left:allPossibleFBT(leftCount))for(TreeNode* right:allPossibleFBT(n-1-leftCount)){TreeNode* root=new TreeNode(0);root->left=left;root->right=right;answer.push_back(root);}return memo[n]=answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'allPossibleFBT',parameterTypes:['int'],returnType:'treeNodeList',cases:[{name:'单节点真二叉树',args:[1],expected:[[0]]},{name:'三节点唯一结构',args:[3],expected:[[0,0,0]]},{name:'五节点两种结构',args:[5],expected:[[0,0,0,null,null,0,0],[0,0,0,0,0]]}]}}
]}
