const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-013',problems:[
{id:950,slug:'reveal-cards-in-increasing-order',title:'按递增顺序显示卡牌',studyTags:['数组','队列','排序','模拟'],summary:'安排牌堆，使反复显示顶牌、再把新顶牌移到底部的过程按递增顺序显示所有牌。',insight:'牌值升序决定显示次序；用队列模拟原过程作用于位置下标，每次把当前最小牌放到将被显示的下标，再轮转下一个下标。',pitfalls:['模拟的是下标而不是反向移动牌值','最后只剩一个下标时无需轮转','输入牌值互不相同'],solutions:[s('sorted-values-index-queue','排序牌值与下标队列','按揭示顺序给原位置赋值。',['升序排序 deck，把 0..n-1 入队','依次取排序值：弹队首 index 并令 answer[index]=value','若队列非空，把下一队首移到队尾；返回 answer'],'O(n log n)','O(n)',
`class Solution { public int[] deckRevealedIncreasing(int[] deck){Arrays.sort(deck);int[] answer=new int[deck.length];Deque<Integer> indices=new ArrayDeque<>();for(int i=0;i<deck.length;i++)indices.offer(i);for(int value:deck){answer[indices.poll()]=value;if(!indices.isEmpty())indices.offer(indices.poll());}return answer;} }`,
`class Solution { fun deckRevealedIncreasing(deck:IntArray):IntArray{deck.sort();val answer=IntArray(deck.size);val indices=java.util.ArrayDeque<Int>();for(i in deck.indices)indices.addLast(i);for(value in deck){answer[indices.removeFirst()]=value;if(indices.isNotEmpty())indices.addLast(indices.removeFirst())};return answer} }`,
`class Solution { public: vector<int> deckRevealedIncreasing(vector<int>& deck){sort(deck.begin(),deck.end());vector<int> answer(deck.size());queue<int> indices;for(int i=0;i<(int)deck.size();++i)indices.push(i);for(int value:deck){int index=indices.front();indices.pop();answer[index]=value;if(!indices.empty()){indices.push(indices.front());indices.pop();}}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'deckRevealedIncreasing',parameterTypes:['intArray'],returnType:'intArray',cases:[{name:'经典七张牌',args:[[17,13,11,2,3,5,7]],expected:[2,13,3,11,5,17,7]},{name:'两张牌',args:[[1,1000]],expected:[1,1000]},{name:'三张牌',args:[[3,1,2]],expected:[1,3,2]}]}},
{id:951,slug:'flip-equivalent-binary-trees',title:'翻转等价二叉树',studyTags:['树','深度优先搜索','递归'],summary:'二叉树任意节点可交换左右子树，判断两棵树能否通过若干次交换变得相同。',insight:'根值必须相同；其子树要么按原方向两两等价，要么交叉方向两两等价，递归判断即可。',pitfalls:['两个空节点等价，只有一个空不等价','每个节点可独立决定是否翻转','不能只比较当前层子节点值'],solutions:[s('paired-recursive-matching','成对递归匹配','同时尝试不翻转和翻转两种子树配对。',['若两节点相同引用返回 true','若一个为空或值不同返回 false','返回 direct=(left-left且right-right) 或 flipped=(left-right且right-left)'],'O(n)','O(height)',
`class Solution { public boolean flipEquiv(TreeNode root1,TreeNode root2){if(root1==root2)return true;if(root1==null||root2==null||root1.val!=root2.val)return false;return flipEquiv(root1.left,root2.left)&&flipEquiv(root1.right,root2.right)||flipEquiv(root1.left,root2.right)&&flipEquiv(root1.right,root2.left);} }`,
`class Solution { fun flipEquiv(root1:TreeNode?,root2:TreeNode?):Boolean{if(root1===root2)return true;if(root1==null||root2==null||root1.\`val\`!=root2.\`val\`)return false;return flipEquiv(root1.left,root2.left)&&flipEquiv(root1.right,root2.right)||flipEquiv(root1.left,root2.right)&&flipEquiv(root1.right,root2.left)} }`,
`class Solution { public: bool flipEquiv(TreeNode* root1,TreeNode* root2){if(root1==root2)return true;if(!root1||!root2||root1->val!=root2->val)return false;return flipEquiv(root1->left,root2->left)&&flipEquiv(root1->right,root2->right)||flipEquiv(root1->left,root2->right)&&flipEquiv(root1->right,root2->left);} };`)],tests:{schemaVersion:1,mode:'function',method:'flipEquiv',parameterTypes:['treeNode','treeNode'],returnType:'boolean',cases:[{name:'多个节点翻转等价',args:[[1,2,3,4,5,6,null,null,null,7,8],[1,3,2,null,6,4,5,null,null,null,null,8,7]],expected:true},{name:'结构不可匹配',args:[[1,2],[1,3]],expected:false},{name:'相同单节点树',args:[[1],[1]],expected:true}]}},
{id:952,slug:'largest-component-size-by-common-factor',title:'按公因数计算最大组件大小',studyTags:['数组','数学','并查集','数论'],summary:'数组元素是图节点，两个数有大于一的公因数时相连，求最大连通分量大小。',insight:'对每个数分解不同质因数；同一质因数首次出现的元素作为代表，之后出现的元素与代表合并，传递关系由并查集维护。',pitfalls:['一个质因数在同一数字中只处理一次','分解结束剩余大于一的数也是质因数','并查集统计的是数组下标而非数值'],solutions:[s('prime-factor-dsu','质因数代表并查集','通过共享质因数合并元素下标。',['初始化下标并查集与 factor->index 映射','对 nums[i] 试除质因数；每个因数若已有代表则合并，否则记录 i，并除尽该因数','处理最终剩余质因数；统计每个根的节点数并取最大'],'O(n√M α(n))','O(n+primes)',
`class Solution { public int largestComponentSize(int[] nums){int n=nums.length;int[] parent=new int[n],size=new int[n];for(int i=0;i<n;i++){parent[i]=i;size[i]=1;}Map<Integer,Integer> owner=new HashMap<>();for(int i=0;i<n;i++){int value=nums[i];for(int factor=2;factor*factor<=value;factor++)if(value%factor==0){connect(factor,i,owner,parent,size);while(value%factor==0)value/=factor;}if(value>1)connect(value,i,owner,parent,size);}int answer=0;for(int i=0;i<n;i++)if(find(i,parent)==i)answer=Math.max(answer,size[i]);return answer;}private void connect(int factor,int i,Map<Integer,Integer> owner,int[] p,int[] s){Integer other=owner.putIfAbsent(factor,i);if(other!=null)union(i,other,p,s);}private int find(int x,int[] p){return p[x]==x?x:(p[x]=find(p[x],p));}private void union(int a,int b,int[] p,int[] s){a=find(a,p);b=find(b,p);if(a==b)return;if(s[a]<s[b]){int t=a;a=b;b=t;}p[b]=a;s[a]+=s[b];} }`,
`class Solution { fun largestComponentSize(nums:IntArray):Int{val parent=IntArray(nums.size){it};val size=IntArray(nums.size){1};fun find(xInput:Int):Int{var x=xInput;while(parent[x]!=x){parent[x]=parent[parent[x]];x=parent[x]};return x};fun union(aInput:Int,bInput:Int){var a=find(aInput);var b=find(bInput);if(a==b)return;if(size[a]<size[b]){val t=a;a=b;b=t};parent[b]=a;size[a]+=size[b]};val owner=mutableMapOf<Int,Int>();fun connect(factor:Int,index:Int){val other=owner.putIfAbsent(factor,index);if(other!=null)union(index,other)};for(i in nums.indices){var value=nums[i];var factor=2;while(factor*factor<=value){if(value%factor==0){connect(factor,i);while(value%factor==0)value/=factor};factor++};if(value>1)connect(value,i)};return nums.indices.filter{find(it)==it}.maxOf{size[it]}} }`,
`class Solution { vector<int> parent,size;int find(int x){return parent[x]==x?x:parent[x]=find(parent[x]);}void unite(int a,int b){a=find(a);b=find(b);if(a==b)return;if(size[a]<size[b])swap(a,b);parent[b]=a;size[a]+=size[b];}public:int largestComponentSize(vector<int>& nums){int n=nums.size();parent.resize(n);iota(parent.begin(),parent.end(),0);size.assign(n,1);unordered_map<int,int> owner;auto connect=[&](int factor,int index){if(owner.count(factor))unite(index,owner[factor]);else owner[factor]=index;};for(int i=0;i<n;++i){int value=nums[i];for(int factor=2;factor*factor<=value;++factor)if(value%factor==0){connect(factor,i);while(value%factor==0)value/=factor;}if(value>1)connect(value,i);}int answer=0;for(int i=0;i<n;++i)if(find(i)==i)answer=max(answer,size[i]);return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'largestComponentSize',parameterTypes:['intArray'],returnType:'int',cases:[{name:'链式四节点',args:[[4,6,15,35]],expected:4},{name:'两个分量最大二',args:[[20,50,9,63]],expected:2},{name:'六个节点全连通',args:[[2,3,6,7,4,12,21,39]],expected:8}]}},
{id:953,slug:'verifying-an-alien-dictionary',title:'验证外星语词典',studyTags:['数组','字符串','哈希表'],summary:'给定外星字母顺序，判断单词数组是否按该语言的字典序非递减排列。',insight:'建立字符排名，只需逐对比较相邻单词的第一个不同字符；若一词是另一词前缀，则短词必须在前。',pitfalls:['只比较第一个不同字符','完全相同的相邻单词合法','较长词以较短词为前缀时顺序非法'],solutions:[s('adjacent-rank-comparison','相邻单词排名比较','按自定义字符秩实现字典序判断。',['构建 rank[26]','对每对相邻单词扫描共同前缀','若一个词耗尽，要求前词长度不大于后词；否则要求前词首个不同字符排名更小，任一失败返回 false'],'O(total characters)','O(1)',
`class Solution { public boolean isAlienSorted(String[] words,String order){int[] rank=new int[26];for(int i=0;i<26;i++)rank[order.charAt(i)-'a']=i;for(int w=1;w<words.length;w++){String a=words[w-1],b=words[w];int i=0;while(i<a.length()&&i<b.length()&&a.charAt(i)==b.charAt(i))i++;if(i==b.length()&&i<a.length())return false;if(i<a.length()&&i<b.length()&&rank[a.charAt(i)-'a']>rank[b.charAt(i)-'a'])return false;}return true;} }`,
`class Solution { fun isAlienSorted(words:Array<String>,order:String):Boolean{val rank=IntArray(26);for(i in order.indices)rank[order[i]-'a']=i;for(w in 1 until words.size){val a=words[w-1];val b=words[w];var i=0;while(i<a.length&&i<b.length&&a[i]==b[i])i++;if(i==b.length&&i<a.length)return false;if(i<a.length&&i<b.length&&rank[a[i]-'a']>rank[b[i]-'a'])return false};return true} }`,
`class Solution { public: bool isAlienSorted(vector<string>& words,string order){int rank[26];for(int i=0;i<26;++i)rank[order[i]-'a']=i;for(int w=1;w<(int)words.size();++w){string& a=words[w-1];string& b=words[w];int i=0;while(i<(int)a.size()&&i<(int)b.size()&&a[i]==b[i])++i;if(i==(int)b.size()&&i<(int)a.size())return false;if(i<(int)a.size()&&i<(int)b.size()&&rank[a[i]-'a']>rank[b[i]-'a'])return false;}return true;} };`)],tests:{schemaVersion:1,mode:'function',method:'isAlienSorted',parameterTypes:['stringArray','string'],returnType:'boolean',cases:[{name:'自定义顺序合法',args:[['hello','leetcode'],'hlabcdefgijkmnopqrstuvwxyz'],expected:true},{name:'首个不同字符逆序',args:[['word','world','row'],'worldabcefghijkmnpqstuvxyz'],expected:false},{name:'长词在前缀前非法',args:[['apple','app'],'abcdefghijklmnopqrstuvwxyz'],expected:false}]}},
{id:954,slug:'array-of-doubled-pairs',title:'二倍数对数组',studyTags:['数组','哈希表','排序','贪心'],summary:'判断能否重排偶数长度数组，使前一半每个元素的二倍等于后一半对应元素。',insight:'按绝对值从小到大处理，保证给 x 匹配 2x 时不会错误消耗本应作为更小值二倍数的元素；用频次表扣减。',pitfalls:['负数也必须按绝对值排序','零必须成对出现','匹配后 x 和 2x 都各减少一次'],solutions:[s('absolute-order-frequency-pairing','绝对值排序频次配对','从最接近零的未配元素贪心找其二倍。',['统计每个值频次，并把元素装箱后按绝对值升序','依次处理 x；若 count[x]==0 跳过','若 count[2*x]==0 返回 false，否则两者频次各减一；全部完成返回 true'],'O(n log n)','O(n)',
`class Solution { public boolean canReorderDoubled(int[] arr){Map<Integer,Integer> count=new HashMap<>();Integer[] values=new Integer[arr.length];for(int i=0;i<arr.length;i++){values[i]=arr[i];count.merge(arr[i],1,Integer::sum);}Arrays.sort(values,Comparator.comparingInt(Math::abs));for(int x:values){if(count.get(x)==0)continue;if(count.getOrDefault(2*x,0)==0)return false;count.put(x,count.get(x)-1);count.put(2*x,count.get(2*x)-1);}return true;} }`,
`class Solution { fun canReorderDoubled(arr:IntArray):Boolean{val count=mutableMapOf<Int,Int>();for(x in arr)count[x]=(count[x]?:0)+1;for(x in arr.toTypedArray().sortedBy{kotlin.math.abs(it)}){if(count[x]==0)continue;if((count[2*x]?:0)==0)return false;count[x]=count[x]!!-1;count[2*x]=count[2*x]!!-1};return true} }`,
`class Solution { public: bool canReorderDoubled(vector<int>& arr){unordered_map<int,int> count;for(int x:arr)++count[x];sort(arr.begin(),arr.end(),[](int a,int b){return abs(a)<abs(b);});for(int x:arr){if(count[x]==0)continue;if(count[2*x]==0)return false;--count[x];--count[2*x];}return true;} };`)],tests:{schemaVersion:1,mode:'function',method:'canReorderDoubled',parameterTypes:['intArray'],returnType:'boolean',cases:[{name:'含负数可配对',args:[[4,-2,2,-4]],expected:true},{name:'缺少二倍数',args:[[3,1,3,6]],expected:false},{name:'多余无法配对元素',args:[[2,1,2,6]],expected:false}]}}
]}
