const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})

export default {batchId:'batch-017',problems:[
{id:1186,slug:'maximum-subarray-sum-with-one-deletion',title:'删除一次得到子数组最大和',studyTags:['数组','动态规划','状态机'],summary:'选择非空连续子数组，并可从中删除至多一个元素，求能得到的最大元素和。',insight:'扫描到当前位置时维护两个状态：keep 表示尚未删除且必须以当前元素结尾，removed 表示已经删除一次。removed 可由之前已删除后加当前值，或删除当前元素而直接继承旧 keep。',pitfalls:['最终子数组必须非空，不能把唯一元素删除','删除是至多一次，所以答案同时比较两个状态','全负数组应返回最大的单个元素'],solutions:[s('two-state-ending-dp','双状态结尾动态规划','滚动维护以当前下标为右端点的未删和已删最优和。',['keep=arr[0]，removed 设为不可达负无穷，answer=arr[0]','对每个 x：nextRemoved=max(removed+x,keep)，nextKeep=max(x,keep+x)','更新两状态与 answer=max(answer,keep,removed)，返回 answer'],'O(n)','O(1)',
`class Solution { public int maximumSum(int[] arr){int keep=arr[0],removed=Integer.MIN_VALUE/2,answer=arr[0];for(int i=1;i<arr.length;i++){int nextRemoved=Math.max(removed+arr[i],keep);int nextKeep=Math.max(arr[i],keep+arr[i]);keep=nextKeep;removed=nextRemoved;answer=Math.max(answer,Math.max(keep,removed));}return answer;} }`,
`class Solution { fun maximumSum(arr:IntArray):Int{var keep=arr[0];var removed=Int.MIN_VALUE/2;var answer=arr[0];for(i in 1 until arr.size){val nextRemoved=maxOf(removed+arr[i],keep);val nextKeep=maxOf(arr[i],keep+arr[i]);keep=nextKeep;removed=nextRemoved;answer=maxOf(answer,keep,removed)};return answer} }`,
`class Solution { public: int maximumSum(vector<int>& arr){int keep=arr[0],removed=INT_MIN/2,answer=arr[0];for(int i=1;i<(int)arr.size();++i){int nextRemoved=max(removed+arr[i],keep),nextKeep=max(arr[i],keep+arr[i]);keep=nextKeep;removed=nextRemoved;answer=max({answer,keep,removed});}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'maximumSum',parameterTypes:['intArray'],returnType:'int',cases:[{name:'删去负二连接两段',args:[[1,-2,0,3]],expected:4},{name:'保留末尾三最优',args:[[1,-2,-2,3]],expected:3},{name:'全负取单个',args:[[-1,-1,-1]],expected:-1}]}},

{id:1187,slug:'make-array-strictly-increasing',title:'使数组严格递增',studyTags:['数组','动态规划','二分查找','排序'],summary:'可把 arr1 任意元素替换为 arr2 中任一元素，求使 arr1 严格递增的最少替换次数，不可能返回负一。',insight:'动态规划状态用最后保留值映射到最少操作数。处理每个 arr1 值时可原样保留，或把它替换成 arr2 中严格大于 last 的最小值；更大的替换值不会带来优势。',pitfalls:['arr2 允许重复，排序后用 upper_bound','严格递增要求新值大于 last','相同或更大的最后值且操作数不更少的状态可删除'],solutions:[s('last-value-frontier-dp','末值前沿动态规划','维护不被支配的末值与最小替换次数。',['排序 arr2；dp 初始 {-1:0}','对 arr1 的每个 value，遍历状态：若 value>last 可保留；再二分 arr2 首个>last 的 replacement 并以 ops+1 转移','按末值升序去掉操作数不优的支配状态；若空返回 -1，最后返回最小操作数'],'O(n²+n log m)','O(n)',
`class Solution { public int makeArrayIncreasing(int[] arr1,int[] arr2){Arrays.sort(arr2);Map<Integer,Integer> states=new HashMap<>();states.put(-1,0);for(int value:arr1){TreeMap<Integer,Integer> next=new TreeMap<>();for(Map.Entry<Integer,Integer> state:states.entrySet()){int last=state.getKey(),operations=state.getValue();if(value>last)next.merge(value,operations,Math::min);int index=upperBound(arr2,last);if(index<arr2.length)next.merge(arr2[index],operations+1,Math::min);}Map<Integer,Integer> pruned=new HashMap<>();int best=Integer.MAX_VALUE;for(Map.Entry<Integer,Integer> state:next.entrySet())if(state.getValue()<best){best=state.getValue();pruned.put(state.getKey(),best);}states=pruned;if(states.isEmpty())return -1;}return Collections.min(states.values());}private int upperBound(int[] values,int target){int left=0,right=values.length;while(left<right){int middle=(left+right)/2;if(values[middle]<=target)left=middle+1;else right=middle;}return left;} }`,
`class Solution { fun makeArrayIncreasing(arr1:IntArray,arr2:IntArray):Int{arr2.sort();var states:Map<Int,Int> = mapOf(-1 to 0);for(value in arr1){val next=java.util.TreeMap<Int,Int>();for((last,operations) in states){if(value>last)next[value]=minOf(next[value]?:Int.MAX_VALUE,operations);val index=upperBound(arr2,last);if(index<arr2.size)next[arr2[index]]=minOf(next[arr2[index]]?:Int.MAX_VALUE,operations+1)};val pruned=mutableMapOf<Int,Int>();var best=Int.MAX_VALUE;for((last,operations) in next)if(operations<best){best=operations;pruned[last]=operations};states=pruned;if(states.isEmpty())return -1};return states.values.min()};private fun upperBound(values:IntArray,target:Int):Int{var left=0;var right=values.size;while(left<right){val middle=(left+right)/2;if(values[middle]<=target)left=middle+1 else right=middle};return left} }`,
`class Solution { int upperBound(vector<int>& values,int target){return upper_bound(values.begin(),values.end(),target)-values.begin();}public:int makeArrayIncreasing(vector<int>& arr1,vector<int>& arr2){sort(arr2.begin(),arr2.end());map<int,int> states{{-1,0}};for(int value:arr1){map<int,int> next;for(auto [last,operations]:states){if(value>last){if(!next.count(value))next[value]=operations;else next[value]=min(next[value],operations);}int index=upperBound(arr2,last);if(index<(int)arr2.size()){int replacement=arr2[index];if(!next.count(replacement))next[replacement]=operations+1;else next[replacement]=min(next[replacement],operations+1);}}map<int,int> pruned;int best=INT_MAX;for(auto [last,operations]:next)if(operations<best){best=operations;pruned[last]=operations;}states.swap(pruned);if(states.empty())return -1;}int answer=INT_MAX;for(auto [last,operations]:states)answer=min(answer,operations);return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'makeArrayIncreasing',parameterTypes:['intArray','intArray'],returnType:'int',cases:[{name:'替换一次',args:[[1,5,3,6,7],[1,3,2,4]],expected:1},{name:'替换两次',args:[[1,5,3,6,7],[4,3,1]],expected:2},{name:'无法严格递增',args:[[1,5,3,6,7],[1,6,3,3]],expected:-1}]}},

{id:1189,slug:'maximum-number-of-balloons',title:'气球的最大数量',studyTags:['字符串','计数','哈希表'],summary:'给定小写字符串，求最多能用其中字符组成多少个单词 balloon，每个字符只能使用一次。',insight:'balloon 需要 b、a、n 各一个，l、o 各两个；统计字母频次后取这五种资源配额的最小值。',pitfalls:['l 和 o 的需求量为二','无关字符不影响答案','资源不足一种就不能再组成完整单词'],solutions:[s('required-letter-quotas','目标字母配额','按 balloon 各字符需求折算可组成数量。',['统计 text 中 26 个字母频次','计算 b、a、n 的原频次，以及 l/2、o/2','返回五者最小值'],'O(n)','O(1)',
`class Solution { public int maxNumberOfBalloons(String text){int[] count=new int[26];for(char ch:text.toCharArray())count[ch-'a']++;return Math.min(Math.min(count['b'-'a'],count['a'-'a']),Math.min(count['n'-'a'],Math.min(count['l'-'a']/2,count['o'-'a']/2)));} }`,
`class Solution { fun maxNumberOfBalloons(text:String):Int{val count=IntArray(26);for(ch in text)count[ch-'a']++;return minOf(count['b'-'a'],count['a'-'a'],count['n'-'a'],count['l'-'a']/2,count['o'-'a']/2)} }`,
`class Solution { public: int maxNumberOfBalloons(string text){int count[26]={};for(char ch:text)++count[ch-'a'];return min({count['b'-'a'],count['a'-'a'],count['n'-'a'],count['l'-'a']/2,count['o'-'a']/2});} };`)],tests:{schemaVersion:1,mode:'function',method:'maxNumberOfBalloons',parameterTypes:['string'],returnType:'int',cases:[{name:'可组成一个',args:['nlaebolko'],expected:1},{name:'可组成两个',args:['loonbalxballpoon'],expected:2},{name:'完全缺字母',args:['leetcode'],expected:0}]}},

{id:1190,slug:'reverse-substrings-between-each-pair-of-parentheses',title:'反转每对括号间的子串',studyTags:['字符串','栈','模拟'],summary:'从内到外反转每对匹配括号中的字符串，最终删除所有括号并返回结果。',insight:'遇左括号时把外层已构造字符串压栈并开始新片段；遇右括号时反转当前内层片段，再接到弹出的外层后方，天然按嵌套顺序处理。',pitfalls:['括号保证匹配且不出现在结果中','反转发生在每一层闭合时','普通字符直接追加到当前片段'],solutions:[s('builder-stack-nested-reversal','构造器栈嵌套反转','用栈保存每层左括号之前的外部前缀。',['current 为空，stack 为空','遇 (：压入 current 并新建空 current；遇 )：反转 current，弹出 outer 并令 current=outer+current','普通字母追加 current，扫描结束返回 current'],'O(n²) 最坏，常见 O(n)','O(n)',
`class Solution { public String reverseParentheses(String s){Deque<StringBuilder> stack=new ArrayDeque<>();StringBuilder current=new StringBuilder();for(char ch:s.toCharArray())if(ch=='('){stack.push(current);current=new StringBuilder();}else if(ch==')'){current.reverse();StringBuilder outer=stack.pop();outer.append(current);current=outer;}else current.append(ch);return current.toString();} }`,
`class Solution { fun reverseParentheses(s:String):String{val stack=java.util.ArrayDeque<StringBuilder>();var current=StringBuilder();for(ch in s)if(ch=='('){stack.push(current);current=StringBuilder()}else if(ch==')'){current.reverse();val outer=stack.pop();outer.append(current);current=outer}else current.append(ch);return current.toString()} }`,
`class Solution { public: string reverseParentheses(string s){stack<string> saved;string current;for(char ch:s)if(ch=='('){saved.push(current);current.clear();}else if(ch==')'){reverse(current.begin(),current.end());current=saved.top()+current;saved.pop();}else current+=ch;return current;} };`)],tests:{schemaVersion:1,mode:'function',method:'reverseParentheses',parameterTypes:['string'],returnType:'string',cases:[{name:'单层反转',args:['(abcd)'],expected:'dcba'},{name:'两层嵌套',args:['(u(love)i)'],expected:'iloveu'},{name:'三层得到 leetcode',args:['(ed(et(oc))el)'],expected:'leetcode'}]}},

{id:1191,slug:'k-concatenation-maximum-sum',title:'K 次串联后最大子数组之和',studyTags:['数组','动态规划','Kadane','数学'],summary:'把数组首尾串联 k 次，求其中非空连续子数组的最大和；若最大和为负则返回零，结果对 10^9+7 取模。',insight:'跨副本的最优子数组边界形态在两份数组内已经确定。先对最多两个副本做 Kadane；若数组总和为正且 k>2，中间完整的 k-2 份都应加入。',pitfalls:['题目规定负答案返回零','中间乘法与总和使用长整型','取模只用于最终数值，不参与大小比较'],solutions:[s('two-copy-kadane-plus-middle','双副本 Kadane 与中间整段','把首尾贡献和正总和的完整中间副本分开。',['求数组 total；遍历 min(k,2) 份，Kadane 维护 ending=max(0,ending+x) 与 best','若 k>2 且 total>0，则 best+=(k-2)*total','返回 best mod 1e9+7'],'O(n·min(k,2))','O(1)',
`class Solution { public int kConcatenationMaxSum(int[] arr,int k){long total=0;for(int value:arr)total+=value;long ending=0,best=0;for(int copy=0;copy<Math.min(k,2);copy++)for(int value:arr){ending=Math.max(0,ending+value);best=Math.max(best,ending);}if(k>2&&total>0)best+=(long)(k-2)*total;return (int)(best%1000000007L);} }`,
`class Solution { fun kConcatenationMaxSum(arr:IntArray,k:Int):Int{val total=arr.sumOf{it.toLong()};var ending=0L;var best=0L;repeat(minOf(k,2)){for(value in arr){ending=maxOf(0L,ending+value);best=maxOf(best,ending)}};if(k>2&&total>0)best+=(k-2L)*total;return (best%1000000007L).toInt()} }`,
`class Solution { public: int kConcatenationMaxSum(vector<int>& arr,int k){long long total=accumulate(arr.begin(),arr.end(),0LL),ending=0,best=0;for(int copy=0;copy<min(k,2);++copy)for(int value:arr){ending=max(0LL,ending+value);best=max(best,ending);}if(k>2&&total>0)best+=(long long)(k-2)*total;return best%1000000007;} };`)],tests:{schemaVersion:1,mode:'function',method:'kConcatenationMaxSum',parameterTypes:['intArray','int'],returnType:'int',cases:[{name:'全正三份',args:[[1,2],3],expected:9},{name:'总和为零只跨边界',args:[[1,-2,1],5],expected:2},{name:'全负按规则返回零',args:[[-1,-2],7],expected:0}]}}
]}
