const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-025',problems:[
{id:1758,slug:'minimum-changes-to-make-alternating-binary-string',title:'生成交替二进制字符串的最少操作数',studyTags:['字符串'],summary:'每次可翻转任一位，求把二进制字符串变成相邻字符均不同的交替串所需最少操作数。',insight:'交替串只有 0101... 和 1010... 两种。统计原串与第一种的不同位数，另一种的不同数恰为 n 减前者，取较小值。',pitfalls:['每个位置只需独立比较','两种目标模式互补','长度一答案为零'],solutions:[s('two-pattern-mismatch-count','两种模式失配计数','只计算一种目标即可推导另一种代价。',['mismatch=0','i 位置期望字符为 i%2 对应的 0/1，失配则计数','返回 min(mismatch,n-mismatch)'],'O(n)','O(1)',
`class Solution { public int minOperations(String text){int mismatch=0;for(int i=0;i<text.length();i++)if(text.charAt(i)!=(char)('0'+i%2))mismatch++;return Math.min(mismatch,text.length()-mismatch);} }`,
`class Solution { fun minOperations(text:String):Int{val mismatch=text.indices.count{text[it]!=('0'.code+it%2).toChar()};return minOf(mismatch,text.length-mismatch)} }`,
`class Solution { public: int minOperations(string text){int mismatch=0;for(int i=0;i<(int)text.size();++i)mismatch+=text[i]!='0'+i%2;return min(mismatch,(int)text.size()-mismatch);} };`)],tests:{schemaVersion:1,mode:'function',method:'minOperations',parameterTypes:['string'],returnType:'int',cases:[{name:'零一零零一零只需翻一位',args:['0100'],expected:1},{name:'全一三位需翻一位',args:['1111'],expected:2},{name:'一零已交替',args:['10'],expected:0}]}},
{id:1759,slug:'count-number-of-homogenous-substrings',title:'统计同构子字符串的数目',studyTags:['数学','字符串'],summary:'若子串所有字符相同则为同构子串，统计所有非空同构子串数量并取模。',insight:'每个长度为 L 的连续同字符段贡献 L(L+1)/2 个子串；也可扫描时令当前连续长度加一并把它加入答案。',pitfalls:['不同下标的相同内容子串分别计数','连续段跨字符边界归零','每步取模'],solutions:[s('running-equal-run-length','连续同字符长度累加','以每个位置结尾的同构子串数就是当前连续段长度。',['run=answer=0','扫描 i，若 i>0 且字符相同则 run++，否则 run=1','answer=(answer+run)%MOD，返回'],'O(n)','O(1)',
`class Solution { public int countHomogenous(String text){final int MOD=1_000_000_007;long answer=0,run=0;for(int i=0;i<text.length();i++){run=i>0&&text.charAt(i)==text.charAt(i-1)?run+1:1;answer=(answer+run)%MOD;}return (int)answer;} }`,
`class Solution { fun countHomogenous(text:String):Int{val mod=1_000_000_007L;var answer=0L;var run=0L;for(i in text.indices){run=if(i>0&&text[i]==text[i-1])run+1 else 1;answer=(answer+run)%mod};return answer.toInt()} }`,
`class Solution { public: int countHomogenous(string text){const int MOD=1000000007;long long answer=0,run=0;for(int i=0;i<(int)text.size();++i){run=i&&text[i]==text[i-1]?run+1:1;answer=(answer+run)%MOD;}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'countHomogenous',parameterTypes:['string'],returnType:'int',cases:[{name:'多个连续段共有十三个',args:['abbcccaa'],expected:13},{name:'两个不同字符各贡献一',args:['xy'],expected:2},{name:'五个相同字符贡献十五',args:['zzzzz'],expected:15}]}},
{id:1760,slug:'minimum-limit-of-balls-in-a-bag',title:'袋子里最少数目的球',studyTags:['数组','二分查找'],summary:'最多执行 maxOperations 次，每次把一袋正整数个球分成两袋，最小化最终单袋最大球数。',insight:'给定上限 penalty，一袋 value 需要 floor((value-1)/penalty) 次分割。所需操作数随 penalty 单调不增，可二分最小可行上限。',pitfalls:['恰好整除时分袋数为 value/penalty，操作数少一','操作数累计可提前超过上限','二分范围一到原最大袋'],solutions:[s('binary-search-penalty','二分最大袋容量','利用限制越宽松所需操作越少的单调性。',['left=1,right=max(nums)','mid 下累计 operations+=(value-1)/mid','operations<=maxOperations 则 right=mid，否则 left=mid+1，返回 left'],'O(n log V)','O(1)',
`class Solution { public int minimumSize(int[] nums,int maxOperations){int left=1,right=Arrays.stream(nums).max().getAsInt();while(left<right){int middle=left+(right-left)/2;long operations=0;for(int value:nums)operations+=(value-1)/middle;if(operations<=maxOperations)right=middle;else left=middle+1;}return left;} }`,
`class Solution { fun minimumSize(nums:IntArray,maxOperations:Int):Int{var left=1;var right=nums.maxOrNull()!!;while(left<right){val middle=left+(right-left)/2;var operations=0L;for(value in nums)operations+=(value-1)/middle;if(operations<=maxOperations)right=middle else left=middle+1};return left} }`,
`class Solution { public: int minimumSize(vector<int>& nums,int maxOperations){int left=1,right=*max_element(nums.begin(),nums.end());while(left<right){int middle=left+(right-left)/2;long long operations=0;for(int value:nums)operations+=(value-1)/middle;if(operations<=maxOperations)right=middle;else left=middle+1;}return left;} };`)],tests:{schemaVersion:1,mode:'function',method:'minimumSize',parameterTypes:['intArray','int'],returnType:'int',cases:[{name:'九个球分两次最大三',args:[[9],2],expected:3},{name:'四袋球分四次最大二',args:[[2,4,8,2],4],expected:2},{name:'七与十七分两次最大七',args:[[7,17],2],expected:7}]}},
{id:1761,slug:'minimum-degree-of-a-connected-trio-in-a-graph',title:'一个图中连通三元组的最小度数',studyTags:['图论','枚举'],summary:'连通三元组是三个节点两两有边，其度数为三节点连接到三元组外部的边数，求最小度数，不存在返回负一。',insight:'先统计每节点总度数与邻接矩阵，枚举 i<j<k 的三角形。三节点总度数包含内部三条边各两次，所以外部度数为 degree[i]+degree[j]+degree[k]-6。',pitfalls:['节点编号从一开始','只枚举两两相连的三节点','内部三条边需共减六'],solutions:[s('triangle-enumeration','邻接矩阵三角形枚举','直接验证每组三节点并由总度数推导外部边数。',['统计 degree 与 connected','枚举 first<second<third','三条边都存在时更新 degree 和减六；无三元组返回 -1'],'O(n³+E)','O(n²)',
`class Solution { public int minTrioDegree(int n,int[][] edges){int[] degree=new int[n];boolean[][] connected=new boolean[n][n];for(int[] edge:edges){int a=edge[0]-1,b=edge[1]-1;degree[a]++;degree[b]++;connected[a][b]=connected[b][a]=true;}int answer=Integer.MAX_VALUE;for(int first=0;first<n;first++)for(int second=first+1;second<n;second++)if(connected[first][second])for(int third=second+1;third<n;third++)if(connected[first][third]&&connected[second][third])answer=Math.min(answer,degree[first]+degree[second]+degree[third]-6);return answer==Integer.MAX_VALUE?-1:answer;} }`,
`class Solution { fun minTrioDegree(n:Int,edges:Array<IntArray>):Int{val degree=IntArray(n);val connected=Array(n){BooleanArray(n)};for(edge in edges){val a=edge[0]-1;val b=edge[1]-1;degree[a]++;degree[b]++;connected[a][b]=true;connected[b][a]=true};var answer=Int.MAX_VALUE;for(first in 0 until n)for(second in first+1 until n)if(connected[first][second])for(third in second+1 until n)if(connected[first][third]&&connected[second][third])answer=minOf(answer,degree[first]+degree[second]+degree[third]-6);return if(answer==Int.MAX_VALUE)-1 else answer} }`,
`class Solution { public: int minTrioDegree(int n,vector<vector<int>>& edges){vector<int> degree(n);vector<vector<bool>> connected(n,vector<bool>(n));for(auto& edge:edges){int a=edge[0]-1,b=edge[1]-1;++degree[a];++degree[b];connected[a][b]=connected[b][a]=true;}int answer=INT_MAX;for(int first=0;first<n;++first)for(int second=first+1;second<n;++second)if(connected[first][second])for(int third=second+1;third<n;++third)if(connected[first][third]&&connected[second][third])answer=min(answer,degree[first]+degree[second]+degree[third]-6);return answer==INT_MAX?-1:answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'minTrioDegree',parameterTypes:['int','intMatrix'],returnType:'int',cases:[{name:'经典图最小三元组度数三',args:[6,[[1,2],[1,3],[3,2],[4,1],[5,2],[3,6]]],expected:3},{name:'没有三角形返回负一',args:[4,[[1,2],[2,3],[3,4]]],expected:-1},{name:'单独三角形外部度数零',args:[3,[[1,2],[2,3],[1,3]]],expected:0}]}},
{id:1763,slug:'longest-nice-substring',title:'最长的美好子字符串',studyTags:['哈希表','字符串','分治','滑动窗口'],summary:'若子串中每个英文字母都同时出现大小写形式，则为美好子串，返回最长者；并列取最早出现。',insight:'若当前区间某字符缺少其大小写对应形式，任何跨过该字符的子串都不可能美好；以它为界递归求左右区间最长解。',pitfalls:['长度小于二不可能美好','并列要保留左侧结果','对应大小写判断不区分原字符形式'],solutions:[s('invalid-character-divide-and-conquer','缺失大小写字符分治','用必不能包含的字符切开候选区间。',['若 text.length<2 返回空串，建立当前字符集合','找到首个缺少对应大小写的字符 index','递归 left=text[0,index)、right=text[index+1,n)，返回更长者；若无此字符当前串即美好'],'O(n²)','O(n)',
`class Solution { public String longestNiceSubstring(String text){if(text.length()<2)return "";Set<Character> set=new HashSet<>();for(char letter:text.toCharArray())set.add(letter);for(int i=0;i<text.length();i++){char letter=text.charAt(i);if(!set.contains(Character.toLowerCase(letter))||!set.contains(Character.toUpperCase(letter))){String left=longestNiceSubstring(text.substring(0,i)),right=longestNiceSubstring(text.substring(i+1));return left.length()>=right.length()?left:right;}}return text;} }`,
`class Solution { fun longestNiceSubstring(text:String):String{if(text.length<2)return "";val set=text.toSet();for(i in text.indices){val letter=text[i];if(letter.lowercaseChar() !in set||letter.uppercaseChar() !in set){val left=longestNiceSubstring(text.substring(0,i));val right=longestNiceSubstring(text.substring(i+1));return if(left.length>=right.length)left else right}};return text} }`,
`class Solution { public: string longestNiceSubstring(string text){if(text.size()<2)return "";unordered_set<char> set(text.begin(),text.end());for(int i=0;i<(int)text.size();++i){char lower=tolower(text[i]),upper=toupper(text[i]);if(!set.count(lower)||!set.count(upper)){string left=longestNiceSubstring(text.substr(0,i)),right=longestNiceSubstring(text.substr(i+1));return left.size()>=right.size()?left:right;}}return text;} };`)],tests:{schemaVersion:1,mode:'function',method:'longestNiceSubstring',parameterTypes:['string'],returnType:'string',cases:[{name:'最长美好子串为 aAa',args:['YazaAay'],expected:'aAa'},{name:'整个 Bb 都美好',args:['Bb'],expected:'Bb'},{name:'单个小写字符无美好子串',args:['c'],expected:''}]}}
]}
