const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-012',problems:[
{id:874,slug:'walking-robot-simulation',title:'模拟行走机器人',studyTags:['数组','哈希集合','模拟'],summary:'机器人从原点朝北，按前进、左转和右转指令移动，不能进入障碍格，求过程中到原点最大欧氏距离平方。',insight:'逐单位执行前进指令才能在障碍前停下；把障碍坐标编码进集合，方向用四个向量和模四下标维护。',pitfalls:['遇障碍时当前前进指令剩余步数全部停止','负一右转、负二左转','答案在每个实际移动后更新'],solutions:[s('unit-step-obstacle-simulation','逐步障碍模拟','用方向下标和坐标集合执行全部命令。',['把 obstacle 编码为 x,y 字符串或整数对集合','direction=北；-1 令 direction=(direction+1)%4，-2 令 direction=(direction+3)%4','正命令逐步计算 next，若是障碍 break，否则更新坐标和最大 x²+y²'],'O(total steps + obstacles)','O(obstacles)',
`class Solution { public int robotSim(int[] commands,int[][] obstacles){Set<String> blocked=new HashSet<>();for(int[] obstacle:obstacles)blocked.add(obstacle[0]+","+obstacle[1]);int[][] directions={{0,1},{1,0},{0,-1},{-1,0}};int direction=0,x=0,y=0,answer=0;for(int command:commands){if(command==-1)direction=(direction+1)%4;else if(command==-2)direction=(direction+3)%4;else for(int step=0;step<command;step++){int nextX=x+directions[direction][0],nextY=y+directions[direction][1];if(blocked.contains(nextX+","+nextY))break;x=nextX;y=nextY;answer=Math.max(answer,x*x+y*y);}}return answer;} }`,
`class Solution { fun robotSim(commands:IntArray,obstacles:Array<IntArray>):Int{val blocked=obstacles.map{it[0] to it[1]}.toSet();val directions=arrayOf(intArrayOf(0,1),intArrayOf(1,0),intArrayOf(0,-1),intArrayOf(-1,0));var direction=0;var x=0;var y=0;var answer=0;for(command in commands){if(command==-1)direction=(direction+1)%4 else if(command==-2)direction=(direction+3)%4 else repeat(command){val nextX=x+directions[direction][0];val nextY=y+directions[direction][1];if(nextX to nextY in blocked)return@repeat;x=nextX;y=nextY;answer=maxOf(answer,x*x+y*y)}};return answer} }`,
`class Solution { public: int robotSim(vector<int>& commands,vector<vector<int>>& obstacles){set<pair<int,int>> blocked;for(auto& obstacle:obstacles)blocked.insert({obstacle[0],obstacle[1]});int directions[4][2]={{0,1},{1,0},{0,-1},{-1,0}},direction=0,x=0,y=0,answer=0;for(int command:commands){if(command==-1)direction=(direction+1)%4;else if(command==-2)direction=(direction+3)%4;else for(int step=0;step<command;++step){int nextX=x+directions[direction][0],nextY=y+directions[direction][1];if(blocked.count({nextX,nextY}))break;x=nextX;y=nextY;answer=max(answer,x*x+y*y);}}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'robotSim',parameterTypes:['intArray','intMatrix'],returnType:'int',cases:[{name:'右转后到三四',args:[[4,-1,3],[]],expected:25},{name:'障碍阻挡路径',args:[[4,-1,4,-2,4],[[2,4]]],expected:65},{name:'两次右转返回原点',args:[[6,-1,-1,6],[]],expected:36}]}},
{id:875,slug:'koko-eating-bananas',title:'爱吃香蕉的珂珂',studyTags:['数组','二分查找'],summary:'每小时选择一堆香蕉并最多吃 speed 根，求在 h 小时内吃完所有堆的最小整数速度。',insight:'所需小时数随速度单调不增；在一到最大堆大小上二分第一个满足 Σceil(pile/speed)<=h 的速度。',pitfalls:['每小时只能处理一堆','整除向上取整写成 (pile+speed-1)/speed','累计小时数可提前超过 h'],solutions:[s('binary-search-minimum-speed','二分最小可行速度','用单调可行性判断收缩速度区间。',['low=1,high=max(piles)','middle=(low+high)/2，计算所需 hours','hours<=h 时 high=middle，否则 low=middle+1；返回 low'],'O(n log maxPile)','O(1)',
`class Solution { public int minEatingSpeed(int[] piles,int h){int low=1,high=Arrays.stream(piles).max().getAsInt();while(low<high){int middle=low+(high-low)/2;long hours=0;for(int pile:piles)hours+=(pile+middle-1)/middle;if(hours<=h)high=middle;else low=middle+1;}return low;} }`,
`class Solution { fun minEatingSpeed(piles:IntArray,h:Int):Int{var low=1;var high=piles.maxOrNull()!!;while(low<high){val middle=low+(high-low)/2;var hours=0L;for(pile in piles)hours+=(pile+middle-1)/middle;if(hours<=h)high=middle else low=middle+1};return low} }`,
`class Solution { public: int minEatingSpeed(vector<int>& piles,int h){int low=1,high=*max_element(piles.begin(),piles.end());while(low<high){int middle=low+(high-low)/2;long long hours=0;for(int pile:piles)hours+=(pile+middle-1)/middle;if(hours<=h)high=middle;else low=middle+1;}return low;} };`)],tests:{schemaVersion:1,mode:'function',method:'minEatingSpeed',parameterTypes:['intArray','int'],returnType:'int',cases:[{name:'八小时速度四',args:[[3,6,7,11],8],expected:4},{name:'五小时速度三十',args:[[30,11,23,4,20],5],expected:30},{name:'六小时速度二十三',args:[[30,11,23,4,20],6],expected:23}]}},
{id:877,slug:'stone-game',title:'石子游戏',studyTags:['数组','动态规划','博弈'],summary:'两人轮流从偶数堆石子的两端取一堆，总石子数为奇数，双方最优时判断先手是否获胜。',insight:'区间 DP 计算当前玩家相对对手可取得的最大分差；取左或右后都要减去对手在剩余区间的最优分差，最终分差为正即先手胜。',pitfalls:['状态保存分差而非当前玩家总分','长度从二递增','题设保证平局不可能'],solutions:[s('interval-score-difference-dp','区间分差动态规划','比较取左右端后的净优势。',['dp[i]=piles[i] 表示单堆分差','length 从二到 n，left 递增、right=left+length-1','dp[left]=max(piles[left]-dp[left+1],piles[right]-dp[left])，原 dp[left] 在右式代表旧区间 [left,right-1]；最后 dp[0]>0'],'O(n²)','O(n)',
`class Solution { public boolean stoneGame(int[] piles){int[] dp=piles.clone();for(int length=2;length<=piles.length;length++)for(int left=0;left+length<=piles.length;left++){int right=left+length-1;dp[left]=Math.max(piles[left]-dp[left+1],piles[right]-dp[left]);}return dp[0]>0;} }`,
`class Solution { fun stoneGame(piles:IntArray):Boolean{val dp=piles.copyOf();for(length in 2..piles.size)for(left in 0..piles.size-length){val right=left+length-1;dp[left]=maxOf(piles[left]-dp[left+1],piles[right]-dp[left])};return dp[0]>0} }`,
`class Solution { public: bool stoneGame(vector<int>& piles){vector<int> dp=piles;for(int length=2;length<=(int)piles.size();++length)for(int left=0;left+length<=(int)piles.size();++left){int right=left+length-1;dp[left]=max(piles[left]-dp[left+1],piles[right]-dp[left]);}return dp[0]>0;} };`)],tests:{schemaVersion:1,mode:'function',method:'stoneGame',parameterTypes:['intArray'],returnType:'boolean',cases:[{name:'经典四堆',args:[[5,3,4,5]],expected:true},{name:'两堆取大者',args:[[1,100]],expected:true},{name:'另一组四堆',args:[[3,7,2,3]],expected:true}]}},
{id:878,slug:'nth-magical-number',title:'第 N 个神奇数字',studyTags:['数学','二分查找','数论'],summary:'能被 a 或 b 整除的正整数是神奇数字，返回第 n 个神奇数字对 1e9+7 取模。',insight:'不超过 x 的神奇数字数量由容斥为 x/a+x/b-x/lcm(a,b)，随 x 单调；二分第一个计数至少 n 的 x。',pitfalls:['最小公倍数计算要用长整型','二分答案本身先不取模','上界可用 n*min(a,b)'],solutions:[s('inclusion-exclusion-binary-search','容斥计数二分答案','在数值域查找第 n 个并集倍数。',['lcm=a/gcd(a,b)*b','low=1,high=n*min(a,b)','若 count(middle)>=n 则 high=middle，否则 low=middle+1；返回 low%MOD'],'O(log(n·min(a,b)))','O(1)',
`class Solution { public int nthMagicalNumber(int n,int a,int b){long lcm=(long)a/gcd(a,b)*b,low=1,high=(long)n*Math.min(a,b);while(low<high){long middle=low+(high-low)/2,count=middle/a+middle/b-middle/lcm;if(count>=n)high=middle;else low=middle+1;}return(int)(low%1000000007);}private int gcd(int a,int b){while(b!=0){int temporary=a%b;a=b;b=temporary;}return a;} }`,
`class Solution { fun nthMagicalNumber(n:Int,a:Int,b:Int):Int{val lcm=a.toLong()/gcd(a,b)*b;var low=1L;var high=n.toLong()*minOf(a,b);while(low<high){val middle=low+(high-low)/2;val count=middle/a+middle/b-middle/lcm;if(count>=n)high=middle else low=middle+1};return(low%1000000007).toInt()};private fun gcd(aInput:Int,bInput:Int):Int{var a=aInput;var b=bInput;while(b!=0){val temporary=a%b;a=b;b=temporary};return a} }`,
`class Solution { int gcdValue(int a,int b){while(b){int temporary=a%b;a=b;b=temporary;}return a;}public:int nthMagicalNumber(int n,int a,int b){long long lcm=(long long)a/gcdValue(a,b)*b,low=1,high=(long long)n*min(a,b);while(low<high){long long middle=low+(high-low)/2,count=middle/a+middle/b-middle/lcm;if(count>=n)high=middle;else low=middle+1;}return low%1000000007;} };`)],tests:{schemaVersion:1,mode:'function',method:'nthMagicalNumber',parameterTypes:['int','int','int'],returnType:'int',cases:[{name:'第一个神奇数',args:[1,2,3],expected:2},{name:'第四个二三倍数',args:[4,2,3],expected:6},{name:'第五个二四倍数',args:[5,2,4],expected:10}]}},
{id:879,slug:'profitable-schemes',title:'盈利计划',studyTags:['数组','动态规划','背包'],summary:'每项工作需要 group[i] 名成员并产生 profit[i] 利润，成员总数不超过 n，统计利润至少 minProfit 的工作子集数量。',insight:'零一背包状态按已用成员和利润记录；利润维度超过阈值后都等价，截断为 minProfit，倒序更新避免重复选择工作。',pitfalls:['空计划在 minProfit=0 时也算一种','成员维度必须倒序','计数每次对 1e9+7 取模'],solutions:[s('member-profit-capped-knapsack','成员与截断利润零一背包','把所有达到阈值的利润合并到同一状态。',['dp[0][0]=1','对每项工作 people,earn，members 从 n-people 倒序到零，profit 从 minProfit 倒序到零','nextProfit=min(minProfit,profit+earn)，dp[members+people][nextProfit]+=dp[members][profit]；最后累加 dp[members][minProfit]'],'O(jobs·n·minProfit)','O(n·minProfit)',
`class Solution { public int profitableSchemes(int n,int minProfit,int[] group,int[] profit){long mod=1000000007L;long[][] dp=new long[n+1][minProfit+1];dp[0][0]=1;for(int job=0;job<group.length;job++)for(int members=n-group[job];members>=0;members--)for(int earned=minProfit;earned>=0;earned--){int next=Math.min(minProfit,earned+profit[job]);dp[members+group[job]][next]=(dp[members+group[job]][next]+dp[members][earned])%mod;}long answer=0;for(int members=0;members<=n;members++)answer=(answer+dp[members][minProfit])%mod;return(int)answer;} }`,
`class Solution { fun profitableSchemes(n:Int,minProfit:Int,group:IntArray,profit:IntArray):Int{val mod=1000000007L;val dp=Array(n+1){LongArray(minProfit+1)};dp[0][0]=1;for(job in group.indices)for(members in n-group[job] downTo 0)for(earned in minProfit downTo 0){val next=minOf(minProfit,earned+profit[job]);dp[members+group[job]][next]=(dp[members+group[job]][next]+dp[members][earned])%mod};var answer=0L;for(members in 0..n)answer=(answer+dp[members][minProfit])%mod;return answer.toInt()} }`,
`class Solution { public: int profitableSchemes(int n,int minProfit,vector<int>& group,vector<int>& profit){const long long mod=1000000007;vector<vector<long long>> dp(n+1,vector<long long>(minProfit+1));dp[0][0]=1;for(int job=0;job<(int)group.size();++job)for(int members=n-group[job];members>=0;--members)for(int earned=minProfit;earned>=0;--earned){int next=min(minProfit,earned+profit[job]);dp[members+group[job]][next]=(dp[members+group[job]][next]+dp[members][earned])%mod;}long long answer=0;for(int members=0;members<=n;++members)answer=(answer+dp[members][minProfit])%mod;return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'profitableSchemes',parameterTypes:['int','int','intArray','intArray'],returnType:'int',cases:[{name:'两种盈利计划',args:[5,3,[2,2],[2,3]],expected:2},{name:'三项工作七种计划',args:[10,5,[2,3,5],[6,7,8]],expected:7},{name:'单项刚好达标',args:[1,1,[1],[1]],expected:1}]}}
]}
