const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})

export default {batchId:'batch-016',problems:[
{id:1163,slug:'last-substring-in-lexicographical-order',title:'按字典序排在最后的子串',studyTags:['字符串','双指针','最大后缀'],summary:'返回字符串所有非空子串中字典序最大的一个。',insight:'最大子串一定延伸到原串末尾，否则还能追加字符使其更大，因此问题等价于寻找最大后缀。用两个候选起点和公共比较偏移一次淘汰整段不可能起点。',pitfalls:['答案一定是后缀但不一定从最大字符最后一次出现处开始','相等字符要继续增大比较偏移','淘汰新区间后比较偏移必须归零'],solutions:[s('two-candidate-maximum-suffix','双候选最大后缀','线性比较两个后缀并批量跳过较小候选。',['令 i=0 为当前最佳起点、j=1 为挑战起点、k=0 为比较偏移','若 s[i+k]==s[j+k] 则 k++；若前者较小，令 i=max(i+k+1,j)、j=i+1；否则令 j=j+k+1','每次不等后令 k=0，直到 j+k 越界，返回 s.substring(i)'],'O(n)','O(1)',
`class Solution { public String lastSubstring(String s){int n=s.length(),i=0,j=1,k=0;while(j+k<n){char first=s.charAt(i+k),second=s.charAt(j+k);if(first==second)k++;else if(first<second){i=Math.max(i+k+1,j);j=i+1;k=0;}else{j=j+k+1;k=0;}}return s.substring(i);} }`,
`class Solution { fun lastSubstring(s:String):String{val n=s.length;var i=0;var j=1;var k=0;while(j+k<n){val first=s[i+k];val second=s[j+k];if(first==second)k++ else if(first<second){i=maxOf(i+k+1,j);j=i+1;k=0}else{j+=k+1;k=0}};return s.substring(i)} }`,
`class Solution { public: string lastSubstring(string s){int n=s.size(),i=0,j=1,k=0;while(j+k<n){if(s[i+k]==s[j+k])++k;else if(s[i+k]<s[j+k]){i=max(i+k+1,j);j=i+1;k=0;}else{j+=k+1;k=0;}}return s.substr(i);} };`)],tests:{schemaVersion:1,mode:'function',method:'lastSubstring',parameterTypes:['string'],returnType:'string',cases:[{name:'重复 ab 的最大后缀',args:['abab'],expected:'bab'},{name:'leetcode 最大后缀',args:['leetcode'],expected:'tcode'},{name:'全相同保留完整串',args:['aaaa'],expected:'aaaa'}]}},

{id:1169,slug:'invalid-transactions',title:'查询无效交易',studyTags:['数组','字符串','模拟','标记'],summary:'交易金额超过一千，或同名用户在六十分钟内于不同城市交易时无效，返回输入中所有无效交易字符串。',insight:'先解析每条交易并标记金额违规项，再逐对比较同名交易的时间和城市；满足跨城时间条件时两条都标为无效，最后按原输入顺序收集。',pitfalls:['跨城冲突会同时使两笔交易无效','时间差取绝对值且六十分钟边界包含','返回原始交易字符串而非解析后的字段'],solutions:[s('parsed-pairwise-invalid-marking','解析后两两标记','利用交易数上限直接检查所有可能冲突对。',['把每条字符串解析为 name、time、amount、city，amount>1000 时标记','枚举 i<j；若姓名相同、城市不同且时间差<=60，将 i、j 都标记','按原下标顺序把已标记的原字符串加入答案'],'O(n²)','O(n)',
`class Solution { static class Transaction{String raw,name,city;int time,amount;Transaction(String raw){this.raw=raw;String[] parts=raw.split(",");name=parts[0];time=Integer.parseInt(parts[1]);amount=Integer.parseInt(parts[2]);city=parts[3];}}public List<String> invalidTransactions(String[] input){int n=input.length;Transaction[] transactions=new Transaction[n];boolean[] invalid=new boolean[n];for(int i=0;i<n;i++){transactions[i]=new Transaction(input[i]);invalid[i]=transactions[i].amount>1000;}for(int i=0;i<n;i++)for(int j=i+1;j<n;j++){Transaction a=transactions[i],b=transactions[j];if(a.name.equals(b.name)&&!a.city.equals(b.city)&&Math.abs(a.time-b.time)<=60)invalid[i]=invalid[j]=true;}List<String> answer=new ArrayList<>();for(int i=0;i<n;i++)if(invalid[i])answer.add(input[i]);return answer;} }`,
`class Solution { private data class Transaction(val raw:String,val name:String,val time:Int,val amount:Int,val city:String);fun invalidTransactions(input:Array<String>):List<String>{val transactions=input.map{raw->val parts=raw.split(',');Transaction(raw,parts[0],parts[1].toInt(),parts[2].toInt(),parts[3])};val invalid=BooleanArray(input.size){transactions[it].amount>1000};for(i in transactions.indices)for(j in i+1 until transactions.size){val a=transactions[i];val b=transactions[j];if(a.name==b.name&&a.city!=b.city&&kotlin.math.abs(a.time-b.time)<=60){invalid[i]=true;invalid[j]=true}};return input.indices.filter{invalid[it]}.map{input[it]}} }`,
`class Solution { struct Transaction{string raw,name,city;int time,amount;};public:vector<string> invalidTransactions(vector<string>& input){vector<Transaction> transactions;vector<bool> invalid(input.size());for(int i=0;i<(int)input.size();++i){stringstream stream(input[i]);string name,time,amount,city;getline(stream,name,',');getline(stream,time,',');getline(stream,amount,',');getline(stream,city,',');transactions.push_back({input[i],name,city,stoi(time),stoi(amount)});invalid[i]=transactions.back().amount>1000;}for(int i=0;i<(int)input.size();++i)for(int j=i+1;j<(int)input.size();++j){auto& a=transactions[i];auto& b=transactions[j];if(a.name==b.name&&a.city!=b.city&&abs(a.time-b.time)<=60)invalid[i]=invalid[j]=true;}vector<string> answer;for(int i=0;i<(int)input.size();++i)if(invalid[i])answer.push_back(input[i]);return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'invalidTransactions',parameterTypes:['stringArray'],returnType:'stringList',cases:[{name:'同名跨城两笔均无效',args:[['alice,20,800,mtv','alice,50,100,beijing']],expected:['alice,20,800,mtv','alice,50,100,beijing']},{name:'仅金额超限',args:[['alice,20,800,mtv','alice,50,1200,mtv']],expected:['alice,50,1200,mtv']},{name:'跨城与金额规则并存',args:[['bob,10,100,mtv','bob,50,200,beijing','alex,20,1200,mtv']],expected:['bob,10,100,mtv','bob,50,200,beijing','alex,20,1200,mtv']}]}},

{id:1170,slug:'compare-strings-by-frequency-of-the-smallest-character',title:'比较字符串最小字母出现频次',studyTags:['数组','字符串','二分查找','排序'],summary:'定义 f(s) 为字符串中字典序最小字符的出现次数；对每个 query，统计 words 中 f(word) 严格大于 f(query) 的数量。',insight:'先计算并排序所有单词的频次。每个查询只需用 upper_bound 找到第一个严格大于其频次的位置，后缀长度就是答案。',pitfalls:['比较条件是严格大于','最小字符可能重复多次','二分应找 upper_bound 而不是 lower_bound'],solutions:[s('sorted-frequency-upper-bound','频次排序与上界二分','把字符串比较转换成整数频次数组上的上界查询。',['函数 frequency 扫描字符串，维护最小字符及其次数','计算 words 的所有频次并升序排序','对每个 query 计算 value，二分第一个 wordFrequency>value 的位置，答案为 words.length-position'],'O(W log W+字符总数+Q log W)','O(W)',
`class Solution { public int[] numSmallerByFrequency(String[] queries,String[] words){int[] frequencies=new int[words.length];for(int i=0;i<words.length;i++)frequencies[i]=frequency(words[i]);Arrays.sort(frequencies);int[] answer=new int[queries.length];for(int i=0;i<queries.length;i++){int value=frequency(queries[i]),left=0,right=frequencies.length;while(left<right){int middle=(left+right)/2;if(frequencies[middle]<=value)left=middle+1;else right=middle;}answer[i]=frequencies.length-left;}return answer;}private int frequency(String text){char minimum='z';int count=0;for(char ch:text.toCharArray())if(ch<minimum){minimum=ch;count=1;}else if(ch==minimum)count++;return count;} }`,
`class Solution { fun numSmallerByFrequency(queries:Array<String>,words:Array<String>):IntArray{val frequencies=words.map{frequency(it)}.sorted();return IntArray(queries.size){index->val value=frequency(queries[index]);var left=0;var right=frequencies.size;while(left<right){val middle=(left+right)/2;if(frequencies[middle]<=value)left=middle+1 else right=middle};frequencies.size-left}};private fun frequency(text:String):Int{var minimum='z';var count=0;for(ch in text)if(ch<minimum){minimum=ch;count=1}else if(ch==minimum)count++;return count} }`,
`class Solution { int frequency(const string& text){char minimum='z';int count=0;for(char ch:text)if(ch<minimum){minimum=ch;count=1;}else if(ch==minimum)++count;return count;}public:vector<int> numSmallerByFrequency(vector<string>& queries,vector<string>& words){vector<int> frequencies;for(string& word:words)frequencies.push_back(frequency(word));sort(frequencies.begin(),frequencies.end());vector<int> answer;for(string& query:queries)answer.push_back(frequencies.end()-upper_bound(frequencies.begin(),frequencies.end(),frequency(query)));return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'numSmallerByFrequency',parameterTypes:['stringArray','stringArray'],returnType:'intArray',cases:[{name:'单查询单单词',args:[['cbd'],['zaaaz']],expected:[1]},{name:'两个查询不同上界',args:[['bbb','cc'],['a','aa','aaa','aaaa']],expected:[1,2]},{name:'相等频次不计入',args:[['a'],['a','b']],expected:[0]}]}},

{id:1171,slug:'remove-zero-sum-consecutive-nodes-from-linked-list',title:'从链表中删去总和值为零的连续节点',studyTags:['链表','哈希表','前缀和'],summary:'反复删除链表中和为零的连续节点，返回不存在零和连续段的最终链表。',insight:'若两个位置的前缀和相同，它们之间节点和为零。第一遍把每个前缀和映射到最后出现节点；第二遍直接把当前节点 next 接到同前缀最后节点之后，一次跳过所有可删除区间。',pitfalls:['虚拟头节点的前缀和为零','映射必须保留最后一次出现位置','第二遍沿修改后的 next 前进即可'],solutions:[s('last-prefix-node-relink','末次前缀节点重连','用相同前缀和的最远位置批量删除零和区间。',['创建值为零的 dummy 指向 head；第一遍从 dummy 开始累计 prefix，并令 last[prefix]=当前节点','第二遍重新累计 prefix，把 node.next 改为 last[prefix].next','沿重连后的链表继续，最后返回 dummy.next'],'O(n)','O(n)',
`class Solution { public ListNode removeZeroSumSublists(ListNode head){ListNode dummy=new ListNode(0,head);Map<Integer,ListNode> last=new HashMap<>();int prefix=0;for(ListNode node=dummy;node!=null;node=node.next){prefix+=node.val;last.put(prefix,node);}prefix=0;for(ListNode node=dummy;node!=null;node=node.next){prefix+=node.val;node.next=last.get(prefix).next;}return dummy.next;} }`,
`class Solution { fun removeZeroSumSublists(head:ListNode?):ListNode?{val dummy=ListNode(0);dummy.next=head;val last=mutableMapOf<Int,ListNode>();var prefix=0;var node:ListNode?=dummy;while(node!=null){prefix+=node.\`val\`;last[prefix]=node;node=node.next};prefix=0;node=dummy;while(node!=null){prefix+=node.\`val\`;node.next=last[prefix]!!.next;node=node.next};return dummy.next} }`,
`class Solution { public: ListNode* removeZeroSumSublists(ListNode* head){ListNode dummy(0,head);unordered_map<int,ListNode*> last;int prefix=0;for(ListNode* node=&dummy;node;node=node->next){prefix+=node->val;last[prefix]=node;}prefix=0;for(ListNode* node=&dummy;node;node=node->next){prefix+=node->val;node->next=last[prefix]->next;}return dummy.next;} };`)],tests:{schemaVersion:1,mode:'function',method:'removeZeroSumSublists',parameterTypes:['listNode'],returnType:'listNode',cases:[{name:'删除前三项零和段',args:[[1,2,-3,3,1]],expected:[3,1]},{name:'删除中间三与负三',args:[[1,2,3,-3,4]],expected:[1,2,4]},{name:'级联删除尾段',args:[[1,2,3,-3,-2]],expected:[1]}]}},

{id:1172,slug:'dinner-plate-stacks',title:'餐盘栈',studyTags:['设计','栈','有序集合'],summary:'维护容量固定的一排栈；push 总放入最左非满栈，pop 从最右非空栈弹出，popAtStack 从指定栈弹出。',insight:'用有序集合维护所有未满栈下标，push 取最小下标；弹出后把该栈加入未满集合，并及时裁掉尾部空栈，使普通 pop 始终访问最右非空栈。',pitfalls:['中间空洞不能直接删除栈，否则下标会变化','尾部空栈可连续裁剪','无效下标或空指定栈返回负一'],solutions:[s('ordered-nonfull-index-set','未满下标有序集合','用最小可写下标和紧凑尾部同时满足两种弹出规则。',['stacks 保存各栈，available 保存未满栈下标','push：available 空则新建栈，否则取最小下标；压入后若满则移出 available，否则保留','popAtStack：校验后弹出并加入 available，再删除所有尾部空栈及其下标；pop 调用最后一个栈的 popAtStack'],'每次 O(log n)','O(元素数+栈数)',
`class DinnerPlates { private final int capacity;private final List<ArrayDeque<Integer>> stacks=new ArrayList<>();private final TreeSet<Integer> available=new TreeSet<>();public DinnerPlates(int capacity){this.capacity=capacity;}public void push(int val){int index;if(available.isEmpty()){index=stacks.size();stacks.add(new ArrayDeque<>());}else index=available.first();ArrayDeque<Integer> stack=stacks.get(index);stack.push(val);if(stack.size()==capacity)available.remove(index);else available.add(index);}public int pop(){return stacks.isEmpty()?-1:popAtStack(stacks.size()-1);}public int popAtStack(int index){if(index<0||index>=stacks.size()||stacks.get(index).isEmpty())return -1;int value=stacks.get(index).pop();available.add(index);while(!stacks.isEmpty()&&stacks.get(stacks.size()-1).isEmpty()){int last=stacks.size()-1;stacks.remove(last);available.remove(last);}return value;} }`,
`class DinnerPlates(private val capacity:Int) { private val stacks=mutableListOf<java.util.ArrayDeque<Int>>();private val available=java.util.TreeSet<Int>();fun push(\`val\`:Int){val index=if(available.isEmpty()){stacks.add(java.util.ArrayDeque());stacks.lastIndex}else available.first();val stack=stacks[index];stack.push(\`val\`);if(stack.size==capacity)available.remove(index) else available.add(index)};fun pop():Int=if(stacks.isEmpty())-1 else popAtStack(stacks.lastIndex);fun popAtStack(index:Int):Int{if(index !in stacks.indices||stacks[index].isEmpty())return -1;val value=stacks[index].pop();available.add(index);while(stacks.isNotEmpty()&&stacks.last().isEmpty()){val last=stacks.lastIndex;stacks.removeAt(last);available.remove(last)};return value} }`,
`class DinnerPlates { int capacity;vector<vector<int>> stacks;set<int> available;public:DinnerPlates(int capacity):capacity(capacity){}void push(int val){int index;if(available.empty()){index=stacks.size();stacks.push_back({});}else index=*available.begin();stacks[index].push_back(val);if((int)stacks[index].size()==capacity)available.erase(index);else available.insert(index);}int pop(){return stacks.empty()?-1:popAtStack(stacks.size()-1);}int popAtStack(int index){if(index<0||index>=(int)stacks.size()||stacks[index].empty())return -1;int value=stacks[index].back();stacks[index].pop_back();available.insert(index);while(!stacks.empty()&&stacks.back().empty()){int last=stacks.size()-1;stacks.pop_back();available.erase(last);}return value;} };`)],tests:{schemaVersion:1,mode:'design',className:'DinnerPlates',constructorTypes:['int'],cases:[{name:'经典空洞填充与右侧弹出',constructorArgs:[2],calls:[{method:'push',parameterTypes:['int'],args:[1]},{method:'push',parameterTypes:['int'],args:[2]},{method:'push',parameterTypes:['int'],args:[3]},{method:'push',parameterTypes:['int'],args:[4]},{method:'push',parameterTypes:['int'],args:[5]},{method:'popAtStack',parameterTypes:['int'],args:[0],returnType:'int',expected:2},{method:'push',parameterTypes:['int'],args:[20]},{method:'push',parameterTypes:['int'],args:[21]},{method:'popAtStack',parameterTypes:['int'],args:[0],returnType:'int',expected:20},{method:'popAtStack',parameterTypes:['int'],args:[2],returnType:'int',expected:21},{method:'pop',parameterTypes:[],args:[],returnType:'int',expected:5},{method:'pop',parameterTypes:[],args:[],returnType:'int',expected:4},{method:'pop',parameterTypes:[],args:[],returnType:'int',expected:3},{method:'pop',parameterTypes:[],args:[],returnType:'int',expected:1},{method:'pop',parameterTypes:[],args:[],returnType:'int',expected:-1}]},{name:'容量一优先填左洞',constructorArgs:[1],calls:[{method:'push',parameterTypes:['int'],args:[1]},{method:'push',parameterTypes:['int'],args:[2]},{method:'popAtStack',parameterTypes:['int'],args:[0],returnType:'int',expected:1},{method:'push',parameterTypes:['int'],args:[3]},{method:'pop',parameterTypes:[],args:[],returnType:'int',expected:2},{method:'pop',parameterTypes:[],args:[],returnType:'int',expected:3}]},{name:'空栈与无效下标',constructorArgs:[2],calls:[{method:'pop',parameterTypes:[],args:[],returnType:'int',expected:-1},{method:'popAtStack',parameterTypes:['int'],args:[3],returnType:'int',expected:-1}]}]}}
]}
