const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-024',problems:[
{id:1697,slug:'checking-existence-of-edge-length-limited-paths',title:'检查边长度限制的路径是否存在',studyTags:['数组','并查集','图论','排序'],summary:'对每组 [p,q,limit]，判断图中是否存在从 p 到 q 且每条边权都严格小于 limit 的路径。',insight:'把边按权重、查询按 limit 排序。处理某个查询前，把所有权重小于其 limit 的边加入并查集，此时连通性正好对应合法路径。',pitfalls:['边权必须严格小于 limit','答案要按查询原顺序返回','同一并查集可随查询阈值递增复用'],solutions:[s('offline-sorted-dsu','离线排序并查集','按阈值逐步开放边并回答连通查询。',['edgeList 按权重升序，查询附原下标并按 limit 升序','维护 edgeIndex；处理查询时合并所有 weight<limit 的边','比较 p、q 根节点并写回原下标'],'O((E+Q) log(E+Q))','O(n+Q)',
`class Solution { private static class DSU{int[] parent,rank;DSU(int n){parent=new int[n];rank=new int[n];for(int i=0;i<n;i++)parent[i]=i;}int find(int x){return parent[x]==x?x:(parent[x]=find(parent[x]));}void union(int a,int b){a=find(a);b=find(b);if(a==b)return;if(rank[a]<rank[b]){int t=a;a=b;b=t;}parent[b]=a;if(rank[a]==rank[b])rank[a]++;}}public List<Boolean> distanceLimitedPathsExist(int n,int[][] edgeList,int[][] queries){Arrays.sort(edgeList,Comparator.comparingInt(edge->edge[2]));Integer[] order=new Integer[queries.length];for(int i=0;i<order.length;i++)order[i]=i;Arrays.sort(order,Comparator.comparingInt(i->queries[i][2]));Boolean[] answer=new Boolean[queries.length];DSU dsu=new DSU(n);int edgeIndex=0;for(int queryIndex:order){int limit=queries[queryIndex][2];while(edgeIndex<edgeList.length&&edgeList[edgeIndex][2]<limit){dsu.union(edgeList[edgeIndex][0],edgeList[edgeIndex][1]);edgeIndex++;}answer[queryIndex]=dsu.find(queries[queryIndex][0])==dsu.find(queries[queryIndex][1]);}return Arrays.asList(answer);} }`,
`class Solution { private class DSU(n:Int){val parent=IntArray(n){it};val rank=IntArray(n);fun find(value:Int):Int{if(parent[value]!=value)parent[value]=find(parent[value]);return parent[value]};fun union(first:Int,second:Int){var a=find(first);var b=find(second);if(a==b)return;if(rank[a]<rank[b]){val temporary=a;a=b;b=temporary};parent[b]=a;if(rank[a]==rank[b])rank[a]++}};fun distanceLimitedPathsExist(n:Int,edgeList:Array<IntArray>,queries:Array<IntArray>):List<Boolean>{edgeList.sortBy{it[2]};val order=queries.indices.sortedBy{queries[it][2]};val answer=BooleanArray(queries.size);val dsu=DSU(n);var edgeIndex=0;for(queryIndex in order){val limit=queries[queryIndex][2];while(edgeIndex<edgeList.size&&edgeList[edgeIndex][2]<limit){dsu.union(edgeList[edgeIndex][0],edgeList[edgeIndex][1]);edgeIndex++};answer[queryIndex]=dsu.find(queries[queryIndex][0])==dsu.find(queries[queryIndex][1])};return answer.toList()} }`,
`class Solution { struct DSU{vector<int> parent,rank;DSU(int n):parent(n),rank(n){iota(parent.begin(),parent.end(),0);}int find(int x){return parent[x]==x?x:parent[x]=find(parent[x]);}void unite(int a,int b){a=find(a);b=find(b);if(a==b)return;if(rank[a]<rank[b])swap(a,b);parent[b]=a;if(rank[a]==rank[b])++rank[a];}};public:vector<bool> distanceLimitedPathsExist(int n,vector<vector<int>>& edgeList,vector<vector<int>>& queries){sort(edgeList.begin(),edgeList.end(),[](auto& a,auto& b){return a[2]<b[2];});vector<int> order(queries.size());iota(order.begin(),order.end(),0);sort(order.begin(),order.end(),[&](int a,int b){return queries[a][2]<queries[b][2];});vector<bool> answer(queries.size());DSU dsu(n);int edgeIndex=0;for(int queryIndex:order){int limit=queries[queryIndex][2];while(edgeIndex<(int)edgeList.size()&&edgeList[edgeIndex][2]<limit){dsu.unite(edgeList[edgeIndex][0],edgeList[edgeIndex][1]);++edgeIndex;}answer[queryIndex]=dsu.find(queries[queryIndex][0])==dsu.find(queries[queryIndex][1]);}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'distanceLimitedPathsExist',parameterTypes:['int','intMatrix','intMatrix'],returnType:'booleanList',cases:[{name:'阈值严格限制两组查询一真一假',args:[3,[[0,1,2],[1,2,4],[2,0,8],[1,0,16]],[[0,1,2],[0,2,5]]],expected:[false,true]},{name:'四节点不同阈值查询',args:[5,[[0,1,10],[1,2,5],[2,3,9],[3,4,13]],[[0,4,14],[1,4,13]]],expected:[true,false]},{name:'同节点无需边即可连通',args:[2,[[0,1,5]],[[0,0,1]]],expected:[true]}]}},
{id:1700,slug:'number-of-students-unable-to-eat-lunch',title:'无法吃午餐的学生数量',studyTags:['数组','队列','模拟','计数'],summary:'学生按队列等待，三明治按栈顶顺序；喜欢顶层的学生拿走，否则移到队尾，求最终无法进餐人数。',insight:'学生轮转顺序无需真实模拟，只要还有喜欢当前三明治类型的学生，就总能轮到他。统计两种偏好，遇到某类库存为零时剩余三明治数就是答案。',pitfalls:['三明治顺序不能改变','学生偏好只有零和一','一旦当前三明治无人喜欢，之后全部停止'],solutions:[s('preference-counts','偏好计数','用两类学生数量替代循环队列。',['count[0],count[1] 统计学生偏好','按顺序遍历 sandwiches','若 count[type]==0 返回剩余数量，否则 count[type]--；全部取完返回零'],'O(n)','O(1)',
`class Solution { public int countStudents(int[] students,int[] sandwiches){int[] count=new int[2];for(int student:students)count[student]++;for(int i=0;i<sandwiches.length;i++){int type=sandwiches[i];if(count[type]==0)return sandwiches.length-i;count[type]--;}return 0;} }`,
`class Solution { fun countStudents(students:IntArray,sandwiches:IntArray):Int{val count=IntArray(2);for(student in students)count[student]++;for(i in sandwiches.indices){val type=sandwiches[i];if(count[type]==0)return sandwiches.size-i;count[type]--};return 0} }`,
`class Solution { public: int countStudents(vector<int>& students,vector<int>& sandwiches){int count[2]={};for(int student:students)++count[student];for(int i=0;i<(int)sandwiches.size();++i){int type=sandwiches[i];if(!count[type])return sandwiches.size()-i;--count[type];}return 0;} };`)],tests:{schemaVersion:1,mode:'function',method:'countStudents',parameterTypes:['intArray','intArray'],returnType:'int',cases:[{name:'所有学生都能取到午餐',args:[[1,1,0,0],[0,1,0,1]],expected:0},{name:'三名学生最终无法进餐',args:[[1,1,1,0,0,1],[1,0,0,0,1,1]],expected:3},{name:'单学生偏好不匹配',args:[[0],[1]],expected:1}]}},
{id:1701,slug:'average-waiting-time',title:'平均等待时间',studyTags:['数组','模拟'],summary:'顾客按到达时间排好序，单厨师依次服务；返回从每位顾客到达到完成的平均等待时间。',insight:'厨师开始服务时刻是当前空闲时刻与顾客到达时刻的较大值，完成时刻再加烹饪时间；完成减到达即等待时长。',pitfalls:['等待时间包含烹饪时间','厨师空闲时需直接跳到下一到达时刻','总等待时长使用 long'],solutions:[s('finish-time-simulation','完成时刻模拟','逐客维护厨师完成上一单的时刻。',['finish=totalWait=0','对 customer：finish=max(finish,arrival)+duration','totalWait+=finish-arrival，最后除以顾客数'],'O(n)','O(1)',
`class Solution { public double averageWaitingTime(int[][] customers){long finish=0,totalWait=0;for(int[] customer:customers){finish=Math.max(finish,customer[0])+customer[1];totalWait+=finish-customer[0];}return (double)totalWait/customers.length;} }`,
`class Solution { fun averageWaitingTime(customers:Array<IntArray>):Double{var finish=0L;var totalWait=0L;for(customer in customers){finish=maxOf(finish,customer[0].toLong())+customer[1];totalWait+=finish-customer[0]};return totalWait.toDouble()/customers.size} }`,
`class Solution { public: double averageWaitingTime(vector<vector<int>>& customers){long long finish=0,totalWait=0;for(auto& customer:customers){finish=max(finish,1LL*customer[0])+customer[1];totalWait+=finish-customer[0];}return (double)totalWait/customers.size();} };`)],tests:{schemaVersion:1,mode:'function',method:'averageWaitingTime',parameterTypes:['intMatrix'],returnType:'double',cases:[{name:'连续到达平均等待五',args:[[[1,2],[2,5],[4,3]]],expected:5.0},{name:'厨师多次空闲平均三点二五',args:[[[5,2],[5,4],[10,3],[20,1]]],expected:3.25},{name:'单顾客等待等于烹饪时间',args:[[[10,7]]],expected:7.0}]}},
{id:1702,slug:'maximum-binary-string-after-change',title:'修改后的最大二进制字符串',studyTags:['字符串','贪心'],summary:'可把 00 变为 10，或把 10 变为 01，反复操作后求字典序最大的二进制字符串。',insight:'若存在零，利用操作可把从第一个零开始的所有零合并成唯一一个零；这个零最终位于 firstZero+zeroCount-1，其余位置均可变成一。',pitfalls:['原串全一时保持不变','最终至多保留一个零','零的位置由第一个零与零总数共同确定'],solutions:[s('single-zero-position','唯一零位置构造','直接刻画所有操作能达到的最大规范形。',['寻找 firstZero 并统计 zeroCount','若没有零返回原串','answer 全填一，在 firstZero+zeroCount-1 处放零'],'O(n)','O(n)',
`class Solution { public String maximumBinaryString(String binary){int first=binary.indexOf('0');if(first<0)return binary;int zeros=0;for(char bit:binary.toCharArray())if(bit=='0')zeros++;char[] answer=new char[binary.length()];Arrays.fill(answer,'1');answer[first+zeros-1]='0';return new String(answer);} }`,
`class Solution { fun maximumBinaryString(binary:String):String{val first=binary.indexOf('0');if(first<0)return binary;val zeros=binary.count{it=='0'};val answer=CharArray(binary.length){'1'};answer[first+zeros-1]='0';return String(answer)} }`,
`class Solution { public: string maximumBinaryString(string binary){int first=binary.find('0');if(first==(int)string::npos)return binary;int zeros=count(binary.begin(),binary.end(),'0');string answer(binary.size(),'1');answer[first+zeros-1]='0';return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'maximumBinaryString',parameterTypes:['string'],returnType:'string',cases:[{name:'多个零最终只留一个零',args:['000110'],expected:'111011'},{name:'零一已是最大可达形态',args:['01'],expected:'01'},{name:'全一保持不变',args:['111'],expected:'111'}]}},
{id:1703,slug:'minimum-adjacent-swaps-for-k-consecutive-ones',title:'得到连续 K 个 1 的最少相邻交换次数',studyTags:['数组','贪心','滑动窗口','前缀和'],summary:'通过相邻交换让数组中至少有 k 个一连续，求最少交换次数。',insight:'记录一的位置 position[i]，减去其序号 i 后，目标连续位置的固定间隔被消去。任取 k 个连续的一，其最小移动代价是这些调整位置到中位数的绝对差和。',pitfalls:['选择的一在原序列中必是连续的一段','减去序号可免去奇偶 k 的额外间隔修正','绝对差和用 long 计算'],solutions:[s('adjusted-one-positions-median','调整后位置中位数窗口','把连续目标转换为所有调整坐标相等。',['收集 adjusted[j]=onePosition-j，并建前缀和','枚举长度 k 的 adjusted 窗口，mid=(left+right)/2','用前缀和计算左右到 adjusted[mid] 的距离和，取最小'],'O(n)','O(number of ones)',
`class Solution { public int minMoves(int[] nums,int k){List<Long> adjusted=new ArrayList<>();for(int i=0;i<nums.length;i++)if(nums[i]==1)adjusted.add((long)i-adjusted.size());long[] prefix=new long[adjusted.size()+1];for(int i=0;i<adjusted.size();i++)prefix[i+1]=prefix[i]+adjusted.get(i);long answer=Long.MAX_VALUE;for(int left=0;left+k<=adjusted.size();left++){int right=left+k-1,mid=(left+right)/2;long median=adjusted.get(mid);long cost=median*(mid-left)-(prefix[mid]-prefix[left])+(prefix[right+1]-prefix[mid+1])-median*(right-mid);answer=Math.min(answer,cost);}return (int)answer;} }`,
`class Solution { fun minMoves(nums:IntArray,k:Int):Int{val adjusted=mutableListOf<Long>();for(i in nums.indices)if(nums[i]==1)adjusted.add(i.toLong()-adjusted.size);val prefix=LongArray(adjusted.size+1);for(i in adjusted.indices)prefix[i+1]=prefix[i]+adjusted[i];var answer=Long.MAX_VALUE;for(left in 0..adjusted.size-k){val right=left+k-1;val mid=(left+right)/2;val median=adjusted[mid];val cost=median*(mid-left)-(prefix[mid]-prefix[left])+(prefix[right+1]-prefix[mid+1])-median*(right-mid);answer=minOf(answer,cost)};return answer.toInt()} }`,
`class Solution { public: int minMoves(vector<int>& nums,int k){vector<long long> adjusted;for(int i=0;i<(int)nums.size();++i)if(nums[i])adjusted.push_back(i-adjusted.size());vector<long long> prefix(adjusted.size()+1);for(int i=0;i<(int)adjusted.size();++i)prefix[i+1]=prefix[i]+adjusted[i];long long answer=LLONG_MAX;for(int left=0;left+k<=(int)adjusted.size();++left){int right=left+k-1,mid=(left+right)/2;long long median=adjusted[mid];long long cost=median*(mid-left)-(prefix[mid]-prefix[left])+(prefix[right+1]-prefix[mid+1])-median*(right-mid);answer=min(answer,cost);}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'minMoves',parameterTypes:['intArray','int'],returnType:'int',cases:[{name:'选择两个一只需一次交换',args:[[1,0,0,1,0,1],2],expected:1},{name:'三个一聚拢需要五次交换',args:[[1,0,0,0,0,0,1,1],3],expected:5},{name:'已有两个连续一无需交换',args:[[1,1,0,1],2],expected:0}]}}
]}
