const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-022',problems:[
{id:1551,slug:'minimum-operations-to-make-array-equal',title:'使数组中所有元素相等的最小操作数',studyTags:['数学'],summary:'数组 arr[i]=2i+1，每次一个元素加一、另一个减一，求使所有 n 个元素相等的最少操作。',insight:'最终平均值为 n；操作数等于所有低于 n 的元素提升到 n 所需增量，化简为 floor(n²/4)。',pitfalls:['一次操作同时守恒总和','奇偶 n 都由同一整数公式覆盖','使用整数除法'],solutions:[s('closed-form-balance','平衡增量闭式公式','由对称等差数列到平均值的距离和推导。',['目标值为 n','低半部分总缺口等于高半部分总盈余','返回 n*n/4 的整数下取整'],'O(1)','O(1)',
`class Solution { public int minOperations(int n){return n*n/4;} }`,
`class Solution { fun minOperations(n:Int):Int=n*n/4 }`,
`class Solution { public: int minOperations(int n){return n*n/4;} };`)],tests:{schemaVersion:1,mode:'function',method:'minOperations',parameterTypes:['int'],returnType:'int',cases:[{name:'三个元素需两次',args:[3],expected:2},{name:'六个元素需九次',args:[6],expected:9},{name:'单元素无需操作',args:[1],expected:0}]}},
{id:1552,slug:'magnetic-force-between-two-balls',title:'两球之间的磁力',studyTags:['数组','二分查找','排序'],summary:'把 m 个球放入不同篮子位置，最大化任意两球间的最小距离。',insight:'给定距离 d 能否放下 m 球具有单调性。排序后贪心把每个球放在距上一个已放球至少 d 的最早位置，最能给后续留空间。',pitfalls:['位置需先排序','二分寻找最大的可行距离','第一只球固定放最左不损失最优性'],solutions:[s('binary-search-greedy-spacing','间距二分与贪心放置','用线性可行性检查最大最小距离。',['排序 position','feasible(distance)：从首位置开始，遇差>=distance 就放球，计数达到 m 成功','二分 left=1,right=range，mid 向上取整；可行则 left=mid，否则 right=mid-1'],'O(n log range)','O(log n)',
`class Solution { private boolean feasible(int[] position,int m,int distance){int count=1,last=position[0];for(int value:position)if(value-last>=distance){last=value;if(++count>=m)return true;}return false;}public int maxDistance(int[] position,int m){Arrays.sort(position);int left=1,right=position[position.length-1]-position[0];while(left<right){int middle=left+(right-left+1)/2;if(feasible(position,m,middle))left=middle;else right=middle-1;}return left;} }`,
`class Solution { private fun feasible(position:IntArray,m:Int,distance:Int):Boolean{var count=1;var last=position[0];for(value in position)if(value-last>=distance){last=value;count++;if(count>=m)return true};return false};fun maxDistance(position:IntArray,m:Int):Int{position.sort();var left=1;var right=position.last()-position.first();while(left<right){val middle=left+(right-left+1)/2;if(feasible(position,m,middle))left=middle else right=middle-1};return left} }`,
`class Solution { bool feasible(vector<int>& position,int m,int distance){int count=1,last=position[0];for(int value:position)if(value-last>=distance){last=value;if(++count>=m)return true;}return false;}public:int maxDistance(vector<int>& position,int m){sort(position.begin(),position.end());int left=1,right=position.back()-position.front();while(left<right){int middle=left+(right-left+1)/2;if(feasible(position,m,middle))left=middle;else right=middle-1;}return left;} };`)],tests:{schemaVersion:1,mode:'function',method:'maxDistance',parameterTypes:['intArray','int'],returnType:'int',cases:[{name:'五篮三球最大间距三',args:[[1,2,3,4,7],3],expected:3},{name:'两个球放在两端',args:[[5,4,3,2,1,1000000000],2],expected:999999999},{name:'三个位置全用最小间距九',args:[[1,10,20],3],expected:9}]}},
{id:1553,slug:'minimum-number-of-days-to-eat-n-oranges',title:'吃掉 N 个橘子的最少天数',studyTags:['动态规划','记忆化搜索'],summary:'每天可吃一个橘子，或在数量被二/三整除时分别吃掉一半/三分之二，求吃完最少天数。',insight:'选择除二前需先用 n%2 天吃到二的倍数，再用一天执行除法；除三同理。递归只进入 n/2、n/3，状态数量对数级。',pitfalls:['除法操作本身也耗一天','n<=1 的答案就是 n','两条路径取较小值'],solutions:[s('division-remainder-memo','除法余数记忆化','把逐个吃的天数压缩为到最近可整除数量的余数。',['memo 含 0->0,1->1','days(n)=1+min(n%2+days(n/2),n%3+days(n/3))','记忆化并返回 days(n)'],'O(log² n)','O(log n)',
`class Solution { private final Map<Integer,Integer> memo=new HashMap<>();public int minDays(int n){if(n<=1)return n;if(memo.containsKey(n))return memo.get(n);int answer=1+Math.min(n%2+minDays(n/2),n%3+minDays(n/3));memo.put(n,answer);return answer;} }`,
`class Solution { private val memo=mutableMapOf<Int,Int>();fun minDays(n:Int):Int{if(n<=1)return n;return memo.getOrPut(n){1+minOf(n%2+minDays(n/2),n%3+minDays(n/3))}} }`,
`class Solution { unordered_map<int,int> memo;public:int minDays(int n){if(n<=1)return n;if(memo.count(n))return memo[n];return memo[n]=1+min(n%2+minDays(n/2),n%3+minDays(n/3));} };`)],tests:{schemaVersion:1,mode:'function',method:'minDays',parameterTypes:['int'],returnType:'int',cases:[{name:'十个橘子四天吃完',args:[10],expected:4},{name:'六个橘子三天吃完',args:[6],expected:3},{name:'一个橘子一天吃完',args:[1],expected:1}]}},
{id:1556,slug:'thousand-separator',title:'千位分隔数',studyTags:['字符串'],summary:'把非负整数 n 的十进制表示每三位从右向左插入点号分隔。',insight:'从右向左读取数字，每加入三位且前面仍有数字时插入点号，最后反转。',pitfalls:['不足四位不插点','零返回 0','分组从最低位开始'],solutions:[s('reverse-grouping','逆向三位分组','从个位向高位构造反向结果再翻转。',['text=toString(n),builder 空','i 从末尾向零，每累计三位且 i>0 时追加点','反转 builder 返回'],'O(log n)','O(log n)',
`class Solution { public String thousandSeparator(int n){String text=String.valueOf(n);StringBuilder reversed=new StringBuilder();int count=0;for(int i=text.length()-1;i>=0;i--){reversed.append(text.charAt(i));if(++count%3==0&&i>0)reversed.append('.');}return reversed.reverse().toString();} }`,
`class Solution { fun thousandSeparator(n:Int):String{val text=n.toString();val reversed=StringBuilder();var count=0;for(i in text.lastIndex downTo 0){reversed.append(text[i]);count++;if(count%3==0&&i>0)reversed.append('.')};return reversed.reverse().toString()} }`,
`class Solution { public: string thousandSeparator(int n){string text=to_string(n),reversed;int count=0;for(int i=text.size()-1;i>=0;--i){reversed+=text[i];if(++count%3==0&&i>0)reversed+='.';}reverse(reversed.begin(),reversed.end());return reversed;} };`)],tests:{schemaVersion:1,mode:'function',method:'thousandSeparator',parameterTypes:['int'],returnType:'string',cases:[{name:'三位数不分隔',args:[987],expected:'987'},{name:'四位数插入一个点',args:[1234],expected:'1.234'},{name:'九位数分为三组',args:[123456789],expected:'123.456.789'}]}},
{id:1557,slug:'minimum-number-of-vertices-to-reach-all-nodes',title:'可以到达所有点的最少点数目',studyTags:['图论','有向无环图'],summary:'有向无环图中选择最少起点，使从这些点出发能到达所有节点，返回任一最小集合。',insight:'所有入度为零的节点无法从其他节点到达，必须选择；DAG 中每个非零入度节点最终都可由某个零入度祖先到达，因此这些节点也足够。',pitfalls:['只需统计直接入度','答案自然按节点扫描升序','图保证无环'],solutions:[s('zero-indegree-vertices','零入度节点','DAG 的最小覆盖起点恰是全部源点。',['indegree[n]=0','对每条 edge 增加 indegree[to]','收集所有 indegree[node]==0 的 node'],'O(n+e)','O(n)',
`class Solution { public List<Integer> findSmallestSetOfVertices(int n,List<List<Integer>> edges){int[] indegree=new int[n];for(List<Integer> edge:edges)indegree[edge.get(1)]++;List<Integer> answer=new ArrayList<>();for(int node=0;node<n;node++)if(indegree[node]==0)answer.add(node);return answer;} }`,
`class Solution { fun findSmallestSetOfVertices(n:Int,edges:List<List<Int>>):List<Int>{val indegree=IntArray(n);for(edge in edges)indegree[edge[1]]++;return (0 until n).filter{indegree[it]==0}} }`,
`class Solution { public: vector<int> findSmallestSetOfVertices(int n,vector<vector<int>>& edges){vector<int> indegree(n);for(auto& edge:edges)++indegree[edge[1]];vector<int> answer;for(int node=0;node<n;++node)if(!indegree[node])answer.push_back(node);return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'findSmallestSetOfVertices',parameterTypes:['int','intListMatrix'],returnType:'intList',cases:[{name:'六节点图源点零三',args:[6,[[0,1],[0,2],[2,5],[3,4],[4,2]]],expected:[0,3]},{name:'五节点图源点零二三',args:[5,[[0,1],[2,1],[3,1],[1,4],[2,4]]],expected:[0,2,3]},{name:'没有边时所有节点都是源点',args:[3,[]],expected:[0,1,2]}]}}
]}
