const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-011',problems:[
{id:808,slug:'soup-servings',title:'分汤',studyTags:['数学','动态规划','概率','记忆化搜索'],summary:'A、B 两锅汤每轮等概率执行四种以 25 毫升为单位的分配，求 A 先空的概率加上同时空的一半概率。',insight:'把容量向上缩放成 25 毫升单位做二维记忆化；n 足够大时 A 先空概率趋近一，可用已证明阈值直接返回一。',pitfalls:['A、B 同时用完贡献 0.5','容量按 ceil(n/25) 缩放','边界判断要在查缓存之前'],solutions:[s('scaled-memo-probability','缩放后的概率记忆化搜索','按四种操作递归计算剩余容量状态。',['units=(n+24)/25；n>4800 时返回 1','dfs(a,b)：两者非正返回 0.5，仅 a 非正返回 1，仅 b 非正返回 0','其余状态为四个后继概率平均并缓存'],'O((n/25)²)','O((n/25)²)',
`class Solution { private Double[][] memo;public double soupServings(int n){if(n>4800)return 1.0;int units=(n+24)/25;memo=new Double[units+1][units+1];return dfs(units,units);}private double dfs(int a,int b){if(a<=0&&b<=0)return 0.5;if(a<=0)return 1.0;if(b<=0)return 0.0;if(memo[a][b]!=null)return memo[a][b];return memo[a][b]=0.25*(dfs(a-4,b)+dfs(a-3,b-1)+dfs(a-2,b-2)+dfs(a-1,b-3));} }`,
`class Solution { private lateinit var memo:Array<Array<Double?>>;fun soupServings(n:Int):Double{if(n>4800)return 1.0;val units=(n+24)/25;memo=Array(units+1){arrayOfNulls(units+1)};return dfs(units,units)};private fun dfs(a:Int,b:Int):Double{if(a<=0&&b<=0)return 0.5;if(a<=0)return 1.0;if(b<=0)return 0.0;memo[a][b]?.let{return it};return(0.25*(dfs(a-4,b)+dfs(a-3,b-1)+dfs(a-2,b-2)+dfs(a-1,b-3))).also{memo[a][b]=it}} }`,
`class Solution { vector<vector<double>> memo;double dfs(int a,int b){if(a<=0&&b<=0)return .5;if(a<=0)return 1;if(b<=0)return 0;double& result=memo[a][b];if(result>=0)return result;return result=.25*(dfs(a-4,b)+dfs(a-3,b-1)+dfs(a-2,b-2)+dfs(a-1,b-3));}public:double soupServings(int n){if(n>4800)return 1;int units=(n+24)/25;memo.assign(units+1,vector<double>(units+1,-1));return dfs(units,units);} };`)],tests:{schemaVersion:1,mode:'function',method:'soupServings',parameterTypes:['int'],returnType:'double',cases:[{name:'五十毫升',args:[50],expected:0.625},{name:'一百毫升',args:[100],expected:0.71875},{name:'超过收敛阈值',args:[5000],expected:1.0}]}},
{id:809,slug:'expressive-words',title:'情感丰富的文字',studyTags:['字符串','双指针','分组'],summary:'字符串 s 可把原词中某个连续字母组扩展到至少三个相同字母，统计 words 中能扩展成 s 的单词数。',insight:'同步按字符组比较：字符必须相同，原组不能更长；若组长不同，目标组长度必须至少为三。',pitfalls:['长度为二的目标组不能由更短组扩展','原组与目标组长度相同始终合法','两字符串都必须恰好遍历完'],solutions:[s('run-length-two-pointers','双指针比较连续字符组','逐组验证字符、长度和可拉伸条件。',['i、j 指向 s 与 word 当前组首字符，字符不同失败','分别找到组尾并计算 targetCount、wordCount','若 wordCount>targetCount，或两者不同且 targetCount<3 则失败；推进到下一组，最后要求同时结束'],'O(total characters)','O(1)',
`class Solution { public int expressiveWords(String s,String[] words){int answer=0;for(String word:words)if(stretchy(s,word))answer++;return answer;}private boolean stretchy(String target,String word){int i=0,j=0;while(i<target.length()&&j<word.length()){if(target.charAt(i)!=word.charAt(j))return false;int nextI=i+1,nextJ=j+1;while(nextI<target.length()&&target.charAt(nextI)==target.charAt(i))nextI++;while(nextJ<word.length()&&word.charAt(nextJ)==word.charAt(j))nextJ++;int a=nextI-i,b=nextJ-j;if(b>a||a!=b&&a<3)return false;i=nextI;j=nextJ;}return i==target.length()&&j==word.length();} }`,
`class Solution { fun expressiveWords(s:String,words:Array<String>):Int=words.count{stretchy(s,it)};private fun stretchy(target:String,word:String):Boolean{var i=0;var j=0;while(i<target.length&&j<word.length){if(target[i]!=word[j])return false;var nextI=i+1;var nextJ=j+1;while(nextI<target.length&&target[nextI]==target[i])nextI++;while(nextJ<word.length&&word[nextJ]==word[j])nextJ++;val a=nextI-i;val b=nextJ-j;if(b>a||a!=b&&a<3)return false;i=nextI;j=nextJ};return i==target.length&&j==word.length} }`,
`class Solution { bool stretchy(string& target,string& word){int i=0,j=0;while(i<(int)target.size()&&j<(int)word.size()){if(target[i]!=word[j])return false;int nextI=i+1,nextJ=j+1;while(nextI<(int)target.size()&&target[nextI]==target[i])++nextI;while(nextJ<(int)word.size()&&word[nextJ]==word[j])++nextJ;int a=nextI-i,b=nextJ-j;if(b>a||(a!=b&&a<3))return false;i=nextI;j=nextJ;}return i==(int)target.size()&&j==(int)word.size();}public:int expressiveWords(string s,vector<string>& words){int answer=0;for(string& word:words)answer+=stretchy(s,word);return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'expressiveWords',parameterTypes:['string','stringArray'],returnType:'int',cases:[{name:'经典仅 hello 合法',args:['heeellooo',['hello','hi','helo']],expected:1},{name:'两个长字符组',args:['zzzzzyyyyy',['zzyy','zy','zyy']],expected:3},{name:'缺少末尾字符组',args:['abcd',['abc']],expected:0}]}},
{id:810,slug:'chalkboard-xor-game',title:'黑板异或游戏',studyTags:['数组','数学','博弈','位运算'],summary:'两人轮流删除一个数，若轮到自己前所有数异或为零则获胜，删除后异或为零则失败，判断先手能否必胜。',insight:'博弈结论是总异或为零时立即获胜；否则只有数组长度为偶数时先手必胜。',pitfalls:['判断的是回合开始前的异或','偶数长度结论不依赖具体数值','单元素非零时先手必败'],solutions:[s('xor-zero-or-even-length','总异或与长度奇偶结论','根据博弈不变量常数时间判定。',['计算所有 nums 的 xor','若 xor==0 返回真','否则返回 nums.length 为偶数'],'O(n)','O(1)',
`class Solution { public boolean xorGame(int[] nums){int xor=0;for(int value:nums)xor^=value;return xor==0||nums.length%2==0;} }`,
`class Solution { fun xorGame(nums:IntArray):Boolean{var xor=0;for(value in nums)xor=xor xor value;return xor==0||nums.size%2==0} }`,
`class Solution { public: bool xorGame(vector<int>& nums){int value=0;for(int number:nums)value^=number;return value==0||nums.size()%2==0;} };`)],tests:{schemaVersion:1,mode:'function',method:'xorGame',parameterTypes:['intArray'],returnType:'boolean',cases:[{name:'奇数长度异或非零',args:[[1,1,2]],expected:false},{name:'偶数长度必胜',args:[[0,1]],expected:true},{name:'初始异或为零',args:[[1,2,3]],expected:true}]}},
{id:811,slug:'subdomain-visit-count',title:'子域名访问计数',studyTags:['字符串','哈希表','计数'],summary:'每项给出完整域名访问次数，累加其自身及所有父级子域名的访问次数并返回结果。',insight:'从完整域名开始累加，随后每次取第一个点之后的后缀，直到没有点；用有序映射可稳定输出。',pitfalls:['次数与域名以空格分隔','com 等顶级域也要计数','同一子域可能由多项贡献，需要累加'],solutions:[s('suffix-domain-count-map','后缀子域计数映射','逐级截取域名后缀并累加访问数。',['解析空格前的 count 和后面的 domain','循环把当前 domain 加 count，再移动到第一个点之后；无点时结束','按域名字典序输出 count + 空格 + domain'],'O(total input length)','O(number of subdomains)',
`class Solution { public List<String> subdomainVisits(String[] cpdomains){Map<String,Integer> counts=new TreeMap<>();for(String item:cpdomains){int space=item.indexOf(' '),count=Integer.parseInt(item.substring(0,space));String domain=item.substring(space+1);while(true){counts.merge(domain,count,Integer::sum);int dot=domain.indexOf('.');if(dot<0)break;domain=domain.substring(dot+1);}}List<String> answer=new ArrayList<>();for(Map.Entry<String,Integer> entry:counts.entrySet())answer.add(entry.getValue()+" "+entry.getKey());return answer;} }`,
`class Solution { fun subdomainVisits(cpdomains:Array<String>):List<String>{val counts=sortedMapOf<String,Int>();for(item in cpdomains){val space=item.indexOf(' ');val count=item.substring(0,space).toInt();var domain=item.substring(space+1);while(true){counts[domain]=(counts[domain]?:0)+count;val dot=domain.indexOf('.');if(dot<0)break;domain=domain.substring(dot+1)}};return counts.map{(domain,count)->"$count $domain"}} }`,
`class Solution { public: vector<string> subdomainVisits(vector<string>& cpdomains){map<string,int> counts;for(string item:cpdomains){int space=item.find(' '),count=stoi(item.substr(0,space));string domain=item.substr(space+1);while(true){counts[domain]+=count;int dot=domain.find('.');if(dot==string::npos)break;domain=domain.substr(dot+1);}}vector<string> answer;for(auto& [domain,count]:counts)answer.push_back(to_string(count)+" "+domain);return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'subdomainVisits',parameterTypes:['stringArray'],returnType:'stringList',cases:[{name:'三级域名',args:[['9001 discuss.leetcode.com']],expected:['9001 com','9001 discuss.leetcode.com','9001 leetcode.com']},{name:'两项共享顶级域',args:[['900 google.mail.com','50 yahoo.com']],expected:['950 com','900 google.mail.com','900 mail.com','50 yahoo.com']},{name:'两个二级域',args:[['1 a.com','2 b.com']],expected:['1 a.com','2 b.com','3 com']}]}},
{id:812,slug:'largest-triangle-area',title:'最大三角形面积',studyTags:['数组','数学','几何','枚举'],summary:'给定平面点集，选择三个不同点构成三角形，返回最大面积。',insight:'三点叉积绝对值的一半就是三角形面积，枚举所有三元组取最大值。',pitfalls:['三点共线时面积为零','先取叉积绝对值再除二','坐标差与乘积可用整数，最终返回浮点数'],solutions:[s('triple-cross-product','三元组叉积枚举','用二维叉积计算每组三点的两倍面积。',['枚举 i<j<k','计算 abs((xj-xi)(yk-yi)-(yj-yi)(xk-xi))','维护最大两倍面积并在返回时除以 2.0'],'O(n³)','O(1)',
`class Solution { public double largestTriangleArea(int[][] points){long twice=0;for(int i=0;i<points.length;i++)for(int j=i+1;j<points.length;j++)for(int k=j+1;k<points.length;k++){long cross=(long)(points[j][0]-points[i][0])*(points[k][1]-points[i][1])-(long)(points[j][1]-points[i][1])*(points[k][0]-points[i][0]);twice=Math.max(twice,Math.abs(cross));}return twice/2.0;} }`,
`class Solution { fun largestTriangleArea(points:Array<IntArray>):Double{var twice=0L;for(i in points.indices)for(j in i+1 until points.size)for(k in j+1 until points.size){val cross=(points[j][0]-points[i][0]).toLong()*(points[k][1]-points[i][1])-(points[j][1]-points[i][1]).toLong()*(points[k][0]-points[i][0]);twice=maxOf(twice,kotlin.math.abs(cross))};return twice/2.0} }`,
`class Solution { public: double largestTriangleArea(vector<vector<int>>& points){long long twice=0;for(int i=0;i<(int)points.size();++i)for(int j=i+1;j<(int)points.size();++j)for(int k=j+1;k<(int)points.size();++k){long long cross=(long long)(points[j][0]-points[i][0])*(points[k][1]-points[i][1])-(long long)(points[j][1]-points[i][1])*(points[k][0]-points[i][0]);twice=max(twice,llabs(cross));}return twice/2.0;} };`)],tests:{schemaVersion:1,mode:'function',method:'largestTriangleArea',parameterTypes:['intMatrix'],returnType:'double',cases:[{name:'最大直角三角形',args:[[[0,0],[0,1],[1,0],[0,2],[2,0]]],expected:2.0},{name:'三点共线',args:[[[0,0],[1,1],[2,2]]],expected:0.0},{name:'单位直角三角形',args:[[[0,0],[1,0],[0,1]]],expected:0.5}]}}
]}
