const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-015',problems:[
{id:1006,slug:'clumsy-factorial',title:'笨阶乘',studyTags:['数学','栈','模拟'],summary:'从 n 递减到一，按乘、除、加、减循环运算并遵循通常优先级，整数除法向零截断，求结果。',insight:'用栈处理优先级：乘除立即与栈顶合并，加法压入正数，减法压入负数；最后求栈和。',pitfalls:['操作符循环从 n*(n-1) 开始','乘除优先于加减','减法后的数以负数压栈'],solutions:[s('operator-cycle-stack','运算符循环栈模拟','即时结算乘除并把加减项留到最后求和。',['栈先压 n，current 从 n-1 递减，operation 从零循环','operation%4 为零乘栈顶，为一除栈顶，为二压正 current，为三压负 current','所有数处理完后求栈内项之和'],'O(n)','O(n)',
`class Solution { public int clumsy(int n){Deque<Integer> stack=new ArrayDeque<>();stack.push(n);int operation=0;for(int value=n-1;value>=1;value--,operation++){if(operation%4==0)stack.push(stack.pop()*value);else if(operation%4==1)stack.push(stack.pop()/value);else if(operation%4==2)stack.push(value);else stack.push(-value);}int answer=0;for(int value:stack)answer+=value;return answer;} }`,
`class Solution { fun clumsy(n:Int):Int{val stack=java.util.ArrayDeque<Int>();stack.push(n);var operation=0;for(value in n-1 downTo 1){when(operation%4){0->stack.push(stack.pop()*value);1->stack.push(stack.pop()/value);2->stack.push(value);else->stack.push(-value)};operation++};return stack.sum()} }`,
`class Solution { public: int clumsy(int n){vector<int> stack{n};int operation=0;for(int value=n-1;value>=1;--value,++operation){if(operation%4==0)stack.back()*=value;else if(operation%4==1)stack.back()/=value;else if(operation%4==2)stack.push_back(value);else stack.push_back(-value);}return accumulate(stack.begin(),stack.end(),0);} };`)],tests:{schemaVersion:1,mode:'function',method:'clumsy',parameterTypes:['int'],returnType:'int',cases:[{name:'四的笨阶乘',args:[4],expected:7},{name:'十的笨阶乘',args:[10],expected:12},{name:'一的笨阶乘',args:[1],expected:1}]}},
{id:1007,slug:'minimum-domino-rotations-for-equal-row',title:'行相等的最少多米诺旋转',studyTags:['数组','贪心'],summary:'每张多米诺上下各有数字，可翻转任意张，求让所有上排或所有下排数字相同的最少翻转数；无解返回负一。',insight:'若存在可统一数字，它必是第一张牌的上值或下值；分别检查这两个候选并统计统一上排、统一下排所需翻转数。',pitfalls:['某位置上下都不是候选时该候选失败','同时计算上排和下排旋转数并取较小','两个首值相同无需重复检查但重复也不影响结果'],solutions:[s('two-first-value-candidates','首牌双候选检查','只验证第一张牌暴露的两个可能统一值。',['定义 rotations(target)，扫描每张牌','若 tops[i] 和 bottoms[i] 都不等于 target 返回极大值；tops 不等则 topRotations++，bottoms 不等则 bottomRotations++','对 tops[0]、bottoms[0] 取最小旋转数，极大值则返回 -1'],'O(n)','O(1)',
`class Solution { public int minDominoRotations(int[] tops,int[] bottoms){int answer=Math.min(check(tops[0],tops,bottoms),check(bottoms[0],tops,bottoms));return answer==Integer.MAX_VALUE?-1:answer;}private int check(int target,int[] tops,int[] bottoms){int top=0,bottom=0;for(int i=0;i<tops.length;i++){if(tops[i]!=target&&bottoms[i]!=target)return Integer.MAX_VALUE;if(tops[i]!=target)top++;if(bottoms[i]!=target)bottom++;}return Math.min(top,bottom);} }`,
`class Solution { fun minDominoRotations(tops:IntArray,bottoms:IntArray):Int{fun check(target:Int):Int{var top=0;var bottom=0;for(i in tops.indices){if(tops[i]!=target&&bottoms[i]!=target)return Int.MAX_VALUE;if(tops[i]!=target)top++;if(bottoms[i]!=target)bottom++};return minOf(top,bottom)};val answer=minOf(check(tops[0]),check(bottoms[0]));return if(answer==Int.MAX_VALUE)-1 else answer} }`,
`class Solution { int check(int target,vector<int>& tops,vector<int>& bottoms){int top=0,bottom=0;for(int i=0;i<(int)tops.size();++i){if(tops[i]!=target&&bottoms[i]!=target)return INT_MAX;if(tops[i]!=target)++top;if(bottoms[i]!=target)++bottom;}return min(top,bottom);}public:int minDominoRotations(vector<int>& tops,vector<int>& bottoms){int answer=min(check(tops[0],tops,bottoms),check(bottoms[0],tops,bottoms));return answer==INT_MAX?-1:answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'minDominoRotations',parameterTypes:['intArray','intArray'],returnType:'int',cases:[{name:'统一为二需两次',args:[[2,1,2,4,2,2],[5,2,6,2,3,2]],expected:2},{name:'无法统一',args:[[3,5,1,2,3],[3,6,3,3,4]],expected:-1},{name:'已经统一',args:[[1,1],[1,1]],expected:0}]}},
{id:1008,slug:'construct-binary-search-tree-from-preorder-traversal',title:'前序遍历构造二叉搜索树',studyTags:['树','二叉搜索树','递归'],summary:'给定互异整数的二叉搜索树前序遍历，重建并返回该树。',insight:'前序下一个值若不超过当前递归允许的上界，就属于当前子树；创建根后先用根值作上界构建左树，再沿用父上界构建右树。',pitfalls:['值互不相同，可用严格上界判断','共享索引只在节点真正被消费时递增','递归顺序必须先左后右'],solutions:[s('preorder-upper-bound-recursion','前序上界递归','用一个索引和子树最大允许值在线重建。',['index=0','build(bound)：若 index 到末尾或 preorder[index]>bound 返回空','取值建根并 index++；left=build(value)，right=build(bound)，返回根；初始 bound 为正无穷'],'O(n)','O(height)',
`class Solution { private int index;public TreeNode bstFromPreorder(int[] preorder){index=0;return build(preorder,Integer.MAX_VALUE);}private TreeNode build(int[] preorder,int bound){if(index==preorder.length||preorder[index]>bound)return null;TreeNode root=new TreeNode(preorder[index++]);root.left=build(preorder,root.val);root.right=build(preorder,bound);return root;} }`,
`class Solution { private var index=0;fun bstFromPreorder(preorder:IntArray):TreeNode?{index=0;return build(preorder,Int.MAX_VALUE)};private fun build(preorder:IntArray,bound:Int):TreeNode?{if(index==preorder.size||preorder[index]>bound)return null;val root=TreeNode(preorder[index++]);root.left=build(preorder,root.\`val\`);root.right=build(preorder,bound);return root} }`,
`class Solution { int index;TreeNode* build(vector<int>& preorder,int bound){if(index==(int)preorder.size()||preorder[index]>bound)return nullptr;TreeNode* root=new TreeNode(preorder[index++]);root->left=build(preorder,root->val);root->right=build(preorder,bound);return root;}public:TreeNode* bstFromPreorder(vector<int>& preorder){index=0;return build(preorder,INT_MAX);} };`)],tests:{schemaVersion:1,mode:'function',method:'bstFromPreorder',parameterTypes:['intArray'],returnType:'treeNode',cases:[{name:'经典前序重建',args:[[8,5,1,7,10,12]],expected:[8,5,10,1,7,null,12]},{name:'三节点左斜树',args:[[3,2,1]],expected:[3,2,null,1]},{name:'单节点',args:[[1]],expected:[1]}]}},
{id:1009,slug:'complement-of-base-10-integer',title:'十进制整数的反码',studyTags:['数学','位运算'],summary:'把非负整数的二进制表示中每一位零一翻转，返回结果。',insight:'构造与 n 最高位等长且全为一的掩码，n 与掩码异或即只翻转有效位；零的表示为单个零，反码是一。',pitfalls:['不能翻转无限前导零','n=0 要单独返回一','掩码逐位左移并加一'],solutions:[s('same-width-ones-mask','同位宽全一掩码','构造覆盖有效二进制位的异或掩码。',['n==0 返回 1','mask=0，copy=n；copy>0 时 mask=(mask<<1)|1，copy>>=1','返回 n^mask'],'O(log n)','O(1)',
`class Solution { public int bitwiseComplement(int n){if(n==0)return 1;int mask=0;for(int copy=n;copy>0;copy>>=1)mask=(mask<<1)|1;return n^mask;} }`,
`class Solution { fun bitwiseComplement(n:Int):Int{if(n==0)return 1;var mask=0;var copy=n;while(copy>0){mask=(mask shl 1) or 1;copy=copy shr 1};return n xor mask} }`,
`class Solution { public: int bitwiseComplement(int n){if(n==0)return 1;int mask=0;for(int copy=n;copy;copy>>=1)mask=mask<<1|1;return n^mask;} };`)],tests:{schemaVersion:1,mode:'function',method:'bitwiseComplement',parameterTypes:['int'],returnType:'int',cases:[{name:'五的反码为二',args:[5],expected:2},{name:'七的反码为零',args:[7],expected:0},{name:'十的反码为五',args:[10],expected:5}]}},
{id:1010,slug:'pairs-of-songs-with-total-durations-divisible-by-60',title:'总持续时间可被 60 整除的歌曲',studyTags:['数组','哈希表','计数'],summary:'统计下标 i<j 且两首歌时长之和能被六十整除的歌曲对数量。',insight:'扫描当前时长余数 r，此前可配对余数唯一是 (60-r)%60；先累加其频次再记录 r，天然保证下标顺序。',pitfalls:['余数零与余数零配对','余数三十与三十配对','必须先查询再增加当前频次避免自配对'],solutions:[s('remainder-complement-count','余数补数计数','用六十个余数桶在线统计配对。',['frequency[60] 初始化零，answer=0','对 duration，remainder=duration%60，complement=(60-remainder)%60','answer+=frequency[complement]，再 frequency[remainder]++；返回 answer'],'O(n)','O(1)',
`class Solution { public int numPairsDivisibleBy60(int[] time){int[] frequency=new int[60];int answer=0;for(int duration:time){int remainder=duration%60;answer+=frequency[(60-remainder)%60];frequency[remainder]++;}return answer;} }`,
`class Solution { fun numPairsDivisibleBy60(time:IntArray):Int{val frequency=IntArray(60);var answer=0;for(duration in time){val remainder=duration%60;answer+=frequency[(60-remainder)%60];frequency[remainder]++};return answer} }`,
`class Solution { public: int numPairsDivisibleBy60(vector<int>& time){int frequency[60]={},answer=0;for(int duration:time){int remainder=duration%60;answer+=frequency[(60-remainder)%60];++frequency[remainder];}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'numPairsDivisibleBy60',parameterTypes:['intArray'],returnType:'int',cases:[{name:'经典三对',args:[[30,20,150,100,40]],expected:3},{name:'三个整分钟',args:[[60,60,60]],expected:3},{name:'一对互补余数',args:[[10,50]],expected:1}]}}
]}
