const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-013',problems:[
{id:935,slug:'knight-dialer',title:'骑士拨号器',studyTags:['动态规划','图论'],summary:'国际象棋骑士从任意数字键出发走 n-1 步，统计可形成的长度 n 数字串数量并取模。',insight:'十个数字是固定图节点；dp[digit] 表示当前长度以该数字结尾的序列数，每轮沿骑士边转移。',pitfalls:['数字五没有可达邻居','长度一时十个起点都有效','每次加法都要取模'],solutions:[s('digit-graph-dp','数字图滚动动态规划','在固定骑士邻接表上逐步转移。',['dp 十个位置初始化为一','重复 n-1 轮，为每个 from 把 dp[from] 加到所有邻接 to','滚动替换 dp，求和取模返回'],'O(n)','O(1)',
`class Solution { public int knightDialer(int n){int[][] next={{4,6},{6,8},{7,9},{4,8},{0,3,9},{},{0,1,7},{2,6},{1,3},{2,4}};long mod=1000000007L;long[] dp=new long[10];Arrays.fill(dp,1);for(int length=1;length<n;length++){long[] updated=new long[10];for(int from=0;from<10;from++)for(int to:next[from])updated[to]=(updated[to]+dp[from])%mod;dp=updated;}long answer=0;for(long ways:dp)answer=(answer+ways)%mod;return(int)answer;} }`,
`class Solution { fun knightDialer(n:Int):Int{val next=arrayOf(intArrayOf(4,6),intArrayOf(6,8),intArrayOf(7,9),intArrayOf(4,8),intArrayOf(0,3,9),intArrayOf(),intArrayOf(0,1,7),intArrayOf(2,6),intArrayOf(1,3),intArrayOf(2,4));val mod=1000000007L;var dp=LongArray(10){1};repeat(n-1){val updated=LongArray(10);for(from in 0..9)for(to in next[from])updated[to]=(updated[to]+dp[from])%mod;dp=updated};return (dp.sum()%mod).toInt()} }`,
`class Solution { public: int knightDialer(int n){vector<vector<int>> next={{4,6},{6,8},{7,9},{4,8},{0,3,9},{},{0,1,7},{2,6},{1,3},{2,4}};const long long mod=1000000007;vector<long long> dp(10,1);for(int length=1;length<n;++length){vector<long long> updated(10);for(int from=0;from<10;++from)for(int to:next[from])updated[to]=(updated[to]+dp[from])%mod;dp.swap(updated);}return accumulate(dp.begin(),dp.end(),0LL)%mod;} };`)],tests:{schemaVersion:1,mode:'function',method:'knightDialer',parameterTypes:['int'],returnType:'int',cases:[{name:'长度一',args:[1],expected:10},{name:'长度二',args:[2],expected:20},{name:'较大长度取模',args:[3131],expected:136006598}]}},
{id:936,slug:'stamping-the-sequence',title:'戳印序列',studyTags:['字符串','贪心','模拟'],summary:'从问号串开始，每次把 stamp 覆盖到一个位置，求不超过十倍目标长度的操作序列生成 target；无解返回空数组。',insight:'反向思考为擦除 target：某窗口的未擦字符都与 stamp 对应位置相同且至少能新擦一个字符时即可擦除；持续贪心直到全为星号。',pitfalls:['窗口中已有星号可匹配任意字符','一次操作必须新擦除至少一个字符','反向擦除位置收集后要逆序返回'],solutions:[s('reverse-greedy-erasure','反向贪心擦除','不断擦除当前可与印章匹配的窗口。',['把 target 转字符数组，done 标记已使用窗口','循环扫描所有窗口；若未擦字符均匹配且存在未擦字符，则置星并记录位置','若一轮无进展且尚未全擦返回空；全部擦除后逆序 moves'],'O(n²m)','O(n)',
`class Solution { public int[] movesToStamp(String stamp,String target){char[] text=target.toCharArray();boolean[] done=new boolean[target.length()-stamp.length()+1];List<Integer> moves=new ArrayList<>();int erased=0;while(erased<text.length){boolean changed=false;for(int start=0;start<done.length;start++)if(!done[start]&&canErase(text,stamp,start)){int added=erase(text,start,stamp.length());if(added>0){erased+=added;changed=true;done[start]=true;moves.add(start);}}if(!changed)return new int[0];}Collections.reverse(moves);return moves.stream().mapToInt(Integer::intValue).toArray();}private boolean canErase(char[] text,String stamp,int start){boolean fresh=false;for(int i=0;i<stamp.length();i++)if(text[start+i]!='*'){if(text[start+i]!=stamp.charAt(i))return false;fresh=true;}return fresh;}private int erase(char[] text,int start,int length){int count=0;for(int i=0;i<length;i++)if(text[start+i]!='*'){text[start+i]='*';count++;}return count;} }`,
`class Solution { fun movesToStamp(stamp:String,target:String):IntArray{val text=target.toCharArray();val done=BooleanArray(target.length-stamp.length+1);val moves=mutableListOf<Int>();var erased=0;while(erased<text.size){var changed=false;for(start in done.indices)if(!done[start]&&canErase(text,stamp,start)){val added=erase(text,start,stamp.length);if(added>0){erased+=added;changed=true;done[start]=true;moves.add(start)}};if(!changed)return intArrayOf()};return moves.asReversed().toIntArray()};private fun canErase(text:CharArray,stamp:String,start:Int):Boolean{var fresh=false;for(i in stamp.indices)if(text[start+i]!='*'){if(text[start+i]!=stamp[i])return false;fresh=true};return fresh};private fun erase(text:CharArray,start:Int,length:Int):Int{var count=0;for(i in 0 until length)if(text[start+i]!='*'){text[start+i]='*';count++};return count} }`,
`class Solution { bool canErase(string& text,string& stamp,int start){bool fresh=false;for(int i=0;i<(int)stamp.size();++i)if(text[start+i]!='*'){if(text[start+i]!=stamp[i])return false;fresh=true;}return fresh;}int erase(string& text,int start,int length){int count=0;for(int i=0;i<length;++i)if(text[start+i]!='*'){text[start+i]='*';++count;}return count;}public:vector<int> movesToStamp(string stamp,string target){vector<bool> done(target.size()-stamp.size()+1);vector<int> moves;int erased=0;while(erased<(int)target.size()){bool changed=false;for(int start=0;start<(int)done.size();++start)if(!done[start]&&canErase(target,stamp,start)){int added=erase(target,start,stamp.size());if(added){erased+=added;changed=true;done[start]=true;moves.push_back(start);}}if(!changed)return {};}reverse(moves.begin(),moves.end());return moves;} };`)],tests:{schemaVersion:1,mode:'function',method:'movesToStamp',parameterTypes:['string','string'],returnType:'intArray',cases:[{name:'经典两次印章',args:['abc','ababc'],expected:[0,2]},{name:'单字符覆盖三次',args:['a','aaa'],expected:[2,1,0]},{name:'两个独立窗口',args:['ab','abab'],expected:[2,0]}]}},
{id:937,slug:'reorder-data-in-log-files',title:'重新排列日志文件',studyTags:['数组','字符串','排序'],summary:'日志首字段是标识符；字母日志按内容再按标识符排序并置前，数字日志保持原相对顺序置后。',insight:'比较器先区分内容首字符是否为数字；两个字母日志比较去掉标识符后的内容，再比较标识符，数字日志比较为相等以保留稳定顺序。',pitfalls:['字母日志排序不包含标识符作为首关键字','内容相同时才比较标识符','数字日志之间必须稳定'],solutions:[s('stable-custom-log-sort','稳定自定义日志排序','按日志类型和题设键建立比较器。',['为日志定位第一个空格并判断内容类型','字母对字母先比较 content，后比较 identifier','字母排数字之前，数字对数字返回零并用稳定排序'],'O(n log n·L)','O(n)',
`class Solution { public String[] reorderLogFiles(String[] logs){Arrays.sort(logs,(a,b)->{int sa=a.indexOf(' '),sb=b.indexOf(' ');boolean da=Character.isDigit(a.charAt(sa+1)),db=Character.isDigit(b.charAt(sb+1));if(da&&db)return 0;if(da!=db)return da?1:-1;int byContent=a.substring(sa+1).compareTo(b.substring(sb+1));return byContent!=0?byContent:a.substring(0,sa).compareTo(b.substring(0,sb));});return logs;} }`,
`class Solution { fun reorderLogFiles(logs:Array<String>):Array<String>{return logs.withIndex().sortedWith(Comparator{a,b->val sa=a.value.indexOf(' ');val sb=b.value.indexOf(' ');val da=a.value[sa+1].isDigit();val db=b.value[sb+1].isDigit();if(da&&db)a.index-b.index else if(da!=db)if(da)1 else -1 else{val content=a.value.substring(sa+1).compareTo(b.value.substring(sb+1));if(content!=0)content else a.value.substring(0,sa).compareTo(b.value.substring(0,sb))}}).map{it.value}.toTypedArray()} }`,
`class Solution { public: vector<string> reorderLogFiles(vector<string>& logs){stable_sort(logs.begin(),logs.end(),[](const string& a,const string& b){int sa=a.find(' '),sb=b.find(' ');bool da=isdigit(a[sa+1]),db=isdigit(b[sb+1]);if(da&&db)return false;if(da!=db)return !da;string ca=a.substr(sa+1),cb=b.substr(sb+1);return ca==cb?a.substr(0,sa)<b.substr(0,sb):ca<cb;});return logs;} };`)],tests:{schemaVersion:1,mode:'function',method:'reorderLogFiles',parameterTypes:['stringArray'],returnType:'stringArray',cases:[{name:'经典混合日志',args:[['dig1 8 1 5 1','let1 art can','dig2 3 6','let2 own kit dig','let3 art zero']],expected:['let1 art can','let3 art zero','let2 own kit dig','dig1 8 1 5 1','dig2 3 6']},{name:'内容相同按标识符',args:[['b act','a act']],expected:['a act','b act']},{name:'数字日志保持顺序',args:[['d1 2 3','d2 1 4']],expected:['d1 2 3','d2 1 4']}]}},
{id:938,slug:'range-sum-of-bst',title:'二叉搜索树的范围和',studyTags:['树','深度优先搜索','二叉搜索树'],summary:'给定二叉搜索树和闭区间 [low,high]，求所有值落在区间内节点的值之和。',insight:'利用搜索树有序性剪枝：节点值小于等于 low 时无需搜索左侧，大于等于 high 时无需搜索右侧。',pitfalls:['边界值要计入答案','空树贡献为零','剪枝条件仍要允许边界另一侧搜索'],solutions:[s('bst-pruned-dfs','二叉搜索树剪枝 DFS','只递归可能含区间值的子树。',['空节点返回零','当前值在区间内则计入','若 node.val>low 搜左子树；若 node.val<high 搜右子树，返回总和'],'O(visited nodes)','O(height)',
`class Solution { public int rangeSumBST(TreeNode root,int low,int high){if(root==null)return 0;int sum=root.val>=low&&root.val<=high?root.val:0;if(root.val>low)sum+=rangeSumBST(root.left,low,high);if(root.val<high)sum+=rangeSumBST(root.right,low,high);return sum;} }`,
`class Solution { fun rangeSumBST(root:TreeNode?,low:Int,high:Int):Int{root?:return 0;var sum=if(root.\`val\` in low..high)root.\`val\` else 0;if(root.\`val\`>low)sum+=rangeSumBST(root.left,low,high);if(root.\`val\`<high)sum+=rangeSumBST(root.right,low,high);return sum} }`,
`class Solution { public: int rangeSumBST(TreeNode* root,int low,int high){if(!root)return 0;int sum=root->val>=low&&root->val<=high?root->val:0;if(root->val>low)sum+=rangeSumBST(root->left,low,high);if(root->val<high)sum+=rangeSumBST(root->right,low,high);return sum;} };`)],tests:{schemaVersion:1,mode:'function',method:'rangeSumBST',parameterTypes:['treeNode','int','int'],returnType:'int',cases:[{name:'范围七到十五',args:[[10,5,15,3,7,null,18],7,15],expected:32},{name:'更多节点',args:[[10,5,15,3,7,13,18,1,null,6],6,10],expected:23},{name:'仅根节点命中',args:[[5],5,5],expected:5}]}},
{id:939,slug:'minimum-area-rectangle',title:'最小面积矩形',studyTags:['数组','哈希集合','几何'],summary:'给定平面上的点，寻找边平行于坐标轴且四角都在点集中的最小正面积矩形，不存在返回零。',insight:'把所有点编码进集合，枚举任意横纵坐标都不同的点作为对角线，查询另两个角是否存在即可。',pitfalls:['同横坐标或同纵坐标不能形成正面积对角线','坐标编码要避免碰撞','每个矩形可能被枚举多次但不影响最小值'],solutions:[s('diagonal-pair-hash-check','对角点枚举与哈希查询','为每对候选对角点补查另外两角。',['把每个 (x,y) 编码进哈希集合','枚举点对，跳过 x 或 y 相同者','若 (x1,y2) 与 (x2,y1) 都存在，用 |x1-x2|·|y1-y2| 更新最小面积；无结果返回零'],'O(n²)','O(n)',
`class Solution { public int minAreaRect(int[][] points){Set<Long> set=new HashSet<>();for(int[] p:points)set.add(key(p[0],p[1]));int answer=Integer.MAX_VALUE;for(int i=0;i<points.length;i++)for(int j=i+1;j<points.length;j++){int[] a=points[i],b=points[j];if(a[0]==b[0]||a[1]==b[1])continue;if(set.contains(key(a[0],b[1]))&&set.contains(key(b[0],a[1])))answer=Math.min(answer,Math.abs(a[0]-b[0])*Math.abs(a[1]-b[1]));}return answer==Integer.MAX_VALUE?0:answer;}private long key(int x,int y){return((long)x<<32)^(y&0xffffffffL);} }`,
`class Solution { fun minAreaRect(points:Array<IntArray>):Int{fun key(x:Int,y:Int):Long{return (x.toLong() shl 32) xor (y.toLong() and 0xffffffffL)};val set=points.map{key(it[0],it[1])}.toHashSet();var answer=Int.MAX_VALUE;for(i in points.indices)for(j in i+1 until points.size){val a=points[i];val b=points[j];if(a[0]==b[0]||a[1]==b[1])continue;if(key(a[0],b[1]) in set&&key(b[0],a[1]) in set)answer=minOf(answer,kotlin.math.abs(a[0]-b[0])*kotlin.math.abs(a[1]-b[1]))};return if(answer==Int.MAX_VALUE)0 else answer} }`,
`class Solution { long long key(int x,int y){return((long long)x<<32)^(unsigned int)y;}public:int minAreaRect(vector<vector<int>>& points){unordered_set<long long> set;for(auto& p:points)set.insert(key(p[0],p[1]));int answer=INT_MAX;for(int i=0;i<(int)points.size();++i)for(int j=i+1;j<(int)points.size();++j){auto& a=points[i];auto& b=points[j];if(a[0]==b[0]||a[1]==b[1])continue;if(set.count(key(a[0],b[1]))&&set.count(key(b[0],a[1])))answer=min(answer,abs(a[0]-b[0])*abs(a[1]-b[1]));}return answer==INT_MAX?0:answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'minAreaRect',parameterTypes:['intMatrix'],returnType:'int',cases:[{name:'单位方形放大面积四',args:[[[1,1],[1,3],[3,1],[3,3],[2,2]]],expected:4},{name:'无矩形',args:[[[1,1],[1,2],[1,3]]],expected:0},{name:'多个矩形取面积二',args:[[[1,1],[1,3],[2,1],[2,3],[3,1],[3,3]]],expected:2}]}}
]}
