const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-022',problems:[
{id:1518,slug:'water-bottles',title:'换水问题',studyTags:['数学','模拟'],summary:'喝完 numBottles 瓶水后，每 numExchange 个空瓶可换一瓶水，求最多喝几瓶。',insight:'维护当前空瓶数；每轮批量兑换 empties/numExchange 瓶，喝完后新空瓶与余数合并，直到不足兑换。',pitfalls:['初始所有水都能喝','兑换得到的瓶子喝完仍产生空瓶','保留不能兑换的空瓶余数'],solutions:[s('batch-exchange-simulation','批量兑换模拟','每轮一次计算所有可兑换的新水。',['answer=numBottles,empty=numBottles','empty>=numExchange 时 full=empty/numExchange','answer+=full，empty=full+empty%numExchange，返回 answer'],'O(log n)','O(1)',
`class Solution { public int numWaterBottles(int numBottles,int numExchange){int answer=numBottles,empty=numBottles;while(empty>=numExchange){int full=empty/numExchange;answer+=full;empty=full+empty%numExchange;}return answer;} }`,
`class Solution { fun numWaterBottles(numBottles:Int,numExchange:Int):Int{var answer=numBottles;var empty=numBottles;while(empty>=numExchange){val full=empty/numExchange;answer+=full;empty=full+empty%numExchange};return answer} }`,
`class Solution { public: int numWaterBottles(int numBottles,int numExchange){int answer=numBottles,empty=numBottles;while(empty>=numExchange){int full=empty/numExchange;answer+=full;empty=full+empty%numExchange;}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'numWaterBottles',parameterTypes:['int','int'],returnType:'int',cases:[{name:'九瓶三换一共十三瓶',args:[9,3],expected:13},{name:'十五瓶四换一共十九瓶',args:[15,4],expected:19},{name:'五瓶可再换一瓶',args:[5,5],expected:6}]}},
{id:1519,slug:'number-of-nodes-in-the-sub-tree-with-the-same-label',title:'子树中标签相同的节点数',studyTags:['树','深度优先搜索','计数','树形 DP'],summary:'无根树以节点零为根，对每个节点统计其子树中与自身标签相同的节点数量。',insight:'后序 DFS 为每个子树返回二十六个标签频次，逐孩子合并后，当前标签对应频次就是答案。',pitfalls:['输入边无方向需建立双向邻接','跳过父节点防止回走','当前节点自身也要计入'],solutions:[s('subtree-frequency-dfs','子树频次深搜','自底向上合并每个孩子的标签计数向量。',['建立无向图，answer[n]','dfs(node,parent) 初始化 count[label[node]]=1','递归孩子并逐字母累加，answer[node]=count[label[node]]，返回 count'],'O(26n)','O(26n)',
`class Solution { private String labels;private int[] answer;private List<Integer>[] graph;private int[] dfs(int node,int parent){int[] count=new int[26];count[labels.charAt(node)-'a']=1;for(int child:graph[node])if(child!=parent){int[] childCount=dfs(child,node);for(int letter=0;letter<26;letter++)count[letter]+=childCount[letter];}answer[node]=count[labels.charAt(node)-'a'];return count;}public int[] countSubTrees(int n,int[][] edges,String labels){this.labels=labels;answer=new int[n];graph=new List[n];for(int i=0;i<n;i++)graph[i]=new ArrayList<>();for(int[] edge:edges){graph[edge[0]].add(edge[1]);graph[edge[1]].add(edge[0]);}dfs(0,-1);return answer;} }`,
`class Solution { private lateinit var labels:String;private lateinit var answer:IntArray;private lateinit var graph:Array<MutableList<Int>>;private fun dfs(node:Int,parent:Int):IntArray{val count=IntArray(26);count[labels[node]-'a']=1;for(child in graph[node])if(child!=parent){val childCount=dfs(child,node);for(letter in 0..25)count[letter]+=childCount[letter]};answer[node]=count[labels[node]-'a'];return count};fun countSubTrees(n:Int,edges:Array<IntArray>,labels:String):IntArray{this.labels=labels;answer=IntArray(n);graph=Array(n){mutableListOf<Int>()};for(edge in edges){graph[edge[0]].add(edge[1]);graph[edge[1]].add(edge[0])};dfs(0,-1);return answer} }`,
`class Solution { string labels;vector<int> answer;vector<vector<int>> graph;array<int,26> dfs(int node,int parent){array<int,26> count{};++count[labels[node]-'a'];for(int child:graph[node])if(child!=parent){auto childCount=dfs(child,node);for(int letter=0;letter<26;++letter)count[letter]+=childCount[letter];}answer[node]=count[labels[node]-'a'];return count;}public:vector<int> countSubTrees(int n,vector<vector<int>>& edges,string labels){this->labels=labels;answer.resize(n);graph.resize(n);for(auto& edge:edges){graph[edge[0]].push_back(edge[1]);graph[edge[1]].push_back(edge[0]);}dfs(0,-1);return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'countSubTrees',parameterTypes:['int','intMatrix','string'],returnType:'intArray',cases:[{name:'经典七节点标签树',args:[7,[[0,1],[0,2],[1,4],[1,5],[2,3],[2,6]],'abaedcd'],expected:[2,1,1,1,1,1,1]},{name:'四个节点标签全相同',args:[4,[[0,1],[1,2],[0,3]],'bbbb'],expected:[4,2,1,1]},{name:'星形树根标签出现三次',args:[5,[[0,1],[0,2],[0,3],[0,4]],'aabab'],expected:[3,1,1,1,1]}]}},
{id:1520,slug:'maximum-number-of-non-overlapping-substrings',title:'最多的不重叠子字符串',studyTags:['哈希表','字符串','贪心'],summary:'选择最多个互不重叠非空子串，且每个子串若包含字符 c 就必须包含 c 在原串的全部出现；数量相同时总长度最小。',insight:'从每个字符首次位置尝试扩展到其中所有字符的末次位置；若遇字符首次位置在起点前则无效。所得最小闭包区间按结束位置贪心选择。',pitfalls:['扩展过程中新字符可能继续扩大右端','出现位置越过起点左侧会使候选无效','按结束位置选择可最大化数量并最小化长度'],solutions:[s('character-closure-interval-greedy','字符闭包区间贪心','生成每个字符的最小合法闭包，再做经典区间调度。',['计算 first、last','仅从 first 字符位置 start 构造：end=last[c]，扫描至 end；若 first[current]<start 无效，否则扩 end','候选按 end 升序，start>previousEnd 时选择对应 substring'],'O(26n)','O(26)',
`class Solution { public List<String> maxNumOfSubstrings(String text){int[] first=new int[26],last=new int[26];Arrays.fill(first,-1);for(int i=0;i<text.length();i++){int c=text.charAt(i)-'a';if(first[c]==-1)first[c]=i;last[c]=i;}List<int[]> intervals=new ArrayList<>();for(int c=0;c<26;c++)if(first[c]!=-1){int start=first[c],end=last[c];boolean valid=true;for(int i=start;i<=end;i++){int value=text.charAt(i)-'a';if(first[value]<start){valid=false;break;}end=Math.max(end,last[value]);}if(valid)intervals.add(new int[]{start,end});}intervals.sort(Comparator.comparingInt(interval->interval[1]));List<String> answer=new ArrayList<>();int previous=-1;for(int[] interval:intervals)if(interval[0]>previous){answer.add(text.substring(interval[0],interval[1]+1));previous=interval[1];}return answer;} }`,
`class Solution { fun maxNumOfSubstrings(text:String):List<String>{val first=IntArray(26){-1};val last=IntArray(26);for(i in text.indices){val value=text[i]-'a';if(first[value]==-1)first[value]=i;last[value]=i};val intervals=mutableListOf<IntArray>();for(c in 0..25)if(first[c]!=-1){val start=first[c];var end=last[c];var valid=true;var i=start;while(i<=end){val value=text[i]-'a';if(first[value]<start){valid=false;break};end=maxOf(end,last[value]);i++};if(valid)intervals.add(intArrayOf(start,end))};intervals.sortBy{it[1]};val answer=mutableListOf<String>();var previous=-1;for(interval in intervals)if(interval[0]>previous){answer.add(text.substring(interval[0],interval[1]+1));previous=interval[1]};return answer} }`,
`class Solution { public: vector<string> maxNumOfSubstrings(string text){int first[26],last[26];fill(begin(first),end(first),-1);for(int i=0;i<(int)text.size();++i){int value=text[i]-'a';if(first[value]==-1)first[value]=i;last[value]=i;}vector<pair<int,int>> intervals;for(int c=0;c<26;++c)if(first[c]!=-1){int start=first[c],end=last[c];bool valid=true;for(int i=start;i<=end;++i){int value=text[i]-'a';if(first[value]<start){valid=false;break;}end=max(end,last[value]);}if(valid)intervals.push_back({end,start});}sort(intervals.begin(),intervals.end());vector<string> answer;int previous=-1;for(auto [end,start]:intervals)if(start>previous){answer.push_back(text.substr(start,end-start+1));previous=end;}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'maxNumOfSubstrings',parameterTypes:['string'],returnType:'stringList',cases:[{name:'选择 e f 与 ccc',args:['adefaddaccc'],expected:['e','f','ccc']},{name:'三个最小闭包互不重叠',args:['abbaccd'],expected:['bb','cc','d']},{name:'相互依赖只能选完整字符串',args:['abab'],expected:['abab']}]}},
{id:1521,slug:'find-a-value-of-a-mysterious-function-closest-to-target',title:'找到最接近目标值的函数值',studyTags:['数组','位运算'],summary:'对任意连续子数组计算按位与，返回其与 target 的最小绝对差。',insight:'以当前位置结尾的不同按位与值数量很少，因为每扩展一个元素只能把置位清零。用集合从前一位置所有值与当前数生成新集合。',pitfalls:['子数组必须非空','集合去重防止状态指数增长','每个新状态都用于更新答案'],solutions:[s('distinct-ending-and-values','结尾按位与状态集合','滚动维护所有以当前下标结尾子数组的不同按位与。',['previous 为空，answer=INF','对 value，current={value}，并加入 previous 中 each&value','遍历 current 更新 abs(and-target)，然后 previous=current'],'O(n·B)','O(B)',
`class Solution { public int closestToTarget(int[] arr,int target){Set<Integer> previous=new HashSet<>();int answer=Integer.MAX_VALUE;for(int value:arr){Set<Integer> current=new HashSet<>();current.add(value);for(int old:previous)current.add(old&value);for(int result:current)answer=Math.min(answer,Math.abs(result-target));previous=current;}return answer;} }`,
`class Solution { fun closestToTarget(arr:IntArray,target:Int):Int{var previous=emptySet<Int>();var answer=Int.MAX_VALUE;for(value in arr){val current=mutableSetOf(value);for(old in previous)current.add(old and value);for(result in current)answer=minOf(answer,kotlin.math.abs(result-target));previous=current};return answer} }`,
`class Solution { public: int closestToTarget(vector<int>& arr,int target){unordered_set<int> previous;int answer=INT_MAX;for(int value:arr){unordered_set<int> current{value};for(int old:previous)current.insert(old&value);for(int result:current)answer=min(answer,abs(result-target));previous=move(current);}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'closestToTarget',parameterTypes:['intArray','int'],returnType:'int',cases:[{name:'最接近五的与值差二',args:[[9,12,3,7,15],5],expected:2},{name:'百万与一相差九十九万九千九百九十九',args:[[1000000,1000000,1000000],1],expected:999999},{name:'相邻不同二次幂按位与为零',args:[[1,2,4,8,16],0],expected:0}]}},
{id:1523,slug:'count-odd-numbers-in-an-interval-range',title:'在区间范围内统计奇数数目',studyTags:['数学'],summary:'统计闭区间 [low,high] 中的奇数数量。',insight:'不超过 x 的正奇数数量是 (x+1)/2；两个前缀计数相减得到区间答案。',pitfalls:['区间包含两个端点','整数除法自动向下取整','low 可为零'],solutions:[s('odd-prefix-count','奇数前缀计数','用不超过边界的奇数数目作差。',['countUpTo(x)=(x+1)/2','high 前缀包含 high','减去 low-1 前缀等价于减 low/2'],'O(1)','O(1)',
`class Solution { public int countOdds(int low,int high){return (high+1)/2-low/2;} }`,
`class Solution { fun countOdds(low:Int,high:Int):Int=(high+1)/2-low/2 }`,
`class Solution { public: int countOdds(int low,int high){return (high+1)/2-low/2;} };`)],tests:{schemaVersion:1,mode:'function',method:'countOdds',parameterTypes:['int','int'],returnType:'int',cases:[{name:'三到七有三个奇数',args:[3,7],expected:3},{name:'八到十只有九',args:[8,10],expected:1},{name:'单个偶数没有奇数',args:[2,2],expected:0}]}}
]}
