const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-013',problems:[
{id:920,slug:'number-of-music-playlists',title:'播放列表的数量',studyTags:['动态规划','组合数学'],summary:'用 n 首不同歌曲组成长度为 goal 的播放列表，每首至少播放一次，且同一首歌再次出现前至少播放 k 首其他歌曲，求方案数。',insight:'状态 dp[length][used] 记录已排长度和已使用歌曲数；下一位可选一首新歌，或从不在最近 k 首中的旧歌里选择。',pitfalls:['最终必须恰好使用全部 n 首歌','旧歌只有 used-k 种可选','每次转移都要取模并使用长整型'],solutions:[s('length-used-dp','长度与已用歌曲数动态规划','按播放列表位置递推新歌与旧歌两类选择。',['dp[0][0]=1','从 dp[length][used] 加入新歌，乘 n-used','若 used>k，复播旧歌并乘 used-k；返回 dp[goal][n]'],'O(goal·n)','O(goal·n)',
`class Solution { public int numMusicPlaylists(int n,int goal,int k){long mod=1000000007L;long[][] dp=new long[goal+1][n+1];dp[0][0]=1;for(int length=0;length<goal;length++)for(int used=0;used<=n;used++){if(used<n)dp[length+1][used+1]=(dp[length+1][used+1]+dp[length][used]*(n-used))%mod;if(used>k)dp[length+1][used]=(dp[length+1][used]+dp[length][used]*(used-k))%mod;}return(int)dp[goal][n];} }`,
`class Solution { fun numMusicPlaylists(n:Int,goal:Int,k:Int):Int{val mod=1000000007L;val dp=Array(goal+1){LongArray(n+1)};dp[0][0]=1;for(length in 0 until goal)for(used in 0..n){if(used<n)dp[length+1][used+1]=(dp[length+1][used+1]+dp[length][used]*(n-used))%mod;if(used>k)dp[length+1][used]=(dp[length+1][used]+dp[length][used]*(used-k))%mod};return dp[goal][n].toInt()} }`,
`class Solution { public: int numMusicPlaylists(int n,int goal,int k){const long long mod=1000000007;vector<vector<long long>> dp(goal+1,vector<long long>(n+1));dp[0][0]=1;for(int length=0;length<goal;++length)for(int used=0;used<=n;++used){if(used<n)dp[length+1][used+1]=(dp[length+1][used+1]+dp[length][used]*(n-used))%mod;if(used>k)dp[length+1][used]=(dp[length+1][used]+dp[length][used]*(used-k))%mod;}return dp[goal][n];} };`)],tests:{schemaVersion:1,mode:'function',method:'numMusicPlaylists',parameterTypes:['int','int','int'],returnType:'int',cases:[{name:'三首恰好各一次',args:[3,3,1],expected:6},{name:'两首可立即重复',args:[2,3,0],expected:6},{name:'两首必须交替',args:[2,3,1],expected:2}]}},
{id:921,slug:'minimum-add-to-make-parentheses-valid',title:'使括号有效的最少添加',studyTags:['字符串','贪心','栈'],summary:'可在任意位置添加左右括号，求让只含括号的字符串有效所需的最少添加数。',insight:'扫描时维护尚未匹配的左括号；无左括号可配的右括号必须补一个左括号，结束后剩余左括号各补一个右括号。',pitfalls:['不能用后面的左括号匹配前面的右括号','空余额遇右括号立即计一次补充','答案包含扫描中补充数和最终余额'],solutions:[s('balance-greedy-scan','括号余额贪心扫描','即时补齐无法匹配的右括号。',['balance=0,added=0','左括号令 balance++；右括号在 balance>0 时抵消，否则 added++','返回 added+balance'],'O(n)','O(1)',
`class Solution { public int minAddToMakeValid(String s){int balance=0,added=0;for(char ch:s.toCharArray())if(ch=='(')balance++;else if(balance>0)balance--;else added++;return added+balance;} }`,
`class Solution { fun minAddToMakeValid(s:String):Int{var balance=0;var added=0;for(ch in s)if(ch=='(')balance++ else if(balance>0)balance-- else added++;return added+balance} }`,
`class Solution { public: int minAddToMakeValid(string s){int balance=0,added=0;for(char ch:s)if(ch=='(')++balance;else if(balance>0)--balance;else ++added;return added+balance;} };`)],tests:{schemaVersion:1,mode:'function',method:'minAddToMakeValid',parameterTypes:['string'],returnType:'int',cases:[{name:'末尾多一个右括号',args:['())'],expected:1},{name:'三个左括号',args:['((('],expected:3},{name:'已经有效',args:['()'],expected:0}]}},
{id:922,slug:'sort-array-by-parity-ii',title:'按奇偶排序数组 II',studyTags:['数组','双指针'],summary:'数组中奇偶元素数量相同，重排后让每个下标的奇偶性与其元素一致。',insight:'分别维护下一个偶数下标和奇数下标，扫描元素并写入对应位置即可。',pitfalls:['下标从零开始，偶数位填偶数','两个写指针每次跨两格','题目保证奇偶元素数量匹配'],solutions:[s('dual-write-indices','奇偶双写指针','按元素奇偶写入对应下标序列。',['创建同长度 answer，even=0、odd=1','扫描 nums；偶数写 answer[even] 并 even+=2','奇数写 answer[odd] 并 odd+=2，返回 answer'],'O(n)','O(n)',
`class Solution { public int[] sortArrayByParityII(int[] nums){int[] answer=new int[nums.length];int even=0,odd=1;for(int value:nums)if(value%2==0){answer[even]=value;even+=2;}else{answer[odd]=value;odd+=2;}return answer;} }`,
`class Solution { fun sortArrayByParityII(nums:IntArray):IntArray{val answer=IntArray(nums.size);var even=0;var odd=1;for(value in nums)if(value%2==0){answer[even]=value;even+=2}else{answer[odd]=value;odd+=2};return answer} }`,
`class Solution { public: vector<int> sortArrayByParityII(vector<int>& nums){vector<int> answer(nums.size());int even=0,odd=1;for(int value:nums)if(value%2==0){answer[even]=value;even+=2;}else{answer[odd]=value;odd+=2;}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'sortArrayByParityII',parameterTypes:['intArray'],returnType:'intArray',cases:[{name:'四个元素交替',args:[[4,2,5,7]],expected:[4,5,2,7]},{name:'已经交替',args:[[2,3]],expected:[2,3]},{name:'先奇后偶',args:[[3,4]],expected:[4,3]}]}},
{id:923,slug:'3sum-with-multiplicity',title:'三数之和的多种可能',studyTags:['数组','计数','组合数学'],summary:'统计数组中下标递增且三数之和等于 target 的三元组数量，对 1e9+7 取模。',insight:'值域只有 0 到 100，可统计频次后枚举 a≤b≤c，并按三值相等关系用组合数计算下标选择数。',pitfalls:['枚举的是值而非下标','全相等、恰有两个相等和全不同公式不同','组合乘法使用长整型'],solutions:[s('frequency-combination-enumeration','频次与组合数枚举','枚举有序值三元组并计算其出现次数。',['统计 count[0..100]','枚举 a≤b≤c 且 a+b+c=target','三值全等用 C(count,3)，两值相等用 C(count,2)，全不同用频次乘积；累加取模'],'O(V²)','O(V)',
`class Solution { public int threeSumMulti(int[] arr,int target){long mod=1000000007L,answer=0;long[] count=new long[101];for(int value:arr)count[value]++;for(int a=0;a<=100;a++)for(int b=a;b<=100;b++){int c=target-a-b;if(c<b||c>100)continue;long ways;if(a==b&&b==c)ways=count[a]*(count[a]-1)*(count[a]-2)/6;else if(a==b)ways=count[a]*(count[a]-1)/2*count[c];else if(b==c)ways=count[a]*count[b]*(count[b]-1)/2;else ways=count[a]*count[b]*count[c];answer=(answer+ways)%mod;}return(int)answer;} }`,
`class Solution { fun threeSumMulti(arr:IntArray,target:Int):Int{val mod=1000000007L;var answer=0L;val count=LongArray(101);for(value in arr)count[value]++;for(a in 0..100)for(b in a..100){val c=target-a-b;if(c<b||c>100)continue;val ways=if(a==b&&b==c)count[a]*(count[a]-1)*(count[a]-2)/6 else if(a==b)count[a]*(count[a]-1)/2*count[c] else if(b==c)count[a]*count[b]*(count[b]-1)/2 else count[a]*count[b]*count[c];answer=(answer+ways)%mod};return answer.toInt()} }`,
`class Solution { public: int threeSumMulti(vector<int>& arr,int target){const long long mod=1000000007;long long answer=0,count[101]={};for(int value:arr)++count[value];for(int a=0;a<=100;++a)for(int b=a;b<=100;++b){int c=target-a-b;if(c<b||c>100)continue;long long ways;if(a==b&&b==c)ways=count[a]*(count[a]-1)*(count[a]-2)/6;else if(a==b)ways=count[a]*(count[a]-1)/2*count[c];else if(b==c)ways=count[a]*count[b]*(count[b]-1)/2;else ways=count[a]*count[b]*count[c];answer=(answer+ways)%mod;}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'threeSumMulti',parameterTypes:['intArray','int'],returnType:'int',cases:[{name:'多组组合二十种',args:[[1,1,2,2,3,3,4,4,5,5],8],expected:20},{name:'两个一四个二',args:[[1,1,2,2,2,2],5],expected:12},{name:'三个零',args:[[0,0,0],0],expected:1}]}},
{id:924,slug:'minimize-malware-spread',title:'尽量减少恶意软件的传播',studyTags:['图论','并查集','连通分量'],summary:'无向图中若干节点初始感染，感染会扩散到整个连通分量；删除一个初始感染节点，求最终感染节点最少且编号最小的删除选择。',insight:'并查集得到连通分量大小和每个分量中的初始感染数；只有某分量恰含一个感染源时，删除它才能挽救整个分量。',pitfalls:['删除的是初始感染列表中的一个节点','多个感染源同分量时删除一个无收益','收益相同时选择编号最小者'],solutions:[s('component-infection-count','连通分量感染源计数','比较每个候选能独自挽救的分量大小。',['并查集合并图中相连节点并统计分量大小','统计每个根包含的初始感染节点数','按 initial 升序枚举；若其分量感染数为一，收益为分量大小，否则为零，选择收益最大者'],'O(n²+n log n)','O(n)',
`class Solution { public int minMalwareSpread(int[][] graph,int[] initial){int n=graph.length;int[] parent=new int[n],size=new int[n];for(int i=0;i<n;i++){parent[i]=i;size[i]=1;}for(int i=0;i<n;i++)for(int j=i+1;j<n;j++)if(graph[i][j]==1)union(i,j,parent,size);int[] infected=new int[n];for(int node:initial)infected[find(node,parent)]++;Arrays.sort(initial);int answer=initial[0],best=-1;for(int node:initial){int root=find(node,parent),saved=infected[root]==1?size[root]:0;if(saved>best){best=saved;answer=node;}}return answer;}private int find(int x,int[] p){return p[x]==x?x:(p[x]=find(p[x],p));}private void union(int a,int b,int[] p,int[] s){a=find(a,p);b=find(b,p);if(a==b)return;if(s[a]<s[b]){int t=a;a=b;b=t;}p[b]=a;s[a]+=s[b];} }`,
`class Solution { fun minMalwareSpread(graph:Array<IntArray>,initial:IntArray):Int{val n=graph.size;val parent=IntArray(n){it};val size=IntArray(n){1};fun find(xInput:Int):Int{var x=xInput;while(parent[x]!=x){parent[x]=parent[parent[x]];x=parent[x]};return x};fun union(aInput:Int,bInput:Int){var a=find(aInput);var b=find(bInput);if(a==b)return;if(size[a]<size[b]){val t=a;a=b;b=t};parent[b]=a;size[a]+=size[b]};for(i in 0 until n)for(j in i+1 until n)if(graph[i][j]==1)union(i,j);val infected=IntArray(n);for(node in initial)infected[find(node)]++;initial.sort();var answer=initial[0];var best=-1;for(node in initial){val root=find(node);val saved=if(infected[root]==1)size[root] else 0;if(saved>best){best=saved;answer=node}};return answer} }`,
`class Solution { vector<int> parent,size;int find(int x){return parent[x]==x?x:parent[x]=find(parent[x]);}void unite(int a,int b){a=find(a);b=find(b);if(a==b)return;if(size[a]<size[b])swap(a,b);parent[b]=a;size[a]+=size[b];}public:int minMalwareSpread(vector<vector<int>>& graph,vector<int>& initial){int n=graph.size();parent.resize(n);iota(parent.begin(),parent.end(),0);size.assign(n,1);for(int i=0;i<n;++i)for(int j=i+1;j<n;++j)if(graph[i][j])unite(i,j);vector<int> infected(n);for(int node:initial)++infected[find(node)];sort(initial.begin(),initial.end());int answer=initial[0],best=-1;for(int node:initial){int root=find(node),saved=infected[root]==1?size[root]:0;if(saved>best){best=saved;answer=node;}}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'minMalwareSpread',parameterTypes:['intMatrix','intArray'],returnType:'int',cases:[{name:'同分量选较小编号',args:[[[1,1,0],[1,1,0],[0,0,1]],[0,1]],expected:0},{name:'两个独立感染点',args:[[[1,0,0],[0,1,0],[0,0,1]],[0,2]],expected:0},{name:'全连通选较小感染点',args:[[[1,1,1],[1,1,1],[1,1,1]],[1,2]],expected:1}]}}
]}
