const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-013',problems:[
{id:905,slug:'sort-array-by-parity',title:'按奇偶排序数组',studyTags:['数组','双指针'],summary:'重排数组使所有偶数出现在所有奇数之前，返回任一合法排列。',insight:'先收集偶数再收集奇数即可稳定地产生合法结果；每个元素只访问一次。',pitfalls:['零是偶数','奇偶两组内部顺序不作要求','返回数组包含原数组全部元素'],solutions:[s('stable-two-pass-partition','稳定两遍奇偶分区','按原顺序依次写入偶数和奇数。',['创建 answer 与 write=0','第一遍把 value%2==0 的元素写入','第二遍把奇数写入，返回 answer'],'O(n)','O(n)',
`class Solution { public int[] sortArrayByParity(int[] nums){int[] answer=new int[nums.length];int write=0;for(int value:nums)if(value%2==0)answer[write++]=value;for(int value:nums)if(value%2!=0)answer[write++]=value;return answer;} }`,
`class Solution { fun sortArrayByParity(nums:IntArray):IntArray{val answer=IntArray(nums.size);var write=0;for(value in nums)if(value%2==0)answer[write++]=value;for(value in nums)if(value%2!=0)answer[write++]=value;return answer} }`,
`class Solution { public: vector<int> sortArrayByParity(vector<int>& nums){vector<int> answer;for(int value:nums)if(value%2==0)answer.push_back(value);for(int value:nums)if(value%2)answer.push_back(value);return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'sortArrayByParity',parameterTypes:['intArray'],returnType:'intArray',cases:[{name:'偶数稳定移到前面',args:[[3,1,2,4]],expected:[2,4,3,1]},{name:'单个零',args:[[0]],expected:[0]},{name:'一奇一偶',args:[[1,2]],expected:[2,1]}]}},
{id:906,slug:'super-palindromes',title:'超级回文数',studyTags:['数学','枚举','回文'],summary:'若一个数及其平方根都是回文数，则它是超级回文数；统计闭区间 [left,right] 中的超级回文数。',insight:'平方根最多十亿，直接从较短前缀生成所有奇数位和偶数位回文根，平方后检查范围和回文性。',pitfalls:['区间边界用长整型解析','奇偶长度回文根分别生成','根是回文仍需检查平方也是回文'],solutions:[s('generate-palindromic-roots','生成回文平方根','枚举十万以内前缀覆盖所有可能根。',['解析 low、high','prefix=1..100000，生成 odd=prefix+reverse(prefix去尾) 与 even=prefix+reverse(prefix)','对每个 root 求 square；若落在区间且 square 字符串回文则计数，返回总数'],'O(100000·digits)','O(digits)',
`class Solution { public int superpalindromesInRange(String left,String right){long low=Long.parseLong(left),high=Long.parseLong(right);int answer=0;for(int prefix=1;prefix<=100000;prefix++){String text=Integer.toString(prefix);answer+=check(Long.parseLong(text+new StringBuilder(text.substring(0,text.length()-1)).reverse()),low,high);answer+=check(Long.parseLong(text+new StringBuilder(text).reverse()),low,high);}return answer;}private int check(long root,long low,long high){if(root>3037000499L)return 0;long square=root*root;if(square<low||square>high)return 0;String text=Long.toString(square);return text.equals(new StringBuilder(text).reverse().toString())?1:0;} }`,
`class Solution { fun superpalindromesInRange(left:String,right:String):Int{val low=left.toLong();val high=right.toLong();var answer=0;for(prefix in 1..100000){val text=prefix.toString();answer+=check((text+text.dropLast(1).reversed()).toLong(),low,high);answer+=check((text+text.reversed()).toLong(),low,high)};return answer};private fun check(root:Long,low:Long,high:Long):Int{if(root>3037000499L)return 0;val square=root*root;if(square !in low..high)return 0;val text=square.toString();return if(text==text.reversed())1 else 0} }`,
`class Solution { int check(long long root,long long low,long long high){if(root>3037000499LL)return 0;long long square=root*root;if(square<low||square>high)return 0;string text=to_string(square),reversed=text;reverse(reversed.begin(),reversed.end());return text==reversed;}public:int superpalindromesInRange(string left,string right){long long low=stoll(left),high=stoll(right);int answer=0;for(int prefix=1;prefix<=100000;++prefix){string text=to_string(prefix),odd=text,even=text;for(int i=text.size()-2;i>=0;--i)odd+=text[i];for(int i=text.size()-1;i>=0;--i)even+=text[i];answer+=check(stoll(odd),low,high)+check(stoll(even),low,high);}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'superpalindromesInRange',parameterTypes:['string','string'],returnType:'int',cases:[{name:'四到一千有四个',args:['4','1000'],expected:4},{name:'一到二只有一',args:['1','2'],expected:1},{name:'四百到五百',args:['400','500'],expected:1}]}},
{id:907,slug:'sum-of-subarray-minimums',title:'子数组的最小值之和',studyTags:['数组','单调栈','动态规划'],summary:'求所有非空连续子数组最小值之和，对 1e9+7 取模。',insight:'每个 arr[i] 作为最小值的子数组数量等于到左侧前一个严格更小元素距离乘到右侧下一个小于等于元素距离；单调栈弹出时可一次结算。',pitfalls:['重复值一侧严格、一侧非严格以避免重复计数','贡献乘法使用长整型','扫描结束要用哨兵弹出剩余元素'],solutions:[s('monotonic-stack-contributions','单调栈弹出贡献','弹出下标时确定其左右最小值边界。',['栈保存严格递增下标','i 从零到 n，n 处视作负无穷；当栈顶值>=current 时弹 mid','left=新栈顶或 -1，贡献 arr[mid]*(mid-left)*(i-mid)，累加取模；真实下标 i<n 时入栈'],'O(n)','O(n)',
`class Solution { public int sumSubarrayMins(int[] arr){long mod=1000000007L,answer=0;Deque<Integer> stack=new ArrayDeque<>();for(int i=0;i<=arr.length;i++){while(!stack.isEmpty()&&(i==arr.length||arr[stack.peek()]>=arr[i])){int middle=stack.pop(),left=stack.isEmpty()?-1:stack.peek();answer=(answer+(long)arr[middle]*(middle-left)*(i-middle))%mod;}if(i<arr.length)stack.push(i);}return(int)answer;} }`,
`class Solution { fun sumSubarrayMins(arr:IntArray):Int{val mod=1000000007L;var answer=0L;val stack=java.util.ArrayDeque<Int>();for(i in 0..arr.size){while(stack.isNotEmpty()&&(i==arr.size||arr[stack.peek()]>=arr[i])){val middle=stack.pop();val left=if(stack.isEmpty())-1 else stack.peek();answer=(answer+arr[middle].toLong()*(middle-left)*(i-middle))%mod};if(i<arr.size)stack.push(i)};return answer.toInt()} }`,
`class Solution { public: int sumSubarrayMins(vector<int>& arr){const long long mod=1000000007;long long answer=0;vector<int> stack;for(int i=0;i<=(int)arr.size();++i){while(!stack.empty()&&(i==(int)arr.size()||arr[stack.back()]>=arr[i])){int middle=stack.back();stack.pop_back();int left=stack.empty()?-1:stack.back();answer=(answer+(long long)arr[middle]*(middle-left)*(i-middle))%mod;}if(i<(int)arr.size())stack.push_back(i);}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'sumSubarrayMins',parameterTypes:['intArray'],returnType:'int',cases:[{name:'经典和十七',args:[[3,1,2,4]],expected:17},{name:'五元素和四百四十四',args:[[11,81,94,43,3]],expected:444},{name:'两个相等元素',args:[[1,1]],expected:3}]}},
{id:908,slug:'smallest-range-i',title:'最小差值 I',studyTags:['数组','数学','贪心'],summary:'可给每个数组元素加上 [-k,k] 内任意整数，求操作后最大值与最小值的最小可能差。',insight:'原区间两端最多各向内移动 k，总跨度减少 2k；若区间重叠则可把差缩到零。',pitfalls:['每个元素可选择不同调整量','答案不能为负数','只需原数组最小和最大值'],solutions:[s('shrink-extreme-gap','收缩极值间距','直接计算原范围减去两端可调幅度。',['minimum=min(nums),maximum=max(nums)','gap=maximum-minimum-2*k','返回 max(0,gap)'],'O(n)','O(1)',
`class Solution { public int smallestRangeI(int[] nums,int k){return Math.max(0,Arrays.stream(nums).max().getAsInt()-Arrays.stream(nums).min().getAsInt()-2*k);} }`,
`class Solution { fun smallestRangeI(nums:IntArray,k:Int):Int=maxOf(0,nums.maxOrNull()!!-nums.minOrNull()!!-2*k) }`,
`class Solution { public: int smallestRangeI(vector<int>& nums,int k){auto [minimum,maximum]=minmax_element(nums.begin(),nums.end());return max(0,*maximum-*minimum-2*k);} };`)],tests:{schemaVersion:1,mode:'function',method:'smallestRangeI',parameterTypes:['intArray','int'],returnType:'int',cases:[{name:'单元素差零',args:[[1],0],expected:0},{name:'两端可合拢',args:[[0,10],5],expected:0},{name:'仍剩三点差',args:[[1,3,6],1],expected:3}]}},
{id:909,slug:'snakes-and-ladders',title:'蛇梯棋',studyTags:['数组','广度优先搜索','矩阵'],summary:'在蛇形编号棋盘上从一号格出发，每次掷一到六并立即按蛇或梯跳转，求到达 n² 格最少步数，不可达返回负一。',insight:'每个编号是图节点，六种骰子结果是边；把编号映射到从底向上交替方向的矩阵坐标，BFS 首次到终点最短。',pitfalls:['一回合最多只沿一条蛇或梯跳一次','编号行方向交替','不能掷过终点格'],solutions:[s('label-space-bfs','编号空间广度优先搜索','按骰子边扩展并解析蛇梯目的地。',['队列从 label=1,distance=0 开始','弹出 label，枚举 next=label+1..min(label+6,n²)','映射 next 到 board 坐标，若格值非 -1 则 destination=格值，否则 next；未访问入队，命中终点返回 distance+1'],'O(n²)','O(n²)',
`class Solution { public int snakesAndLadders(int[][] board){int n=board.length,target=n*n;Queue<int[]> queue=new ArrayDeque<>();boolean[] seen=new boolean[target+1];queue.offer(new int[]{1,0});seen[1]=true;while(!queue.isEmpty()){int[] state=queue.poll();if(state[0]==target)return state[1];for(int next=state[0]+1;next<=Math.min(target,state[0]+6);next++){int quotient=(next-1)/n,row=n-1-quotient,column=(next-1)%n;if(quotient%2==1)column=n-1-column;int destination=board[row][column]==-1?next:board[row][column];if(!seen[destination]){seen[destination]=true;queue.offer(new int[]{destination,state[1]+1});}}}return -1;} }`,
`class Solution { fun snakesAndLadders(board:Array<IntArray>):Int{val n=board.size;val target=n*n;val queue=java.util.ArrayDeque<IntArray>();val seen=BooleanArray(target+1);queue.addLast(intArrayOf(1,0));seen[1]=true;while(queue.isNotEmpty()){val state=queue.removeFirst();if(state[0]==target)return state[1];for(next in state[0]+1..minOf(target,state[0]+6)){val quotient=(next-1)/n;val row=n-1-quotient;var column=(next-1)%n;if(quotient%2==1)column=n-1-column;val destination=if(board[row][column]==-1)next else board[row][column];if(!seen[destination]){seen[destination]=true;queue.addLast(intArrayOf(destination,state[1]+1))}}};return -1} }`,
`class Solution { public: int snakesAndLadders(vector<vector<int>>& board){int n=board.size(),target=n*n;queue<pair<int,int>> pending;vector<bool> seen(target+1);pending.push({1,0});seen[1]=true;while(!pending.empty()){auto [label,distance]=pending.front();pending.pop();if(label==target)return distance;for(int next=label+1;next<=min(target,label+6);++next){int quotient=(next-1)/n,row=n-1-quotient,column=(next-1)%n;if(quotient%2)column=n-1-column;int destination=board[row][column]==-1?next:board[row][column];if(!seen[destination]){seen[destination]=true;pending.push({destination,distance+1});}}}return -1;} };`)],tests:{schemaVersion:1,mode:'function',method:'snakesAndLadders',parameterTypes:['intMatrix'],returnType:'int',cases:[{name:'经典棋盘四步',args:[[[ -1,-1,-1,-1,-1,-1],[-1,-1,-1,-1,-1,-1],[-1,-1,-1,-1,-1,-1],[-1,35,-1,-1,13,-1],[-1,-1,-1,-1,-1,-1],[-1,15,-1,-1,-1,-1]]],expected:4},{name:'二阶空棋盘一步',args:[[[ -1,-1],[-1,-1]]],expected:1},{name:'单格已到终点',args:[[[ -1]]],expected:0}]}}
]}
