const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-022',problems:[
{id:1537,slug:'get-the-maximum-score',title:'最大得分',studyTags:['数组','双指针','动态规划','贪心'],summary:'沿两个严格递增数组之一前进，在公共值处可切换数组，每个不同位置值最多计一次，求最大路径和取模。',insight:'双指针累加两条路径在相邻公共值间的区段和；遇公共值时选择较大区段和加上该公共值，并同步两条累计得分。',pitfalls:['公共值只加一次','末尾还需取两条剩余路径较大值','比较最大值后才取模'],solutions:[s('two-path-segment-merge','双路径区段合并','在每个交点选择此前收益更大的路径。',['i=j=0,sumFirst=sumSecond=0','较小元素加入对应 sum 并前进；相等时 common=max(sumFirst,sumSecond)+value，两 sum 都设为 common','扫描剩余项，返回 max(sumFirst,sumSecond)%MOD'],'O(m+n)','O(1)',
`class Solution { public int maxSum(int[] nums1,int[] nums2){int i=0,j=0;long first=0,second=0;while(i<nums1.length&&j<nums2.length)if(nums1[i]<nums2[j])first+=nums1[i++];else if(nums1[i]>nums2[j])second+=nums2[j++];else{long common=Math.max(first,second)+nums1[i];first=second=common;i++;j++;}while(i<nums1.length)first+=nums1[i++];while(j<nums2.length)second+=nums2[j++];return (int)(Math.max(first,second)%1_000_000_007L);} }`,
`class Solution { fun maxSum(nums1:IntArray,nums2:IntArray):Int{var i=0;var j=0;var first=0L;var second=0L;while(i<nums1.size&&j<nums2.size)if(nums1[i]<nums2[j])first+=nums1[i++]else if(nums1[i]>nums2[j])second+=nums2[j++]else{val common=maxOf(first,second)+nums1[i];first=common;second=common;i++;j++};while(i<nums1.size)first+=nums1[i++];while(j<nums2.size)second+=nums2[j++];return (maxOf(first,second)%1_000_000_007L).toInt()} }`,
`class Solution { public: int maxSum(vector<int>& nums1,vector<int>& nums2){int i=0,j=0;long long first=0,second=0;while(i<(int)nums1.size()&&j<(int)nums2.size())if(nums1[i]<nums2[j])first+=nums1[i++];else if(nums1[i]>nums2[j])second+=nums2[j++];else{long long common=max(first,second)+nums1[i];first=second=common;++i;++j;}while(i<(int)nums1.size())first+=nums1[i++];while(j<(int)nums2.size())second+=nums2[j++];return max(first,second)%1000000007;} };`)],tests:{schemaVersion:1,mode:'function',method:'maxSum',parameterTypes:['intArray','intArray'],returnType:'int',cases:[{name:'两个交点最大路径和三十',args:[[2,4,5,8,10],[4,6,8,9]],expected:30},{name:'切换到一百获得一百零九',args:[[1,3,5,7,9],[3,5,100]],expected:109},{name:'无交点选择第二数组',args:[[1,2,3],[4,5,6]],expected:15}]}},
{id:1539,slug:'kth-missing-positive-number',title:'第 K 个缺失的正整数',studyTags:['数组','二分查找'],summary:'严格递增正整数数组中，返回未出现的第 k 个正整数。',insight:'到下标 i 为止缺失数为 arr[i]-i-1。二分首个缺失数不少于 k 的位置 left，答案统一为 left+k。',pitfalls:['缺失序列从正整数一开始','答案可能在数组末尾之后','二分位置可等于数组长度'],solutions:[s('missing-count-binary-search','缺失计数二分','按每个数组位置之前累计缺失数量寻找边界。',['left=0,right=n','middle 缺失数 arr[middle]-middle-1<k 时 left=middle+1，否则 right=middle','返回 left+k'],'O(log n)','O(1)',
`class Solution { public int findKthPositive(int[] arr,int k){int left=0,right=arr.length;while(left<right){int middle=left+(right-left)/2;if(arr[middle]-middle-1<k)left=middle+1;else right=middle;}return left+k;} }`,
`class Solution { fun findKthPositive(arr:IntArray,k:Int):Int{var left=0;var right=arr.size;while(left<right){val middle=left+(right-left)/2;if(arr[middle]-middle-1<k)left=middle+1 else right=middle};return left+k} }`,
`class Solution { public: int findKthPositive(vector<int>& arr,int k){int left=0,right=arr.size();while(left<right){int middle=left+(right-left)/2;if(arr[middle]-middle-1<k)left=middle+1;else right=middle;}return left+k;} };`)],tests:{schemaVersion:1,mode:'function',method:'findKthPositive',parameterTypes:['intArray','int'],returnType:'int',cases:[{name:'第五个缺失正数是九',args:[[2,3,4,7,11],5],expected:9},{name:'数组后第二个缺失是六',args:[[1,2,3,4],2],expected:6},{name:'首个缺失正数是一',args:[[5,6],1],expected:1}]}},
{id:1540,slug:'can-convert-string-in-k-moves',title:'K 次操作转变字符串',studyTags:['哈希表','字符串'],summary:'第 i 次操作可把一个字符循环后移 i 位且每个操作编号最多用一次，判断 k 次内能否把 s 转成 t。',insight:'每个位置需要位移 diff∈1..25。相同 diff 的第 c 次使用必须安排在 diff+26c，因为循环二十六位效果相同；检查最大安排编号不超过 k。',pitfalls:['两串长度不同直接失败','零位移不消耗操作','相同非零位移不能复用同一操作编号'],solutions:[s('shift-occurrence-scheduling','位移出现次数调度','为每种位移安排互不相同且效果等价的操作编号。',['count[26]=0','逐位置计算 diff=(t-s+26)%26，零跳过','scheduled=diff+26*count[diff]，然后 count++；scheduled>k 则 false，结束 true'],'O(n)','O(1)',
`class Solution { public boolean canConvertString(String s,String t,int k){if(s.length()!=t.length())return false;int[] count=new int[26];for(int i=0;i<s.length();i++){int difference=(t.charAt(i)-s.charAt(i)+26)%26;if(difference==0)continue;int scheduled=difference+26*count[difference]++;if(scheduled>k)return false;}return true;} }`,
`class Solution { fun canConvertString(s:String,t:String,k:Int):Boolean{if(s.length!=t.length)return false;val count=IntArray(26);for(i in s.indices){val difference=(t[i]-s[i]+26)%26;if(difference==0)continue;val scheduled=difference+26*count[difference]++;if(scheduled>k)return false};return true} }`,
`class Solution { public: bool canConvertString(string s,string t,int k){if(s.size()!=t.size())return false;int count[26]={};for(int i=0;i<(int)s.size();++i){int difference=(t[i]-s[i]+26)%26;if(!difference)continue;int scheduled=difference+26*count[difference]++;if(scheduled>k)return false;}return true;} };`)],tests:{schemaVersion:1,mode:'function',method:'canConvertString',parameterTypes:['string','string','int'],returnType:'boolean',cases:[{name:'各非零位移可在九次内完成',args:['input','ouput',9],expected:true},{name:'三个相同位移无法复用操作',args:['abc','bcd',10],expected:false},{name:'第二个同位移安排在二十七',args:['aab','bbb',27],expected:true}]}},
{id:1541,slug:'minimum-insertions-to-balance-a-parentheses-string',title:'平衡括号字符串的最少插入次数',studyTags:['字符串','贪心','括号序列'],summary:'每个左括号必须由连续两个右括号闭合，求把字符串变为平衡形式的最少插入数。',insight:'need 表示当前还需要的右括号数。遇左括号前若 need 为奇数，先插一个右括号完成上一对，再增加两个需求；遇右括号减少需求，负数时插入左括号。',pitfalls:['两个右括号必须连续配对','新左括号增加两个右括号需求','结尾所有剩余 need 都需插入'],solutions:[s('required-right-parentheses-greedy','所需右括号数贪心','在线修复奇数需求与过量右括号。',['insertions=0,need=0','遇 (：若 need 奇数则插一个 ) 并 need--，再 need+=2','遇 )：need--；若 need<0 则插入 (，insertions++，need=1；返回 insertions+need'],'O(n)','O(1)',
`class Solution { public int minInsertions(String text){int insertions=0,need=0;for(char value:text.toCharArray())if(value=='('){if(need%2==1){insertions++;need--;}need+=2;}else{need--;if(need<0){insertions++;need=1;}}return insertions+need;} }`,
`class Solution { fun minInsertions(text:String):Int{var insertions=0;var need=0;for(value in text)if(value=='('){if(need%2==1){insertions++;need--};need+=2}else{need--;if(need<0){insertions++;need=1}};return insertions+need} }`,
`class Solution { public: int minInsertions(string text){int insertions=0,need=0;for(char value:text)if(value=='('){if(need%2){++insertions;--need;}need+=2;}else if(--need<0){++insertions;need=1;}return insertions+need;} };`)],tests:{schemaVersion:1,mode:'function',method:'minInsertions',parameterTypes:['string'],returnType:'int',cases:[{name:'末尾缺一个右括号',args:['(()))'],expected:1},{name:'一左两右已平衡',args:['())'],expected:0},{name:'混合失衡需插入三次',args:['))())('],expected:3}]}},
{id:1542,slug:'find-longest-awesome-substring',title:'找出最长的超赞子字符串',studyTags:['哈希表','字符串','位运算'],summary:'若数字字符串的字符可重排成回文则为超赞，求最长超赞子字符串长度。',insight:'用十位掩码表示前缀中各数字频次奇偶。合法子串两端掩码相同或只相差一位；记录每个掩码最早位置即可求最长。',pitfalls:['零个或一个奇频数字都合法','状态零最早位置为负一','每个状态只记录首次出现'],solutions:[s('digit-parity-prefix-mask','数字奇偶前缀掩码','查询相同或一位不同的历史前缀状态。',['earliest[1024] 初始化 -2，earliest[0]=-1','扫描 i 切换 digit 位','用同 mask 与 mask xor (1<<digit) 的最早位置更新答案；未见 mask 时记录 i'],'O(10n)','O(1024)',
`class Solution { public int longestAwesome(String text){int[] earliest=new int[1<<10];Arrays.fill(earliest,-2);earliest[0]=-1;int mask=0,answer=0;for(int i=0;i<text.length();i++){mask^=1<<(text.charAt(i)-'0');if(earliest[mask]!=-2)answer=Math.max(answer,i-earliest[mask]);for(int digit=0;digit<10;digit++){int other=mask^(1<<digit);if(earliest[other]!=-2)answer=Math.max(answer,i-earliest[other]);}if(earliest[mask]==-2)earliest[mask]=i;}return answer;} }`,
`class Solution { fun longestAwesome(text:String):Int{val earliest=IntArray(1 shl 10){-2};earliest[0]=-1;var mask=0;var answer=0;for(i in text.indices){mask=mask xor (1 shl (text[i]-'0'));if(earliest[mask]!=-2)answer=maxOf(answer,i-earliest[mask]);for(digit in 0..9){val other=mask xor (1 shl digit);if(earliest[other]!=-2)answer=maxOf(answer,i-earliest[other])};if(earliest[mask]==-2)earliest[mask]=i};return answer} }`,
`class Solution { public: int longestAwesome(string text){int earliest[1<<10];fill(begin(earliest),end(earliest),-2);earliest[0]=-1;int mask=0,answer=0;for(int i=0;i<(int)text.size();++i){mask^=1<<(text[i]-'0');if(earliest[mask]!=-2)answer=max(answer,i-earliest[mask]);for(int digit=0;digit<10;++digit){int other=mask^(1<<digit);if(earliest[other]!=-2)answer=max(answer,i-earliest[other]);}if(earliest[mask]==-2)earliest[mask]=i;}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'longestAwesome',parameterTypes:['string'],returnType:'int',cases:[{name:'三二四二四最长五',args:['3242415'],expected:5},{name:'全部数字不同最长一',args:['12345678'],expected:1},{name:'每个数字出现偶数次',args:['213123'],expected:6}]}}
]}
