const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-020',problems:[
{id:1389,slug:'create-target-array-in-the-given-order',title:'按既定顺序创建目标数组',studyTags:['数组','模拟'],summary:'依次把 nums[i] 插入 target 的 index[i] 位置，返回最终数组。',insight:'动态数组的按位插入恰好对应题意；按输入顺序模拟即可。',pitfalls:['后续插入会把已有元素右移','必须按 i 从小到大处理','index[i] 在当前数组范围内'],solutions:[s('dynamic-list-insertion','动态数组插入','逐项调用列表的指定位置插入操作。',['创建空动态数组 target','对 i 从零到末尾，在 index[i] 插入 nums[i]','把列表转成整数数组返回'],'O(n²)','O(n)',
`class Solution { public int[] createTargetArray(int[] nums,int[] index){List<Integer> target=new ArrayList<>();for(int i=0;i<nums.length;i++)target.add(index[i],nums[i]);return target.stream().mapToInt(Integer::intValue).toArray();} }`,
`class Solution { fun createTargetArray(nums:IntArray,index:IntArray):IntArray{val target=mutableListOf<Int>();for(i in nums.indices)target.add(index[i],nums[i]);return target.toIntArray()} }`,
`class Solution { public: vector<int> createTargetArray(vector<int>& nums,vector<int>& index){vector<int> target;for(int i=0;i<(int)nums.size();++i)target.insert(target.begin()+index[i],nums[i]);return target;} };`)],tests:{schemaVersion:1,mode:'function',method:'createTargetArray',parameterTypes:['intArray','intArray'],returnType:'intArray',cases:[{name:'多次中间插入',args:[[0,1,2,3,4],[0,1,2,2,1]],expected:[0,4,1,3,2]},{name:'最后插到开头',args:[[1,2,3,4,0],[0,1,2,3,0]],expected:[0,1,2,3,4]},{name:'单元素',args:[[1],[0]],expected:[1]}]}},
{id:1390,slug:'four-divisors',title:'四因数',studyTags:['数组','数学','枚举'],summary:'对数组中恰好有四个正因数的整数求其全部因数之和，再累加。',insight:'枚举到平方根；每发现一对因数就增加一个或两个计数并累加，计数超过四可提前结束。',pitfalls:['完全平方数的平方根只能计一次','只有最终计数恰为四才贡献','不同数组元素分别计算'],solutions:[s('sqrt-divisor-enumeration','平方根因数枚举','成对统计每个整数的因数数量和总和。',['对 value 从 divisor=1 枚举至 divisor²<=value','整除时加入 divisor 与 value/divisor，若相等只加一次','因数数恰为四则把局部和加入答案'],'O(Σsqrt(nums[i]))','O(1)',
`class Solution { public int sumFourDivisors(int[] nums){int answer=0;for(int value:nums){int count=0,sum=0;for(int divisor=1;divisor*divisor<=value&&count<=4;divisor++)if(value%divisor==0){int other=value/divisor;count++;sum+=divisor;if(other!=divisor){count++;sum+=other;}}if(count==4)answer+=sum;}return answer;} }`,
`class Solution { fun sumFourDivisors(nums:IntArray):Int{var answer=0;for(value in nums){var count=0;var sum=0;var divisor=1;while(divisor*divisor<=value&&count<=4){if(value%divisor==0){val other=value/divisor;count++;sum+=divisor;if(other!=divisor){count++;sum+=other}};divisor++};if(count==4)answer+=sum};return answer} }`,
`class Solution { public: int sumFourDivisors(vector<int>& nums){int answer=0;for(int value:nums){int count=0,sum=0;for(int divisor=1;divisor*divisor<=value&&count<=4;++divisor)if(value%divisor==0){int other=value/divisor;++count;sum+=divisor;if(other!=divisor){++count;sum+=other;}}if(count==4)answer+=sum;}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'sumFourDivisors',parameterTypes:['intArray'],returnType:'int',cases:[{name:'只有二十一贡献三十二',args:[[21,4,7]],expected:32},{name:'重复元素分别贡献',args:[[21,21]],expected:64},{name:'没有四因数',args:[[1,2,3,5]],expected:0}]}},
{id:1391,slug:'check-if-there-is-a-valid-path-in-a-grid',title:'检查网格中是否存在有效路径',studyTags:['数组','广度优先搜索','矩阵'],summary:'街道网格每种类型连接两个方向，判断能否沿相互接通的街道从左上走到右下。',insight:'从当前格沿其允许方向移动时，邻格必须包含反方向接口；把满足双向兼容的相邻格视为图边后 BFS。',pitfalls:['只看当前格方向不够，邻格必须能接回','方向编码需与六种街道类型一致','入队时标记避免重复'],solutions:[s('compatible-street-bfs','街道兼容广搜','仅沿两端接口相互匹配的边扩展。',['为六种类型保存可走方向集合','从起点 BFS，枚举当前类型方向并检查边界','邻格方向中含反向且未访问才入队，终点可达则成功'],'O(mn)','O(mn)',
`class Solution { private static final int[][][] PATHS={{{0,0}},{{0,-1},{0,1}},{{-1,0},{1,0}},{{0,-1},{1,0}},{{0,1},{1,0}},{{0,-1},{-1,0}},{{0,1},{-1,0}}};public boolean hasValidPath(int[][] grid){int rows=grid.length,cols=grid[0].length;boolean[][] seen=new boolean[rows][cols];Queue<int[]> queue=new ArrayDeque<>();queue.offer(new int[]{0,0});seen[0][0]=true;while(!queue.isEmpty()){int[] cell=queue.poll();if(cell[0]==rows-1&&cell[1]==cols-1)return true;for(int[] direction:PATHS[grid[cell[0]][cell[1]]]){int nr=cell[0]+direction[0],nc=cell[1]+direction[1];if(nr<0||nr>=rows||nc<0||nc>=cols||seen[nr][nc])continue;for(int[] back:PATHS[grid[nr][nc]])if(back[0]==-direction[0]&&back[1]==-direction[1]){seen[nr][nc]=true;queue.offer(new int[]{nr,nc});break;}}}return false;} }`,
`class Solution { private val paths=arrayOf(emptyArray(),arrayOf(intArrayOf(0,-1),intArrayOf(0,1)),arrayOf(intArrayOf(-1,0),intArrayOf(1,0)),arrayOf(intArrayOf(0,-1),intArrayOf(1,0)),arrayOf(intArrayOf(0,1),intArrayOf(1,0)),arrayOf(intArrayOf(0,-1),intArrayOf(-1,0)),arrayOf(intArrayOf(0,1),intArrayOf(-1,0)));fun hasValidPath(grid:Array<IntArray>):Boolean{val rows=grid.size;val cols=grid[0].size;val seen=Array(rows){BooleanArray(cols)};val queue=java.util.ArrayDeque<IntArray>();queue.add(intArrayOf(0,0));seen[0][0]=true;while(queue.isNotEmpty()){val cell=queue.removeFirst();if(cell[0]==rows-1&&cell[1]==cols-1)return true;for(direction in paths[grid[cell[0]][cell[1]]]){val nr=cell[0]+direction[0];val nc=cell[1]+direction[1];if(nr !in 0 until rows||nc !in 0 until cols||seen[nr][nc])continue;if(paths[grid[nr][nc]].any{it[0]==-direction[0]&&it[1]==-direction[1]}){seen[nr][nc]=true;queue.addLast(intArrayOf(nr,nc))}}};return false} }`,
`class Solution { vector<vector<pair<int,int>>> paths{{},{{0,-1},{0,1}},{{-1,0},{1,0}},{{0,-1},{1,0}},{{0,1},{1,0}},{{0,-1},{-1,0}},{{0,1},{-1,0}}};public:bool hasValidPath(vector<vector<int>>& grid){int rows=grid.size(),cols=grid[0].size();vector<vector<bool>> seen(rows,vector<bool>(cols));queue<pair<int,int>> pending;pending.push({0,0});seen[0][0]=true;while(!pending.empty()){auto [row,col]=pending.front();pending.pop();if(row==rows-1&&col==cols-1)return true;for(auto [dr,dc]:paths[grid[row][col]]){int nr=row+dr,nc=col+dc;if(nr<0||nr>=rows||nc<0||nc>=cols||seen[nr][nc])continue;for(auto [br,bc]:paths[grid[nr][nc]])if(br==-dr&&bc==-dc){seen[nr][nc]=true;pending.push({nr,nc});break;}}}return false;} };`)],tests:{schemaVersion:1,mode:'function',method:'hasValidPath',parameterTypes:['intMatrix'],returnType:'boolean',cases:[{name:'弯道相互连通',args:[[[2,4,3],[6,5,2]]],expected:true},{name:'纵横接口不匹配',args:[[[1,2,1],[1,2,1]]],expected:false},{name:'末端街道方向不接通',args:[[[1,1,2]]],expected:false}]}},
{id:1392,slug:'longest-happy-prefix',title:'最长快乐前缀',studyTags:['字符串','字符串匹配','KMP'],summary:'返回字符串中既是非空前缀又是后缀的最长字符串，但不能等于整个字符串。',insight:'KMP 前缀函数 pi[i] 就是 s[0..i] 的最长真前后缀长度；答案长度为 pi[n-1]。',pitfalls:['前缀和后缀可重叠','不能选择整个字符串','不存在时返回空串'],solutions:[s('kmp-prefix-function','KMP 前缀函数','计算完整字符串最后位置的最长边界长度。',['pi[0]=0','对 i 从一开始，失配时沿 pi 回退，匹配时长度加一','返回 s.substring(0,pi[n-1])'],'O(n)','O(n)',
`class Solution { public String longestPrefix(String text){int[] prefix=new int[text.length()];for(int i=1;i<text.length();i++){int length=prefix[i-1];while(length>0&&text.charAt(i)!=text.charAt(length))length=prefix[length-1];if(text.charAt(i)==text.charAt(length))length++;prefix[i]=length;}return text.substring(0,prefix[text.length()-1]);} }`,
`class Solution { fun longestPrefix(text:String):String{val prefix=IntArray(text.length);for(i in 1 until text.length){var length=prefix[i-1];while(length>0&&text[i]!=text[length])length=prefix[length-1];if(text[i]==text[length])length++;prefix[i]=length};return text.substring(0,prefix[text.lastIndex])} }`,
`class Solution { public: string longestPrefix(string text){vector<int> prefix(text.size());for(int i=1;i<(int)text.size();++i){int length=prefix[i-1];while(length&&text[i]!=text[length])length=prefix[length-1];if(text[i]==text[length])++length;prefix[i]=length;}return text.substr(0,prefix.back());} };`)],tests:{schemaVersion:1,mode:'function',method:'longestPrefix',parameterTypes:['string'],returnType:'string',cases:[{name:'level 首尾字母相同',args:['level'],expected:'l'},{name:'重复 ab 的最长边界',args:['ababab'],expected:'abab'},{name:'前后均为 leet',args:['leetcodeleet'],expected:'leet'}]}},
{id:1394,slug:'find-lucky-integer-in-an-array',title:'找出数组中的幸运数',studyTags:['数组','哈希表','计数'],summary:'幸运整数的数值等于它在数组中的出现次数，返回最大的幸运整数或负一。',insight:'先统计每个数的频次，再检查 value==frequency 并维护最大值。',pitfalls:['返回最大幸运数','数组中可能没有幸运数','判断数值而不是下标'],solutions:[s('frequency-map','频次哈希表','计数后筛选值与频次相同的条目。',['构造 value 到 count 映射','answer 初始化 -1','遍历条目，若 value==count 则更新最大值'],'O(n)','O(n)',
`class Solution { public int findLucky(int[] arr){Map<Integer,Integer> count=new HashMap<>();for(int value:arr)count.merge(value,1,Integer::sum);int answer=-1;for(Map.Entry<Integer,Integer> entry:count.entrySet())if(entry.getKey().equals(entry.getValue()))answer=Math.max(answer,entry.getKey());return answer;} }`,
`class Solution { fun findLucky(arr:IntArray):Int{val count=arr.toList().groupingBy{it}.eachCount();return count.filter{it.key==it.value}.keys.maxOrNull()?:-1} }`,
`class Solution { public: int findLucky(vector<int>& arr){unordered_map<int,int> count;for(int value:arr)++count[value];int answer=-1;for(auto [value,frequency]:count)if(value==frequency)answer=max(answer,value);return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'findLucky',parameterTypes:['intArray'],returnType:'int',cases:[{name:'二出现两次',args:[[2,2,3,4]],expected:2},{name:'三出现三次且最大',args:[[1,2,2,3,3,3]],expected:3},{name:'没有幸运数',args:[[2,2,2,3,3]],expected:-1}]}}
]}
