const s=(id,title,idea,steps,time,space,java,kotlin,cpp)=>({id,title,kind:'最优',idea,steps,complexity:{time,space},code:{java,kotlin,cpp}})
export default {batchId:'batch-019',problems:[
{id:1372,slug:'longest-zigzag-path-in-a-binary-tree',title:'二叉树中的最长交错路径',studyTags:['树','深度优先搜索','动态规划'],summary:'求二叉树中相邻边方向左右交替的最长路径边数。',insight:'后序 DFS 对每个节点返回从它出发先向左、先向右的最长交错长度；向左后必须接左孩子的向右状态，反之亦然。',pitfalls:['答案按边数而不是节点数','路径可从任意节点开始','空孩子对应可延伸长度零'],solutions:[s('two-direction-tree-dp','双方向树形动态规划','每个节点维护下一步选择左右方向的两个状态。',['空节点返回 (-1,-1)，使父节点加一得到零','goLeft=left.goRight+1，goRight=right.goLeft+1','用两状态更新全局最大值并返回'],'O(n)','O(h)',
`class Solution { private int answer=0;private int[] dfs(TreeNode node){if(node==null)return new int[]{-1,-1};int[] left=dfs(node.left),right=dfs(node.right);int goLeft=left[1]+1,goRight=right[0]+1;answer=Math.max(answer,Math.max(goLeft,goRight));return new int[]{goLeft,goRight};}public int longestZigZag(TreeNode root){dfs(root);return answer;} }`,
`class Solution { private var answer=0;private fun dfs(node:TreeNode?):IntArray{if(node==null)return intArrayOf(-1,-1);val left=dfs(node.left);val right=dfs(node.right);val goLeft=left[1]+1;val goRight=right[0]+1;answer=maxOf(answer,goLeft,goRight);return intArrayOf(goLeft,goRight)};fun longestZigZag(root:TreeNode?):Int{dfs(root);return answer} }`,
`class Solution { int answer=0;pair<int,int> dfs(TreeNode* node){if(!node)return {-1,-1};auto left=dfs(node->left),right=dfs(node->right);int goLeft=left.second+1,goRight=right.first+1;answer=max({answer,goLeft,goRight});return {goLeft,goRight};}public:int longestZigZag(TreeNode* root){dfs(root);return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'longestZigZag',parameterTypes:['treeNode'],returnType:'int',cases:[{name:'左后右后左共三边',args:[[1,2,null,null,3,4]],expected:3},{name:'单根节点为零',args:[[1]],expected:0},{name:'根有两个孩子最长一边',args:[[1,2,3]],expected:1}]}},
{id:1373,slug:'maximum-sum-bst-in-binary-tree',title:'二叉搜索子树的最大键值和',studyTags:['树','深度优先搜索','二叉搜索树','动态规划'],summary:'在二叉树中寻找节点值总和最大的二叉搜索子树，并返回其和。',insight:'后序遍历返回子树是否为 BST、最小值、最大值和总和；左右都合法且 left.max<node.val<right.min 时当前子树也合法。',pitfalls:['必须使用严格大小关系','空树提供正负无穷边界','所有值为负时允许选择空子树，答案为零'],solutions:[s('postorder-bst-state','后序 BST 状态合并','自底向上同时验证有序性并计算子树和。',['空节点返回 valid、min=+INF、max=-INF、sum=0','合并左右状态，满足严格边界时计算 sum 并更新答案','不满足时返回 invalid；最终返回全局答案'],'O(n)','O(h)',
`class Solution { private int answer=0;private int[] dfs(TreeNode node){if(node==null)return new int[]{1,Integer.MAX_VALUE,Integer.MIN_VALUE,0};int[] left=dfs(node.left),right=dfs(node.right);if(left[0]==1&&right[0]==1&&node.val>left[2]&&node.val<right[1]){int sum=left[3]+right[3]+node.val;answer=Math.max(answer,sum);return new int[]{1,Math.min(node.val,left[1]),Math.max(node.val,right[2]),sum};}return new int[]{0,0,0,0};}public int maxSumBST(TreeNode root){dfs(root);return answer;} }`,
`class Solution { private var answer=0;private fun dfs(node:TreeNode?):IntArray{if(node==null)return intArrayOf(1,Int.MAX_VALUE,Int.MIN_VALUE,0);val left=dfs(node.left);val right=dfs(node.right);if(left[0]==1&&right[0]==1&&node.\`val\`>left[2]&&node.\`val\`<right[1]){val sum=left[3]+right[3]+node.\`val\`;answer=maxOf(answer,sum);return intArrayOf(1,minOf(node.\`val\`,left[1]),maxOf(node.\`val\`,right[2]),sum)};return intArrayOf(0,0,0,0)};fun maxSumBST(root:TreeNode?):Int{dfs(root);return answer} }`,
`class Solution { int answer=0;array<int,4> dfs(TreeNode* node){if(!node)return {1,INT_MAX,INT_MIN,0};auto left=dfs(node->left),right=dfs(node->right);if(left[0]&&right[0]&&node->val>left[2]&&node->val<right[1]){int sum=left[3]+right[3]+node->val;answer=max(answer,sum);return {1,min(node->val,left[1]),max(node->val,right[2]),sum};}return {0,0,0,0};}public:int maxSumBST(TreeNode* root){dfs(root);return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'maxSumBST',parameterTypes:['treeNode'],returnType:'int',cases:[{name:'经典树最大和二十',args:[[1,4,3,2,4,2,5,null,null,null,null,null,null,4,6]],expected:20},{name:'全负数返回零',args:[[-4,-2,-5]],expected:0},{name:'整棵树为搜索树',args:[[2,1,3]],expected:6}]}},
{id:1374,slug:'generate-a-string-with-characters-that-have-odd-counts',title:'生成每种字符都是奇数个的字符串',studyTags:['字符串','构造'],summary:'构造长度为 n 的小写字符串，使其中每种出现字符的频次都是奇数。',insight:'n 为奇数时全部使用 a；n 为偶数时使用 n-1 个 a 和一个 b，两种频次都为奇数。',pitfalls:['题目允许任意合法答案','偶数长度不能只使用一种字符','构造长度必须恰为 n'],solutions:[s('parity-construction','奇偶构造','按 n 的奇偶性使用一种或两种字符。',['若 n 为奇数，返回 n 个 a','若 n 为偶数，返回 n-1 个 a 加一个 b','两种情况总长均为 n 且所有频次为奇数'],'O(n)','O(n)',
`class Solution { public String generateTheString(int n){return n%2==1?"a".repeat(n):"a".repeat(n-1)+"b";} }`,
`class Solution { fun generateTheString(n:Int):String=if(n%2==1)"a".repeat(n)else "a".repeat(n-1)+"b" }`,
`class Solution { public: string generateTheString(int n){return n%2?string(n,'a'):string(n-1,'a')+'b';} };`)],tests:{schemaVersion:1,mode:'function',method:'generateTheString',parameterTypes:['int'],returnType:'string',cases:[{name:'偶数四使用三加一',args:[4],expected:'aaab'},{name:'偶数二各一个',args:[2],expected:'ab'},{name:'奇数七全部相同',args:[7],expected:'aaaaaaa'}]}},
{id:1375,slug:'number-of-times-binary-string-is-prefix-aligned',title:'二进制字符串前缀一致的次数',studyTags:['数组','数学'],summary:'按 flips 顺序把二进制串对应位置置一，统计每步之后所有已置一位恰好形成前缀的次数。',insight:'执行第 i 步后已有 i 个一；它们形成长度 i 的前缀，当且仅当目前翻转位置最大值等于 i。',pitfalls:['flips 使用一基位置','第 i 步按一开始计数','只需维护最大位置，无需真的构造字符串'],solutions:[s('running-maximum','前缀最大值','用已翻转位置最大值判断一的集合是否无空洞。',['maximum=0,answer=0','按 step 从一开始扫描，更新 maximum=max(maximum,flips[step-1])','若 maximum==step 则 answer++，返回'],'O(n)','O(1)',
`class Solution { public int numTimesAllBlue(int[] flips){int maximum=0,answer=0;for(int i=0;i<flips.length;i++){maximum=Math.max(maximum,flips[i]);if(maximum==i+1)answer++;}return answer;} }`,
`class Solution { fun numTimesAllBlue(flips:IntArray):Int{var maximum=0;var answer=0;for(i in flips.indices){maximum=maxOf(maximum,flips[i]);if(maximum==i+1)answer++};return answer} }`,
`class Solution { public: int numTimesAllBlue(vector<int>& flips){int maximum=0,answer=0;for(int i=0;i<(int)flips.size();++i){maximum=max(maximum,flips[i]);if(maximum==i+1)++answer;}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'numTimesAllBlue',parameterTypes:['intArray'],returnType:'int',cases:[{name:'经典顺序两次全蓝',args:[[3,2,4,1,5]],expected:2},{name:'最后才成为完整前缀',args:[[4,1,2,3]],expected:1},{name:'顺序翻转每次均满足',args:[[1,2,3]],expected:3}]}},
{id:1376,slug:'time-needed-to-inform-all-employees',title:'通知所有员工所需的时间',studyTags:['树','深度优先搜索','广度优先搜索'],summary:'公司管理关系构成树，负责人通知直属下属耗时 informTime，求消息传到所有员工的总时间。',insight:'从 headID 沿管理树传播，孩子收到消息的时刻等于父亲收到时刻加父亲通知耗时；遍历过程中取最大到达时刻。',pitfalls:['使用的是父节点的 informTime','同一经理的下属并行收到消息','叶子通知时间通常为零'],solutions:[s('management-tree-traversal','管理树传播遍历','建立经理到下属邻接表并累计每个节点的到达时间。',['由 manager 构造 children 列表','栈从 (headID,0) 开始，弹出后更新最大时间','每个 child 以 time+informTime[node] 入栈，返回最大值'],'O(n)','O(n)',
`class Solution { public int numOfMinutes(int n,int headID,int[] manager,int[] informTime){List<Integer>[] children=new List[n];for(int i=0;i<n;i++)children[i]=new ArrayList<>();for(int employee=0;employee<n;employee++)if(manager[employee]!=-1)children[manager[employee]].add(employee);Deque<int[]> stack=new ArrayDeque<>();stack.push(new int[]{headID,0});int answer=0;while(!stack.isEmpty()){int[] state=stack.pop();int node=state[0],time=state[1];answer=Math.max(answer,time);for(int child:children[node])stack.push(new int[]{child,time+informTime[node]});}return answer;} }`,
`class Solution { fun numOfMinutes(n:Int,headID:Int,manager:IntArray,informTime:IntArray):Int{val children=Array(n){mutableListOf<Int>()};for(employee in 0 until n)if(manager[employee]!=-1)children[manager[employee]].add(employee);val stack=java.util.ArrayDeque<IntArray>();stack.push(intArrayOf(headID,0));var answer=0;while(stack.isNotEmpty()){val state=stack.pop();val node=state[0];val time=state[1];answer=maxOf(answer,time);for(child in children[node])stack.push(intArrayOf(child,time+informTime[node]))};return answer} }`,
`class Solution { public: int numOfMinutes(int n,int headID,vector<int>& manager,vector<int>& informTime){vector<vector<int>> children(n);for(int employee=0;employee<n;++employee)if(manager[employee]!=-1)children[manager[employee]].push_back(employee);stack<pair<int,int>> pending;pending.push({headID,0});int answer=0;while(!pending.empty()){auto [node,time]=pending.top();pending.pop();answer=max(answer,time);for(int child:children[node])pending.push({child,time+informTime[node]});}return answer;} };`)],tests:{schemaVersion:1,mode:'function',method:'numOfMinutes',parameterTypes:['int','int','intArray','intArray'],returnType:'int',cases:[{name:'只有负责人',args:[1,0,[-1],[0]],expected:0},{name:'负责人一秒通知五人',args:[6,2,[2,2,-1,2,2,2],[0,0,1,0,0,0]],expected:1},{name:'七人管理链',args:[7,6,[1,2,3,4,5,6,-1],[0,6,5,4,3,2,1]],expected:21}]}}
]}
